package inifile

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// WriteExpanded scans filename for #INCLUDE directives.  If none are found it
// returns filename unchanged.  If any are found it writes a fully-expanded
// copy to <filename>.expanded (with all nested #INCLUDEs inlined) and returns
// the path to the expanded file.
//
// The expanded file format mirrors scripts/linuxcnc.in handle_includes():
//
//	#*** <outfile>
//	#*** Created: <date>
//	#*** Autogenerated file with expanded #INCLUDEs
//	(original lines, with #INCLUDE replaced by the included file content)
func WriteExpanded(filename string) (string, error) {
	abs, err := filepath.Abs(filename)
	if err != nil {
		return "", fmt.Errorf("inifile: resolving path %q: %w", filename, err)
	}

	if !fileHasIncludes(abs) {
		return filename, nil
	}

	outPath := abs + ".expanded"
	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("inifile: creating expanded file %q: %w", outPath, err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "#*** %s\n", outPath)
	fmt.Fprintf(w, "#*** Created: %s\n", time.Now().Format(time.RFC1123))
	fmt.Fprintf(w, "#*** Autogenerated file with expanded #INCLUDEs\n")
	fmt.Fprintln(w, "")

	if err := writeExpanded(w, abs, map[string]bool{}); err != nil {
		// Remove the partially-written file so callers don't use a corrupt file.
		_ = os.Remove(outPath)
		return "", err
	}

	if err := w.Flush(); err != nil {
		_ = os.Remove(outPath)
		return "", fmt.Errorf("inifile: writing expanded file %q: %w", outPath, err)
	}
	return outPath, nil
}

// fileHasIncludes reports whether the file at filename contains at least one
// line whose trimmed content starts with "#INCLUDE".
func fileHasIncludes(filename string) bool {
	f, err := os.Open(filename)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if strings.HasPrefix(strings.TrimSpace(scanner.Text()), "#INCLUDE") {
			return true
		}
	}
	return false
}

// writeExpanded recursively writes the contents of filename to w, replacing
// each #INCLUDE directive with the contents of the referenced file.
// visited tracks already-included files to detect simple import cycles.
func writeExpanded(w *bufio.Writer, filename string, visited map[string]bool) error {
	if visited[filename] {
		return fmt.Errorf("inifile: circular #INCLUDE detected: %s", filename)
	}
	visited[filename] = true

	f, err := os.Open(filename)
	if err != nil {
		return fmt.Errorf("inifile: opening %q: %w", filename, err)
	}
	defer f.Close()

	dir := filepath.Dir(filename)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "#INCLUDE") {
			fmt.Fprintln(w, line)
			continue
		}

		rest := strings.TrimSpace(trimmed[len("#INCLUDE"):])
		if rest == "" {
			// Malformed #INCLUDE with no path — preserve as a comment so the
			// expanded file reflects the problem.
			fmt.Fprintln(w, line)
			continue
		}

		rest = os.ExpandEnv(rest)
		if !filepath.IsAbs(rest) {
			rest = filepath.Join(dir, rest)
		}
		incAbs, err := filepath.Abs(rest)
		if err != nil {
			return fmt.Errorf("inifile: resolving #INCLUDE path %q: %w", rest, err)
		}

		fmt.Fprintf(w, "\n#*** Begin #INCLUDE file: %s\n", incAbs)

		// Use a copy of visited so sibling includes don't block each other.
		visited2 := make(map[string]bool, len(visited))
		for k, v := range visited {
			visited2[k] = v
		}
		if err := writeExpanded(w, incAbs, visited2); err != nil {
			return err
		}

		fmt.Fprintf(w, "#*** End   #INCLUDE file: %s\n", incAbs)
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("inifile: reading %q: %w", filename, err)
	}
	return nil
}
