void InitRungs(void);
void PrepareRungs(void);
void InitTimers(void);
void PrepareTimers(void);
void InitMonostables(void);
void PrepareMonostables(void);
void InitCounters(void);
void PrepareCounters(void);
void InitTimersIEC(void);
void PrepareTimersIEC(void);
void PrepareAllDatasBeforeRun(void);
void InitArithmExpr(void);
void InitIOConf( void );
void RefreshASection( StrSection * pSection );
void ClassicLadder_RefreshAllSections(void);
void CopyRungToRung(StrRung * RungSrc,StrRung * RungDest);
