void InitRungs(void);
void PrepareRungs(void);
void InitTimers(void);
void PrepareTimers(void);
void InitMonostables(void);
void PrepareMonostables(void);
void InitCounters(void);
void PrepareCounters(void);
void InitArithmExpr(void);
void InitIOConf( void );
void RefreshAllRungs(void);
void CopyRungToRung(StrRung * RungSrc,StrRung * RungDest);
