# Code generated by gmicompile --client-python - DO NOT EDIT.
#
# REST client for ini API v1

from __future__ import annotations

import json
import urllib.request
import urllib.parse
import urllib.error
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any, Optional


# --- Types ---

@dataclass
class IniQueryItem:
    section: str = ""
    key: str = ""
    all: Optional[bool] = None
    namespace: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> IniQueryItem:
        return cls(
            section=d.get("section", ""),
            key=d.get("key", ""),
            all=d.get("all", None),
            namespace=d.get("namespace", None),
        )

    def to_dict(self) -> dict:
        return {
            "section": self.section,
            "key": self.key,
            "all": self.all,
            "namespace": self.namespace,
        }


@dataclass
class IniQueryResult:
    value: Optional[str] = None
    values: list[Optional[str]] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict) -> IniQueryResult:
        return cls(
            value=d.get("value", None),
            values=d.get("values", field(default_factory=list)),
        )

    def to_dict(self) -> dict:
        return {
            "value": self.value,
            "values": self.values,
        }


# --- Client ---

class APIError(Exception):
    """Error response from the server."""

    def __init__(self, status_code: int, message: str):
        self.status_code = status_code
        self.message = message
        super().__init__(f"{message} (HTTP {status_code})")


class IniClient:
    """REST client for the ini API."""

    def __init__(self, base_url: str, instance: str = "ini"):
        self.base_url = base_url.rstrip("/") + "/api/v1/" + instance

    def _do_request(self, method: str, path: str, body: Any = None, has_result: bool = False) -> Any:
        url = self.base_url + path
        data = None
        if body is not None:
            data = json.dumps(body).encode("utf-8")
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Accept", "application/json")
        if data is not None:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req) as resp:
                resp_body = resp.read()
                if has_result and resp_body:
                    return json.loads(resp_body)
                return None
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8", errors="replace")
            try:
                err_data = json.loads(err_body)
                msg = err_data.get("error", err_body)
            except (json.JSONDecodeError, ValueError):
                msg = err_body
            raise APIError(e.code, msg)

    # --- API Methods ---

    def query(self, items: list[IniQueryItem]) -> list[IniQueryResult]:
        path = "/query"
        body = {
            "items": items,
        }
        result = self._do_request("POST", path, body, has_result=True)
        return [IniQueryResult.from_dict(item) for item in (result or [])]

    def get_parameter_file(self, namespace: Optional[str] = None) -> str:
        path = "/parameter-file"
        body = {
            "namespace": namespace,
        }
        result = self._do_request("POST", path, body, has_result=True)
        return result

