.TH ABS_S32 "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

abs_s32 \- Compute the absolute value and sign of the input signal
.SH SYNOPSIS
.HP
.B loadrt abs_s32 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBabs-s32.\fIN\fB\fR

.SH PINS
.TP
.B abs-s32.\fIN\fB.in\fR s32 in \fR
input value
.TP
.B abs-s32.\fIN\fB.out\fR s32 out \fR
output value, always non-negative
.TP
.B abs-s32.\fIN\fB.sign\fR bit out \fR
Sign of input, false for positive, true for negative
.TP
.B abs-s32.\fIN\fB.is-positive\fR bit out \fR
TRUE if input is positive, FALSE if input is 0 or negative
.TP
.B abs-s32.\fIN\fB.is-negative\fR bit out \fR
TRUE if input is negative, FALSE if input is 0 or positive
.SH LICENSE

GPL
