.TH LIMIT1 "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

limit1 \- Limit the output signal to fall between min and max
.SH SYNOPSIS
.HP
.B loadrt limit1 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBlimit1.\fIN\fB\fR (requires a floating-point thread)

.SH PINS
.TP
.B limit1.\fIN\fB.in\fR float in \fR
.TQ
.B limit1.\fIN\fB.out\fR float out \fR
.TQ
.B limit1.\fIN\fB.min\fR float in \fR(default: \fI-1e20\fR)
.TQ
.B limit1.\fIN\fB.max\fR float in \fR(default: \fI1e20\fR)
.SH LICENSE

GPL
