.TH MUX2 "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

mux2 \- Select from one of two input values
.SH SYNOPSIS
.HP
.B loadrt mux2 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBmux2.\fIN\fB\fR (requires a floating-point thread)

.SH PINS
.TP
.B mux2.\fIN\fB.sel\fR bit in \fR
.TQ
.B mux2.\fIN\fB.out\fR float out \fR
Follows the value of in0 if sel is FALSE, or in1 if sel is TRUE
.TP
.B mux2.\fIN\fB.in1\fR float in \fR
.TQ
.B mux2.\fIN\fB.in0\fR float in \fR
.SH LICENSE

GPL
