.TH NOT "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

not \- Inverter
.SH SYNOPSIS
.HP
.B loadrt not [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBnot.\fIN\fB\fR

.SH PINS
.TP
.B not.\fIN\fB.in\fR bit in \fR
.TQ
.B not.\fIN\fB.out\fR bit out \fR
.SH LICENSE

GPL
