.TH OR2 "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

or2 \- Two-input OR gate
.SH SYNOPSIS
.HP
.B loadrt or2 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBor2.\fIN\fB\fR

.SH PINS
.TP
.B or2.\fIN\fB.in0\fR bit in \fR
.TQ
.B or2.\fIN\fB.in1\fR bit in \fR
.TQ
.B or2.\fIN\fB.out\fR bit out \fR

\fBout\fR is computed from the value of \fBin0\fR and \fBin1\fR according
to the following rule:
.RS
.TP
\fBin0=FALSE in1=FALSE\fB
\fBout=FALSE\fR
.TP
Otherwise,
\fBout=TRUE\fR
.RE
.SH LICENSE

GPL
