#!/bin/sh

comp="$(which comp)"

if ! [ -x "$comp" ]; then
    echo 'The required program "comp" could not be found' 1>&2
    exit 1
fi

bindir="`dirname $comp`"
prefix="`dirname $bindir`"
libdir=$prefix/lib

echo "$libdir"
