= hm2_7i90(9)

== NAME

hm2_7i90 - LinuxCNC HAL driver for the Mesa Electronics 7i90 EPP
Anything IO board with HostMot2 firmware.

== SYNOPSIS

**loadrt hm2_7i90** [**ioaddr=**__N__[,_N_...]] [**ioaddr_hi=**__N__[,_N_...]] [**epp_wide=**__N__[,_N_...]] [**debug_epp=**__N__[,_N_...]]

____
*ioaddr* [default: 0 (parport0)]:: The base address of the parallel port.

The number of ioaddr indexes/addresses given is used by the driver to
determine how many boards to search for. Previously the number of config
strings was used, but a blank config string is perfectly acceptable for
7i90.

*ioaddr_hi* [default: 0]::
  The secondary address of the parallel port, used to set EPP mode.
  0 means to use ioaddr + 0x400.
*epp_wide* [default: 1]::
  Set to zero to disable the "wide EPP mode". "Wide" mode allows a 16-
  and 32-bit EPP transfers, which can reduce the time spent in the read
  and write functions. However, this may not work on all EPP parallel ports.
*config* [default: ""]::
  HostMot2 config strings, described in the hostmot2(9) manpage.
*debug_epp* [default: 0]::
  Developer/debug use only! Enable debug logging of most EPP transfers.
____

== DESCRIPTION

hm2_7i90 is a device driver that interfaces the Mesa 7i90 board with the
HostMot2 firmware to the LinuxCNC HAL.

The 7i90 firmware is stored on the 7i90 itself, it is not programmed by
the driver at load time. The 7i90 firmware can be changed using the
mesaflash program.

The driver talks with the 7i90 over the parallel port, via EPP.

== Communicating with the board

The 7i90 communicates with the LinuxCNC computer over EPP, the Enhanced
Parallel Port. This provides about 1 MBps of throughput, and the
communication latency is very predictable and reasonably low.

The parallel port must support EPP 1.7 or EPP 1.9. EPP 1.9 is preferred,
but EPP 1.7 will work too. The EPP mode of the parallel port is
sometimes a setting in the BIOS.

Note that the popular "NetMOS" aka "MosChip 9805" PCI parport cards *do*
not work. They do not meet the EPP spec, and cannot be reliably used
with the 7i90. You have to find another card, sorry.

EPP is very reliable under normal circumstances, but bad cabling or
excessively long cabling runs may cause communication timeouts. The
driver exports a parameter named hm2_7i90.<BoardNum>.io_error to inform
HAL of this condition. When the driver detects an EPP timeout, it sets
io_error to True and stops communicating with the 7i90 board. Setting
io_error back to False makes the driver start trying to communicate with
the 7i90 again.

Access to the EPP bus is not threadsafe: only one realtime thread may
access the EPP bus.

== SEE ALSO

hostmot2(9)

== LICENSE

GPL
