= mux_generic(9)

== NAME

mux_generic - select one from several inputs and forwards it to a single output

== SYNOPSIS

**loadrt mux_generic config="**__<input_type><output_type><size>__[,__<input_type><output_type><size>__],...**"**

Types: **b** = bool, **f** = real, **s** = sint, **u** = uint

Example: **loadrt mux_generic config="**bb8,fu12**"**

== FUNCTIONS

**mux-gen.**_NN_ Multiplexer function.

== PINS

               mux-gen.NN.sel-bit-00 ───────────────────┐
                                 ... ─────────────────┐ │
               mux-gen.NN.sel-bit-BB ───────────────┐ │ │
                  mux-gen.NN.sel-int ─────────────┐ │ │ │
                                          ┌───────┴─┴─┴─┴───────┐
mux-gen.NN.in-[bool/real/sint/uint]-00 ───┤   ─────o \          │
                                 ... ─────┤   ─────o   o─────   ├───── mux-gen.NN.out-[bool/real/sint/uint]
mux-gen.NN.in-[bool/real/sint/uint]-MM ───┤   ─────o            │
                                          │                     │
        mux-gen.NN.suppress-no-input ─────┤                     │
              mux-gen.NN.debounce-us ─────┤                     │
                                          └─────────────────────┘

**mux-gen**.__N__.**suppress-no-input** bool in::
  This suppresses changing the output if all select lines are false.
  This stops unwanted jumps in output between transitions of input but makes in00 unavailable.
**mux-gen**.__N__.**debounce-us** uint in::
  sets debounce time in microseconds, e.g. 100000 = a tenth of a second.
  The selection inputs must be stable this long before the output
  changes. This helps to ignore 'noisy' switches.
**mux-gen**.__N__.**sel-bit-**__BB__ bit in (BB=0..bit width of _size_)::
**mux-gen**.__N__.**sel-int** uint in::
  Together, these determine which **in**__M__ value is copied to *output*.
  The bit pins are interpreted as binary bits, and the result is simply
  added on to the integer pin input. It is expected that either one or
  the other would normally be used. However, the possibility exists to
  use a higher-order bit to "shift" the values set by the integer pin.
  The sel-bit pins are only created when the size of the mux_gen
  component is an integer power of two. This component (unlike mux16)
  does not offer the option of decoding Gray-code, however the same
  effect can be achieved by arranging the order of the input values to suit.
**mux-gen**.__N__.**in-**[**bool**/**real**/**sint**/**uint**]**-**__MM__ variable-type in::
  The possible output values that are selected by the selection pins.
**mux-gen**.__N__.**out-**[**real**/**real**/**sint**/**uint**] variable-type out::
  Follows the value of one of the **in**__N__ values according to the
  selection bits and/or the selection number. Values will be
  converted and clamped. This means, for example that a REAL input greater
  than (approx.) 2^63^-1 will give a SINT output of 2^63^-1.

== PARAMETERS

**mux-gen**.__N__.**elapsed** real r::
  Current value of the internal debounce timer for debugging.
**mux-gen**.__N__.**selected** sint r::
  Current value of the internal selection variable after conversion for debugging.
  Possibly useful for setting up gray-code switches.

== DESCRIPTION

This component is a more general version of the other multiplexing
components. It allows the creation of arbitrary-size multiplexers (up to
1024 entries) and also supports differing data types on the input and
output pins. The configuration string is a comma-separated list of
code-letters and numbers, such as "bb4,fu12". This would create a
4-element bit-to-bit mux and a 12-element real-to-uint mux. The
code letters are **b** = bool, **f** = real, **s** = sint, **u** = uint
integer. The first letter code is the input type, the second is the
output type. The codes are not case-sensitive. The order of the letters
is significant but the position in the string is not. Do not insert any
spaces in the config string. Any non-zero real value will be converted
to a "true" output in bool form when it is more than ±2e-7 from zero.

Each mux has its own HAL function and must be added to a thread
separately.

== SEE ALSO

mux2(9), mux4(9), mux8(9), mux16(9)

== AUTHOR

Andy Pugh

== LICENSE

GPL
