= sserial(9)

== NAME

sserial - Smart Serial LinuxCNC HAL driver for the Mesa Electronics HostMot2 Smart-Serial remote cards

== SYNOPSIS

The Mesa Smart-Serial interface is a 2.5Mbs proprietary interface
between the Mesa Anything-IO cards and a range of subsidiary devices
termed "smart-serial remotes". The remote cards perform a variety of
functions, but typically they combine various classes of IO. The remote
cards are self-configuring, in that they tell the main LinuxCNC Hostmot2
driver what their pin functions are and what they should be named.

Many sserial remotes offer different pinouts depending on the mode they
are started up in. This is set using the sserial_port_N= option in the
hm2_pci modparam. See the hostmot2 manpage for further details.

It is likely that this documentation will be permanently out of date.

Each Anything-IO board can attach up to 8 sserial remotes to each header
(either the 50-pin headers on the 5I20/5I22/5I23/7I43 or the 25-pin
connectors on the 5I25, 6I25 and 7I80). The remotes are grouped into
"ports" of up to 8 "channels". Typically each header will be a single 8
channel port, but this is not necessarily always the case.

== PORTS

In addition to the per-channel/device pins detailed below there are
three per-port pins and three parameters. These use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.sserial.port-**__N__**.**.

*Pins:*

 .run (bool, in):: Enables the specific Smart Serial module.
  Setting this pin low will disable all boards on the port and puts the
  port in a pass-through mode where device parameter setting is possible.
  It is necessary to toggle the state of this pin if there is a
  requirement to alter a remote parameter on a live system.
  This pin defaults to TRUE and can be left unconnected.
  However, toggling the pin low-to-high will re-enable a faulted drive,
  so the pin could usefully be connected to the `iocontrol.0.user-enable-out` pin.

 .port_state (uint, out):: Shows the state of the sserial communications state-machine.
  This pin will generally show a value of 0x03 in normal operation, 0x07 in setup mode and 0x00 when the "run" pin is false.

 .fault-count (uint, out):: Indicates the state of the Smart Serial error handler, see the parameters section for more details.

*Parameters:*

 .fault-inc (uint, rw):: Any over-run or handshaking error in the
  SmartSerial communications will increment the .fault-count pin by the
  amount specified by this parameter. Default = 10.

 .fault-dec (uint, rw):: Every successful read/write cycle decrements the fault counter by this amount. Default = 1.

 .fault-lim (uint, rw):: When the fault counter reaches this threshold the
  Smart Serial interface on the corresponding port will be stopped and an
  error printed in dmesg. Together these three pins allow for control over
  the degree of fault- tolerance allowed in the interface. The default
  values mean that if more than one transaction in ten fails, more than 20
  times, then a hard error will be raised. If the increment were to be set
  to zero then no error would ever be raised, and the system would carry
  on regardless. Conversely setting decrement to zero, threshold to 1 and
  limit to 1 means that absolutely no errors will be tolerated.
  (This structure is copied directly from vehicle ECU practice.)

Any other parameters than the ones above are created by the card itself
from data in the remote firmware. They may be set in the HAL file using
"setp" in the usual way.

[NOTE]
====
Because a Smart-Serial remote can only communicate non-process data to the host card in setup mode,
it is necessary to stop and re-start the smart-serial port associated with the card to alter the value of a parameter.
====

NOTE: In the case of parameters beginning with "nv" (which are stored in non-volatile memory) the effect will not be seen until after the next power cycle of the drive.

Unchanged values will not be re-written so it is safe to leave the
"setp" commands in the HAL file or delete them as you see fit.

== DEVICES

The other pins and parameters created in HAL depend on the devices detected.
The following list of Smart Serial devices is by no means exhaustive.

=== 8I20

The 8I20 is a 2.2 kW three-phase drive for brushless DC motors and AC
servo motors. 8I20 pins and parameters have names like
"**hm2_**__<BoardType>__**.**__<BoardNum>__**.8i20.**__<PortNum>__**.**__<ChanNum>__**.<pin>",
for example "hm2_5i23.0.8i20.1.3.current" would set the phase current
for the drive connected to the fourth channel of the second sserial port
of the first 5I23 board. Note that the sserial ports do not necessarily
correlate in layout or number to the physical ports on the card.

*Pins:*

 .angle (real, in)::
  The rotor angle of the motor in fractions of a full *phase* revolution.
  An angle of 0.5 indicates that the motor is half a turn / 180 degrees / π radians from the zero position.
  The zero position is taken to be the position that the motor adopts under no load with a
  positive voltage applied to the A (or U) phase and both B and C (or V and W) connected to -V or 0 V.
  A 6 pole motor will have 3 zero positions per physical rotation.
  Note that the 8I20 drive automatically adds the phase lead/lag angle, and that this pin should see the raw rotor angle.
  There is a HAL module (bldc) which handles the complexity of differing motor and drive types.
 .current (real, in)::
  The phase current command to the drive.
  This is scaled from -1 to +1 for forwards and reverse maximum currents.
  The absolute value of the current is set by the max_current parameter.
 .bus-voltage (real, ro)::
  The drive bus voltage in V.
  This will tend to show 25.6 V when the drive is unpowered and the drive will not operate below about 50 V.
 .temp (real, ro):: The temperature of the driver in degrees C.
 .comms (uint, ro):: The communication status of the drive. See the manual for more details.
 .status.* (bool, ro)::
  The following status bits are exported, each with an inverted (-not) companion pin.
  For further details see the 8I20 manual:
  .brake-old, .brake-old-not;;
   Brake has been applied status (sticky).
  .brake-on, .brake-on-not;;
   Current brake on status.
  .bus-underv, .bus-underv-not;;
   Bus undervoltage status.
  .current-lim, .current-lim-not;;
   Indicates that MAXCURRENT is not available due to 8I20 temperature/current limiting.
  .ext-reset, .ext-reset-not;;
   DSP startup due to external reset (sticky).
  .no-enable, .no-enable-not;;
   No external enable.
  .pid-on, .pid-on-not;;
   Current loop PID active.
  .sw-reset, .sw-reset-not;;
   DSP startup due to software reset (sticky).
  .wd-reset, .wd-reset-not;;
   DSP startup due to hardware watchdog timeout (sticky).
 .fault.* (bool, ro)::
  The following fault bits are exported, each with an inverted (-not) companion pin.
  When a fault occurs the 8I20 turns off motor drive and the current control loop:
  .U-current, .U-current-not;;
   U phase current > 125% of MAXCURRENT.
  .V-current, .V-current-not;;
   V phase current > 125% of MAXCURRENT.
  .W-current, .W-current-not;;
   W phase current > 125% of MAXCURRENT.
  .bus-high, .bus-high-not;;
   High motor voltage fault (settable threshold).
  .bus-overv, .bus-overv-not;;
   High motor voltage fault (fixed at 400 V).
  .bus-underv, .bus-underv-not;;
   Low motor voltage fault.
  .framingr, .framingr-not;;
   8I20 serial port framing error.
  .module, .module-not;;
   Module over temperature or low gate voltage.
  .no-enable, .no-enable-not;;
   No external enable fault.
  .overcurrent, .overcurrent-not;;
   8I20 high side overcurrent fault.
  .overrun, .overrun-not;;
   8I20 serial port overrun error.
  .overtemp, .overtemp-not;;
   8I20 PCB temperature > 85 °C.
  .watchdog, .watchdog-not;;
   Communication timeout fault.

*Parameters:*:: The following parameters are exported. See the PDF documentation downloadable from Mesa for further details:

 .angle-maxlim::
 .angle-minlim::
 .angle-scalemax::
 .current-maxlim::
 .current-minlim::
 .current-scalemax::
 .nvbrakeoffv::
 .nvbrakeonv::
 .nvbusoverv::
 .nvbusundervmax::
 .nvbusundervmin::
 .nvkdihi::
 .nvkdil::
 .nvkdilo::
 .nvkdp::
 .nvkqihi::
 .nvkqil::
 .nvkqilo::
 .nvkqp::
 .nvmaxcurrent::
 .nvrembaudrate::
 .swrevision::
 .unitnumber::

 .max_current (real, rw):: Sets the maximum drive current in Amps.
  The default value is the maximum current programmed into the drive EEPROM.
  The value must be positive, and an error will be raised if a current in excess of the
  drive maximum is requested.
 .serial_number (uint, ro):: The serial number of the connected drive. This is also shown on the label on the drive.

=== 7I64

The 7I64 is a 24-input 24-output IO card. 7I64 pins and parameters use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.7i64.**__<PortNum>__**.**__<ChanNum>__**.**,
for example `hm2_5i23.0.7i64.1.3.output-01`.

*Pins:*

 .output-__NN__ (bool, in)::
  Writing a 1 or TRUE to this pin will enable output driver _NN_.
  Note that the outputs are drivers (switches) rather than voltage outputs.
  The LED adjacent to the connector on the board shows the status.
  The output can be inverted by setting a parameter.

 .input-__NN__ (bool, out):: The value of input _NN_.
  Note that the inputs are isolated and both pins of each input must be connected,
  typically to signal and the ground of the signal.
  (This need not be the ground of the board.)

 .input-__NN__-not (bool, out):: An inverted copy of the corresponding input.
 .analog0, .analog1 (real, out):: The two analogue inputs (0 to 3.3 V) on the board.

*Parameters:*

 .output-__NN__-invert (bool, rw):: Setting this parameter to 1 / TRUE will invert the output value,
  such that writing 0 to `.gpio.NN.out` will enable the output and vice-versa.

=== 7I76

The 7I76 is not really a smart-serial device.
It serves as a breakout for a number of other Hostmot2 functions.
There are connections for 5 step generators (for which see the main hostmot2 manpage).
The stepgen pins are associated with the 5I25 (`hm2_5i25.0.stepgen.00`....),
whereas the smart-serial pins are associated with the 7I76 (`hm2_5i25.0.7i76.0.0.output-00`).

*Pins:*

 .7i76.0.0.analog__N__ (modes 1 and 2 only) (real, out):: Analogue input values.
 .7i76.0.0.fieldvoltage (mode 2 only) (real, out):: Field voltage monitoring pin.
 .7i76.0.0.spindir (bool, in):: This pin provides a means to drive the spindle VFD direction terminals on the 7I76 board.
 .7i76.0.0.spinena (bool, in):: This pin drives the spindle-enable terminals on the 7I76 board.
 .7i76.0.0.spinout (real, in):: This controls the analogue output of the 7I76.
  This is intended as a speed control signal for a VFD.
 .7i76.0.0.output-__NN__ (bool, in):: (_NN_ = 0 to 15). 16 digital outputs.
  The sense of the signal can be set via a parameter.
 .7i76.0.0.input-__NN__ (bool, out):: (_NN_ = 0 to 31) 32 digital inputs.
 .7i76.0.0.input-__NN__-not (bool, out):: (_NN_ = 0 to 31) An inverted copy of the inputs provided for convenience.
  The two complementary pins may be connected to different signal nets.

*Parameters:*

 .7i76.0.0.nvbaudrate (uint, ro):: Indicates the vbaud rate. This probably should not be altered.
 .7i76.0.0.nvunitnumber (uint, ro):: Indicates the serial number of the device and should match a sticker on the card.
  This can be useful for working out which card is which.
 .7i76.0.0.nvwatchdogtimeout (uint, ro):: The sserial remote watchdog timeout.
  This is separate from the Anything-IO card timeout.
  This is unlikely to need to be changed.
 .7i76.0.0.output-__NN__-invert (bool, rw):: Invert the sense of the corresponding output pin.
 .7i76.0.0.spindir-invert (bool, rw):: Invert the senseof the spindle direction pin.
 .7i76.0.0.spinena-invert (bool, rw):: Invert the sense of the spindle-enable pin.
 .7i76.0.0.spinout-maxlim (real, rw):: The maximum speed request allowable
 .7i76.0.0.spinout-minlim (real, rw):: The minimum speed request.
 .7i76.0.0.spinout-scalemax (real, rw):: The spindle speed scaling.
  This is the speed request which would correspond to full-scale output from the spindle control pin.
  For example with a 10 V drive voltage and a 10000 RPM scalemax a value of 10,000 RPM on the spinout pin would produce 10 V output.
  However, if spinout-maxlim were set to 5000 RPM then no voltage above 5 V would be output.
 .7i76.0.0.swrevision (uint, ro):: The onboard firmware revision number.
  Utilities (man setsserial for details) exist to update and change this firmware.

=== 7I77

The 7I77 is an 6-axis servo control card. The analogue outputs are
smart-serial devices, but the encoders are conventional hostmot2
encoders and further details of them may be found in the hostmot2 manpage.

*Pins:*

 .7i77.0.0.input-__NN__ (bool, out):: (_NN_ = 0 to 31) 32 digital inputs.
 .7i77.0.0.input-__NN__-not (bool, out):: (_NN_ = 0 to 31) An inverted copy of the inputs provided for convenience. The two complementary pins may be connected to different signal nets.
 .7i77.0.0.output-__NN__ (bool, in):: (_NN_ = 0 to 15). 16 digital outputs. The sense of the signal can be set via a parameter.
 .7i77.0.0.spindir (bool, in):: This pin provides a means to drive the spindle VFD direction terminals on the 7I76 board.
 .7i77.0.0.spinena (bool, in):: This pin drives the spindle-enable terminals on the 7I76 board.
 .7i77.0.0.spinout (real, in):: This controls the analog output of the 7I77. This is intended as a speed control signal for a VFD.
 .7i77.0.1.analogena (bool, in):: This pin drives the analog enable terminals on the 7I77 board.
 .7i77.0.1.analogout__N__ (real, in):: (_N_ = 0 to 5) This controls the analog output of the 7I77.

*Parameters:*

 .7i77.0.0.output-__NN__-invert (bool, rw):: Invert the sense of the corresponding output pin.
 .7i77.0.0.spindir-invert (bool, rw):: Invert the sense of the spindle direction pin.
 .7i77.0.0.spinena-invert (bool, rw):: Invert the sense of the spindle-enable pin.
 .7i77.0.0.spinout-maxlim (real, rw):: The maximum speed request allowable
 .7i77.0.0.spinout-minlim (real, rw):: The minimum speed request.
 .7i77.0.0.spinout-scalemax (real, rw):: The spindle speed scaling.
  This is the speed request which would correspond to full-scale output from the spindle control pin.
  For example with a 10&#8201;V drive voltage and a 10000&#8201;RPM scalemax a value of 10000&#8201;RPM on the spinout pin would produce 10&#8201;V output.
  However, if spinout-maxlim were set to 5000&#8201;RPM then no voltage above 5&#8201;V would be output.
 .7i77.0.0.analogout__N__-maxlim (real, rw):: (_N_ = 0 to 5) The maximum speed request allowable
 .7i77.0.0.analogout__N__-minlim (real, rw):: (_N_ = 0 to 5) The minimum speed request.
 .7i77.0.0.analogout__N__-scalemax (real, rw):: (_N_ = 0 to 5) The analog speed scaling.
  This is the speed request which would correspond to full-scale output from the spindle control pin.
  For example with a 10&#8201;V drive voltage and a 10000&#8201;RPM scalemax a value of 10000&#8201;RPM on the spinout pin would produce 10V output.
  However, if spinout-maxlim were set to 5000&#8201;RPM then no voltage above 5&#8201;V would be output.

=== 7I69

The 7I69 is a 48 channel digital IO card.
7I69 pins and parameters use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.7i69.**__<PortNum>__**.**__<ChanNum>__**.**
It can be configured in five different modes:

.Modes
|===
|Mode |Function

|0 |Bidirectional mode (48 bits in, 48 bits out)
|1 |Input only mode (48 bits in)
|2 |Output only mode (48 bits out)
|3 |24/24 mode (24 bits in = bits 0..23 and 24 bits out = bits 24..47)
|4 |Bidirectional mode (48 bits in, 48 bits out) plus 4 MPG encoder channels on inputs 0 through 7
|===

*Pins:*

 .output-__NN__ (bool, in):: Digital output. Sense can be inverted with the corresponding Parameter.
 .input-__NN__ (bool, out):: Digital input
 .input-__NN__-not (bool, out):: Digital input, inverted.

*Parameters:*

 .nvbaudrate (uint, ro):: Indicates the vbaud rate. This probably should not be altered.
 .nvunitnumber (uint, ro):: Indicates the serial number of the device and should match a sticker on the card.  This can be useful for working out which card is which.
 .nvwatchdogtimeout (uint, ro):: The sserial remote watchdog timeout.  This is separate from the Anything-IO card timeout.  This is unlikely to need to be changed.
 .output-__NN__-invert (bool, rw):: Invert the sense of the corresponding output pin.
 .swrevision (uint, ro):: The onboard firmware revision number. Utilities exist to update and change this firmware.

=== 7I70

The 7I70 is a remote isolated 48 input card. The 7I70 inputs sense
positive inputs relative to a common field ground. Input impedance is
10&#8201;KΩ and input voltage can range from 5&#8201;VDC to 32&#8201;VDC.
All inputs have LED status indicators.
The input common field ground is galvanically isolated from the communications link.

The 7I70 has three software selectable modes. These different modes
select different sets of 7I70 data to be transferred between the host
and the 7I70 during real time process data exchanges. For high speed
applications, choosing the correct mode can reduced the data transfer
sizes, resulting in higher maximum update rates.
7I70 pins and parameters use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.7i70.**__<PortNum>__**.**__<ChanNum>__**.**

.Modes
|===
|Mode |Function

|0 |Input mode (48 bits input data only)
|1 |Input plus analog mode (48 bits input data plus 6 channels of analog data)
|2 |Input plus field voltage
|===

*Pins:*

 .analog__N__ (modes 1 and 2 only) (real, out):: Analogue input values.
 .fieldvoltage (mode 2 only) (real, out):: Field voltage monitoring pin.
 .input-__NN__ (bool, out):: (_NN_ = 0 to 47) 48 digital inputs.
 .input-__NN__-not (bool, out):: (_NN_ = 0 to 47) An inverted copy of the inputs provided for convenience. The two complementary pins may be connected to different signal nets.

*Parameters:*

 .nvbaudrate (uint, ro):: Indicates the vbaud rate. This probably should not be altered.
 .nvunitnumber (uint, ro):: Indicates the serial number of the device and should match a sticker on the card. This can be useful for working out which card is which.
 .nvwatchdogtimeout (uint, ro):: The sserial remote watchdog timeout. This is separate from the Anything-IO card timeout. This is unlikely to need to be changed.
 .swrevision (uint, ro):: The onboard firmware revision number. Utilities exist to update and change this firmware.

=== 7I71

The 7I71 is a remote isolated 48 output card. The 48 outputs are 8&#8201;VDC to
28&#8201;VDC sourcing drivers (common + field power) with 300&#8201;mA maximum
current capability. All outputs have LED status indicators.

The 7I71 has two software selectable modes. For high speed applications,
choosing the correct mode can reduced the data transfer sizes, resulting
in higher maximum update rates.
7I71 pins and parameters use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.7i71.**__<PortNum>__**.**__<ChanNum>__**.**

.Modes
|===
|Mode |Function

|0 |Output only mode (48 bits output data only)
|1 |Outputs plus read back field voltage
|===

*Pins:*

 .fieldvoltage (mode 2 only) (real, out):: Field voltage monitoring pin.

 .output-__NN__ (bool, in):: (_NN_ = 0 to 47) 48 digital outputs.
  The sense may be inverted by the invert parameter.

*Parameters:*

 .output-__NN__-invert (bool, rw):: Invert the sense of the corresponding output pin.
 .nvbaudrate (uint, ro):: Indicates the vbaud rate. This probably should not be altered.
 .nvunitnumber (uint, ro):: Indicates the serial number of the device and should match a sticker on the card. This can be useful for determining which card is which.
 .nvwatchdogtimeout (uint, ro):: The sserial remote watchdog timeout. This is separate from the Anything-IO card timeout. This is unlikely to need to be changed.
 .swrevision (uint, ro):: The onboard firmware revision number. Utilities exist to update and change this firmware.

=== 7I73

The 7I73 is a remote real time pendant or control panel interface.

The 7I73 supports up to four 50 kHz encoder inputs for MPGs, 8 digital
inputs and 6 digital outputs and up to a 64 Key keypad. If a smaller
keypad is used, more digital inputs and outputs become available.
Up to eight 0.0&#8201;V to 3.3&#8201;V analog inputs are also provided.
The 7I73 can drive a 4 line 20 character LCD for local DRO applications.

The 7I73 has 3 software selectable process data modes. These different
modes select different sets of 7I73 data to be transferred between the
host and the 7I73 during real time process data exchanges. For high
speed applications, choosing the correct mode can reduced the data
transfer sizes, resulting in higher maximum update rates.
7I73 pins and parameters use the prefix
**hm2_**__<BoardType>__**.**__<BoardNum>__**.7i73.**__<PortNum>__**.**__<ChanNum>__**.**.
The analog inputs are on channel 0 of the card, the remaining pins on channel 1.

.Modes
|===
|Mode |Function

|0 |I/O + ENCODER
|1 |I/O + ENCODER + ANALOG IN
|2 |I/O + ENCODER + ANALOG IN FAST DISPLAY
|===

*Pins:*

 .analogin__N__ (real, out):: Analogue inputs.
  Up to 8 channels may be available dependent on software and hardware configuration modes
  (see the PDF manual downloadable from https://www.mesanet.com).

 .display (modes 1 and 2) (uint, in):: Data for LCD display.
  This pin may be conveniently driven by the HAL "lcd" component which allows
  the formatted display of the values any number of HAL pins and textual content.

 .display32 (mode 2 only) (uint, in):: 4 bytes of data for LCD display. This mode is not supported by the HAL "lcd" component.
 .enc__N__.count (sint, out):: The position of the MPG encoder counters.
 .enc__N__.rawcounts (sint, out):: Raw count of the MPG encoder counters.
 .enc__N__.position (real, out):: Scaled position of the MPG encoder counters.
 .enc__N__.index-enable (bool, io):: Simulated index of the MPG encoder counters.
 .enc__N__.reset (bool, io):: Reset of the MPG encoder counters.
 .input-__NN__ (bool, out):: Up to 24 digital inputs (dependent on config)
 .input-__NN__-not (bool, out):: Inverted copy of the digital inputs
 .output-__NN__ (bool, in):: Up to 22 digital outputs (dependent on config)

*Parameters:*

 .nvanalogfilter (uint, ro)::
 .nvbaudrate (uint, ro)::
 .nvcontrast (uint, ro)::
 .nvdispmode (uint, ro)::
 .nvencmode0 (uint, ro)::
 .nvencmode1 (uint, ro)::
 .nvencmode2 (uint, ro)::
 .nvencmode3 (uint, ro)::
 .nvkeytimer (uint, ro)::
 .nvunitnumber (uint, ro)::
 .nvwatchdogtimeout (uint, ro)::
 .output-00-invert (bool, rw)::

For further details of the use of the above see the Mesa manual.

 .output-01-invert (bool, rw):: Invert the corresponding output bit.
 .swrevision (sint, ro):: The version of firmware installed.
