// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package apiserver_test

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"syscall"
	"testing"
	"unsafe"

	"github.com/sittner/linuxcnc/src/gomc/internal/apiserver"
)

// --- Mock API types (these would normally be generated by gmicompile) ---

type Item struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type MockCallbacks interface {
	ListItems(pattern string) ([]Item, error)
	GetItem(name string) (*Item, error)
	CreateItem(name string, value float64) (*Item, error)
	DeleteItem(name string) error
}

// --- Mock implementation ---

type mockImpl struct {
	items map[string]Item
}

func (m *mockImpl) ListItems(pattern string) ([]Item, error) {
	var result []Item
	for _, item := range m.items {
		if pattern == "" || strings.Contains(item.Name, pattern) {
			result = append(result, item)
		}
	}
	return result, nil
}

func (m *mockImpl) GetItem(name string) (*Item, error) {
	item, ok := m.items[name]
	if !ok {
		return nil, syscall.ENOENT
	}
	return &item, nil
}

func (m *mockImpl) CreateItem(name string, value float64) (*Item, error) {
	if _, exists := m.items[name]; exists {
		return nil, syscall.EEXIST
	}
	item := Item{Name: name, Value: value}
	m.items[name] = item
	return &item, nil
}

func (m *mockImpl) DeleteItem(name string) error {
	if _, ok := m.items[name]; !ok {
		return syscall.ENOENT
	}
	delete(m.items, name)
	return nil
}

// --- Dispatch functions (these would normally be generated) ---

func dispatchListItems(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*MockCallbacks)(callbacks)
	var params struct {
		Pattern string `json:"pattern"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.ListItems(params.Pattern)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func dispatchGetItem(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*MockCallbacks)(callbacks)
	var params struct {
		Name string `json:"name"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.GetItem(params.Name)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func dispatchCreateItem(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*MockCallbacks)(callbacks)
	var params struct {
		Name  string  `json:"name"`
		Value float64 `json:"value"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.CreateItem(params.Name, params.Value)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func dispatchDeleteItem(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*MockCallbacks)(callbacks)
	var params struct {
		Name string `json:"name"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	err := impl.DeleteItem(params.Name)
	if err != nil {
		return nil, err
	}
	return nil, nil
}

// --- Setup: register API just like generated code would ---

func setupIntegrationServer(t *testing.T) *httptest.Server {
	t.Helper()

	impl := &mockImpl{items: map[string]Item{
		"axis.0.pos-cmd": {Name: "axis.0.pos-cmd", Value: 1.23},
		"axis.1.vel":     {Name: "axis.1.vel", Value: 4.56},
	}}

	var cb MockCallbacks = impl

	meta := &apiserver.APIMeta{
		Name:       "items",
		Version:    1,
		RESTExport: true,
		Prefix:     "items",
		Funcs: []apiserver.FuncMeta{
			{Name: "list_items", Method: "GET", Path: "/items", Dispatch: dispatchListItems},
			{Name: "get_item", Method: "GET", Path: "/item/{name}", Dispatch: dispatchGetItem},
			{Name: "create_item", Method: "POST", Path: "/item", Dispatch: dispatchCreateItem},
			{Name: "delete_item", Method: "DELETE", Path: "/item/{name}", Dispatch: dispatchDeleteItem},
		},
	}

	reg := apiserver.NewRegistry()
	apiserver.RegisterMeta(meta)
	err := reg.Register("items", 1, "items0", unsafe.Pointer(&cb))
	if err != nil {
		t.Fatalf("Register: %v", err)
	}

	srv := apiserver.NewServer(reg, "localhost:0")
	ts := httptest.NewServer(srv.Handler())
	t.Cleanup(ts.Close)
	return ts
}

// --- Integration Tests ---

func TestIntegrationListItems(t *testing.T) {
	ts := setupIntegrationServer(t)

	resp, err := http.Get(ts.URL + "/api/v1/items0/items")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, body = %s", resp.StatusCode, body)
	}

	var items []Item
	json.NewDecoder(resp.Body).Decode(&items)
	if len(items) != 2 {
		t.Errorf("got %d items, want 2", len(items))
	}
}

func TestIntegrationListItemsWithFilter(t *testing.T) {
	ts := setupIntegrationServer(t)

	resp, err := http.Get(ts.URL + "/api/v1/items0/items?pattern=axis.0")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		t.Fatalf("status = %d", resp.StatusCode)
	}

	var items []Item
	json.NewDecoder(resp.Body).Decode(&items)
	if len(items) != 1 {
		t.Errorf("got %d items, want 1", len(items))
	}
	if len(items) == 1 && items[0].Name != "axis.0.pos-cmd" {
		t.Errorf("item name = %q, want axis.0.pos-cmd", items[0].Name)
	}
}

func TestIntegrationGetItem(t *testing.T) {
	ts := setupIntegrationServer(t)

	resp, err := http.Get(ts.URL + "/api/v1/items0/item/axis.0.pos-cmd")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, body = %s", resp.StatusCode, body)
	}

	var item Item
	json.NewDecoder(resp.Body).Decode(&item)
	if item.Name != "axis.0.pos-cmd" {
		t.Errorf("name = %q, want axis.0.pos-cmd", item.Name)
	}
	if item.Value != 1.23 {
		t.Errorf("value = %f, want 1.23", item.Value)
	}
}

func TestIntegrationGetItemNotFound(t *testing.T) {
	ts := setupIntegrationServer(t)

	resp, err := http.Get(ts.URL + "/api/v1/items0/item/nonexistent")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 404 {
		t.Errorf("status = %d, want 404", resp.StatusCode)
	}
}

func TestIntegrationCreateItem(t *testing.T) {
	ts := setupIntegrationServer(t)

	body := `{"name":"new-item","value":7.89}`
	resp, err := http.Post(ts.URL+"/api/v1/items0/item", "application/json", strings.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		respBody, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, body = %s", resp.StatusCode, respBody)
	}

	var item Item
	json.NewDecoder(resp.Body).Decode(&item)
	if item.Name != "new-item" {
		t.Errorf("name = %q, want new-item", item.Name)
	}
	if item.Value != 7.89 {
		t.Errorf("value = %f, want 7.89", item.Value)
	}

	// Verify item exists via GET
	resp2, _ := http.Get(ts.URL + "/api/v1/items0/item/new-item")
	defer resp2.Body.Close()
	if resp2.StatusCode != 200 {
		t.Errorf("created item not found: status = %d", resp2.StatusCode)
	}
}

func TestIntegrationCreateItemDuplicate(t *testing.T) {
	ts := setupIntegrationServer(t)

	body := `{"name":"axis.0.pos-cmd","value":0}`
	resp, err := http.Post(ts.URL+"/api/v1/items0/item", "application/json", strings.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 409 { // EEXIST → Conflict
		t.Errorf("status = %d, want 409", resp.StatusCode)
	}
}

func TestIntegrationDeleteItem(t *testing.T) {
	ts := setupIntegrationServer(t)

	req, _ := http.NewRequest("DELETE", ts.URL+"/api/v1/items0/item/axis.0.pos-cmd", nil)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("DELETE status = %d, body = %s", resp.StatusCode, body)
	}

	// Verify item is gone
	resp2, _ := http.Get(ts.URL + "/api/v1/items0/item/axis.0.pos-cmd")
	defer resp2.Body.Close()
	if resp2.StatusCode != 404 {
		t.Errorf("deleted item still found: status = %d", resp2.StatusCode)
	}
}

func TestIntegrationDeleteItemNotFound(t *testing.T) {
	ts := setupIntegrationServer(t)

	req, _ := http.NewRequest("DELETE", ts.URL+"/api/v1/items0/item/nonexistent", nil)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 404 {
		t.Errorf("status = %d, want 404", resp.StatusCode)
	}
}

func TestIntegrationCRUDSequence(t *testing.T) {
	ts := setupIntegrationServer(t)
	baseURL := ts.URL + "/api/v1/items0"

	// 1. List → 2 items
	resp, _ := http.Get(baseURL + "/items")
	var items []Item
	json.NewDecoder(resp.Body).Decode(&items)
	resp.Body.Close()
	if len(items) != 2 {
		t.Fatalf("initial list: got %d items, want 2", len(items))
	}

	// 2. Create new item
	resp, _ = http.Post(baseURL+"/item", "application/json",
		strings.NewReader(`{"name":"new","value":99}`))
	resp.Body.Close()
	if resp.StatusCode != 200 {
		t.Fatalf("create: status %d", resp.StatusCode)
	}

	// 3. List → 3 items
	resp, _ = http.Get(baseURL + "/items")
	json.NewDecoder(resp.Body).Decode(&items)
	resp.Body.Close()
	if len(items) != 3 {
		t.Fatalf("after create: got %d items, want 3", len(items))
	}

	// 4. Get new item
	resp, _ = http.Get(baseURL + "/item/new")
	var item Item
	json.NewDecoder(resp.Body).Decode(&item)
	resp.Body.Close()
	if item.Value != 99 {
		t.Errorf("get new: value = %f, want 99", item.Value)
	}

	// 5. Delete new item
	req, _ := http.NewRequest("DELETE", baseURL+"/item/new", nil)
	resp, _ = http.DefaultClient.Do(req)
	resp.Body.Close()

	// 6. List → 2 items again
	resp, _ = http.Get(baseURL + "/items")
	json.NewDecoder(resp.Body).Decode(&items)
	resp.Body.Close()
	if len(items) != 2 {
		t.Fatalf("after delete: got %d items, want 2", len(items))
	}

	// 7. Get deleted item → 404
	resp, _ = http.Get(baseURL + "/item/new")
	resp.Body.Close()
	if resp.StatusCode != 404 {
		t.Errorf("deleted item: status %d, want 404", resp.StatusCode)
	}
}

func TestIntegrationVersionMismatch(t *testing.T) {
	reg := apiserver.NewRegistry()
	impl := &mockImpl{items: map[string]Item{}}
	var cb MockCallbacks = impl
	reg.Register("v", 3, "v0", unsafe.Pointer(&cb))

	_, err := reg.GetAPIUntracked("v", "v0", 2)
	if err != syscall.EINVAL {
		t.Errorf("version mismatch: got %v, want EINVAL", err)
	}

	_, err = reg.GetAPIUntracked("v", "v0", 3)
	if err != nil {
		t.Errorf("exact version: got %v, want nil", err)
	}
}

func TestIntegrationMultipleAPIs(t *testing.T) {
	reg := apiserver.NewRegistry()
	impl := &mockImpl{items: map[string]Item{"x": {Name: "x", Value: 1}}}
	var cb MockCallbacks = impl

	meta1 := &apiserver.APIMeta{
		Name: "api1", Version: 1, RESTExport: true, Prefix: "api1",
		Funcs: []apiserver.FuncMeta{
			{Name: "list", Method: "GET", Path: "/items", Dispatch: dispatchListItems},
		},
	}
	meta2 := &apiserver.APIMeta{
		Name: "api2", Version: 1, RESTExport: true, Prefix: "api2",
		Funcs: []apiserver.FuncMeta{
			{Name: "list", Method: "GET", Path: "/items", Dispatch: dispatchListItems},
		},
	}

	apiserver.RegisterMeta(meta1)
	apiserver.RegisterMeta(meta2)

	reg.Register("api1", 1, "a1", unsafe.Pointer(&cb))
	reg.Register("api2", 1, "a2", unsafe.Pointer(&cb))

	srv := apiserver.NewServer(reg, "localhost:0")
	ts := httptest.NewServer(srv.Handler())
	defer ts.Close()

	for _, inst := range []string{"a1", "a2"} {
		resp, err := http.Get(fmt.Sprintf("%s/api/v1/%s/items", ts.URL, inst))
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		if resp.StatusCode != 200 {
			t.Errorf("%s: status %d, want 200", inst, resp.StatusCode)
		}
	}
}
