#!/bin/bash

if [ $# -eq 0 ]; then
    echo -e '\nlocale is missing\n'
    exit
elif [ ${#1} -ne 2 ]; then
    echo -e '\nlocale needs to be two characters\n'
    exit
fi

echo -e '\ncreating language translation file qtdragon_lathe_'$1'.ts\n'

pylupdate5 *.py ../*.py  -ts qtdragon_lathe_$1.ts
