# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtdragon.ui'
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


