:manvolnum: 3

= hal_list_funct(3)

== NAME

hal_list_funct - Iterate HAL functions

== SYNOPSIS

[source,c]
----
#include <hal.h>

typedef int (*hal_query_cb)(hal_query_t *query, void *arg);

int hal_list_funct(hal_query_t *query, hal_query_cb callback, void *arg);
----

== ARGUMENTS

query::
  The query structure that returns all data found.

callback::
  The callback function to invoke for each signal found.

arg::
  A user defined pointer to a user defined data structure.
  The _arg_ pointer is passed verbatim to the _callback_ function.

== DESCRIPTION

The *hal_list_funct()* function will iterate all registered components and call the _callback_ for each.
The _query_ structure should be set to zero before the call.

The _callback_ is called with all fields set appropriately.
The _query.qtype_ is set to `HAL_QTYPE_FUNCT`.

The iteration continues until no more components are available or the _callback_ returns non-zero.
You can return a positive value from the _callback_ to signal termination of iteration without triggering an error.
The return value from the _callback_ is returned from the *hal_list_comp()* function as is.

== RETURN VALUE

Returns zero (0) on success.
The return value of the _callback_ is returned if it was non-zero.
A negative errno code is returned if any problem is detected:

[horizontal]
-EFAULT:: The shared memory was not mapped.
-EINVAL:: An invalid argument was passed.

== EXAMPLES

[source,c]
----
static int print_functs_cb(hal_query_t *query, void *arg)
{
    const char *pattern = (const char *)arg;

    if(!fnmatch(pattern, query->name, FNM_NOESCAPE|FNM_CASEFOLD)) {
        printf("%s %s(%d) %d %s\n",
            query->name,
            query->funct.comp,
            query->funct.comp_id,
            query->funct.users,
            query->funct.reentrant ? "reentrant" : "non-reentrant");
    }
    return 0; // Keep on going
}

// Print functions that match a pattern
int print_functs(const char *pattern)
{
    hal_query_t query = {};

    int rv = hal_list_funct(&query, print_functs_cb, (void *)pattern);

    if(0 != rv)
        printf("Iteration failure: %s", hal_strerror(rv));
    return rv;
}
----

== SEE ALSO

hal_query_t(3)
