:manvolnum: 3

= hal_list_s(3)

== NAME

hal_list_s - Iterate HAL signals

== SYNOPSIS

[source,c]
----
#include <hal.h>

typedef int (*hal_query_cb)(hal_query_t *query, void *arg);

int hal_list_s(hal_query_t *query, hal_query_cb callback, void *arg);
----

== ARGUMENTS

query::
  The query structure that returns all data found.

callback::
  The callback function to invoke for each signal found.

arg::
  A user defined pointer to a user defined data structure.
  The _arg_ pointer is passed verbatim to the _callback_ function.

== DESCRIPTION

The *hal_list_s()* function will iterate all registered signals and call the _callback_ for each.
The _query_ structure should be set to zero before the call.

The _callback_ is called with all fields set appropriately, including value and data reference.
The _query.qtype_ is set to `HAL_QTYPE_SIGNAL`.
You must demultiplex the _query.sig.value_ and _query.sig.ref_ according to the _query.sig.type_ field in the callback function.

The iteration continues until no more signals are available or the _callback_ returns non-zero.
You can return a positive value from the _callback_ to signal termination of iteration without triggering an error.
The return value from the _callback_ is returned from the *hal_list_s()* function as is.

== RETURN VALUE

Returns zero (0) on success.
The return value of the _callback_ is returned if it was non-zero.
A negative errno code is returned if any problem is detected:

[horizontal]
-EFAULT:: The shared memory was not mapped.
-EINVAL:: An invalid argument was passed.
-EBADF:: An invalid type was detected.

== EXAMPLES

[source,c]
----
static int print_sigs_cb(hal_query_t *query, void *arg)
{
    const char *pattern = (const char *)arg;

    if(!fnmatch(pattern, query->name, FNM_NOESCAPE|FNM_CASEFOLD)) {
        printf("%s (%s): ", query->name, query->sig.writers ? "driven" : "not driven");
        switch(query->sig.type) {
        case HAL_BOOL: printf("%s\n",  query->sig.value.b ? "true" : "false"); break;
        case HAL_REAL: printf("%f\n",  query->sig.value.r); break;
        case HAL_SINT: printf("%ld\n", query->sig.value.s); break;
        case HAL_UINT: printf("%lu\n", query->sig.value.u); break;
        /* case HAL_PORT: could also happen, but that is left to the reader */
        default: printf("unsupported value type %d\n", (int)query->sig.type); break;
        }
    }
    return 0; // Keep on going
}

// Print signals that match a pattern
int print_sigs(const char *pattern)
{
    hal_query_t query = {};

    int rv = hal_list_s(&query, print_sigs_cb, (void *)pattern);

    if(0 != rv)
        printf("Iteration failure: %s", hal_strerror(rv));
    return rv;
}
----

== SEE ALSO

hal_query_t(3),
hal_list_p(3), hal_list_p_s(3),
hal_get_s(3)
