:manvolnum: 3

= hal_list_p_s(3)

== NAME

hal_list_p_s - Iterate HAL pins connected to a specific signal

== SYNOPSIS

[source,c]
----
#include <hal.h>

typedef int (*hal_query_cb)(hal_query_t *query, void *arg);

int hal_list_p_s(hal_query_t *query, hal_query_cb callback, void *arg);
----

== ARGUMENTS

query::
  The query structure containing the data to search for and returns all data found.

callback::
  The callback function to invoke for each signal found.

arg::
  A user defined pointer to a user defined data structure.
  The _arg_ pointer is passed verbatim to the _callback_ function.

== DESCRIPTION

The *hal_list_p_s()* function will iterate all pins connected to a specific signal and call the _callback_ for each.
The _query_ structure should be set to zero before the call, except the _query.name_ field.
The _query.name_ must be set to the signal to search for.

The _callback_ is called with all fields set appropriately, including value and data reference.
The _query.qtype_ is set to `HAL_QTYPE_PIN` for each pin found.
You must demultiplex the _query.pp.value_ and _query.pp.ref_ according to the _query.pp.type_ field in the callback function.
However, the pin type is always the same as the signal type or they could not be connected.
If you know the signal type, then you could use that for the pins too.

The iteration continues until no more connected pins are found or the _callback_ returns non-zero.
You can return a positive value from the _callback_ to signal termination of iteration without triggering an error.
The return value from the _callback_ is returned from the *hal_list_p_s()* function as is.

== RETURN VALUE

Returns zero (0) on success.
The return value of the _callback_ is returned if it was non-zero.
A negative errno code is returned if any problem is detected:

[horizontal]
-EFAULT:: The shared memory was not mapped.
-EINVAL:: An invalid argument was passed.
-ENOENT:: The signal is not found.
-EBADF:: An invalid type was detected.

== EXAMPLES

[source,c]
----
static int print_sigpins_cb(hal_query_t *query, void *arg)
{
    (void)arg; // Not used in this example

    printf("%s: %s: ", query->pp.signal, query->name);
    if(HAL_OUT == query->pp.dir)
        printf("out: ");
    else if(HAL_IN == query->pp.dir)
        printf("in : ");
    else
        printf("io : ");
    switch(query->pp.type) {
    case HAL_BOOL: printf("%s\n",  query->pp.value.b ? "true" : "false"); break;
    case HAL_REAL: printf("%f\n",  query->pp.value.r); break;
    case HAL_SINT: printf("%ld\n", query->pp.value.s); break;
    case HAL_PORT:
    case HAL_UINT: printf("%lu\n", query->pp.value.u); break;
    default: printf("unsupported value type %d\n", (int)query->pp.type); break;
    }
    return 0; // Keep on going
}

// Print only pins that match a pattern
int print_sigpins(const char *signame)
{
    hal_query_t query = {};
    query.name = signame;

    int rv = hal_list_p_s(&query, print_sigpins_cb, NULL);

    if(0 != rv)
        printf("Iteration failure: %s", hal_strerror(rv));
    return rv;
}
----

== SEE ALSO

hal_query_t(3),
hal_list_p(3), hal_list_s(3),
hal_get_p(3), hal_get_s(3)
