= PM_ROTATION_VECTOR(3)

== NAME

PM_ROTATION_VECTOR - Three-axis cartesian position

== SYNTAX

[source,c]
----
#include <posemath.h>
struct PM_CARTESIAN;
----

== CONSTRUCTORS

PM_CARTESIAN()::
  Construct the point <0,0,0>.
PMCARTESIAN(double _x_, double _y_, double _z_)::
  Construct the point (__x__, __y__, __z__).
PMCARTESIAN(const PM_CARTESIAN &v)::
  Construct a copy of point __v__.

== DATA

[source,c]
----
double x, y, z ;
----

== OPERATORS

operator[](int _n_);::
  Return the __n__^th^ component of the vector (x=0, y=1, z=2) +
  FIXME: Unclear.

int operator==(PM_CARTESIAN __v~1~_, PM_CARTESIAN __v~2~__)::
int operator!=(PM_CARTESIAN __v~1~_, PM_CARTESIAN __v~2~__)::
  Elementwise equality and inequality operator

PM_CARTESIAN operator+(PM_CARTESIAN __v~1~__, PM_CARTESIAN __v~2~__)::
PM_CARTESIAN operator-(PM_CARTESIAN __v~1~__, PM_CARTESIAN __v~2~__)::
  Addition and subtraction of vectors

PM_CARTESIAN operator*(double _s_, PM_CARTESIAN _v_)::
PM_CARTESIAN operator*(PM_CARTESIAN _v_, double _s_)::
  Scalar multiplication of _v_ by _s_.

PM_CARTESIAN operator/(PM_CARTESIAN _v_, double _s_)::
  Scalar multiplication of _v_ by _1/s_

== OTHER FUNCTIONS ON PM_CARTESIAN OBJECTS

double dot(PM_CARTESIAN __v~l~__, PM_CARTESIAN __v~2~__)::
  Returns the dot product of the two vectors.
  Both vectors are required to have the same length, the return value
  is the sum of the pairwise products of the vectors' components.

PM_CARTESIAN cross(PM_CARTESIAN __v~1~__, PM_CARTESIAN __v~2~__)::
  Returns the cross-product of two vectors, which in 3D
  yields a vector that is orthogonal to both v~1~ and v~2~.
  See https://en.wikipedia.org/wiki/Cross_product .

PM_CARTESIAN norm(PM_CARTESIAN _v_)::
  FIXME: It just normalizes _v_, right?
  
