#!/usr/bin/python

import os
import gtk

import emc
from gremlin import Gremlin

def W(p, k, *args, **kw):
    w = k(*args, **kw)
    w.show()
    p.add(w)
    return w

class GremlinApp(gtk.Window):
    def __init__(self, inifile):
        if not inifile:
            inifile = os.environ.get('INI_FILE_NAME', None)

        inifile = emc.ini(inifile)
        gtk.Window.__init__(self)

        self.vbox = W(self, gtk.VBox)
        self.gremlin = W(self.vbox, Gremlin, inifile)
        self.gremlin.set_size_request(400, 400)

        self.connect("destroy", self.quit)

        self.show()
    def quit(self, event):
        gtk.main_quit()

def main():
    from sys import argv
    g = GremlinApp(argv[1])
    gtk.main()

if __name__ == '__main__': raise SystemExit, main()
