# Makefile for compiling the interface between HAL and emc

include ../../../Makefile.inc

HEADERS = \
	extintf.h

SRCS =

BINS =

OBJS =

all: headers

# Generic rules.
include ../../../Make.rules

headers: def_headers

indent: def_indent

depend: def_depend

clean: def_clean

.PHONY: all clean install indent depend headers
