#!/bin/sh
#
# Based on tests/single-step/

set -e

cd $(dirname $0)

if ! linuxcnc -r linuxcnc-test.ini ; then
    echo "error: failed to execute linuxcnc"
    exit 1
fi

echo "success: linuxcnc ran successfully."
exit 0
