:lang: en

[[cha:gs2-vfd-driver]]
= Variateur de fréquence GS2

Composant de HAL pour la série de variateurs de fréquence GS2 fournie par
la société Automation Direct. footnote:[En Europe on trouve l'équivalent sous la marque Omron.]

Ce composant est chargé en utilisant la commande suivante:

----
loadusr -Wn spindle-vfd gs2_vfd -n spindle-vfd
----

The above command says: loadusr, wait for named to load,
component gs2_vfd, named spindle-vfd.
La commande de HAL _loadusr_ est détaillée au chapitre: <<sec:loadusr,loadusr>>.

== Options spécifiques au chargement

* '-b' ou '--bits <n>' (défaut 8) Fixe le nombre de bits de donnée à _<n>_, dans
  lequel _<n>' doit être compris entre 5 et 8 inclus.
* '-d' ou '--device <path>' (défaut /dev/ttyS0) Fixe le nom de la liaison série
  à utiliser.
* '-g' ou '--debug' Active les messages de débogage.
  Le drapeau du mode verbeux pourra être activé. Le débogage affichera tous
  les messages modbus en hexadécimal sur terminal.
* '-n' ou '--name <string>' (défaut gs2_vfd) Fixe le nom du composant de HAL à
  _<string>_, les noms de toutes ses pins et paramètres commenceront également
  par _<string>_.
* '-p' ou '--parity {even, odd, none}' (défaut odd) Fixe la parité de la liaison
  série à parité paire, parité impaire ou sans parité.
* '-r' ou '--rate <n>' (défaut 38400) Fixe le débit de la liaisons à _<n>_.
  C'est une erreur si le débit n'est pas une des valeurs suivantes: 110, 300,
  600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200.
* '-s' ou '--stopbits {1,2}' (défaut 1) Fixe le nombre de bits de stop de la liaison série à 1 ou 2.
* '-t' ou '--target <n>' (défaut 1) Fixe le nombre de cibles MODBUS (esclaves).
  Doit correspondre au nombre de périphériques réglé dans le GS2.
* '-v' ou '--verbose' Active les messages de débogage. Noter qu'en cas d'erreurs série, cela ne fera pas beaucoup de différence ce qui peut être gênant.
* '-A ou --accel-seconds' <n> (default 10.0) Seconds to accelerate the spindle
  from 0 to Max RPM.
* '-D or --decel-seconds' <n> (default 0.0) Seconds to decelerate the spindle
  from Max RPM to 0. If set to 0.0 the spindle will be allowed to coast to a
  stop without controlled deceleration.
* '-R or --braking-resistor' This argument should be used when a braking
  resistor is installed on the GS2 VFD (see Appendix A of the GS2 manual).
  It disables deceleration over-voltage stall prevention (see GS2 modbus
  Parameter 6.05), allowing the VFD to keep braking even in situations where
  the motor is regenerating high voltage. The regenerated voltage gets safely
  dumped into the braking resistor.

[NOTE]
That if there are serial configuration errors, turning on verbose
may result in a flood of timeout errors.

== Consignes de dialogue avec le variateur

Les valeurs _<name>_ sont les noms donnés par l'option _-n_ durant la phase de chargement du composant.

* _<name>.DC-bus-volts_ (float, out) La tension du bus DC sur le variateur.
* _<name>.at-speed_ (bit, out) Quand la consigne vitesse est atteinte.
* _<name>.err-reset_ (bit, in) Envoi d'un _reset errors_ au variateur.
* _<name>.firmware-revision_ (s32, out) envoyé par le variateur.
* _<name>.frequency-command_ (float, out) envoyé par le variateur.
* _<name>.frequency-out_ (float, out) envoyé par le variateur.
* _<name>.is-stopped_ (bit, out) when the VFD reports 0 Hz output.
* _<name>.load-percentage_ (float, out) envoyé par le variateur.
* _<name>.motor-RPM_ (float, out) envoyé par le variateur.
* _<name>.output-current_ (float, out) envoyé par le variateur.
* _<name>.output-voltage_ (float, out) envoyé par le variateur.
* _<name>.power-factor_ (float, out) envoyé par le variateur.
* _<name>.scale-frequency_ (float, out) envoyé par le variateur.
* _<name>.speed-command_ (float, in) Consigne vitesse envoyée.
  au variateur en tr.mn^-1^. C'est une erreur d'envoyer une consigne de
  vitesse supérieure à la valeur maximum réglée dans le variateur.
* _<name>.spindle-fwd_ (bit, in) Sens de rotation envoyé au variateur, 1 pour le sens horaire et 0 pour le sens anti-horaire.
* _<name>.spindle-rev_ (bit, in) 1 pour marche en sens anti-horaire et 0 pour ARRÊT.
* _<name>.spindle-on_ (bit, in) 1 pour MARCHE et 0 pour ARRÊT du variateur.
* _<name>.status-1_ (s32, out) Drive Status du VFD (voir le manuel du GS2).
* _<name>.status-2_ (s32, out) Drive Status du VFD (voir le manuel du GS2).

[NOTE]
La valeur est la somme de tous les bits à 1. Ainsi, 163
signifie que le pilote est dans le mode de marche qui est la somme de: 3 (marche) + 32
(fréquence fixée par liaison série) + 128 (opération fixée par liaison série).

== Paramètres de réglage du variateur

Les valeurs _<name>_ sont les noms donnés par l'option _-n_ durant la phase de chargement du composant.

* _<name>.error-count_ (s32, RW) 
* _<name>.loop-time_ (float, RW) Nombre d'interrogation d modbus (défaut 0.1).
* _<name>.nameplate-HZ_ (float, RW) Vitesse plaquée du moteur en Hz (défaut 50).
* _<name>.nameplate-RPM_ (float, RW) Vitesse plaquée du moteur en tr.mn^-1^ (défaut 1500).
* _<name>.retval_ (s32, RW) la valeur de retour d'une erreur dans HAL.
* _<name>.tolerance_ (s32, RW) Tolérance en vitesse (défaut 0.01).
* _<n>.ack-delay_ (s32, RW) number of read/write cycles before checking at-speed
  (default 2)

Un exemple d'utilisation d'un variateur de fréquence pour piloter une broche
est donné dans le manuel de l'intégrateur au chapitre Exemples: utiliser un GS2.
