[[cha:mb2hal]]

= MB2HAL

MB2HAL is a generic userspace HAL component to communicate with one or more Modbus devices.
So far, there are two options to communicate with a Modbus device:

. One option is to create a HAL component as a driver see 
http://wiki.linuxcnc.org/cgi-bin/wiki.pl?VFD_Modbus[VFD Modbus].
. Another option is to use Classic Ladder which has Modbus built in see
<<cha:classicladder,ClassicLadder>>.
. Now there is a third option that consists of a "generic" driver configured by text file, this is called MB2HAL.
Why MB2HAL ?
Consider using Mb2hal if:

* You have to write a new driver and you don't know anything about programming. 
* You need to use Classic Ladder "only" to manage the Modbus connections. 
* You have to discover and configure first time the Modbus transactions. Mb2hal have debug levels to facilitate the low level protocol debug. 
* You have more than one device to connect. Mb2hal is very efficient managing multiple devices, transactions and links. Currently i am monitoring two axis drivers using a Rs232 port, a VFD driver using another Rs232 port, and a remote I/O using TCP/IP. 
* You want a protocol to connect your Arduino to HAL. Look the included sample configuration file, sketch and library for Arduino Modbus. 

== Example config file.
----
#This .INI file is also the HELP, MANUAL and HOW-TO file for mb2hal.

#Load the modbus HAL userspace module as the examples below,
#change to match your own HAL_MODULE_NAME and .ini file name
#Using HAL_MODULE_NAME=mb2hal or nothing (default): loadusr -W mb2hal config=config_file.ini
#Using HAL_MODULE_NAME=mymodule: loadusr -Wn mymodule mb2hal config=config_file.ini

#Common section

[MB2HAL_INIT]


== Example config file
Click link:mb2hal_HOWTO.ini[here] to download.
[source,ini]
----
include::../../../src/hal/user_comps/mb2hal/mb2hal_HOWTO.ini[]
----