CLARKEINV
=========

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<functions,FUNCTIONS>>
. <<pins,PINS>>
. <<see,SEE>>
. <<license,LICENSE>>




===== [[name]]NAME

clarkeinv -- Inverse Clarke transform


===== [[synopsis]]SYNOPSIS
loadrt clarkeinv [count=__N__**|names=**__name1__**[,**__name2...__**]]
**

===== [[description]]DESCRIPTION

The inverse Clarke transform can be used rotate a 
vector quantity and then translate it from Cartesian coordinate
system to a three phase system (three components 120 degrees apart).


===== [[functions]]FUNCTIONS

**clarkeinv.**__N__ (requires a floating-point thread)



===== [[pins]]PINS

clarkeinv.__N__**.x** float in 
clarkeinv.__N__**.y** float in 
cartesian components of input

clarkeinv.__N__**.h** float in 
homopolar component of input (usually zero)

clarkeinv.__N__**.theta** float in 
rotation angle: 0.00 to 1.00 = 0 to 360 degrees

clarkeinv.__N__**.a** float out 
clarkeinv.__N__**.b** float out 
clarkeinv.__N__**.c** float out 
three phase output vector


===== [[see]]SEE

**clarke2** and **clarke3** for the forward transform.


===== [[license]]LICENSE

GPL
