ONESHOT
=======

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<functions,FUNCTIONS>>
. <<pins,PINS>>
. <<parameters,PARAMETERS>>
. <<license,LICENSE>>




===== [[name]]NAME

oneshot -- one-shot pulse generator


===== [[synopsis]]SYNOPSIS
loadrt oneshot [count=__N__**|names=**__name1__**[,**__name2...__**]]
**

===== [[description]]DESCRIPTION

creates a variable-length output pulse when the input changes 
state. This function needs to run in a thread which supports floating point
(typically the servo thread). This means that the pulse length has to be a
multiple of that thread period, typically 1mS. 
For a similar function that can run in the base thread, and which offers higher 
resolution, see "edge".


===== [[functions]]FUNCTIONS

**oneshot.**__N__ (requires a floating-point thread)
Produce output pulses from input edges


===== [[pins]]PINS

oneshot.__N__**.in** bit in 
Trigger input

oneshot.__N__**.out** bit out 
Active high pulse

oneshot.__N__**.out-not** bit out 
Active low pulse

oneshot.__N__**.width** float in (default: __0__)
Pulse width in seconds

oneshot.__N__**.time-left** float out 
Time left in current output pulse


===== [[parameters]]PARAMETERS

oneshot.__N__**.retriggerable** bit rw (default: __TRUE__)
Allow additional edges to extend pulse

oneshot.__N__**.rising** bit rw (default: __TRUE__)
Trigger on rising edge

oneshot.__N__**.falling** bit rw (default: __FALSE__)
Trigger on falling edge


===== [[license]]LICENSE

GPL
