:lang: fr
:toc:

[[cha:Halui]]
= L'interface Halui

== Introduction

Halui est une interface utilisateur pour LinuxCNC s'appuyant sur HAL, elle connecte les pins de HAL à des commandes NML. La plupart des
fonctionnalités (boutons, indicateurs etc.) utilisées par les
interfaces graphiques traditionnelles (mini, Axis, etc.), sont fournies
par des pins de HAL dans Halui.

La façon la plus facile pour utiliser halui est d'ajouter la ligne suivante à
la section [HAL] du fichier ini:

----
[HAL]
HALUI = halui
----

Une solution alternative pour l'invoquer (surtout si vous générez la config avec stepconf) est d'inclure la ligne suivante dans votre fichier `custom.hal`. +
Assurez vous d'utiliser le chemin correct vers votre fichier ini.

----
loadusr halui -ini /path/to/inifile.ini
----

== MDI

Sometimes the user wants to add more complicated tasks to be performed
by the activation of a HAL pin. +
This is possible by adding MDI commands to the ini file in the [HALUI] section. +
Example:

----
[HALUI]
MDI_COMMAND = G0 X0
MDI_COMMAND = G0 G53 Z0
MDI_COMMAND = G28
MDI_COMMAND = o<mysub>call
...
----

When halui starts it will read the `MDI_COMMAND` fields in the ini and
export pins from 00 to the number of `MDI_COMMAND` 's found in the ini, up
to a maximum of 64 commands. These pins can be connected like any
hal pins. A common method is to use buttons provided by virtual
control panels. Example halfile connections:

----
net quill-up       <= pyvcp.quillup
net quill-up       => halui.mdi-command-00
net reference-pos  <= pyvcp.referencepos
net reference-pos  => halui.mdi-command-01
net call-mysub     <= pyvcp.callmysub
net call-mysub     => halui.mdi-command-02
----

These nets connect the `halui.mdi-command-NN` pins
provided by halui:

----
$ halcmd show pin halui.mdi
Component Pins:
Owner  Type  Dir Value  Name
   10  bit   IN  FALSE  halui.mdi-command-00 <== quill-up
   10  bit   IN  FALSE  halui.mdi-command-01 <== reference-pos
   10  bit   IN  FALSE  halui.mdi-command-02 <== call-mysub
    ...
----

When a halui MDI pin is set (pulsed) true, halui will send the MDI
command defined in the ini. +
This will not always succeed depending on the current operating
mode (e.g., while in AUTO halui can't successfully send MDI commands).

== Example Configuration

An example sim config (`configs/sim/axis/halui_pyvcp/halui.ini`)
is included in the distribution.

== Nomenclature des pins d'Halui

All halui pins are also documented in the halui man page:

----
$ man halui
----

=== Abandon (abort)

* halui.abort (bit, in) - pin de requête d'abandon (efface les erreurs)

=== Arrêt d'urgence (E-Stop)

* halui.estop.activate (bit, in) - pin de requête d'arrêt d'urgence (E-Stop)
* halui.estop.is-activated (bit, out) - indique si l'arrêt d'urgence est actif
* halui.estop.reset (bit, in) - pin de requête de relâchement de l'arrêt d'urgence (E-Stop reset)

=== Correcteur de vitesse d'avance (Feed override)

* halui.feed-override.count-enable (bit, in) - doit être vraie pour que _counts_ ou _direct-value_ soient opérationnels.
* halui.feed-override.counts (s32, in) - _counts_ * scale = FO pourcent. Peutêtre utilisé avec un codeur ou _direct-value_.
* halui.feed-override.decrease (bit, in) - pin pour diminuer la correction (-=scale)
* halui.feed-override.increase (bit, in) - pin pour augmenter la correction (+=scale)
* halui.feed-override.direct-value (bit, in) - fausse lors de l'utilisation un codeur pour changer counts, vraie pour ajuster counts directement. La pin _count-enable_ doit être vraie.
* halui.feed-override.scale (float, in) - pin pour positionner l'échelle pour accroître ou décroître la correction de vitesse d'avance.
* halui.feed-override.value (float, out) - Valeur de la correction courante de vitesse d'avance

=== Arrosage par gouttelettes (Mist)

* halui.mist.is-on (bit, out) - indique si l'arrosage par gouttelettes est actif
* halui.mist.off (bit, in) - pin de requête d'arrêt de l'arrosage par gouttelettes
* halui.mist.on (bit, in) - pin de requête de l'arrosage par gouttelettes

=== Arrosage fluide (Flood)

* halui.flood.is-on (bit, out) - indique si l'arrosage fluide est actif
* halui.flood.off (bit, in) - pin de requête d'arrêt d'arrosage fluide
* halui.flood.on (bit, in) - pin de requête d'arrosage fluide

=== Prise d'origine machine de tous les axes (Homing)

* halui.home-all (bit, in) - pin de requête de prise d'origine machine de tous les axes.
  Cette pin sera présente seulement si HOME_SEQUENCE est fixée dans le fichier ini.

=== Graissage centralisé (Lube)

* halui.lube.is-on (bit, out) - indique si le graissage est actif
* halui.lube.off (bit, in) - pin de requête d'arrêt du graissage
* halui.lube.on (bit, in) - pin de requête de graissage

=== Machine (Marche / Arrêt)

* 'halui.machine.units-per-mm' (float out) - pin  for  machine  units-per-mm
  (inch:1/25.4,  mm:1) according to inifile setting: [TRAJ]LINEAR_UNITS
* halui.machine.is-on (bit, out) - indique que la machine est en marche
* halui.machine.off (bit, in) - pin de requête d'arrêt machine
* halui.machine.on (bit, in) - pin de requête de marche machine

=== Vitesse maximum

La vitesse linéaire maximum peut être ajustée entre 0 et la valeur de
la variable MAX_VELOCITY dans la section [TRAJ] du fichier ini.

* halui.max-velocity.count-enable (bit, in) - Doit être vraie pour que les _counts_ ou _direct-value_ soit opérationnels.
* halui.max-velocity.counts (s32, in) - counts * scale = MV pourcent. Utilisable avec un codeur ou _direct-value_.
* halui.max-velocity.direct-value (bit, in) - faux quand un codeur est utilisé pour modifier _counts_, vraie pour ajuster _counts_ directement. La pin _count-enable_ doit être vraie.
* halui.max-velocity.decrease (bit, in) - pin pour diminuer la vitesse max
* halui.max-velocity.increase (bit, in) - pin pour augmenter la vitesse max
* halui.max-velocity.scale (float, in) - Valeur appliquée sur le nombre de fronts montants des pins increase ou decrease en unités machine par seconde.
* halui.max-velocity.value (float, out) - Valeur de la vitesse linéaire maximum en unités machine par seconde.

=== MDI

* 'halui.mdi-command-<nn>' (bit, in) - halui will try to send the MDI
  command defined in the ini. <nn> is a  two  digit number  starting  at 00. +
  If the command succeeds then it will place LinuxCNC in the MDI mode and then back to Manual mode. +
  If no [HALUI]MDI_COMMAND variables are set in the  ini  file, no halui.mdi-command-<nn> pins will be
  exported by halui.

=== Articulations (Joints)

N est un nombre compris entre 0 et 8, ou <selected>. +
Exemple:

* halui.joint.N.select (bit, in) - select joint (0..8) - interne à halui
* halui.joint.N.is-selected (bit, out) - pin indiquant que l'articulation est <selected> - interne à halui
* halui.joint.N.has-fault (bit, out) - pin de status indiquant que l'articulation est en défaut
* halui.joint.N.home (bit, in) - pin pour la prise d'origine d'une articulation spécifique 
* halui.joint.N.is-homed (bit, out) - pin de status indiquant que l'articulation est référencée
* halui.joint.N.on-hard-max-limit (bit, out) - pin de status indiquant que le joint est sur son fin de course de limite positive
* halui.joint.N.on-hard-min-limit (bit, out) - pin de status indiquant que le joint est sur son fin de course de limite négative
* halui.joint.N.on-soft-max-limit (bit, out) - pin de status indiquant que le joint est sur sa limite logicielle positive
* halui.joint.N.on-soft-min-limit (bit, out) - pin de status indiquant que le joint est sur sa limite logicielle négative
* 'halui.joint.N.override-limits' (bit out) - status pin telling that joint N's limits are  temporarily  overridden
* halui.joint.N.unhome (bit, in) - unhomes this joint
* halui.joint.selected (u32, out) - selected joint (0..8) - interne à halui
* halui.joint.selected.has-fault (bit, out) - pin de status indiquant que le joint N est en défaut
* halui.joint.selected.home (bit, in) - pin pour la prise d'origine de l'articulation <selected> 
* halui.joint.selected.is-homed (bit, out) - pin de status indiquant que le joint <selected> est référencé
* halui.joint.selected.on-hard-max-limit (bit, out) - pin de status indiquant que le joint <selected> est sur son fin de course de limite positive
* halui.joint.selected.on-hard-min-limit (bit, out) - pin de status indiquant que le joint <selected> est sur son fin de course de limite négative
* halui.joint.selected.on-soft-max-limit (bit, out) - pin de status indiquant que le joint <selected> est sur sa limite logicielle positive
* halui.joint.selected.on-soft-min-limit (bit, out) - pin de status indiquant que le joint <selected> est sur sa limite logicielle négative
* 'halui.joint.selected.override-limits' (bit out) - status  pin  telling that the selected joint's limits are temporarily overridden
* halui.joint.selected.unhome (bit, in) - pin for unhoming  l'articulation selected.

=== Jog (Manivelle)

N est un nombre compris entre 0 et 8, ou <selected>.

* halui.jog-deadband (float, in)- bande morte pour le jogging analogique (les petites vitesses de jog sont sans effet)
* halui.jog.speed (float, in) - positionne la vitesse de jog
* halui.jog.N.analog (float, in) - entrée analogique de vitesse de jog (utilisé avec les joysticks ou autres matériels analogiques)
* 'halui.joint.N.increment' (float in) - pin for setting the jog increment for joint N when using  increment-plus/minus
* 'halui.joint.N.increment-minus' (bit in) - a  rising edge will will make joint N jog in the negative direction by the increment amount
* 'halui.joint.N.increment-plus' (bit in) - a rising edge will will make joint N jog in the positive  direction by the increment amount
* halui.jog.N.minus (bit, in) - jog en direction négative
* halui.jog.N.plus (bit, in) - jog en direction positive
* 'halui.joint.selected.increment' (float in) - pin  for  setting  the jog increment for the selected joint when using increment-plus/minus
* 'halui.joint.selected.increment-minus' (bit in) - a rising edge will will make the selected joint jog in the negative direction by the increment amount
* 'halui.joint.selected.increment-plus' (bit in) - a rising edge will will make the selected joint jog in the positive direction by the increment amount
* halui.jog.selected.minus (bit, in) - jog l'axe <selected> en direction négative et à la vitesse de halui.jog.speed velocity
* halui.jog.selected.plus (bit, in) - jog l'axe <selected> en direction positive et à la vitesse de halui.jog.speed velocity

=== Axes (axis)

L = axis letter (xyzabcuvw)

* 'halui.axis.L.select' (bit) - pin for selecting axis by letter
* 'halui.axis.L.is-selected' (bit out) - status pin that axis L is selected
* halui.axis.L.pos-commanded (float, out) - Position de l'axe commandée, en coordonnées machine
* halui.axis.L.pos-feedback (float, out) - Position de l'axe lue, en coordonnées machine
* halui.axis.L.pos-relative (float, out) - Position de l'axe, en coordonnées relatives

=== Axis Jogging

L = axis letter (xyzabcuvw)

* 'halui.axis.jog-deadband' (float in) - pin  for  setting  jog  analog  deadband  (jog   analog   inputs smaller/slower than this (in absolute value) are ignored)
* 'halui.axis.jog-speed' (float in) - pin for setting jog speed for plus/minus jogging.
* 'halui.axis.L.analog' (float in) - pin for jogging the axis L using an float value (e.g. joystick). The value, typically set between 0.0 and  ±1.0,  is  used as a jog-speed multiplier.
* 'halui.axis.L.increment' (float in) - pin  for  setting the jog increment for axis L when using increment-plus/minus
* 'halui.axis.L.increment-minus' (bit in) - a rising edge will will make axis L jog in the  negative  direction by the increment amount
* 'halui.axis.L.increment-plus' (bit in) - a  rising  edge will will make axis L jog in the positive direction by the increment amount
* 'halui.axis.L.minus' (bit in) - pin  for  jogging  axis  L  in   negative   direction   at   the halui.axis.jog-speed velocity
* 'halui.axis.L.plus' (bit in) - pin   for   jogging   axis   L  in  positive  direction  at  the halui.axis.jog-speed velocity
* 'halui.axis.selected' (u32 out) - selected axis (by index: 0:x 1:y 2:z 3:a 4:b 5:cr 6:u 7:v 8:w)
* 'halui.axis.selected.increment' (float in) - pin for setting the jog increment for  the  selected  axis  when using increment-plus/minus
* 'halui.axis.selected.increment-minus' (bit in) - a  rising edge will will make the selected axis jog in the negative direction by the increment amount
* 'halui.axis.selected.increment-plus' (bit in) - a rising edge will will make the selected axis jog in the  positive direction by the increment amount
* 'halui.axis.selected.minus' (bit in) - pin  for  jogging the selected axis in negative direction at the halui.axis.jog-speed velocity
* 'halui.axis.selected.plus' (pin in) - for jogging the selected axis bit in in positive  direction at the halui.axis.jog-speed velocity

=== Mode de fonctionnement (Mode)

* halui.mode.auto (bit, in) - pin de requête du mode auto
* halui.mode.is_auto (bit, out)- indique si le mode auto est actif
* halui.mode.is-joint (bit, out) - indique si le mode articulation par articulation est actif
* halui.mode.is_manual (bit, out) - indique si le mode manuel est actif
* halui.mode.is_mdi (bit, out) - indique si le mode données manuelles est actif
* halui.mode.is-teleop (bit, out) - indique que le mode jog coordonné est actif
* halui.mode.joint (bit, in) - pin de requête du mode jog articulation par articulation
* halui.mode.manual (bit, in) - pin de requête du mode manuel
* halui.mode.mdi (bit, in) - pin de requête du mode données manuelles
* halui.mode.teleop (bit, in) - pin de requête du mode jog coordonné

=== Programme (Program)

* halui.program.block-delete.is-on (bit, out) - status pin telling that block delete is on
* halui.program.block-delete.off (bit, in) - pin for requesting that block delete is off
* halui.program.block-delete.on (bit, in) - pin for requesting that block delete is on
* halui.program.is-idle (bit, out) - pin de status indiquant qu'aucun programme n'est lancé
* halui.program.is-paused (bit, out) - pin de status indiquant qu'un programme est en pause
* halui.program.is-running (bit, out) - pin de status indiquant qu'un programme est lancé
* halui.program.optional-stop.is-on (bit, out) - status pin telling that the optional stop is on
* halui.program.optional-stop.off (bit, in) - pin requesting that the optional stop is off
* halui.program.optional-stop.on (bit, in) - pin requesting that the optional stop is on
* halui.program.pause (bit, in) - pin pour passer un programme en pause
* halui.program.resume (bit, in) - pin pour lancer la reprise d'un programme
* halui.program.run (bit, in) - pin de lancement d'un programme
* halui.program.step (bit, in) - pin pour avancer d'une ligne de programme
* halui.program.stop (bit, in) - pin pour stopper un programme

=== Correcteur de déplacement Rapide (Rapid Override)

* 'halui.rapid-override.count-enable' (bit in  (default: TRUE)) - When TRUE, modify Rapid Override when counts changes.
* 'halui.rapid-override.counts' (s32 in) - counts X scale = Rapid Override percentage. Can be used with an encoder or 'direct-value'.
* 'halui.rapid-override.decrease' (bit in) - pin for decreasing the Rapid Override (-=scale)
* 'halui.rapid-override.direct-value' (bit in) - pin to enable direct value Rapid Override input
* 'halui.rapid-override.increase' (bit in) - pin for increasing the Rapid Override (+=scale)
* 'halui.rapid-override.scale' (float in) - pin for setting the scale on changing the Rapid Override
* 'halui.rapid-override.value' (float out) - current Rapid Override value

=== Correcteur de vitesse de broche (Spindle Override)

* halui.spindle-override.count-enable (bit, in) - doit être vraie pour que _counts_ ou _direct-value_ soient opérationnels.
* halui.spindle-override.counts (s32, in) - comptage depuis un codeur, par exemple pour modifier la correction de vitesse de broche
* halui.spindle-override.decrease (bit, in) - pin pour diminuer la correction de vitesse de broche (-=scale)
* halui.spindle-override.direct-value (bit, in) - fausse en utilisant un codeur pour modifier _counts_ directement. La pin _count-enable_ doit être vraie.
* halui.spindle-override.increase (bit, in) - pin pour augmenter la correction de vitesse de broche (+=scale)
* halui.spindle-override.scale (float, in) - pin pour positionner l'échelle des corrections de vitesse de broche possibles
* halui.spindle-override.value (float, out) - Valeur courante de la correction de vitesse de broche

=== Broche (Spindle)

* halui.spindle.brake-is-on (bit, out) - indique si le frein est actif
* halui.spindle.brake-off (bit, in) - pin de désactivation du frein de broche
* halui.spindle.brake-on (bit, in) - pin d'activation du frein de broche
* halui.spindle.decrease (bit, in) - Diminue la vitesse de broche
* halui.spindle.forward (bit, in) - Marche broche en sens horaire
* halui.spindle.increase (bit, in) - Augmente la vitesse de broche
* halui.spindle.is-on (bit, out) - indique la broche est en marche (les deux sens)
* halui.spindle.reverse (bit, in) - Marche broche en sens anti-horaire
* halui.spindle.runs-backward (bit, out) - indique la broche est en marche et en sens inverse
* halui.spindle.runs-forward (bit, out) - indique la broche est en marche et en marche avant
* halui.spindle.start (bit, in) - Marche de la broche
* halui.spindle.stop (bit, in) - Arrêt de la broche

=== Outil (Tool)

* 'halui.tool.length-offset.a' (float out) - current applied tool length offset for the A axis
* 'halui.tool.length-offset.b' (float out) - current applied tool length offset for the B axis
* 'halui.tool.length-offset.c' (float out) - current applied tool length offset for the C axis
* 'halui.tool.length-offset.u' (float out) - current applied tool length offset for the U axis
* 'halui.tool.length-offset.v' (float out) - current applied tool length offset for the V axis
* 'halui.tool.length-offset.w' (float out) - current applied tool length offset for the W axis
* 'halui.tool.length-offset.x' (float out) - current applied tool length offset for the X axis
* 'halui.tool.length-offset.y' (float out) - current applied tool length offset for the Y axis
* 'halui.tool.length-offset.z' (float out) - current applied tool length offset for the Z axis
* 'halui.tool.diameter' (float out) - Current tool diameter, or 0 if no tool is loaded.
* 'halui.tool.number' (u32, out) - indicates current selected tool

// vim: set syntax=asciidoc:
