.TH BLOCKS "9" "2007-01-19" "EMC Documentation" "HAL Component"

.SH NAME
blocks \- Old style HAL blocks (deprecated)
.SH SYNOPSIS
.B loadrt blocks [\fIblockname\fB=\fIN\fB]

.SH DESCRIPTION
Most of the items available in \fBblocks\fR are the same as in the individual
components, named below.  \fBblocks\fR is deprecated and should not be used
in new HAL configurations.  \fBblocks\fR may be removed from emc2 as early
as version 2.2.0.

.SH SEE ALSO
\fBconstant(9)\fR, \fBwcomp(9)\fR, \fBcomp(9)\fR, \fBsum2(9)\fR,
\fBmult2(9)\fR, \fBhypot(9)\fR, \fBmux2(9)\fR, \fBmux4(9)\fR, \fBinteg(9)\fR,
\fBddt(9)\fR, \fBlimit1(9)\fR, \fBlimit2(9)\fR, \fBlimit3(9)\fR,
\fBestop_latch(9)\fR (called "estop" in blocks), \fBnot(9)\fR, \fBand2(9)\fR,
\fBor2(9)\fR, \fBscale(9)\fR, \fBlowpass(9)\fR, \fBmatch8(9)\fR,
\fBminmax(9)\fR
