
.\"*******************************************************************
.\"
.\" This file was extracted from hal/components/constant.comp using halcompile.g.
.\" Modify the source file.
.\"
.\"*******************************************************************

.TH CONSTANT "9" "2023-10-21" "LinuxCNC Documentation" "HAL Component"
.SH NAME

constant \- Use a parameter to set the value of a pin
.SH SYNOPSIS
.HP
.B loadrt constant [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBconstant.\fIN\fB\fR (requires a floating-point thread)

.SH PINS
.TP
.B constant.\fIN\fB.out\fR float out \fR
.SH PARAMETERS
.TP
.B constant.\fIN\fB.value\fR float rw \fR
.SH AUTHOR

John Kasunich
.SH LICENSE

GPL
