.TH CONV_BIT_U32 "9" "2020-08-11" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

conv_bit_u32 \- Convert a value from bit to u32
.SH SYNOPSIS
.HP
.B loadrt conv_bit_u32 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBconv-bit-u32.\fIN\fB\fR
Update 'out' based on 'in'
.SH PINS
.TP
.B conv-bit-u32.\fIN\fB.in\fR bit in \fR
.TQ
.B conv-bit-u32.\fIN\fB.out\fR u32 out \fR
.SH LICENSE

GPL
