.TH GANTRYKINS "9" "2010-10-12" "EMC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

gantrykins \- A kinematics module that maps one axis to multiple joints

.SH SYNOPSIS
.HP
.B loadrt gantrykins coordinates=\fIaxisletters

.SS Specifying gantry joint mapping via loadrt
The \fBcoordinates=\fR parameter specifies the initial gantry joint mapping.
Each axis letter is mapped to a joint, starting from 0.  So
\fBcoordinates=XYYZ\fR maps the X axis to joint 0, the Y axis to joint 1 and 2,
and the Z axis to joint 4.  If not specified, the default mapping is
\fBcoordinates=XYZABC\fR.  Coordinate letters may be specified in uppercase
or lowercase.

.SH KINEMATICS
In the inverse kinematics, each joint gets the value of its corresponding axis.
In the forward kinematics, each axis gets the value of the highest numbered
corresponding joint.  For example, with \fBcoordinates=XYYZ\fR the Y axis
position comes from joint 2, not joint 1.

.SH FUNCTIONS
None.  

.SH PINS
None.

.SH PARAMETERS
.TP
.B gantrykins.joint-\fIN\fR (s32)
Specifies the axis mapped to joint \fIN\fR.  The values 0 through 8
correspond to the axes XYZABCUVW.

.SH NOTES
\fBgantrykins\fR must be loaded before \fBmotion\fR.

.SH SEE ALSO
kins(9),
The Kinematics section of the EMC2 Developer Manual

.SH LICENSE
GPL
