.TH HM2_PCI "9" "2008-05-13" "EMC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

hm2_pci \- RTAI driver for the Mesa Electronics 5i20, 4i65, and 5i22 Anything IO boards, with HostMot2 firmware.
.SH SYNOPSIS

.HP
.B loadrt hm2_pci [config=\fI"str"\fB]
.RS 4
.TP
\fBconfig\fR [default: ""]
HostMot2 config string, described in the hostmot2(9) manpage.
.RE
.SH DESCRIPTION

hm2_pci is an RTAI device driver that interfaces the Mesa 5i20 (PCI),
the 4i65 (PC/104-Plus), and the 5i22 (PCI) boards with the HostMot2
firmware to the EMC2 HAL.

This driver replaces the hm2_5i20 driver.

The driver programs the board's FPGA with firmware when it registers
the board with the hostmot2 driver.  The firmware to load is specified
in the \fBconfig\fR modparam, as described in the hostmot2(9) manpage,
in the \fIconfig modparam\fR section.
.SH SEE ALSO

hostmot2(9)
.SH LICENSE

GPL
