.TH HM2_PCI "9" "2008-05-13" "Documentación LinuxCNC" "Componente HAL"
.de TQ
.br
.ns
.TP \\$1
..

.SH NOMBRE

hm2_pci \- Controlador HAL LinuxCNC para las tarjetas Anything IO basadas en PCI de Mesa Electronics, con firmware HostMot2.
.SH SINOPSIS

.HP
.B loadrt hm2_pci [config=\fI"str[,str...]"\fB]
.RS 4
.TP
\fBconfig\fR [predeterminado: ""]
Cadenas de configuración de HostMot2, descritas en la página de manual de hostmot2 (9).
.RE
.SH DESCRIPCIÓN

hm2_pci es un controlador de dispositivo que interconecta tarjetas Mesa's PCI y PC-104/Plus based Anything I/O (con el firmware HostMot2) y LinuxCNC HAL

Las tarjetas compatibles son: 5i20, 5i21, 5i22, 5i23, 5i24 y 5i25 (todas en
PCI); el 4i65, 4i68 y 4i69 (en PC-104/Plus) y 3x20 (usando una
tarjeta portadora 6i68 o 7i68) y 6i25 (en PCI Express).

El controlador opcionalmente programa la FPGA de la tarjeta con firmware cuando registra la tarjeta con el controlador hostmot2. El firmware a cargar está especificado en el modparam \fBconfig\fR, como se describe en la página de manual hostmot2 (9), en la sección \fIconfig modparam\fR.
.SH VER TAMBIÉN

hostmot2 (9)
.SH LICENCIA

GPL
