.\" a large part of this file (the pin names and descriptions) came from
.\" docs/src/config/emc2hal.lyx 
.\"
.TH IOCONTROL "9" "2007-08-25" "EMC Documentation" "HAL Component" 
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME
iocontrol \- accepts NML I/O commands, interacts with HAL in userspace

.SH SYNOPSIS
\fBloadusr io [-ini \fIinifile\fB]


.SH DESCRIPTION
These pins are created by the userspace IO controller, usually found in $EMC2_HOME/bin/io
.P
The signals are turned on and off in userspace - if you have strict timing requirements or simply need more i/o, consider using the realtime synchronized i/o provided by \fBmotion\fR(9) instead.
.P
The inifile is searched for in the directory from which halcmd was run, unless an absolute path is specified.

.SH PINS

.TP
\fBiocontrol.0.coolant-flood
TRUE when flood coolant is requested

.TP
\fBiocontrol.0.coolant-mist 
TRUE when mist coolant is requested

.TP
\fBiocontrol.0.emc-enable-in 
Should be driven FALSE when an external estop condition exists.

.TP
\fBiocontrol.0.lube 
TRUE when lube is requested

.TP
\fBiocontrol.0.lube_level 
Should be driven FALSE when lubrication tank is empty.

.TP
\fBiocontrol.0.tool-change 
TRUE when a tool change is requested

.TP
\fBiocontrol.0.tool-changed 
Should be driven TRUE when a tool change is completed.

.TP
\fBiocontrol.0.tool-prep-number 
The number of the next tool, from the RS274NGC T-word

.TP
\fBiocontrol.0.tool-prepare 
TRUE when a T\fIn\fR tool prepare is requested

.TP
\fBiocontrol.0.tool-prepared 
Should be driven TRUE when a tool prepare is completed.

.TP
\fBiocontrol.0.user-enable-out 
FALSE when an internal estop condition exists

.TP
\fBiocontrol.0.user-request-enable 
TRUE when the user has requested that estop be cleared

.SH SEE ALSO
\fBmotion\fR(9)


