.TH SETSERIAL "9" "2012-10-28" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME
setsserial - a utility for setting Smart Serial NVRAM parameters. 
.SH SYNOPSIS
.HP
.B loadrt setsserial cmd="set hm2_8i20.001f.nvmaxcurrent 750"
.SH FUNCTIONS
.TP
None
.SH PINS
.TP
None
.SH USAGE
.TP

.RE
.SH LICENSE

GPL
