.TH SKELETON "9" "2007-01-16" "EMC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME
skeleton \- gives the general format of manual pages for HAL components
.SH SYNOPSIS
.B loadrt skeleton [count=\fIN\fB]
.SH DESCRIPTION
.SH FUNCTIONS
\" .TP 
\" \fBskeleton.\fIN\fB (uses floating-point)
\" Describe the function here

.SH PINS
\" .TP  
\" .B skeleton.\fIN\fB.in float in 
\" Analog input value

.SH PARAMETERS
\" .TP  
\" .B skeleton.\fIN\fB.gain float rw 
\" Analog gain value

.SH SEE ALSO
