.TH XHC_HB04_UTIL "9" "2014-03-02" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

xhc_hb04_util \- xhc-hb04 convenience utility
.SH SYNOPSIS
.HP
.B loadrt xhc_hb04_util [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH DESCRIPTION

Provides logic for a start/pause button and an interface
to halui.program.is_paused,is_idle,is_running to generate outputs for
halui.program.pause,resume,run.

Includes 4 simple lowpass filters with coef and scale pins.  The coef value should
be 0 <= coef <=1, smaller coef values slow response.  Note: the xhc_hb04
component includes smoothing so these values can usually be left at 1.0

.SH FUNCTIONS
.TP
\fBxhc-hb04-util.\fIN\fB\fR (requires a floating-point thread)

.SH PINS
.TP
.B xhc-hb04-util.\fIN\fB.start-or-pause\fR bit in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.is-paused\fR bit in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.is-idle\fR bit in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.is-running\fR bit in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.pause\fR bit out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.resume\fR bit out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.run\fR bit out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.in0\fR s32 in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.in1\fR s32 in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.in2\fR s32 in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.in3\fR s32 in \fR
.TQ
.B xhc-hb04-util.\fIN\fB.out0\fR s32 out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.out1\fR s32 out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.out2\fR s32 out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.out3\fR s32 out \fR
.TQ
.B xhc-hb04-util.\fIN\fB.scale0\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.scale1\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.scale2\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.scale3\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.coef0\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.coef1\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.coef2\fR float in \fR(default: \fI1.0\fR)
.TQ
.B xhc-hb04-util.\fIN\fB.coef3\fR float in \fR(default: \fI1.0\fR)
.SH LICENSE

GPL
