# ------------------------------------------
# Locale file for TkEmc - German translation
# ------------------------------------------
#
# Copyright (C) 2005 Alex Joni
# This file is distributed under GPL.
#

::msgcat::mcset de "Set Run Mark" "Setze Startpunkt"
::msgcat::mcset de "Set run mark at line" "Setze Startpunkt an Linie"

::msgcat::mcset de "Load Tool Table" "Lade Werkzeugtabelle"

::msgcat::mcset de "Load Parameter File" "Lade Parameterdatei"
::msgcat::mcset de "Cancel" "Abbrechen"
::msgcat::mcset de "OK" "OK"

::msgcat::mcset de "EMC Diagnostics" "EMC - Diagnose"
::msgcat::mcset de "Task" "Task"
::msgcat::mcset de "Heartbeat:" "Herzschlag:"
::msgcat::mcset de "Command:" "Befehl:"
::msgcat::mcset de "Command #:" "Befehl #:"
::msgcat::mcset de "Status:" "Status:"
::msgcat::mcset de "Io" "Io"
::msgcat::mcset de "Motion" "Bewegung"
::msgcat::mcset de "About TkEmc" "Über TkEmc"
::msgcat::mcset de "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "TkEmc\n\nGrafisches Interface in Tcl/Tk für Enhanced Machine Controller\n\nPublic Domain (1999)"
::msgcat::mcset de "Set Tool Offset" "Setze Werkzeugoffset"
::msgcat::mcset de "Tool:" "Werkzeug:"
::msgcat::mcset de "Length:" "Länge:"
::msgcat::mcset de "Diameter" "Diameter:"
::msgcat::mcset de "can't open" "kann nicht geöffnet werden"

::msgcat::mcset de "All files" "Alle Dateien"
::msgcat::mcset de "Text files" "Textdateien"
::msgcat::mcset de "NC files" "NC Dateien"

#Main menu
::msgcat::mcset de "File" "Datei"
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Edit..." "Editieren..."
::msgcat::mcset de "Reset" "Zurücksetzen"
::msgcat::mcset de "Exit" "Beenden"
::msgcat::mcset de "View" "Ansicht"
::msgcat::mcset de "Tools..." "Werkzeug..."
::msgcat::mcset de "Offsets and Variables..." "Offsets und Variable..."
::msgcat::mcset de "Diagnostics..." "Diagnose..."
::msgcat::mcset de "Backplot..." "Zeichnen..."
::msgcat::mcset de "Settings" "Einstellungen"
::msgcat::mcset de "Calibration..." "Abstimmungen..."
::msgcat::mcset de "Logging..." "Logs..."
::msgcat::mcset de "Testing..." "Testen..."
::msgcat::mcset de "Debug..." "Debug..."
::msgcat::mcset de "Font..." "Font..."
::msgcat::mcset de "Units" "Masseinheiten"
::msgcat::mcset de "auto" "auto"
::msgcat::mcset de "inches" "inch"
::msgcat::mcset de "mm" "mm"
::msgcat::mcset de "cm" "cm"
::msgcat::mcset de "Scripts" "Scripts"
::msgcat::mcset de "Help" "Hilfe"
::msgcat::mcset de "Help..." "Hilfe..."
::msgcat::mcset de "Balloon help" ""
::msgcat::mcset de "Info..." "Info..."
::msgcat::mcset de "About..." "Über..."

#ESTOP
::msgcat::mcset de "Estop on" "Estop an"
::msgcat::mcset de "Estop off" "Estop aus"

#Machine
::msgcat::mcset de "Machine on" "Maschine an"
::msgcat::mcset de "Machine off" "Maschine aus"

#Mode
::msgcat::mcset de "Manual" "Manuell"
::msgcat::mcset de "Auto" "Auto"
::msgcat::mcset de "MDI" "MDI"

#Mist
::msgcat::mcset de "Mist on" "Nebel an"
::msgcat::mcset de "Mist off" "Nebel aus"

#Flood
::msgcat::mcset de "Flood on" "Kühlmittel an"
::msgcat::mcset de "Flood off" "Kühlmittel aus"

#Lube
::msgcat::mcset de "Lube on" "Schmieröl an"
::msgcat::mcset de "Lube off" "Schmieröl aus"

#Spindle
::msgcat::mcset de "Spindle forward" "Spindel vor"
::msgcat::mcset de "Spindle reverse" "Spindel zurück"
::msgcat::mcset de "Spindle off" "Spindel aus"
::msgcat::mcset de "Break on" "Bremse an"
::msgcat::mcset de "Break off" "Bremse aus"

#Bremse
::msgcat::mcset de "Brake on" "Bremse an"
::msgcat::mcset de "Brake off" "Bremse aus"

::msgcat::mcset de "ABORT" "Abbruch"

::msgcat::mcset de "Offset:" "Offset:"
::msgcat::mcset de "Work Offsets:" "Arbeitsoffset:"

::msgcat::mcset de "override limits" "Grenzw. aufheben"
::msgcat::mcset de "relative" "relativ"
::msgcat::mcset de "machine" "maschine"
::msgcat::mcset de "actual" "- real"
::msgcat::mcset de "commanded" "- befohlen"
::msgcat::mcset de "joint" "Achse"
::msgcat::mcset de "world" "Global"

::msgcat::mcset de "continuous" "fortfahrend"

::msgcat::mcset de "home" "home"

::msgcat::mcset de "Axis Offset" "Achsenoffset"
::msgcat::mcset de "Set axis value:" "Setze Achsenwert:"

::msgcat::mcset de "Set Jog Speed" "Setze Joggeschw."
::msgcat::mcset de "Set jog speed:" "Joggeschw.:"
::msgcat::mcset de "Set Feed Override" "Geschwindigkeit übersteuern"
::msgcat::mcset de "Set feed override:" "Geschwindigkeit übersteuern:"

::msgcat::mcset de "Axis Speed:" "Achsgeschwindigkeit:"
::msgcat::mcset de "Feed Override:" "Geschwindigkeitsübersteuerung:"

::msgcat::mcset de "MDI:" "MDI:"

#modes
::msgcat::mcset de "MDI" "MDI"
::msgcat::mcset de "AUTO" "AUTO"
::msgcat::mcset de "MANUAL" "MANUELL"

::msgcat::mcset de "Program: " "Programm: "
::msgcat::mcset de " - Status: " " - Status: "

#bottom menu
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Run" "Ausführen"
::msgcat::mcset de "Pause" "Pause"
::msgcat::mcset de "Resume" "Fortsetzen"
::msgcat::mcset de "Step" "Schritt"
::msgcat::mcset de "Verify" "Überprüfen"

::msgcat::mcset de "Error: " "Fehler: "
::msgcat::mcset de "Error" "Fehler"

#popupFont
::msgcat::mcset de "Set Font" "Setze Font"

#updateStatus
::msgcat::mcset de "ESTOP" "ESTOP"
::msgcat::mcset de "ON" "AN"
::msgcat::mcset de "ESTOP RESET" "ESTOP RESET"
::msgcat::mcset de "MIST ON" "NEBEL AN"
::msgcat::mcset de "MIST OFF" "NEBEL AUS"
::msgcat::mcset de "MIST ?" "NEBEL ?"
::msgcat::mcset de "FLOOD ON" "KÜHLM. AN"
::msgcat::mcset de "FLOOD OFF" "KÜHLM. AUS"
::msgcat::mcset de "FLOOD ?" "KÜHLM. ?"
::msgcat::mcset de "LUBE ON" "SCHMIERM. AN"
::msgcat::mcset de "LUBE OFF" "SCHMIERM. AUS"
::msgcat::mcset de "SPINDLE FORWARD" "SPINDEL VOR"
::msgcat::mcset de "SPINDLE REVERSE" "SPINDEL ZURÜCK"
::msgcat::mcset de "SPINDLE OFF" "SPINDEL HALT"
::msgcat::mcset de "SPINDLE INCREASE" "SPINDEL ERHÖHEND"
::msgcat::mcset de "SPINDLE DECREASE" "SPINDEL ABNEHMEND"
::msgcat::mcset de "SPINDLE ?" "SPINDEL ?"
::msgcat::mcset de "BRAKE ON" "BREMSE AN"
::msgcat::mcset de "BRAKE OFF" "BREMSE AUS"
::msgcat::mcset de "BRAKE ?" "BREMSE ?"


################################################################################
# Translations for setupconfig.tcl                                             #
################################################################################
::msgcat::mcset de "No details available." ""

# main_page {}
::msgcat::mcset de "Welcome to EMC2!\n" ""
::msgcat::mcset de "To run EMC2 with an existing configuration," ""
::msgcat::mcset de "click the RUN button.\n" ""
::msgcat::mcset de "To create a new configuration, edit a configuration, backup or" ""
::msgcat::mcset de "restore a configuration, or do other configuration related tasks," ""
::msgcat::mcset de "click the CONFIG button.\n" ""

# choose_run_config {}
::msgcat::mcset de "Please select an EMC2 configuration from the list below and click 'RUN'." ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""
::msgcat::mcset de "You must choose a config if you want to run EMC2!" ""

# check_run_ini {}
::msgcat::mcset de "ERROR: no ini file(s) found in config directory" ""
::msgcat::mcset de "Click OK to continue." ""

# choose_run_ini {}
::msgcat::mcset de "The config contains multiple ini files.\nPick one from the list below and click NEXT." ""
::msgcat::mcset de "You must select one ini file!" ""

# execute_run {}
::msgcat::mcset de "The next step is to invoke the run script to run" ""
::msgcat::mcset de "But thats not coded yet, so just click OK to quit." ""

# config_manager {}
::msgcat::mcset de "This page is used to manage EMC2 machine configurations.\n" ""
::msgcat::mcset de "The list below shows all of the existing EMC2\nconfigurations on this computer.\n\nSelect a config, then click one of the buttons below.\n" ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""

# not_implemented {}
::msgcat::mcset de "Sorry, this function is not implemented yet.\n\nClick OK to return to the menu" ""

# new_intro {}
::msgcat::mcset de "You have chosen to create a new EMC2 configuration.\n\nThe next few screens will walk you through the process." ""

# new_get_name {}
::msgcat::mcset de "Please select a name for your new configuration." ""
::msgcat::mcset de "(This will become a directory name, so please use only letters,\ndigits, period, dash, or underscore.)" ""
::msgcat::mcset de "contains illegal characters!\nPlease choose a new name." ""
::msgcat::mcset de "A directory or file called" ""
::msgcat::mcset de "already exists!\nPlease choose a new name." ""

# new_get_template {}
::msgcat::mcset de "Please select one of these existing configurations as the template\nfor your new configuration.\n\nAll the files associated with the template will be copied into your new\nconfig, so you can make whatever modifications are needed." ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""
::msgcat::mcset de "Creating new EMC2 configuration" ""
::msgcat::mcset de "A internal error has occurred, or the template directory was deleted.\nClick OK to quit" ""
::msgcat::mcset de "Enter a description here" ""

# new_get_description {}
::msgcat::mcset de "Creating new EMC2 configuration" ""
::msgcat::mcset de "based on template" ""
::msgcat::mcset de "Please enter a description of your configuration.\n\nThe box below has been preloaded with the description of the template, but\nit is strongly recommended that you revise it.  At a minimum,\nput your name and some specifics about your machine here." ""
::msgcat::mcset de "(If you ever need help, someone may ask you to send them your\nconfiguration, and this information could be very usefull.)" ""
::msgcat::mcset de "You must enter at least one word!" ""

# new_verify {}
::msgcat::mcset de "You are about to create a new EMC2 configuration.\n\nPlease verify that this is what you want:" ""
::msgcat::mcset de "Name" ""
::msgcat::mcset de "Template" ""
::msgcat::mcset de "Description" ""
::msgcat::mcset de "If this information is correct, click NEXT to create\nthe configuration directory and begin copying files." ""

# new_do_copying {}
::msgcat::mcset de "Creating new config directory" ""
::msgcat::mcset de "ERROR: Config directory could not be created." ""
::msgcat::mcset de "Done" ""
::msgcat::mcset de "Checking for ini file(s)..." ""
::msgcat::mcset de "Transferring ini file" ""
::msgcat::mcset de "Writing description file 'README'..." ""
::msgcat::mcset de "Checking for other template file(s)..." ""
::msgcat::mcset de "Copying template file" ""
::msgcat::mcset de "Checking for common file(s)..." ""
::msgcat::mcset de "Copying common file" ""

# new_config_done {}
::msgcat::mcset de "Your new configuration" ""
::msgcat::mcset de "has been created.\nClick OK to return to the main menu." ""

# new_config_error {}
::msgcat::mcset de "An error happened while creating the new configuration.\nIdeally this code would clean everything up and\nthen return to the main menu, but the cleanup isn't done yet.\nClick OK to return to the main menu." ""

# resolve_config {}
::msgcat::mcset de "ERROR: Not a valid config directory (contains no .ini files)\n\n'$input'\n($abs_input)\n\nClick OK to continue." ""
::msgcat::mcset de "ERROR: Not a valid ini file (must end in .ini)" ""
::msgcat::mcset de "Click OK to continue." ""
::msgcat::mcset de "ERROR: Not a valid config directory (contains no .ini files)" ""
::msgcat::mcset de "ERROR: Config not found" ""
::msgcat::mcset de "ERROR: Not a valid config name\n(must be either <config-name> or <config-name>/<ini-name>)" ""

# main program
::msgcat::mcset de "EMC2 Configuration Manager" ""
::msgcat::mcset de "ERROR: option '--configs_dir' must be followed by a directory name." ""
::msgcat::mcset de "Click OK to exit." ""
::msgcat::mcset de "ERROR: '--configs-dir' argument is" ""
::msgcat::mcset de "which is not a directory." ""
::msgcat::mcset de "ERROR: environment variable EMC2_CONFIG_DIR is" ""
::msgcat::mcset de "ERROR: Cannot find the EMC2 configurations directory.\nYou can specify the directory with the '--configs_dir <dir>' option." ""
::msgcat::mcset de "ERROR: options '--run', '--new', and '--get-config' are\nmutually exclusive, please specify only one." ""
::msgcat::mcset de "ERROR: unknown command line option:" ""
