# ------------------------------------------
# Locale file for TkEmc - German translation
# ------------------------------------------
#
# Copyright (C) 2005 Alex Joni
# This file is distributed under GPL.
#

::msgcat::mcset de "Set Run Mark" "Setze Startpunkt"
::msgcat::mcset de "Set run mark at line" "Setze Startpunkt an Linie"

::msgcat::mcset de "Load Tool Table" "Lade Werkzeugtabelle"

::msgcat::mcset de "Load Parameter File" "Lade Parameterdatei"
::msgcat::mcset de "Cancel" "Abbrechen"
::msgcat::mcset de "OK" "OK"

::msgcat::mcset de "EMC Diagnostics" "EMC - Diagnose"
::msgcat::mcset de "Task" "Task"
::msgcat::mcset de "Heartbeat:" "Herzschlag:"
::msgcat::mcset de "Command:" "Befehl:"
::msgcat::mcset de "Command #:" "Befehl #:"
::msgcat::mcset de "Status:" "Status:"
::msgcat::mcset de "Io" "Io"
::msgcat::mcset de "Motion" "Bewegung"
::msgcat::mcset de "About TkEmc" "Über TkEmc"
::msgcat::mcset de "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "TkEmc\n\nGrafisches Interface in Tcl/Tk für Enhanced Machine Controller\n\nPublic Domain (1999)"
::msgcat::mcset de "Set Tool Offset" "Setze Werkzeugoffset"
::msgcat::mcset de "Tool:" "Werkzeug:"
::msgcat::mcset de "Length:" "Länge:"
::msgcat::mcset de "Diameter" "Diameter:"
::msgcat::mcset de "can't open" "kann nicht geöffnet werden"

::msgcat::mcset de "All files" "Alle Dateien"
::msgcat::mcset de "Text files" "Textdateien"
::msgcat::mcset de "NC files" "NC Dateien"

#Main menu
::msgcat::mcset de "File" "Datei"
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Edit..." "Editieren..."
::msgcat::mcset de "Reset" "Zurücksetzen"
::msgcat::mcset de "Exit" "Beenden"
::msgcat::mcset de "View" "Ansicht"
::msgcat::mcset de "Tools..." "Werkzeug..."
::msgcat::mcset de "Offsets and Variables..." "Offsets und Variable..."
::msgcat::mcset de "Diagnostics..." "Diagnose..."
::msgcat::mcset de "Backplot..." "Zeichnen..."
::msgcat::mcset de "Settings" "Einstellungen"
::msgcat::mcset de "Calibration..." "Abstimmungen..."
::msgcat::mcset de "Logging..." "Logs..."
::msgcat::mcset de "Testing..." "Testen..."
::msgcat::mcset de "Debug..." "Debug..."
::msgcat::mcset de "Font..." "Font..."
::msgcat::mcset de "Units" "Masseinheiten"
::msgcat::mcset de "auto" "auto"
::msgcat::mcset de "inches" "inch"
::msgcat::mcset de "mm" "mm"
::msgcat::mcset de "cm" "cm"
::msgcat::mcset de "Scripts" "Scripts"
::msgcat::mcset de "Help" "Hilfe"
::msgcat::mcset de "Help..." "Hilfe..."
::msgcat::mcset de "Balloon help" ""
::msgcat::mcset de "Info..." "Info..."
::msgcat::mcset de "About..." "Über..."

#ESTOP
::msgcat::mcset de "Estop on" "Estop an"
::msgcat::mcset de "Estop off" "Estop aus"

#Machine
::msgcat::mcset de "Machine on" "Maschine an"
::msgcat::mcset de "Machine off" "Maschine aus"

#Mode
::msgcat::mcset de "Manual" "Manuell"
::msgcat::mcset de "Auto" "Auto"
::msgcat::mcset de "MDI" "MDI"

#Mist
::msgcat::mcset de "Mist on" "Nebel an"
::msgcat::mcset de "Mist off" "Nebel aus"

#Flood
::msgcat::mcset de "Flood on" "Kühlmittel an"
::msgcat::mcset de "Flood off" "Kühlmittel aus"

#Lube
::msgcat::mcset de "Lube on" "Schmieröl an"
::msgcat::mcset de "Lube off" "Schmieröl aus"

#Spindle
::msgcat::mcset de "Spindle forward" "Spindel vor"
::msgcat::mcset de "Spindle reverse" "Spindel zurück"
::msgcat::mcset de "Spindle off" "Spindel aus"
::msgcat::mcset de "Break on" "Bremse an"
::msgcat::mcset de "Break off" "Bremse aus"

#Bremse
::msgcat::mcset de "Brake on" "Bremse an"
::msgcat::mcset de "Brake off" "Bremse aus"

::msgcat::mcset de "ABORT" "Abbruch"

::msgcat::mcset de "Offset:" "Offset:"
::msgcat::mcset de "Work Offsets:" "Arbeitsoffset:"

::msgcat::mcset de "override limits" "Grenzw. aufheben"
::msgcat::mcset de "relative" "relativ"
::msgcat::mcset de "machine" "maschine"
::msgcat::mcset de "actual" "- real"
::msgcat::mcset de "commanded" "- befohlen"
::msgcat::mcset de "joint" "Achse"
::msgcat::mcset de "world" "Global"

::msgcat::mcset de "continuous" "fortfahrend"

::msgcat::mcset de "home" "home"

::msgcat::mcset de "Axis Offset" "Achsenoffset"
::msgcat::mcset de "Set axis value:" "Setze Achsenwert:"

::msgcat::mcset de "Set Jog Speed" "Setze Joggeschw."
::msgcat::mcset de "Set jog speed:" "Joggeschw.:"
::msgcat::mcset de "Set Feed Override" "Geschwindigkeit übersteuern"
::msgcat::mcset de "Set feed override:" "Geschwindigkeit übersteuern:"

::msgcat::mcset de "Axis Speed:" "Achsgeschwindigkeit:"
::msgcat::mcset de "Feed Override:" "Geschwindigkeitsübersteuerung:"

::msgcat::mcset de "MDI:" "MDI:"

#modes
::msgcat::mcset de "MDI" "MDI"
::msgcat::mcset de "AUTO" "AUTO"
::msgcat::mcset de "MANUAL" "MANUELL"

::msgcat::mcset de "Program: " "Programm: "
::msgcat::mcset de " - Status: " " - Status: "

#bottom menu
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Run" "Ausführen"
::msgcat::mcset de "Pause" "Pause"
::msgcat::mcset de "Resume" "Fortsetzen"
::msgcat::mcset de "Step" "Schritt"
::msgcat::mcset de "Verify" "Überprüfen"

::msgcat::mcset de "Error: " "Fehler: "
::msgcat::mcset de "Error" "Fehler"

#popupFont
::msgcat::mcset de "Set Font" "Setze Font"

#updateStatus
::msgcat::mcset de "ESTOP" "ESTOP"
::msgcat::mcset de "ON" "AN"
::msgcat::mcset de "ESTOP RESET" "ESTOP RESET"
::msgcat::mcset de "MIST ON" "NEBEL AN"
::msgcat::mcset de "MIST OFF" "NEBEL AUS"
::msgcat::mcset de "MIST ?" "NEBEL ?"
::msgcat::mcset de "FLOOD ON" "KÜHLM. AN"
::msgcat::mcset de "FLOOD OFF" "KÜHLM. AUS"
::msgcat::mcset de "FLOOD ?" "KÜHLM. ?"
::msgcat::mcset de "LUBE ON" "SCHMIERM. AN"
::msgcat::mcset de "LUBE OFF" "SCHMIERM. AUS"
::msgcat::mcset de "SPINDLE FORWARD" "SPINDEL VOR"
::msgcat::mcset de "SPINDLE REVERSE" "SPINDEL ZURÜCK"
::msgcat::mcset de "SPINDLE OFF" "SPINDEL HALT"
::msgcat::mcset de "SPINDLE INCREASE" "SPINDEL ERHÖHEND"
::msgcat::mcset de "SPINDLE DECREASE" "SPINDEL ABNEHMEND"
::msgcat::mcset de "SPINDLE ?" "SPINDEL ?"
::msgcat::mcset de "BRAKE ON" "BREMSE AN"
::msgcat::mcset de "BRAKE OFF" "BREMSE AUS"
::msgcat::mcset de "BRAKE ?" "BREMSE ?"
