# ------------------------------------------
# Locale file for TkEmc - German translation
# ------------------------------------------
#
# Copyright (C) 2005 Alex Joni
# This file is distributed under GPL.
#

::msgcat::mcset de "Set Run Mark" "Setze Startpunkt"
::msgcat::mcset de "Set run mark at line" "Setze Startpunkt an Linie"

::msgcat::mcset de "Load Tool Table" "Lade Werkzeugtabelle"

::msgcat::mcset de "Load Parameter File" "Lade Parameterdatei"
::msgcat::mcset de "Cancel" "Abbrechen"
::msgcat::mcset de "OK" "OK"

::msgcat::mcset de "EMC Diagnostics" "EMC - Diagnose"
::msgcat::mcset de "Task" "Task"
::msgcat::mcset de "Heartbeat:" "Herzschlag:"
::msgcat::mcset de "Command:" "Befehl:"
::msgcat::mcset de "Command #:" "Befehl #:"
::msgcat::mcset de "Status:" "Status:"
::msgcat::mcset de "Io" "Io"
::msgcat::mcset de "Motion" "Bewegung"
::msgcat::mcset de "About TkEmc" "Über TkEmc"
::msgcat::mcset de "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "TkEmc\n\nGrafisches Interface in Tcl/Tk fr Enhanced Machine Controller\n\nPublic Domain (1999)"
::msgcat::mcset de "Set Tool Offset" "Setze Werkzeugoffset"
::msgcat::mcset de "Tool:" "Werkzeug:"
::msgcat::mcset de "Length:" "Länge:"
::msgcat::mcset de "Diameter" "Diameter:"
::msgcat::mcset de "can't open" "kann nicht geöffnet werden"

::msgcat::mcset de "All files" "Alle Dateien"
::msgcat::mcset de "Text files" "Textdateien"
::msgcat::mcset de "NC files" "NC Dateien"

#Main menu
::msgcat::mcset de "File" "Datei"
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Edit..." "Editieren..."
::msgcat::mcset de "Reset" "Zurcksetzen"
::msgcat::mcset de "Exit" "Beenden"
::msgcat::mcset de "View" "Ansicht"
::msgcat::mcset de "Tools..." "Werkzeug..."
::msgcat::mcset de "Offsets and Variables..." "Offsets und Variable..."
::msgcat::mcset de "Diagnostics..." "Diagnose..."
::msgcat::mcset de "Backplot..." "Zeichnen..."
::msgcat::mcset de "Settings" "Einstellungen"
::msgcat::mcset de "Calibration..." "Abstimmungen..."
::msgcat::mcset de "Logging..." "Logs..."
::msgcat::mcset de "Testing..." "Testen..."
::msgcat::mcset de "Debug..." "Debug..."
::msgcat::mcset de "Font..." "Font..."
::msgcat::mcset de "Units" "Masseinheiten"
::msgcat::mcset de "auto" "auto"
::msgcat::mcset de "inches" "inch"
::msgcat::mcset de "mm" "mm"
::msgcat::mcset de "cm" "cm"
::msgcat::mcset de "Scripts" "Scripts"
::msgcat::mcset de "Help" "Hilfe"
::msgcat::mcset de "Help..." "Hilfe..."
::msgcat::mcset de "Balloon help" ""
::msgcat::mcset de "Info..." "Info..."
::msgcat::mcset de "About..." "Über..."

#ESTOP
::msgcat::mcset de "Estop on" "Estop an"
::msgcat::mcset de "Estop off" "Estop aus"

#Machine
::msgcat::mcset de "Machine on" "Maschine an"
::msgcat::mcset de "Machine off" "Maschine aus"

#Mode
::msgcat::mcset de "Manual" "Manuell"
::msgcat::mcset de "Auto" "Auto"
::msgcat::mcset de "MDI" "MDI"

#Mist
::msgcat::mcset de "Mist on" "Nebel an"
::msgcat::mcset de "Mist off" "Nebel aus"

#Flood
::msgcat::mcset de "Flood on" "Kühlmittel an"
::msgcat::mcset de "Flood off" "Kühlmittel aus"

#Lube
::msgcat::mcset de "Lube on" "Schmieröl an"
::msgcat::mcset de "Lube off" "Schmieröl aus"

#Spindle
::msgcat::mcset de "Spindle forward" "Spindel vor"
::msgcat::mcset de "Spindle reverse" "Spindel zurck"
::msgcat::mcset de "Spindle off" "Spindel aus"
::msgcat::mcset de "Break on" "Bremse an"
::msgcat::mcset de "Break off" "Bremse aus"

#Bremse
::msgcat::mcset de "Brake on" "Bremse an"
::msgcat::mcset de "Brake off" "Bremse aus"

::msgcat::mcset de "ABORT" "Abbruch"

::msgcat::mcset de "Offset:" "Offset:"
::msgcat::mcset de "Work Offsets:" "Arbeitsoffset:"

::msgcat::mcset de "override limits" "Grenzw. aufheben"
::msgcat::mcset de "relative" "relativ"
::msgcat::mcset de "machine" "maschine"
::msgcat::mcset de "actual" "- real"
::msgcat::mcset de "commanded" "- befohlen"
::msgcat::mcset de "joint" "Achse"
::msgcat::mcset de "world" "Global"

::msgcat::mcset de "continuous" "fortfahrend"

::msgcat::mcset de "home" "home"

::msgcat::mcset de "Axis Offset" "Achsenoffset"
::msgcat::mcset de "Set axis value:" "Setze Achsenwert:"

::msgcat::mcset de "Set Jog Speed" "Setze Joggeschw."
::msgcat::mcset de "Set jog speed:" "Joggeschw.:"
::msgcat::mcset de "Set Feed Override" "Geschwindigkeit bersteuern"
::msgcat::mcset de "Set feed override:" "Geschwindigkeit bersteuern:"

::msgcat::mcset de "Axis Speed:" "Achsgeschwindigkeit:"
::msgcat::mcset de "Feed Override:" "Geschwindigkeitsbersteuerung:"

::msgcat::mcset de "MDI:" "MDI:"

#modes
::msgcat::mcset de "MDI" "MDI"
::msgcat::mcset de "AUTO" "AUTO"
::msgcat::mcset de "MANUAL" "MANUELL"

::msgcat::mcset de "Program: " "Programm: "
::msgcat::mcset de " - Status: " " - Status: "

#bottom menu
::msgcat::mcset de "Open..." "Öffnen..."
::msgcat::mcset de "Run" "Ausfhren"
::msgcat::mcset de "Pause" "Pause"
::msgcat::mcset de "Resume" "Fortsetzen"
::msgcat::mcset de "Step" "Schritt"
::msgcat::mcset de "Verify" "Überprüfen"

::msgcat::mcset de "Error: " "Fehler: "
::msgcat::mcset de "Error" "Fehler"

#popupFont
::msgcat::mcset de "Set Font" "Setze Font"

#updateStatus
::msgcat::mcset de "ESTOP" "ESTOP"
::msgcat::mcset de "ON" "AN"
::msgcat::mcset de "ESTOP RESET" "ESTOP RESET"
::msgcat::mcset de "MIST ON" "NEBEL AN"
::msgcat::mcset de "MIST OFF" "NEBEL AUS"
::msgcat::mcset de "MIST ?" "NEBEL ?"
::msgcat::mcset de "FLOOD ON" "KÜHLM. AN"
::msgcat::mcset de "FLOOD OFF" "KÜHLM. AUS"
::msgcat::mcset de "FLOOD ?" "KÜHLM. ?"
::msgcat::mcset de "LUBE ON" "SCHMIERM. AN"
::msgcat::mcset de "LUBE OFF" "SCHMIERM. AUS"
::msgcat::mcset de "SPINDLE FORWARD" "SPINDEL VOR"
::msgcat::mcset de "SPINDLE REVERSE" "SPINDEL ZURÜCK"
::msgcat::mcset de "SPINDLE OFF" "SPINDEL HALT"
::msgcat::mcset de "SPINDLE INCREASE" "SPINDEL ERHÖHEND"
::msgcat::mcset de "SPINDLE DECREASE" "SPINDEL ABNEHMEND"
::msgcat::mcset de "SPINDLE ?" "SPINDEL ?"
::msgcat::mcset de "BRAKE ON" "BREMSE AN"
::msgcat::mcset de "BRAKE OFF" "BREMSE AUS"
::msgcat::mcset de "BRAKE ?" "BREMSE ?"


################################################################################
# Translations for setupconfig.tcl                                             #
################################################################################

# main_page {}
::msgcat::mcset de "Config" "Konfig"
::msgcat::mcset de "Quit" "Beenden"
::msgcat::mcset de "Run" "Ausfuehren"
::msgcat::mcset de  "Welcome to EMC2!\n\nTo run EMC2 with an existing configuration, click the 'Run' button.\nTo create a new configuration, edit, backup, or restore a configuration,\nor do other configuration related tasks, click the 'Config' button." "Willkommen zu EMC2\n\nUm eine existierende Konfiguration zu starten drücken Sie 'Ausführen'.\nUm eine neue Konfiguration zu erstellen, eine Existierende zu\neditieren, um eine Konfiguration zu speichern oder zu laden, drücken sie 'Konfig'"

# choose_run_config {}
::msgcat::mcset de "Cancel" " Abbrechen"
::msgcat::mcset de "Please select an EMC2 configuration from the list below and click 'Run'." "Bitte wählen sie eine EMC" Konfiguration aus der Liste und drücken Sie 'Ausführen'"
::msgcat::mcset de "\nDetails about the selected configuration:" "\nDetails ber die gewählte Konfiguration:"
::msgcat::mcset de "No details available." "Keine Details verfügbar."
::msgcat::mcset de "You must choose a config if you want to run EMC2." "Sie mssen eine Konfig wählen um EMC2 zu starten."

# check_run_ini {}
msgcat::mcset de "ERROR: no ini file(s) found in config directory\n\n'%s'\n\n" "FEHLER: keine ini Datei(en) im Konfig Ordner gefunden\n\n'%s'\n\n"
msgcat::mcset de "Click 'OK' to continue." "Drücken Sie 'OK' um fortzufahren."

# choose_run_ini {}
::msgcat::mcset de "< Back" "< Zurück"
::msgcat::mcset de "Next >" "Weiter >"
::msgcat::mcset de "The config contains multiple ini files.\nPick one from the list below and click 'Next'." "Die Konfiguration beinhaltet mehrere ini Dateien.\nWählen Sie eine aus, und drücken Sie 'Weiter' um fortzufahren."
::msgcat::mcset de "You must select one ini file." "Sie müssen eine ini Datei auswählen."

# execute_run {}

::msgcat::mcset de "The next step is to invoke the run script to run\n'%s'\n\nBut thats not coded yet, so just click OK to quit." "Der nächste Schritt ist das Startscript zu starten\n'%s'\n\nDas ist noch nicht verfügbar, drücken sie OK um zu beenden."

# config_manager {}
::msgcat::mcset de "Edit" "Bearbeiten"
::msgcat::mcset de "Backup" "Arhivieren"
::msgcat::mcset de "Restore" "Wiederherstellen"
::msgcat::mcset de "Delete" "Löschen"
::msgcat::mcset de "New" "Neu"
::msgcat::mcset de "This page is used to manage EMC2 machine configurations.\n" "Diese Seite wird verwendet um EMC2 maschinenspezifische Konfigurationen zu verwalten."
::msgcat::mcset de "The list below shows all of the existing EMC2\nconfigurations on this computer.\n\nSelect a config, then click one of the buttons below.\n" "Die Liste weiter unten zeigt alle verfügbaren EMC2 Konfigurationen.\n\nWählen Sie eine aus, dann drücken Sie einen der Knöpfe"
::msgcat::mcset de "\nDetails about the selected configuration:" "\nDetails der ausgewählten Konfiguration:"
::msgcat::mcset de "You must choose a config first." "Sie müssen erst eine Konfiguration auswählen."


# not_implemented {}
::msgcat::mcset de "Sorry, this function is not implemented yet.\n\n" "Leider ist diese Funktion noch nicht implementiert.\n\n"
::msgcat::mcset de "Click 'OK' to return to the main menu." "Drücken Sie 'OK' um zum Menü zurückzukehren."

# new_intro {}
::msgcat::mcset de "You have chosen to create a new EMC2 configuration.\n\nThe next few screens will walk you through the process." "Sie haben eine neue EMC2 Konfiguration ausgewählt.\n\nDie nächsten Schritte werden Ihnen bei diesem Prozess behilflich sein."

# new_get_name {}
::msgcat::mcset de "Please select a name for your new configuration." "Bitte wählen Sie einen Namen für die neue Konfiguration aus."
::msgcat::mcset de "(This will become a directory name, so please use only letters,\ndigits, period, dash, or underscore.)" "(das wird ein Ordnername, also benützen Sie bitte nur Buchstaben, Nummern, Punkt, Bindestrich)"
::msgcat::mcset de "You must enter a name." "Sie müssen einen Namen eintragen."
::msgcat::mcset de "'%s' contains illegal characters.\nPlease choose a new name." "'%s' beinhaltet illegale Zeichen.\nBitte wählen Sie einen neuen Namen aus."
::msgcat::mcset de "A directory or file called '%s' already exists.\nPlease choose a new name." "Ein Ordner oder Datei namens '%s' existiert bereits.\nBitte wählen Sie einen neuen Namen aus."

# new_get_template {}
::msgcat::mcset de "Creating new EMC2 configuration '%s'" "Eine neue EMC2 Konfiguration '%s' wird erstellt"
::msgcat::mcset de "Please select one of these existing configurations as the template\nfor your new configuration.\n\nAll the files associated with the template will be copied into your new\nconfig, so you can make whatever modifications are needed." "Bitte wählen Sie eine Vorlage für Ihre Konfiguration.\nAlle Dateien die zu dieser Vorlage gehören, werden mitkopiert, so dass Sie alle nötigen Modifikationen machen können."
::msgcat::mcset de "\nDetails about the selected configuration:" "\nDetails der ausgewählten Konfiguration:"
::msgcat::mcset de "You must choose a template." "Sie müssen eine Vorlage wählen."
::msgcat::mcset de "A internal error has occurred, or the template directory was deleted.\n" "Ein interner Fehler ist aufgetreten, oder die Vorlage wurde gelöscht.\n"
::msgcat::mcset de "Enter a description here" "Beschreibung der neuen Konfiguration"

# new_get_description {}
::msgcat::mcset de  "Creating new EMC2 configuration '%s'\nbased on template '%s'" "Eine neue EMC2 Konfiguration '%s'\nerstellen basierend auf Vorlage '%s'"
::msgcat::mcset de "Please enter a description of your configuration.\n\nThe box below has been preloaded with the description of the template, but\nit is strongly recommended that you revise it.  At a minimum,\nput your name and some specifics about your machine here." "Bitte beschreiben Sie die Konfiguration in der Box unten.\n\nDiese wurde schon mit den Daten der Vorlage ausgefüllt, jedoch ist es empfohlen diese auszubessern. Wenigstens Ihr Name und spezifische Daten über Ihre Maschine sollten hier stehen."
::msgcat::mcset de "(If you ever need help, someone may ask you to send them your\nconfiguration, and this information could be very usefull.)" "(falls Sie irgendwann mal Hilfe benötigen, wären diese Daten sehr nützlich.)"
::msgcat::mcset de "You must enter at least one word." "Sie müssen wenigstens ein Wort schreiben."

# new_verify {}\
::msgcat::mcset de "Finish" "Fertig stellen"
::msgcat::mcset de "You are about to create a new EMC2 configuration.\n\nPlease verify that this is what you want:\n\nName: '%s'\nTemplate: '%s'\nDescription:" "Sie sind soweit eine neue Konfiguration zu erstellen.\n\nBitte überprüfen Sie ob folgende Daten korrekt sind:\n\nName: '%s'\nVorlage: '%s'\nBeschreibung:"
::msgcat::mcset de "If this information is correct, click 'Finish' to create\nthe configuration directory and begin copying files." "Falls dise Informationen korrekt sind, drücken Sie 'Fertig stellen'\num die Konfiguration zu erstellen, und Dateien zu kopieren."

# new_do_copying {}
::msgcat::mcset de "Creating new config directory '%s'..." "Erstelle einen neuen Konfigurationsordner '%s'..."
::msgcat::mcset de "ERROR: Config directory could not be created." "FEHLER: der Ordner konnte nicht erstellt werden."
::msgcat::mcset de "Done" "Fertig"
::msgcat::mcset de "Checking for ini file(s)..." "Suche nach ini Detei(en)..."
::msgcat::mcset de "Transferring ini file '%s'..." "Kopiere ini Datei '%s'..."
::msgcat::mcset de "Writing description file 'README'..." "Schreibe Beschreibungsdatei 'README'"
::msgcat::mcset de "Checking for other template file(s)..." "Suche nach anderen Vorlagdateien.."
::msgcat::mcset de "Copying template file '%s'..." "Kopiere Vorlagdateien '%s'..."
::msgcat::mcset de "Checking for common file(s)..." "Suche nach gemeinsamen(common) Datei(en)..."
::msgcat::mcset de "Copying common file '%s'..." "Kopiere gemeinsame(common) Datei '%s'..."

# new_config_done {}
::msgcat::mcset de "Your new configuration '%s' has been created.\n" "Ihre neue Konfiguration '%s' wurde erstellt.\n"

# new_config_error {}
::msgcat::mcset de "An error happened while creating the new configuration.\nIdeally this code would clean everything up and\nthen return to the main menu, but the cleanup isn't done yet.\n" "Ein Fehler ist aufgetreten während die Konfiguration erstellt wurde.\nIdealerweise würde der Code hier alles\nrückgängig machen und dann zum Menü zurückkehren,\nleider ist das noch nicht implementiert.\n"

# resolve_config {}
::msgcat::mcset de "ERROR: Not a valid config directory (contains no .ini files)\n\n'%s'\n(%s)\n\n" "Kein valider Konfigurationsordner (keine .ini Dateien verfügbar)\n\n'%s'\n(%s)\n\n"
::msgcat::mcset de "ERROR: Not a valid ini file (must end with '.ini')\n\n'%s'\n(%s)\n\n" "FEHLER: Keine valide ini Datei (muss mit '.ini' enden)\n\n'%s'\n(%s)\n\n"

::msgcat::mcset de "ERROR: Config not found\n\n'%s'\n(%s)\n\n" "FEHLER: Konfig nicht gefunden\n\n'%s'\n(%s)\n\n"
::msgcat::mcset de "ERROR: config/ini not found\n\n'%s'\n(%s)\n\n" "FEHLER: konfig/ini nicht gefunden\n\n'%s'\n(%s)\n\n"
::msgcat::mcset de "ERROR: Not a valid config name\n(must be either <config-name> or <config-name>/<ini-name>)\n\n'%s'\n\n" "FEHLER: kein valider Konfig name\n(muss entweder <konfig-name> oder <konfig-name>/<ini-name> sein)\n\n'%s'\n\n"

# main program
::msgcat::mcset de "EMC2 Configuration Manager" "EMC2 Konfigurationsasistent"
::msgcat::mcset de "ERROR: option '--configs-dir' must be followed by a directory name.\n\n" "FEHLER: Option '--configs-dir' muss von einem Ordnernamen gefolget werden.\n\n"
::msgcat::mcset de "Click 'OK' to exit." "Drücke 'OK' um den Asistenten zu beenden."
::msgcat::mcset de "ERROR: '--configs-dir' argument is\n\n'%s'\n\nwhich is not a directory.\n\n" "FEHLER: '--configs-dir' Argument ist\n\n'%s'\n\nwelches kein Ordner ist.\n\n"
::msgcat::mcset de "ERROR: environment variable EMC2_CONFIG_DIR is\n\n'%s'\n\nwhich is not a directory.\n\n" "FEHLER: Umgebungsvariable EMC2_CONFIG_DIR ist\n\n'%s'\n\nwelches kein Ordner ist.\n\n"
::msgcat::mcset de "ERROR: Cannot find the EMC2 configurations directory.\nYou can specify the directory with the '--configs-dir <dir>' option.\n\n" "FEHLER: kann den EMC2 Konfigurationsordner nicht finden.\nSie können einen mit der Option '--configs-dir <dir>' spezifizieren.\n\n"

::msgcat::mcset de "ERROR: options '--run', '--new', and '--get-config' are\nmutually exclusive, please specify only one." "FEHLER: Optionen '--run', '--new' und '--get-config' sind\nmutual Exklusiv. Bitte nur eins auswählen."
::msgcat::mcset de "ERROR: unknown command line option:\n\n'%s'\n\n" "FEHLER: unbekannte Option:\n\n'%s'\n\n"
