# ---------------------
# Locale file for TkEmc
# ---------------------
#
# Copyright (C) 2005 Ben Lipkowitz
# This file is distributed under the GPL.
# まだ翻訳にしております。訂正をfenn(at)sdf.lonestar.orgかCVSに送れて教えてお願いします。

::msgcat::mcset ja "Set Run Mark" "動く点を決める"
::msgcat::mcset ja "Set run mark at line" "線に動く点を決める"

::msgcat::mcset ja "Load Tool Table" "ツール表を読む"

::msgcat::mcset ja "Load Parameter File" "パラムのファイルを読む"
::msgcat::mcset ja "Cancel" "中止"
::msgcat::mcset ja "OK" "OK"

::msgcat::mcset ja "EMC Diagnostics" "EMCの診断"
::msgcat::mcset ja "Task" "Task"
::msgcat::mcset ja "Heartbeat:" "心臓の鼓動:"
::msgcat::mcset ja "Command:" "命令:"
::msgcat::mcset ja "Command #:" "命令番:"
::msgcat::mcset ja "Status:" "状態:"
::msgcat::mcset ja "Io" "IO"
::msgcat::mcset ja "Motion" "動き"
::msgcat::mcset ja "About TkEmc" "TkEmcについて"
::msgcat::mcset ja "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "Enhanced Machine Controller(EMC)の\n\nTkEmc\n\n
Tcl/Tkで書いたGUI\n\n パブリックドメイン(1999)"
::msgcat::mcset ja "Set Tool Offset" "道具が平行移動"
::msgcat::mcset ja "Tool:" "道具:"
::msgcat::mcset ja "Length:" "長さ:"
::msgcat::mcset ja "Diameter" "直径:"
::msgcat::mcset ja "can't open" "開けません"
::msgcat::mcset ja "All files" "全部のファイル"
::msgcat::mcset ja "Text files" "テキストファイル"
::msgcat::mcset ja "NC files" "NCファイル"

#Main menu
::msgcat::mcset ja "File" "ファイル"
::msgcat::mcset ja "Open..." "開く..."
::msgcat::mcset ja "Edit..." "エディット..."
::msgcat::mcset ja "Reset" "リーセット"
::msgcat::mcset ja "Exit" "出る"
::msgcat::mcset ja "View" "見方"
::msgcat::mcset ja "Tools..." "道具..."
::msgcat::mcset ja "Offsets and Variables..." "平行移動と価..."
::msgcat::mcset ja "Diagnostics..." "診断"
::msgcat::mcset ja "Backplot..." "描"
::msgcat::mcset ja "Settings" "撰" 
::msgcat::mcset ja "Calibration..." "較正..."
::msgcat::mcset ja "Logging..." "ローグ..."
::msgcat::mcset ja "Testing..." "テスト..."
::msgcat::mcset ja "Debug..." "ディバッグ..."
::msgcat::mcset ja "Font..." "フォント..."
::msgcat::mcset ja "Units" "ユーニット（刻）"
::msgcat::mcset ja "auto" "自動"
::msgcat::mcset ja "inches" "インチ"
::msgcat::mcset ja "mm" "mm"
::msgcat::mcset ja "cm" "cm"
::msgcat::mcset ja "Scripts" "スクリプト"
::msgcat::mcset ja "Help" "助け"
::msgcat::mcset ja "Help..." "助け..."
::msgcat::mcset ja "Balloon help" "バルーン助け"
::msgcat::mcset ja "Info..." "インフォ..."
::msgcat::mcset ja "About..." "これについて..."

#ESTOP
::msgcat::mcset ja "Estop on" "終止符点いた"
::msgcat::mcset ja "Estop off" "終止符消した"

#Machine
::msgcat::mcset ja "Machine on" "出来るように"
::msgcat::mcset ja "Machine off" "出来ないように"

#Mode
::msgcat::mcset ja "Manual" "手動"
::msgcat::mcset ja "Auto" "自動"
::msgcat::mcset ja "MDI" "一線(MDI)"

#Mist
::msgcat::mcset ja "Mist on" "雰点いた"
::msgcat::mcset ja "Mist off" "雰消した"

#Flood
::msgcat::mcset ja "Flood on" "水洗点いた"
::msgcat::mcset ja "Flood off" "水洗消した"

#Lube
::msgcat::mcset ja "Lube on" "油点いた"
::msgcat::mcset ja "Lube off" "油消した"

#Spindle
::msgcat::mcset ja "Spindle forward" "スピンドル前進"
::msgcat::mcset ja "Spindle reverse" "スピンドル逆"
::msgcat::mcset ja "Spindle off" "スピンドル消した"
::msgcat::mcset ja "Break on" "ブレーキ点いた"
::msgcat::mcset ja "Break off" "ブレーキ消した"

#Bremse
::msgcat::mcset ja "Brake on" "ブレーキ点いた"
::msgcat::mcset ja "Brake off" "ブレーキ消した"

::msgcat::mcset ja "ABORT" "中断"

::msgcat::mcset ja "Offset:" "平行移動:"
::msgcat::mcset ja "Work Offsets:" "工作物平行移動:"

::msgcat::mcset ja "override limits" "方図を聞き捨てる"
::msgcat::mcset ja "relative" "相対"
::msgcat::mcset ja "machine" "マッシン"
::msgcat::mcset ja "actual" "本当"
::msgcat::mcset ja "commanded" "命令な"
::msgcat::mcset ja "joint" "関節"
::msgcat::mcset ja "world" "世界"

::msgcat::mcset ja "continuous" "連綿"

::msgcat::mcset ja "home" "原点"

::msgcat::mcset ja "Axis Offset" "軸の平行移動"
::msgcat::mcset ja "Set axis value:" "軸の数値:"

::msgcat::mcset ja "Set Jog Speed" "ジョグ時速"
::msgcat::mcset ja "Set jog speed:" "ジョグ時速:"
::msgcat::mcset ja "Set Feed Override" "フィード手直して"
::msgcat::mcset ja "Set feed override:" "フィード手直して:"

::msgcat::mcset ja "Axis Speed:" "軸の時速:"
::msgcat::mcset ja "Feed Override:" "フィード手直し:"

::msgcat::mcset ja "MDI:" "一線(MDI):"

#modes
::msgcat::mcset ja "MDI" "一線(MDI)"
::msgcat::mcset ja "AUTO" "自動"
::msgcat::mcset ja "MANUAL" "手動"

::msgcat::mcset ja "Program: " "プローグラム: "
::msgcat::mcset ja " - Status: " " - 状態: "

#bottom menu
::msgcat::mcset ja "Open..." "開く..."
::msgcat::mcset ja "Run" "動く"
::msgcat::mcset ja "Pause" "間断"
::msgcat::mcset ja "Resume" "つづく"
::msgcat::mcset ja "Step" "一足"
::msgcat::mcset ja "Verify" "質す"

::msgcat::mcset ja "Error: " "越度: "
::msgcat::mcset ja "Error" "越度"

#popupFont
::msgcat::mcset ja "Set Font" "フォントを撰ぶ"

#updateStatus
::msgcat::mcset ja "ESTOP" "終止符"
::msgcat::mcset ja "ON" "点いた"
::msgcat::mcset ja "ESTOP RESET" "リーセット"
::msgcat::mcset ja "MIST ON" "雰点け"
::msgcat::mcset ja "MIST OFF" "雰消した"
::msgcat::mcset ja "MIST ?" "雰は?"
::msgcat::mcset ja "FLOOD ON" "水洗点いた"
::msgcat::mcset ja "FLOOD OFF" "水洗消した"
::msgcat::mcset ja "FLOOD ?" "水洗は?"
::msgcat::mcset ja "LUBE ON" "油点いた"
::msgcat::mcset ja "LUBE OFF" "油消した"
::msgcat::mcset ja "SPINDLE FORWARD" "スピンドル前進"
::msgcat::mcset ja "SPINDLE REVERSE" "スピンドル逆"
::msgcat::mcset ja "SPINDLE OFF" "スピンドル消した"
::msgcat::mcset ja "SPINDLE INCREASE" "スピンドル加速"
::msgcat::mcset ja "SPINDLE DECREASE" "スピンドル減速"
::msgcat::mcset ja "SPINDLE ?" "スピンドルは?"
::msgcat::mcset ja "BRAKE ON" "ブレーキ点いた"
::msgcat::mcset ja "BRAKE OFF" "ブレーキ消した"
::msgcat::mcset ja "BRAKE ?" "ぶれーきは?"
