# ---------------------
# Locale file for TkEmc
# ---------------------
#
# Copyright (C) 2005 Alex Joni
# This file is distributed under GPL.
#

::msgcat::mcset ro "Set Run Mark" "Seteaza punct pornire"
::msgcat::mcset ro "Set run mark at line" "Seteaza punct pornire la linia"

::msgcat::mcset ro "Load Tool Table" "Incarca tabela scule"

::msgcat::mcset ro "Load Parameter File" "Incarca fisier parametri"
::msgcat::mcset ro "Cancel" "Anulare"
::msgcat::mcset ro "OK" "OK"

::msgcat::mcset ro "EMC Diagnostics" "EMC-Diagnostic"
::msgcat::mcset ro "Task" "Task"
::msgcat::mcset ro "Heartbeat:" "Bataie:"
::msgcat::mcset ro "Command:" "Comanda:"
::msgcat::mcset ro "Command #:" "Nr. Comanda:"
::msgcat::mcset ro "Status:" "Stare:"
::msgcat::mcset ro "Io" "Io"
::msgcat::mcset ro "Motion" "Miscare"
::msgcat::mcset ro "About TkEmc" "Despre TkEmc"
::msgcat::mcset ro "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "TkEmc\n\nInterfata grafica Tcl/Tk pentru Enhanced Machine Controller\n\nPublic Domain (1999)"
::msgcat::mcset ro "Set Tool Offset" "Seteaza offset scula"
::msgcat::mcset ro "Tool:" "Scula:"
::msgcat::mcset ro "Length:" "Lungime:"
::msgcat::mcset ro "Diameter" "Diametru:"
::msgcat::mcset ro "can't open" "nu pot deschide"

::msgcat::mcset ro "All files" "Toate fisierele"
::msgcat::mcset ro "Text files" "Fisiere text"
::msgcat::mcset ro "NC files" "Fisiere NC"

#Main menu
::msgcat::mcset ro "File" "Fisier"
::msgcat::mcset ro "Open..." "Deschide"
::msgcat::mcset ro "Edit..." "Editeaza"
::msgcat::mcset ro "Reset" "Reseteaza"
::msgcat::mcset ro "Exit" "Iesire"
::msgcat::mcset ro "View" "Vizualizare"
::msgcat::mcset ro "Tools..." "Scule..."
::msgcat::mcset ro "Offsets and Variables..." "Offseturi si variabile..."
::msgcat::mcset ro "Diagnostics..." "Diagnostic"
::msgcat::mcset ro "Backplot..." "Desenare"
::msgcat::mcset ro "Settings" "Setari"
::msgcat::mcset ro "Calibration..." "Calibrare..."
::msgcat::mcset ro "Logging..." "Log-uri..."
::msgcat::mcset ro "Testing..." "Testare..."
::msgcat::mcset ro "Debug..." "Depanare..."
::msgcat::mcset ro "Font..." "Font..."
::msgcat::mcset ro "Units" "Unitati"
::msgcat::mcset ro "auto" "auto"
::msgcat::mcset ro "inches" "inch"
::msgcat::mcset ro "mm" "mm"
::msgcat::mcset ro "cm" "cm"
::msgcat::mcset ro "Scripts" "Scripturi"
::msgcat::mcset ro "Help" "Ajutor"
::msgcat::mcset ro "Help..." "Ajutor..."
::msgcat::mcset ro "Balloon help" "Caseta info"
::msgcat::mcset ro "Info..." "Info..."
::msgcat::mcset ro "About..." "Despre..."

#ESTOP
::msgcat::mcset ro "Estop on" "Estop pornit"
::msgcat::mcset ro "Estop off" "Estop oprit"

#Machine
::msgcat::mcset ro "Machine on" "Masina pornita"
::msgcat::mcset ro "Machine off" "Masina oprita"

#Mode
::msgcat::mcset ro "Manual" "Manual"
::msgcat::mcset ro "Auto" "Auto"
::msgcat::mcset ro "MDI" "MDI"

#Mist
::msgcat::mcset ro "Mist on" "Vapori porniti"
::msgcat::mcset ro "Mist off" "Vapori opriti"

#Flood
::msgcat::mcset ro "Flood on" "Lichid pornit"
::msgcat::mcset ro "Flood off" "Lichid oprit"

#Lube
::msgcat::mcset ro "Lube on" "Lubrifiant pornit"
::msgcat::mcset ro "Lube off" "Lubrifiant oprit"

#Spindle
::msgcat::mcset ro "Spindle forward" "Freza pornita"
::msgcat::mcset ro "Spindle reverse" "Freza sens invers"
::msgcat::mcset ro "Spindle off" "Freza oprita"
::msgcat::mcset ro "Break on" "Frana pornita"
::msgcat::mcset ro "Break off" "Frana oprita"

#Bremse
::msgcat::mcset ro "Brake on" "Frana pornita"
::msgcat::mcset ro "Brake off" "Frana oprita"

::msgcat::mcset ro "ABORT" "ABORTARE"

::msgcat::mcset ro "Offset:" "Ofset:"
::msgcat::mcset ro "Work Offsets:" "Ofseturi de lucru:"

::msgcat::mcset ro "override limits" "depaseste limite"
::msgcat::mcset ro "relative" "relativ"
::msgcat::mcset ro "machine" "masina"
::msgcat::mcset ro "actual" "actual"
::msgcat::mcset ro "commanded" "comandat"
::msgcat::mcset ro "joint" "articulatie"
::msgcat::mcset ro "world" "global"

::msgcat::mcset ro "continuous" "continuu"

::msgcat::mcset ro "home" "poz.0"

::msgcat::mcset ro "Axis Offset" "Ofset axa"
::msgcat::mcset ro "Set axis value:" "Seteaza valoara axa:"

::msgcat::mcset ro "Set Jog Speed" "Seteaza viteza jog"
::msgcat::mcset ro "Set jog speed:" "Viteza jog:"
::msgcat::mcset ro "Set Feed Override" "Seteaza depasire viteza"
::msgcat::mcset ro "Set feed override:" "Seteaza depasire viteza:"

::msgcat::mcset ro "Axis Speed:" "Viteza axa:"
::msgcat::mcset ro "Feed Override:" "Depasire viteza:"

::msgcat::mcset ro "MDI:" "MDI:"

#modes
::msgcat::mcset ro "MDI" "MDI"
::msgcat::mcset ro "AUTO" "AUTO"
::msgcat::mcset ro "MANUAL" "MANUAL"

::msgcat::mcset ro "Program: " "Program: "
::msgcat::mcset ro " - Status: " " - Stare: "

#bottom menu
::msgcat::mcset ro "Open..." "Deschide..."
::msgcat::mcset ro "Run" "Ruleaza"
::msgcat::mcset ro "Pause" "Pauza"
::msgcat::mcset ro "Resume" "Rezuma"
::msgcat::mcset ro "Step" "Pas"
::msgcat::mcset ro "Verify" "Verifica"

::msgcat::mcset ro "Error: " "Eroare: "
::msgcat::mcset ro "Error" "Eroare"

#popupFont
::msgcat::mcset ro "Set Font" "Seteaza font"

#updateStatus
::msgcat::mcset ro "ESTOP" "ESTOP"
::msgcat::mcset ro "ON" "PORNIT"
::msgcat::mcset ro "ESTOP RESET" "ESTOP RESETAT"
::msgcat::mcset ro "MIST ON" "VAPORI PORNITI"
::msgcat::mcset ro "MIST OFF" "VAPORI OPRITI"
::msgcat::mcset ro "MIST ?" "VAPORI ?"
::msgcat::mcset ro "FLOOD ON" "LICHID PORNIT"
::msgcat::mcset ro "FLOOD OFF" "LICHID OPRIT"
::msgcat::mcset ro "FLOOD ?" "LICHID ?"
::msgcat::mcset ro "LUBE ON" "LUBRIFIANT PORNIT"
::msgcat::mcset ro "LUBE OFF" "LUBRIFIANT OPRIT"
::msgcat::mcset ro "SPINDLE FORWARD" "FREZA PORNITA"
::msgcat::mcset ro "SPINDLE REVERSE" "FREZA SENS INVERS"
::msgcat::mcset ro "SPINDLE OFF" "FREZA OPRITA"
::msgcat::mcset ro "SPINDLE INCREASE" "FREZA ACCELERARE"
::msgcat::mcset ro "SPINDLE DECREASE" "FREZA DECELERARE"
::msgcat::mcset ro "SPINDLE ?" "SPINDLE ?"
::msgcat::mcset ro "BRAKE ON" "FRANA PORNITA"
::msgcat::mcset ro "BRAKE OFF" "FRANA OPRITA"
::msgcat::mcset ro "BRAKE ?" "FRANA ?"



################################################################################
# Translations for setupconfig.tcl                                             #
################################################################################
::msgcat::mcset de "No details available." ""

# main_page {}
::msgcat::mcset de "Welcome to EMC2!\n" ""
::msgcat::mcset de "To run EMC2 with an existing configuration," ""
::msgcat::mcset de "click the RUN button.\n" ""
::msgcat::mcset de "To create a new configuration, edit a configuration, backup or" ""
::msgcat::mcset de "restore a configuration, or do other configuration related tasks," ""
::msgcat::mcset de "click the CONFIG button.\n" ""

# choose_run_config {}
::msgcat::mcset de "Please select an EMC2 configuration from the list below and click 'RUN'." ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""
::msgcat::mcset de "You must choose a config if you want to run EMC2!" ""

# check_run_ini {}
::msgcat::mcset de "ERROR: no ini file(s) found in config directory" ""
::msgcat::mcset de "Click OK to continue." ""

# choose_run_ini {}
::msgcat::mcset de "The config contains multiple ini files.\nPick one from the list below and click NEXT." ""
::msgcat::mcset de "You must select one ini file!" ""

# execute_run {}
::msgcat::mcset de "The next step is to invoke the run script to run" ""
::msgcat::mcset de "But thats not coded yet, so just click OK to quit." ""

# config_manager {}
::msgcat::mcset de "This page is used to manage EMC2 machine configurations.\n" ""
::msgcat::mcset de "The list below shows all of the existing EMC2\nconfigurations on this computer.\n\nSelect a config, then click one of the buttons below.\n" ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""

# not_implemented {}
::msgcat::mcset de "Sorry, this function is not implemented yet.\n\nClick OK to return to the menu" ""

# new_intro {}
::msgcat::mcset de "You have chosen to create a new EMC2 configuration.\n\nThe next few screens will walk you through the process." ""

# new_get_name {}
::msgcat::mcset de "Please select a name for your new configuration." ""
::msgcat::mcset de "(This will become a directory name, so please use only letters,\ndigits, period, dash, or underscore.)" ""
::msgcat::mcset de "contains illegal characters!\nPlease choose a new name." ""
::msgcat::mcset de "A directory or file called" ""
::msgcat::mcset de "already exists!\nPlease choose a new name." ""

# new_get_template {}
::msgcat::mcset de "Please select one of these existing configurations as the template\nfor your new configuration.\n\nAll the files associated with the template will be copied into your new\nconfig, so you can make whatever modifications are needed." ""
::msgcat::mcset de "\nDetails about the selected configuration:" ""
::msgcat::mcset de "Creating new EMC2 configuration" ""
::msgcat::mcset de "A internal error has occurred, or the template directory was deleted.\nClick OK to quit" ""
::msgcat::mcset de "Enter a description here" ""

# new_get_description {}
::msgcat::mcset de "Creating new EMC2 configuration" ""
::msgcat::mcset de "based on template" ""
::msgcat::mcset de "Please enter a description of your configuration.\n\nThe box below has been preloaded with the description of the template, but\nit is strongly recommended that you revise it.  At a minimum,\nput your name and some specifics about your machine here." ""
::msgcat::mcset de "(If you ever need help, someone may ask you to send them your\nconfiguration, and this information could be very usefull.)" ""
::msgcat::mcset de "You must enter at least one word!" ""

# new_verify {}
::msgcat::mcset de "You are about to create a new EMC2 configuration.\n\nPlease verify that this is what you want:" ""
::msgcat::mcset de "Name" ""
::msgcat::mcset de "Template" ""
::msgcat::mcset de "Description" ""
::msgcat::mcset de "If this information is correct, click NEXT to create\nthe configuration directory and begin copying files." ""

# new_do_copying {}
::msgcat::mcset de "Creating new config directory" ""
::msgcat::mcset de "ERROR: Config directory could not be created." ""
::msgcat::mcset de "Done" ""
::msgcat::mcset de "Checking for ini file(s)..." ""
::msgcat::mcset de "Transferring ini file" ""
::msgcat::mcset de "Writing description file 'README'..." ""
::msgcat::mcset de "Checking for other template file(s)..." ""
::msgcat::mcset de "Copying template file" ""
::msgcat::mcset de "Checking for common file(s)..." ""
::msgcat::mcset de "Copying common file" ""

# new_config_done {}
::msgcat::mcset de "Your new configuration" ""
::msgcat::mcset de "has been created.\nClick OK to return to the main menu." ""

# new_config_error {}
::msgcat::mcset de "An error happened while creating the new configuration.\nIdeally this code would clean everything up and\nthen return to the main menu, but the cleanup isn't done yet.\nClick OK to return to the main menu." ""

# resolve_config {}
::msgcat::mcset de "ERROR: Not a valid config directory (contains no .ini files)" ""
::msgcat::mcset de "ERROR: Not a valid ini file (must end in .ini)" ""
::msgcat::mcset de "Click OK to continue." ""
::msgcat::mcset de "ERROR: Not a valid config directory (contains no .ini files)" ""
::msgcat::mcset de "ERROR: Config not found" ""
::msgcat::mcset de "ERROR: Not a valid config name\n(must be either <config-name> or <config-name>/<ini-name>)" ""

# main program
::msgcat::mcset de "EMC2 Configuration Manager" ""
::msgcat::mcset de "ERROR: option '--configs_dir' must be followed by a directory name." ""
::msgcat::mcset de "Click OK to exit." ""
::msgcat::mcset de "ERROR: '--configs-dir' argument is" ""
::msgcat::mcset de "which is not a directory." ""
::msgcat::mcset de "ERROR: environment variable EMC2_CONFIG_DIR is" ""
::msgcat::mcset de "ERROR: Cannot find the EMC2 configurations directory.\nYou can specify the directory with the '--configs_dir <dir>' option." ""
::msgcat::mcset de "ERROR: options '--run', '--new', and '--get-config' are\nmutually exclusive, please specify only one." ""
::msgcat::mcset de "ERROR: unknown command line option:" ""
