# ---------------------
# Locale file for TkEmc
# ---------------------
#
# Copyright (C) 2005 Alex Joni
# This file is distributed under GPL.
#

::msgcat::mcset ro "Set Run Mark" "Seteaza punct pornire"
::msgcat::mcset ro "Set run mark at line" "Seteaza punct pornire la linia"

::msgcat::mcset ro "Load Tool Table" "Incarca tabela scule"

::msgcat::mcset ro "Load Parameter File" "Incarca fisier parametri"
::msgcat::mcset ro "Cancel" "Anulare"
::msgcat::mcset ro "OK" "OK"

::msgcat::mcset ro "EMC Diagnostics" "EMC-Diagnostic"
::msgcat::mcset ro "Task" "Task"
::msgcat::mcset ro "Heartbeat:" "Bataie:"
::msgcat::mcset ro "Command:" "Comanda:"
::msgcat::mcset ro "Command #:" "Nr. Comanda:"
::msgcat::mcset ro "Status:" "Stare:"
::msgcat::mcset ro "Io" "Io"
::msgcat::mcset ro "Motion" "Miscare"
::msgcat::mcset ro "About TkEmc" "Despre TkEmc"
::msgcat::mcset ro "TkEmc\n\nTcl/Tk GUI for Enhanced Machine Controller\n\nPublic Domain (1999)" "TkEmc\n\nInterfata grafica Tcl/Tk pentru Enhanced Machine Controller\n\nPublic Domain (1999)"
::msgcat::mcset ro "Set Tool Offset" "Seteaza offset scula"
::msgcat::mcset ro "Tool:" "Scula:"
::msgcat::mcset ro "Length:" "Lungime:"
::msgcat::mcset ro "Diameter" "Diametru:"
::msgcat::mcset ro "can't open" "nu pot deschide"

::msgcat::mcset ro "All files" "Toate fisierele"
::msgcat::mcset ro "Text files" "Fisiere text"
::msgcat::mcset ro "NC files" "Fisiere NC"

#Main menu
::msgcat::mcset ro "File" "Fisier"
::msgcat::mcset ro "Open..." "Deschide"
::msgcat::mcset ro "Edit..." "Editeaza"
::msgcat::mcset ro "Reset" "Reseteaza"
::msgcat::mcset ro "Exit" "Iesire"
::msgcat::mcset ro "View" "Vizualizare"
::msgcat::mcset ro "Tools..." "Scule..."
::msgcat::mcset ro "Offsets and Variables..." "Offseturi si variabile..."
::msgcat::mcset ro "Diagnostics..." "Diagnostic"
::msgcat::mcset ro "Backplot..." "Desenare"
::msgcat::mcset ro "Settings" "Setari"
::msgcat::mcset ro "Calibration..." "Calibrare..."
::msgcat::mcset ro "Logging..." "Log-uri..."
::msgcat::mcset ro "Testing..." "Testare..."
::msgcat::mcset ro "Debug..." "Depanare..."
::msgcat::mcset ro "Font..." "Font..."
::msgcat::mcset ro "Units" "Unitati"
::msgcat::mcset ro "auto" "auto"
::msgcat::mcset ro "inches" "inch"
::msgcat::mcset ro "mm" "mm"
::msgcat::mcset ro "cm" "cm"
::msgcat::mcset ro "Scripts" "Scripturi"
::msgcat::mcset ro "Help" "Ajutor"
::msgcat::mcset ro "Help..." "Ajutor..."
::msgcat::mcset ro "Balloon help" "Caseta info"
::msgcat::mcset ro "Info..." "Info..."
::msgcat::mcset ro "About..." "Despre..."

#ESTOP
::msgcat::mcset ro "Estop on" "Estop pornit"
::msgcat::mcset ro "Estop off" "Estop oprit"

#Machine
::msgcat::mcset ro "Machine on" "Masina pornita"
::msgcat::mcset ro "Machine off" "Masina oprita"

#Mode
::msgcat::mcset ro "Manual" "Manual"
::msgcat::mcset ro "Auto" "Auto"
::msgcat::mcset ro "MDI" "MDI"

#Mist
::msgcat::mcset ro "Mist on" "Vapori porniti"
::msgcat::mcset ro "Mist off" "Vapori opriti"

#Flood
::msgcat::mcset ro "Flood on" "Lichid pornit"
::msgcat::mcset ro "Flood off" "Lichid oprit"

#Lube
::msgcat::mcset ro "Lube on" "Lubrifiant pornit"
::msgcat::mcset ro "Lube off" "Lubrifiant oprit"

#Spindle
::msgcat::mcset ro "Spindle forward" "Freza pornita"
::msgcat::mcset ro "Spindle reverse" "Freza sens invers"
::msgcat::mcset ro "Spindle off" "Freza oprita"
::msgcat::mcset ro "Break on" "Frana pornita"
::msgcat::mcset ro "Break off" "Frana oprita"

#Bremse
::msgcat::mcset ro "Brake on" "Frana pornita"
::msgcat::mcset ro "Brake off" "Frana oprita"

::msgcat::mcset ro "ABORT" "ABORTARE"

::msgcat::mcset ro "Offset:" "Ofset:"
::msgcat::mcset ro "Work Offsets:" "Ofseturi de lucru:"

::msgcat::mcset ro "override limits" "depaseste limite"
::msgcat::mcset ro "relative" "relativ"
::msgcat::mcset ro "machine" "masina"
::msgcat::mcset ro "actual" "actual"
::msgcat::mcset ro "commanded" "comandat"
::msgcat::mcset ro "joint" "articulatie"
::msgcat::mcset ro "world" "global"

::msgcat::mcset ro "continous" "continuu"

::msgcat::mcset ro "home" "poz.0"

::msgcat::mcset ro "Axis Offset" "Ofset axa"
::msgcat::mcset ro "Set axis value:" "Seteaza valoara axa:"

::msgcat::mcset ro "Set Jog Speed" "Seteaza viteza jog"
::msgcat::mcset ro "Set jog speed:" "Viteza jog:"
::msgcat::mcset ro "Set Feed Override" "Seteaza depasire viteza"
::msgcat::mcset ro "Set feed override:" "Seteaza depasire viteza:"

::msgcat::mcset ro "Axis Speed:" "Viteza axa:"
::msgcat::mcset ro "Feed Override:" "Depasire viteza:"

::msgcat::mcset ro "MDI:" "MDI:"

#modes
::msgcat::mcset ro "MDI" "MDI"
::msgcat::mcset ro "AUTO" "AUTO"
::msgcat::mcset ro "MANUAL" "MANUAL"

::msgcat::mcset ro "Program: " "Program: "
::msgcat::mcset ro " - Status: " " - Stare: "

#bottom menu
::msgcat::mcset ro "Open..." "Deschide..."
::msgcat::mcset ro "Run" "Ruleaza"
::msgcat::mcset ro "Pause" "Pauza"
::msgcat::mcset ro "Resume" "Rezuma"
::msgcat::mcset ro "Step" "Pas"
::msgcat::mcset ro "Verify" "Verifica"

::msgcat::mcset ro "Error: " "Eroare: "
::msgcat::mcset ro "Error" "Eroare"

#popupFont
::msgcat::mcset ro "Set Font" "Seteaza font"

#updateStatus
::msgcat::mcset ro "ESTOP" "ESTOP"
::msgcat::mcset ro "ON" "PORNIT"
::msgcat::mcset ro "ESTOP RESET" "ESTOP RESETAT"
::msgcat::mcset ro "MIST ON" "VAPORI PORNITI"
::msgcat::mcset ro "MIST OFF" "VAPORI OPRITI"
::msgcat::mcset ro "MIST ?" "VAPORI ?"
::msgcat::mcset ro "FLOOD ON" "LICHID PORNIT"
::msgcat::mcset ro "FLOOD OFF" "LICHID OPRIT"
::msgcat::mcset ro "FLOOD ?" "LICHID ?"
::msgcat::mcset ro "LUBE ON" "LUBRIFIANT PORNIT"
::msgcat::mcset ro "LUBE OFF" "LUBRIFIANT OPRIT"
::msgcat::mcset ro "SPINDLE FORWARD" "FREZA PORNITA"
::msgcat::mcset ro "SPINDLE REVERSE" "FREZA SENS INVERS"
::msgcat::mcset ro "SPINDLE OFF" "FREZA OPRITA"
::msgcat::mcset ro "SPINDLE INCREASE" "FREZA ACCELERARE"
::msgcat::mcset ro "SPINDLE DECREASE" "FREZA DECELERARE"
::msgcat::mcset ro "SPINDLE ?" "SPINDLE ?"
::msgcat::mcset ro "BRAKE ON" "FRANA PORNITA"
::msgcat::mcset ro "BRAKE OFF" "FRANA OPRITA"
::msgcat::mcset ro "BRAKE ?" "FRANA ?"
