// Package gomodtest provides tests for pure Go inter-module calls (gomod→gomod).
// This tests the pattern where a Go module registers callbacks and another
// Go module looks them up and calls them directly.
package gomodtest

import (
	"errors"
	"syscall"
	"testing"
	"unsafe"

	"github.com/sittner/linuxcnc/src/gomc/internal/apiserver"
)

// ─── Test API Definition ───

// ItemInfo represents an item in our test API.
type ItemInfo struct {
	Name  string
	Value float64
}

// ItemCallbacks defines the test API that modules implement.
type ItemCallbacks interface {
	ListItems(pattern string) ([]ItemInfo, error)
	GetItem(name string) (*ItemInfo, error)
	CreateItem(name string, value float64) (*ItemInfo, error)
	DeleteItem(name string) error
}

// ─── Test Implementation ───

type memoryStore struct {
	items map[string]ItemInfo
}

func newMemoryStore() *memoryStore {
	return &memoryStore{items: make(map[string]ItemInfo)}
}

func (s *memoryStore) ListItems(pattern string) ([]ItemInfo, error) {
	result := make([]ItemInfo, 0, len(s.items))
	for _, item := range s.items {
		result = append(result, item)
	}
	return result, nil
}

func (s *memoryStore) GetItem(name string) (*ItemInfo, error) {
	item, ok := s.items[name]
	if !ok {
		return nil, syscall.ENOENT
	}
	return &item, nil
}

func (s *memoryStore) CreateItem(name string, value float64) (*ItemInfo, error) {
	if _, exists := s.items[name]; exists {
		return nil, syscall.EEXIST
	}
	item := ItemInfo{Name: name, Value: value}
	s.items[name] = item
	return &item, nil
}

func (s *memoryStore) DeleteItem(name string) error {
	if _, exists := s.items[name]; !exists {
		return syscall.ENOENT
	}
	delete(s.items, name)
	return nil
}

// ─── Helper: Convert interface to/from unsafe.Pointer ───
// In real code, this would be generated by gmicompile.

func registerItemAPI(reg *apiserver.Registry, instance string, impl ItemCallbacks) error {
	// Store the interface as unsafe.Pointer
	// The pointer points to the interface value itself
	iface := impl
	return reg.Register("items", 1, instance, unsafe.Pointer(&iface))
}

func getItemAPI(reg *apiserver.Registry, instance string) (ItemCallbacks, error) {
	ptr, err := reg.GetAPIUntracked("items", instance, 1)
	if err != nil {
		return nil, err
	}
	// Cast back to interface pointer and dereference
	return *(*ItemCallbacks)(ptr), nil
}

// ─── Tests: gomod → gomod ───

func TestGomodToGomodRegisterAndCall(t *testing.T) {
	reg := apiserver.NewRegistry()

	// Provider: register the API implementation
	store := newMemoryStore()
	err := registerItemAPI(reg, "store1", store)
	if err != nil {
		t.Fatalf("Register: %v", err)
	}

	// Consumer: look up and use the API
	api, err := getItemAPI(reg, "store1")
	if err != nil {
		t.Fatalf("GetAPI: %v", err)
	}

	// Test CreateItem
	item, err := api.CreateItem("widget", 42.5)
	if err != nil {
		t.Fatalf("CreateItem: %v", err)
	}
	if item.Name != "widget" || item.Value != 42.5 {
		t.Errorf("CreateItem returned %+v, want {widget, 42.5}", item)
	}

	// Test GetItem
	item, err = api.GetItem("widget")
	if err != nil {
		t.Fatalf("GetItem: %v", err)
	}
	if item.Name != "widget" || item.Value != 42.5 {
		t.Errorf("GetItem returned %+v, want {widget, 42.5}", item)
	}

	// Test ListItems
	items, err := api.ListItems("*")
	if err != nil {
		t.Fatalf("ListItems: %v", err)
	}
	if len(items) != 1 {
		t.Errorf("ListItems returned %d items, want 1", len(items))
	}

	// Test DeleteItem
	err = api.DeleteItem("widget")
	if err != nil {
		t.Fatalf("DeleteItem: %v", err)
	}

	// Verify deleted
	_, err = api.GetItem("widget")
	if !errors.Is(err, syscall.ENOENT) {
		t.Errorf("GetItem after delete: got %v, want ENOENT", err)
	}
}

func TestGomodToGomodMultipleInstances(t *testing.T) {
	reg := apiserver.NewRegistry()

	// Register two different instances
	store1 := newMemoryStore()
	store2 := newMemoryStore()

	registerItemAPI(reg, "store1", store1)
	registerItemAPI(reg, "store2", store2)

	// Get both APIs
	api1, _ := getItemAPI(reg, "store1")
	api2, _ := getItemAPI(reg, "store2")

	// Create items in different stores
	api1.CreateItem("a", 1.0)
	api2.CreateItem("b", 2.0)

	// Verify isolation
	items1, _ := api1.ListItems("*")
	items2, _ := api2.ListItems("*")

	if len(items1) != 1 || items1[0].Name != "a" {
		t.Errorf("store1 items = %v, want [{a, 1.0}]", items1)
	}
	if len(items2) != 1 || items2[0].Name != "b" {
		t.Errorf("store2 items = %v, want [{b, 2.0}]", items2)
	}
}

func TestGomodToGomodErrorPropagation(t *testing.T) {
	reg := apiserver.NewRegistry()
	store := newMemoryStore()
	registerItemAPI(reg, "store", store)
	api, _ := getItemAPI(reg, "store")

	// GetItem on non-existent should return ENOENT
	_, err := api.GetItem("nonexistent")
	if !errors.Is(err, syscall.ENOENT) {
		t.Errorf("GetItem(nonexistent): got %v, want ENOENT", err)
	}

	// CreateItem duplicate should return EEXIST
	api.CreateItem("foo", 1.0)
	_, err = api.CreateItem("foo", 2.0)
	if !errors.Is(err, syscall.EEXIST) {
		t.Errorf("CreateItem(duplicate): got %v, want EEXIST", err)
	}

	// DeleteItem non-existent should return ENOENT
	err = api.DeleteItem("nonexistent")
	if !errors.Is(err, syscall.ENOENT) {
		t.Errorf("DeleteItem(nonexistent): got %v, want ENOENT", err)
	}
}

func TestGomodToGomodLookupNotFound(t *testing.T) {
	reg := apiserver.NewRegistry()

	_, err := getItemAPI(reg, "nonexistent")
	if !errors.Is(err, syscall.ENOENT) {
		t.Errorf("GetAPI(nonexistent): got %v, want ENOENT", err)
	}
}

func TestGomodToGomodVersionMismatch(t *testing.T) {
	reg := apiserver.NewRegistry()
	store := newMemoryStore()
	registerItemAPI(reg, "store", store)

	// Try to get with wrong version
	_, err := reg.GetAPIUntracked("items", "store", 2)
	if !errors.Is(err, syscall.EINVAL) {
		t.Errorf("GetAPI(wrong version): got %v, want EINVAL", err)
	}
}
