#!/bin/sh
cd "$(dirname "$1")" || { echo "E: Could not change directory to '$(dirname "$1")'"; exit 1; }
RETVAL=0
for EXPECTED in *.expected ; do
    BASE=$(basename "$EXPECTED" .expected)
    RESULT=$BASE.result
    diff -u "$EXPECTED" "$RESULT" || RETVAL=1
done
exit $RETVAL
