= rtapi_print(3rtapi)
:manmanual: HAL Components
:mansource: ../man/man3/rtapi_print.3rtapi.asciidoc
:man version : 


== NAME

rtapi_print, rtapi_print_msg -- print diagnostic messages



== SYNTAX
 void rtapi_print(const char *__fmt__, __...__)

 void rtapi_print_msg(int level, const char *__fmt__, __...__)

 typedef void(***rtapi_msg_handler_t**)(msg_level_t __level__, const char *__msg__);
 void **rtapi_set_msg_handler**(rtapi_msg_handler_t __handler__);
 rtapi_msg_handler_t **rtapi_set_msg_handler**(void);


== ARGUMENTS
.IP __level__
A message level: One of **RTAPI_MSG_ERR**,
**RTAPI_MSG_WARN**, **RTAPI_MSG_INFO**, or **RTAPI_MSG_DBG**.

.IP __handler__
A function to call from **rtapi_print** or **rtapi_print_msg** to
actually output the message.

.IP __fmt
__.IP __...
__Other arguments are as for __printf(3)__.



== DESCRIPTION
**rtapi_print** and **rtapi_print_msg** work like the standard C
printf functions, except that a reduced set of formatting operations are
supported.

Depending on the RTOS, the default may be to print the message to stdout,
stderr, a kernel log, etc.   In RTAPI code, the action may be changed by
a call to **rtapi_set_msg_handler**.  A **NULL** argument to
**rtapi_set_msg_handler** restores the default handler.
**rtapi_msg_get_handler** returns the current handler.  When the
message came from **rtapi_print**, __level__ is RTAPI_MSG_ALL.

**rtapi_print_msg** works like rtapi_print but only prints if
__level__ is less than or equal to the current message level.



== REALTIME CONSIDERATIONS
**rtapi_print** and **rtapi_print_msg** May be called from user,
init/cleanup, and realtime code.  **rtapi_get_msg_handler** and
**ftapi_set_msg_handler** may be called from realtime init/cleanup
code.  A message handler passed to **rtapi_set_msg_handler** may only
call functions that can be called from realtime code.



== RETURN VALUE
None.



== SEE ALSO
**rtapi_set_msg_level(3rtapi)**, **rtapi_get_msg_level(3rtapi)**,
**printf(3)**
