#!/bin/sh


export INI_FILE_NAME=motorctrl.ini

# to get the MKUUID to gladevcp and avconfigserver via environment
# (might be remote after all)

export MKUUID=`inivar -var MKUUID -sec GLOBAL -ini motorctrl.ini`
killall avconfigserver
sleep 1
avconfigserver &

halrun -I motorctrl.hal
#DEBUG=5 halrun -I motorctrl.hal

killall avconfigserver
