component and2 "Two-input AND gate";
pin in bit in0;
pin in bit in1;
pin out bit out r"""
computed from the value of *in0* and *in1* according to the following truth table:
+
[options="header"]
|=======================
|in0   | in1   | out
|TRUE  | TRUE  | TRUE
2+|otherwise   | FALSE
|=======================
"""
;
function _ nofp;
option asciidoc;
license "GPL";
;;
FUNCTION(_) { out = in0 && in1; }
