component bitwise "Computes various bitwise operations on the two input values";
pin in uint in0 "First input value";
pin in uint in1 "Second input value";
pin out uint out-and "The bitwise AND of the two inputs";
pin out uint out-or "The bitwise OR of the two inputs";
pin out uint out-xor "The bitwise XOR of the two inputs";
pin out uint out-nand "The inverse of the bitwise AND";
pin out uint out-nor "The inverse of the bitwise OR";
pin out uint out-xnor "The inverse of the bitwise XOR";

author "Andy Pugh";
license "GPL 2+";
function _;
option period no;
;;

rtapi_uint i0 = in0;
rtapi_uint i1 = in1;
out_nand_set(~out_and_set(i0 & i1));
out_nor_set( ~out_or_set( i0 | i1));
out_xnor_set(~out_xor_set(i0 ^ i1));
