component gray2bin "convert a gray-code input to binary";
description """Converts a gray-coded number into the corresponding binary value""";
pin in uint in "gray code in";
pin out uint out "binary code out";
license "GPL";
author "Andy Pugh";
function _;
option period no;
;;
rtapi_uint mask;
rtapi_uint val = in;
for(mask = val >> 1 ; mask != 0 ; mask = mask >> 1){
    val ^= mask;
}
out_set(val);
