component integ "Integrator with gain pin and windup limits";
pin in real in;
pin in real gain = 1.0;
pin out real out "The discrete integral of 'gain * in' since 'reset' was deasserted";
pin in bool reset "When asserted, set out to 0";
pin in real max_ =  1e20;
pin in real min_ = -1e20;

function _;
license "GPL";
author "Jeff Epler";
;;
FUNCTION(_) {
    rtapi_real val = out;
    if(reset) val = 0.0;
    else out_set(val += gain * in * fperiod);
    rtapi_real tmp;
    if(val > (tmp = max_)) out_set(tmp);
    if(val < (tmp = min_)) out_set(tmp);
}
