component latencybins
"""comp utility for scripts/latency-histogram
""";
description """
Read *availablebins* pin for the number of bins available. Set the
*maxbinnumber* pin for the number of ±;bins.
Ensure *maxbinnumber* ≤ *availablebins*.

For *maxbinnumber* = N, the bins are numbered:

* -N ... 0 ... +N bins +
  (the -0 bin is not populated) +
  (total effective bins = 2 * maxbinnumber + 1)

Set *nsbinsize* pin for the binsize (ns).

Iterate:

* Set *index* pin to a bin number: 0 ≤ *index* ≤ maxbinnumber.
* Read check pin and verify that check pin == *index* pin.
* Read output pins:
** *pbinvalue* is count for bin = +*index*
** *nbinvalue* is count for bin = -*index*
** *pextra*    is count for all bins > *maxbinnumber*
** *nextra*    is count for all bins < *maxbinnumber*
** *latency-min* is max negative latency
** *latency-max* is max positive latency

If *index* is out of range (*index* < 0 or *index* > *maxbinnumber*)
then *pbinvalue* = *nbinvalue* = -1. The reset pin may be used to restart.

The latency pin outputs the instantaneous latency.

Maintainers note: hardcoded for MAXBINNUMBER==1000
""";

pin in  sint maxbinnumber = 1000;  // MAXBINNUMBER
pin in  sint index;  //use sint to avoid 0x hex display in hal
pin in  bool reset;
pin in  sint nsbinsize;

pin out sint check;
pin out sint latency;
pin out sint latency_max;
pin out sint latency_min;
pin out sint pbinvalue;
pin out sint nbinvalue;
pin out sint pextra;
pin out sint nextra;
pin out sint variance;

// user may interrogate available bins to determine this compiled-in limit
pin out sint availablebins = 1000; // MAXBINNUMBER

function _;
variable rtapi_sint last_timer = 0;
variable rtapi_sint last_binmax = 0;
variable int    first = 1;
variable rtapi_sint pbins[1001]; // MAXBINNUMBER+1
variable rtapi_sint nbins[1001]; // MAXBINNUMBER+1
variable rtapi_sint binmax = 0;

variable rtapi_uint nsamples;
variable rtapi_uint sum;
variable rtapi_uint sq_sum;

license "GPL";
author "Dewey Garrett";
;;

rtapi_sint now = rtapi_get_time();
rtapi_sint lat = (rtapi_sint)(now - last_timer - period);

last_timer = now;

binmax =  maxbinnumber;
if (binmax > availablebins) binmax = availablebins;
last_binmax = binmax;

if (reset) {first = 1;}

if (   first
     || binmax != last_binmax
     || nsbinsize == 0  // important to avoid divide by zero
  ) {
  first = 0;
  latency_set(0);
  latency_min_set(RTAPI_SINT_MAX);
  latency_max_set(RTAPI_SINT_MIN);
  pextra_set(0);
  nextra_set(0);
  for (int i = 0; i <= binmax; i++) {
    pbins[i] = 0; nbins[i] = 0;
  }
  nsamples = 0;
  sum = 0;
  sq_sum = 0;
} else {
  latency_set(lat);
  rtapi_sint i = lat/nsbinsize;
  if (lat > latency_max) latency_max_set(lat);
  if (lat < latency_min) latency_min_set(lat);
  if (i >= 0) {
     if (i > binmax) {
       pextra_set(pextra + 1);
     } else {
       pbins[i]++;
     }
  } else {
     i = -i;
     if (i > binmax) {
       nextra_set(nextra + 1);
     } else {
       nbins[i]++;
     }
  }
  nsamples++;
  sum    += lat;
  sq_sum += lat * lat;
  if (nsamples > 1) {
    // note: division required is: u64/u32
    rtapi_u64 dividend;
    rtapi_u64 divisor;
    dividend = sq_sum - rtapi_div_u64(sum * sum,nsamples);
    divisor  = nsamples -1;
    variance_set(rtapi_div_u64(dividend,divisor));
  }
}

check_set(index); // user should verify check==index for reading values
// -1 value indicates illegal index
if (index < 0) {
  pbinvalue_set(-1);
  nbinvalue_set(-1);
} else if (index <=binmax) {
  pbinvalue_set(pbins[index]);
  nbinvalue_set(nbins[index]);
} else {
  pbinvalue_set(-1);
  nbinvalue_set(-1);
}
