component minmax "Track the minimum and maximum values of the input to the outputs";
pin in real in;
pin in bool reset "When reset is asserted, 'in' is copied to the outputs";
pin out real max_;
pin out real min_;
option period no;
function _;
license "GPL";
author "Jeff Epler";
;;
FUNCTION(_) {
    if(reset) { max__set(min__set(in)); }
    else {
        if(in > max_) max__set(in);
        if(in < min_) min__set(in);
    }
}
