component or2 "Two-input OR gate";
pin in bit in0;
pin in bit in1;
pin out bit out r"""
**out** is computed from the value of **in0** and **in1** according
to the following rule:
+
[options="header"]
|=======================
|in0   | in1   | out
|FALSE | FALSE | FALSE
2+|otherwise   | TRUE
|=======================
""";

option asciidoc;
function _ nofp;
license "GPL";
;;
FUNCTION(_) { out = in0 || in1; }
