component or2 "Two-input OR gate";
pin in bit in0;
pin in bit in1;
pin out bit out r"""
\fBout\fR is computed from the value of \fBin0\fR and \fBin1\fR according
to the following rule:
.RS
.TP
\fBin0=FALSE in1=FALSE\fB
\fBout=FALSE\fR
.TP
Otherwise,
\fBout=TRUE\fR
.RE"""
;
function _ nofp;
see_also """
\\fBlogic\\fR(9)
""";
license "GPL";
author "Jeff Epler";
option period no;
;;
FUNCTION(_) { out = in0 || in1; }
