component or2 "Two-input OR gate";
pin in bool in0 "First input";
pin in bool in1 "Second input";
pin out bool out "Output";

description """
The *out* pin is computed from the value of the *in0* and *in1* pins according
to the following truth table:

[options="header",cols="^1,^1,^1"]
|===
^h|in1
^h|in0
^h|out

|0|0|0
|0|1|1
|1|0|1
|1|1|1
|===

"""
;
function _;
see_also """
*logic*(9)
""";
license "GPL";
author "Jeff Epler";
option period no;
;;
FUNCTION(_) { out_set(in0 || in1); }
