component scaled_sint_sums "Sum of four inputs (each with a scale)";
see_also "sum2(9), weighted_sum(9)";
pin in sint in0;
pin in sint in1;
pin in sint in2;
pin in sint in3;
pin in real scale0 = 1.0;
pin in real scale1 = 1.0;
pin in real scale2 = 1.0;
pin in real scale3 = 1.0;
pin out sint out_s;
pin out real out_f "out-s = out-f = (in0 * scale0) + (in1 * scale1) + (in2 * scale2) + (in3 * scale3)";
option period no;
function _;
license "GPL";
author "Chris S Morley";
;;
FUNCTION(_) {
    out_s_set(out_f_set(in0 * scale0 + in1 * scale1 + in2 * scale2 + in3 * scale3));
}
