component sphereprobe "Probe a pretend hemisphere";
author "Jeff Epler";
license "GPL";

pin in sint px;
pin in sint py;
pin in sint pz "*rawcounts* position from software encoder";

pin in sint cx;
pin in sint cy;
pin in sint cz "Center of sphere in counts";
pin in sint r "Radius of hemisphere in counts";

pin out bool probe-out;

option period no;
function _ "update probe-out based on inputs";
;;
static inline rtapi_uint myabs(rtapi_sint x) { return x < 0 ? -x : x; }

FUNCTION(_) {
    rtapi_uint dx = myabs(px-cx);
    rtapi_uint dy = myabs(py-cy);
    rtapi_uint dz = myabs(pz-cz);
    rtapi_uint d2 = dx*dx + dy*dy;
    rtapi_uint r2 = r*r;
    if(d2 > r2) {
        probe_out_set(pz < cz);
    } else {
        d2 += dz*dz;
        probe_out_set(d2 <= r2);
    }
}
