component sum2 "Sum of two inputs (each with a gain) and an offset";
see_also "scaled_s32_sums(9), weighted_sum(9)";
pin in real in0;
pin in real in1;
param rw real gain0 = 1.0;
param rw real gain1 = 1.0;
param rw real offset;
pin out real out "out = in0 * gain0 + in1 * gain1 + offset";
option period no;
function _;
license "GPL";
author "Jeff Epler";
;;
FUNCTION(_) {
    out_set(in0 * gain0 + in1 * gain1 + offset);
}
