#!/bin/bash
########   Start A-axis as spindle   #########
####     Creator: Piet van Rensburg      #####
####     Company: Craftsman CNC          #####
####     wwww.craftsmancnc.co.nz         #####
#### 	 Use: M100 P80  (80 RPM CW)      #####
####     Use: M100 P-80 (80 RPM CCW)     ##### 
##############################################

rpm=$1
halcmd unlinkp stepgen.3.step
halcmd unlinkp stepgen.3.dir

halcmd net adir stepgen.5.dir
halcmd net astep stepgen.5.step

halcmd setp stepgen.5.enable TRUE
halcmd setp stepgen.5.velocity-cmd $rpm
exit 0
