#!/bin/bash
########   Stop A-axis as spindle    #########
####     Creator: Piet van Rensburg      #####
####     Company: Craftsman CNC          #####
####     wwww.craftsmancnc.co.nz         #####
##############################################

halcmd setp stepgen.5.velocity-cmd 0
halcmd setp stepgen.5.enable FALSE

halcmd unlinkp stepgen.5.step
halcmd unlinkp stepgen.5.dir

halcmd net astep stepgen.3.step
halcmd net adir stepgen.3.dir
exit 0

