#!/bin/bash
########    Set pin 10 for Probe     #########
####     Creator: Piet van Rensburg      #####
####     Company: Craftsman CNC          #####
####     wwww.craftsmancnc.co.nz         #####
##############################################


halcmd net homeswitches motion.probe-input

exit 0

