#!/bin/bash
########    Start plasma trigger     #########
####     Creator: Piet van Rensburg      #####
####     Company: Craftsman CNC          #####
####     wwww.craftsmancnc.co.nz         #####
##############################################



halcmd sets trigger-enable TRUE
exit 0
