#!/bin/bash
########    Stop plasma trigger      #########
####     Creator: Piet van Rensburg      #####
####     Company: Craftsman CNC          #####
####     www.craftsmancnc.co.nz          #####
##############################################



halcmd sets trigger-enable FALSE

exit 0
