#!/bin/bash
########     Set pin 10 for Home and Active low    #########
####             Creator: Piet van Rensburg            #####
####             Company: Craftsman CNC                #####
####             wwww.craftsmancnc.co.nz               #####
############################################################

halcmd unlinkp motion.probe-input

exit 0

