package inifile_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sittner/linuxcnc/src/launcher/pkg/inifile"
)

// --------------------------------------------------------------------------
// WriteExpanded: no #INCLUDE → original path returned, no file created
// --------------------------------------------------------------------------

func TestWriteExpanded_NoIncludes(t *testing.T) {
	dir := t.TempDir()
	f := writeFile(t, dir, "plain.ini", `
[SECTION]
KEY = value
`)
	got, err := inifile.WriteExpanded(f)
	if err != nil {
		t.Fatalf("WriteExpanded: %v", err)
	}
	if got != f {
		t.Errorf("WriteExpanded = %q, want original %q", got, f)
	}
	// No .expanded file should be created.
	if _, err := os.Stat(f + ".expanded"); !os.IsNotExist(err) {
		t.Errorf("unexpected .expanded file created when there are no #INCLUDEs")
	}
}

// --------------------------------------------------------------------------
// WriteExpanded: #INCLUDE → expanded file created with correct content
// --------------------------------------------------------------------------

func TestWriteExpanded_WithInclude(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "sub.ini", "[SUB]\nSUB_KEY = subval\n")
	main := writeFile(t, dir, "main.ini", "[MAIN]\nMAIN_KEY = mainval\n#INCLUDE sub.ini\n")

	got, err := inifile.WriteExpanded(main)
	if err != nil {
		t.Fatalf("WriteExpanded: %v", err)
	}
	wantPath := main + ".expanded"
	if got != wantPath {
		t.Errorf("WriteExpanded path = %q, want %q", got, wantPath)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("reading expanded file: %v", err)
	}
	content := string(data)

	// Header lines.
	if !strings.Contains(content, "#*** "+wantPath) {
		t.Errorf("expanded file missing header with path:\n%s", content)
	}
	if !strings.Contains(content, "#*** Autogenerated file with expanded #INCLUDEs") {
		t.Errorf("expanded file missing autogenerated header:\n%s", content)
	}

	// Original main content.
	if !strings.Contains(content, "MAIN_KEY = mainval") {
		t.Errorf("expanded file missing MAIN_KEY:\n%s", content)
	}

	// Included file content.
	if !strings.Contains(content, "SUB_KEY = subval") {
		t.Errorf("expanded file missing SUB_KEY from included file:\n%s", content)
	}

	// Begin/End markers.
	subPath := filepath.Join(dir, "sub.ini")
	if !strings.Contains(content, "#*** Begin #INCLUDE file: "+subPath) {
		t.Errorf("expanded file missing Begin marker:\n%s", content)
	}
	if !strings.Contains(content, "#*** End   #INCLUDE file: "+subPath) {
		t.Errorf("expanded file missing End marker:\n%s", content)
	}

	// The #INCLUDE directive itself should NOT appear verbatim.
	if strings.Contains(content, "#INCLUDE sub.ini") {
		t.Errorf("expanded file still contains unexpanded #INCLUDE directive:\n%s", content)
	}
}

// --------------------------------------------------------------------------
// WriteExpanded: nested #INCLUDEs are fully expanded
// --------------------------------------------------------------------------

func TestWriteExpanded_NestedIncludes(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "deep.ini", "[DEEP]\nD = deepval\n")
	writeFile(t, dir, "middle.ini", "[MIDDLE]\nM = middleval\n#INCLUDE deep.ini\n")
	main := writeFile(t, dir, "root.ini", "[ROOT]\nR = rootval\n#INCLUDE middle.ini\n")

	got, err := inifile.WriteExpanded(main)
	if err != nil {
		t.Fatalf("WriteExpanded: %v", err)
	}

	data, err := os.ReadFile(got)
	if err != nil {
		t.Fatalf("reading expanded file: %v", err)
	}
	content := string(data)

	for _, want := range []string{"R = rootval", "M = middleval", "D = deepval"} {
		if !strings.Contains(content, want) {
			t.Errorf("expanded file missing %q:\n%s", want, content)
		}
	}
	// No unexpanded #INCLUDE should remain.
	for _, bad := range []string{"#INCLUDE middle.ini", "#INCLUDE deep.ini"} {
		if strings.Contains(content, bad) {
			t.Errorf("expanded file still contains %q:\n%s", bad, content)
		}
	}
}

// --------------------------------------------------------------------------
// WriteExpanded: absolute path in #INCLUDE
// --------------------------------------------------------------------------

func TestWriteExpanded_AbsoluteIncludePath(t *testing.T) {
	dir := t.TempDir()
	subPath := writeFile(t, dir, "abs.ini", "[ABSEC]\nABS = yes\n")
	main := writeFile(t, dir, "main.ini", "[MAIN]\nFOO = bar\n#INCLUDE "+subPath+"\n")

	got, err := inifile.WriteExpanded(main)
	if err != nil {
		t.Fatalf("WriteExpanded: %v", err)
	}

	data, err := os.ReadFile(got)
	if err != nil {
		t.Fatalf("reading expanded file: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "ABS = yes") {
		t.Errorf("expanded file missing ABS = yes:\n%s", content)
	}
}

// --------------------------------------------------------------------------
// WriteExpanded: missing included file returns error, no partial file left
// --------------------------------------------------------------------------

func TestWriteExpanded_MissingIncludedFile(t *testing.T) {
	dir := t.TempDir()
	main := writeFile(t, dir, "main.ini", "[X]\nK = v\n#INCLUDE nonexistent.ini\n")

	_, err := inifile.WriteExpanded(main)
	if err == nil {
		t.Fatal("expected error for missing #INCLUDE file, got nil")
	}

	// The partial .expanded file should have been cleaned up.
	if _, statErr := os.Stat(main + ".expanded"); !os.IsNotExist(statErr) {
		t.Error("partial .expanded file was not cleaned up after error")
	}
}

// --------------------------------------------------------------------------
// WriteExpanded: the returned expanded file can itself be parsed by inifile.Parse
// --------------------------------------------------------------------------

func TestWriteExpanded_ParseableByIniParse(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "kins.ini", "[KINS]\nKINEMATICS = trivkins\n")
	main := writeFile(t, dir, "twopass.ini", "[EMC]\nMACHINE = Test\n#INCLUDE kins.ini\n")

	expandedPath, err := inifile.WriteExpanded(main)
	if err != nil {
		t.Fatalf("WriteExpanded: %v", err)
	}

	ini, err := inifile.Parse(expandedPath)
	if err != nil {
		t.Fatalf("Parse(expanded): %v", err)
	}
	if got := ini.Get("KINS", "KINEMATICS"); got != "trivkins" {
		t.Errorf("[KINS]KINEMATICS = %q, want %q", got, "trivkins")
	}
	if got := ini.Get("EMC", "MACHINE"); got != "Test" {
		t.Errorf("[EMC]MACHINE = %q, want %q", got, "Test")
	}
}
