# 29.12.2025 mk default ngv 1wiglZneg,ngc
# 25.03.2026 cleaned
#
[HAL]
HALFILE = sedm.hal
POSTGUI_HALFILE = sedmpost.hal
HALUI =  halui

[EMC]
MACHINE = sedm
# vvv bewares of nagging upddate dlog due top chging thiusvvv
VERSION = 1.1
#DEBUG = 0x00000003

[DISPLAY]
DISPLAY = axis
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_LINEAR_VELOCITY = 2
OPEN_FILE = ./ngc/wxample.ngc

# Introductory graphic
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 1

[TASK]
TASK = milltask
CYCLE_TIME = 0.001

[RS274NGC]
USER_M_PATH = ./Mcodes/
PARAMETER_FILE = sim.var

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = sedm.tbl

[EMCMOT]
EMCMOT = motmod
BASE_PERIOD = 50000
SERVO_PERIOD = 1000000

[TRAJ]
COORDINATES = XYZ
LINEAR_UNITS = mm
ANGULAR_UNITS = degree

[KINS]
JOINTS = 3
KINEMATICS = trivkins coordinates=XYZ

[AXIS_X]
# Note: low OFFSET_AV_RATIO:
#OFFSET_AV_RATIO  =   0.05
# 0/9 is max allowed
OFFSET_AV_RATIO  =   0.9
MIN_LIMIT        =  -150
MAX_LIMIT        =  150
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200

[AXIS_Y]
# Note: low OFFSET_AV_RATIO:
#OFFSET_AV_RATIO  =   0.05
OFFSET_AV_RATIO  =   0.9
MIN_LIMIT        =  -150
MAX_LIMIT        =   150
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200

[AXIS_Z]
# Note: low OFFSET_AV_RATIO:
OFFSET_AV_RATIO  =   0.9
MIN_LIMIT        =  -150
MAX_LIMIT        =   150
#MAX_VELOCITY     =   2
#MAX_ACCELERATION =  20
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200

[JOINT_0]
TYPE             = LINEAR
HOME_SEQUENCE    =   0
#MAX_VELOCITY     =   2
#MAX_ACCELERATION =  20
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200

[JOINT_1]
TYPE             = LINEAR
HOME_SEQUENCE    =   0
#MAX_VELOCITY     =   2
#MAX_ACCELERATION =  20
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200

[JOINT_2]
TYPE             = LINEAR
HOME_SEQUENCE    =   0
#MAX_VELOCITY     =   2
#MAX_ACCELERATION =  20
MAX_VELOCITY     =   20
MAX_ACCELERATION =  200
