#!/bin/bash
cd "$(dirname "$1")" || exit
RETVAL=0
for EXPECTED in *.expected ; do
    BASE=$(basename "$EXPECTED" .expected)
    RESULT=$BASE.result
    diff -u "$EXPECTED" "$RESULT" || RETVAL=1
done
exit $RETVAL

