debian/extras/usr/share/applications/linuxcnc-documentation.desktop   usr/share/applications
debian/extras/usr/share/applications/linuxcnc-gcoderef.desktop        usr/share/applications
debian/extras/usr/share/applications/linuxcnc-gettingstarted.desktop  usr/share/applications
debian/extras/usr/share/applications/linuxcnc-integratorinfo.desktop  usr/share/applications
debian/extras/usr/share/applications/linuxcnc-manualpages.desktop     usr/share/applications
