#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")/../"

scripts/version-create.sh
# Need to use $? because we need the output capture
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
    echo "error determining version!"
    exit 1
fi

DEB_VERSION=$(git show HEAD:debian/changelog | head -1 | sed 's/.*(\(.*\)).*/\1/')

NEW_DEB_VERSION=$(cat VERSION | sed -r 's/-pre/~pre/; s/-/./g')
NEW_DEB_VERSION="1:${NEW_DEB_VERSION}"

if [ "$NEW_DEB_VERSION" = "$DEB_VERSION" ]; then
    echo "no changes since the version at the top of the debian/changelog file"
    echo "not modifying debian/changelog"
    exit 0
fi

# Workaround until <URL: https://bugs.debian.org/1008735 > in lsb_release is fixed.
CODENAME="$(lsb_release --codename --short)"
case "$CODENAME" in
  n/a)
    CODENAME=unstable
    ;;
esac

set -e
(
echo "linuxcnc ($NEW_DEB_VERSION) $CODENAME; urgency=low"
echo
echo "  * Development build"
echo
echo " -- buildbot <buildbot@example.com>  $(date -R)"
echo
git show HEAD:debian/changelog
) > debian/changelog

dch -r --nomultimaint ""
