#!/bin/bash

GIT_VERSION=`git describe --match "v2.[0-9]*"`
GIT_TAG=`echo $GIT_VERSION | sed -r 's/^(.*)-[^-]+-[^-]+$/\1/'`

DEB_VERSION=`git show HEAD:debian/changelog | head -1 | sed 's/.*(\(.*\)).*/\1/'`

NEW_DEB_VERSION="${GIT_VERSION/-pre/~pre}"
NEW_DEB_VERSION="1:${NEW_DEB_VERSION/v/}"

set -e
(
echo "emc2 ($NEW_DEB_VERSION) $(lsb_release -cs); urgency=low"
echo
git log --pretty=format:"  * %s" $GIT_TAG..
echo
echo
echo " -- buildbot <buildbot@example.com>  $(date -R)"
echo
git show HEAD:debian/changelog
) > debian/changelog

dch -r --nomultimaint ""
