#!/usr/bin/python

import sys
import os

# Params from test.hal
period = 1000000
# Params from pll_correction.comp
numsamps = 1000

os.chdir(os.path.dirname(os.path.realpath(__file__)))

with open("result", 'r') as f:
    with open("stderr", 'a') as log:
        for line in f:
            line = line.rstrip('[ \n]')
            (cycle_count, period_actual, pll_err, samp_avg, phase_diff) = (
                [int(s) for s in line.split(' ')])

            if cycle_count == 2*numsamps:
                log.write("%s\n" % line)
                if abs(samp_avg) > period/100:
                    log.write("0 PLL didn't converge:  abs(%d) > %d/100\n" % (
                        samp_avg, period))
                    sys.exit(-1)
                else:
                    log.write("0 PLL converged:  abs(%d) <= %d/100\n" % (
                        samp_avg, period))
            if cycle_count == 4*numsamps:
                log.write("%s\n" % line)
                if abs(samp_avg) > period/100:
                    log.write("10 PLL didn't converge:  abs(%d) > %d/100\n" % (
                        samp_avg, period))
                    sys.exit(-1)
                else:
                    log.write("10 PLL converged:  abs(%d) <= %d/100\n" % (
                        samp_avg, period))
