:lang: fr

= Se procurer LinuxCNC(((Obtenir LinuxCNC)))

== Par téléchargement classique

Téléchargez le CD Live sur le http://www.linuxcnc.org/index.php?lang=french[site de LinuxCNC]

== Par téléchargement fragmenté (((Téléchargement fragmenté)))

Si le fichier est trop important pour être téléchargé en une seule
fois parce que votre connexion Internet est lente ou mauvaise,
utilisez _wget_ qui permet la reprise après un téléchargement interrompu.

La commande Wget sous Linux:: (((Wget sous Linux)))
Ouvrez un terminal. Dans Gnome, il est dans _Applications_ → _Accessoires_ → 
_Terminal_.
Utilisez _cd_ pour changer le répertoire dans lequel vous voulez stocker l'image 
ISO. Utilisez _mkdir_ pour créer un nouveau répertoire si nécessaire.
+
Notez que les noms de fichiers réels peuvent changer, vous pourriez avoir à 
aller sur http://www.linuxcnc.org/index.php/french[le site de LinuxCNC] et y suivre 
le lien _Téléchargement_ pour obtenir le nom réel du fichier. Dans la plupart 
des navigateurs, vous pouvez faire un clic droit sur le lien et sélectionner 
_Copier le lien vers_, ou similaire, coller ensuite ce lien dans la fenêtre du 
terminal avec un clic droit puis en choisissant _Coller_.
+
.Ubuntu 10.04 Lucid Lynx et LinuxCNC (version actuelle)
****
Pour obtenir la version de Ubuntu 10.04 Lucid Lynx, copier l'un des liens 
ci-dessous dans la fenêtre du terminal et appuyez sur _Entrée_:

Pour le miroir Etats-Unis:
wget http://www.linuxcnc.org/iso/ubuntu-10.04-linuxcnc3-i386.iso

Pour le miroir européen: 
wget http://dsplabs.upt.ro/~juve/emc/get.php?file=ubuntu-10.04-linuxcnc3-i386.iso

La somme MD5 du fichier ci-dessus est: `76dc2416b917679b71255e464ede84ec`
****
+
Pour continuer un téléchargement partiel qui aurait été interrompu par exemple, 
ajoutez l'option -c à wget:
+
wget -c http://www.linuxcnc.org/iso/ubuntu-10.04-linuxcnc3-i386.iso
+
Pour arrêter un téléchargement, utilisez Ctrl-C ou fermer la fenêtre du terminal.
+
.Ubuntu 8.04 Hardy Heron et LinuxCNC (ancien)
****
Si vous avez besoin d'une ancienne version d'Ubuntu, vous pouvez télécharger 
Ubuntu 8.04. L'image du CD ci-dessous est l'ancienne version EMC 2.3.x, mais 
elle peut être modifiée vers la version 2.4.x en suivant les instructions sur:
 http://wiki.linuxcnc.org/cgi-bin/wiki.pl?UpdatingTo2.4[le wiki LinuxCNC.org]

Pour le miroir Etats-Unis:
wget http://www.linuxcnc.org/iso/ubuntu-8.04-desktop-emc2-aj13-i386.iso

Pour le miroir européen:
wget http://dsplabs.upt.ro/~juve/emc/get.php?file=ubuntu-8.04-desktop-emc2-aj13-i386.iso

La somme MD5 du fichier ci-dessus est: `1bab052ec879f941628927c988863f14`
****
+
Quand le téléchargement est terminé, vous trouverez le fichier ISO dans le 
répertoire que vous avez sélectionné précédemment. Ensuite, il ne vous restera 
plus qu'à graver le CD.

La commande Wget sous Windows:: (((Wget sous Windows)))
Le programme wget est également disponible pour Windows depuis: 
+
http://gnuwin32.sourceforge.net/packages/wget.htm
+
Suivez les instructions de la page web pour télécharger et installer
le programme wget sous Windows.
+
Pour lancer wget ouvrez l'invite de commande.
+
Dans la plupart des Windows elle est dans _Programmes_ → _Accessoires_ → 
_Commande_
+
Naviguez jusqu'au répertoire dans lequel s'est installé wget.
Habituellement il est dans _C:\Program Files\GnuWin32\bin_ si 
c'est le cas, tapez la commande:
----
cd C:\Program Files\GnuWin32\bin
----

et le prompt devrait changer pour: _C:\Program Files\GnuWin32_
+
Tapez les commandes _wget_ dans la fenêtre et pressez Entrée comme précédemment. 

== Graver l'image ISO du CD

LinuxCNC est distribué sous la forme d'un fichier image de CD, l'image ISO du CD. 
Pour installer LinuxCNC, vous devez d'abord graver cette image ISO sur un CD. 
Vous devez disposer d'un graveur de CD/DVD et d'un CD vierge de 80 minutes 
(700 Mio). Pour éviter tout échec de gravure, graver à la vitesse la plus lente 
possible.

=== Sous Linux

==== Vérifier la somme de contrôle sous Linux

Avant de graver un CD, il est fortement recommandé de vérifier la
somme de contrôle md5 (hash) du fichier de l'image iso.

Ouvrez un terminal. 
Dans Ubuntu il est dans _Applications_ → _Accessoires_ → _Terminal_.

Allez dans le répertoire contenant l'image ISO précédemment téléchargée avec:
----
cd répertoire_de_l'image
----

Puis lancez la commande _md5sum_ suivie du nom du fichier, exemple:
----
md5sum -b ubuntu-10.04-linuxcnc3-i386.iso
----

La commande md5sum doit retourner une simple ligne après le calcul de la somme 
    de contrôle. 
Sur une machine lente le calcul peut prendre plusieurs minutes: 
----
md5sum: 41b71c4956c0c89033a99a590ebaefec
sha256sum: a542092aa9f399d3ad50bbb2f0f4dd63ad9332c23d8387f6061bdd186d1df3b0
----

Il reste à comparer avec la somme md5 fournie sur la page de téléchargement.

Si vous avez téléchargé le md5sum ainsi que l'ISO, vous pouvez demander au 
programme md5sum de faire la vérification pour vous. 
Dans le même répertoire:

----
md5sum -c ubuntu-10.04-linuxcnc1-i386.iso.md5
----

Si tout va bien, après un court délai le terminal affichera:

----
ubuntu-10.04-linuxcnc1-i386.iso: OK
----

==== Graver le CD sous Linux

- Insérez un CD vierge dans votre graveur. Une fenêtre surgissante
   _CD/DVD Creator_ ou _Choisissez le type de disque_ va s'ouvrir. 
   Fermez la, elle ne sera pas utilisée.
- Naviguez jusqu'au répertoire contenant l'image ISO.
- Faites un clic droit sur le fichier de l'image ISO et choisissez
   _Graver le Disque_.
- Sélectionnez la vitesse de gravure. Pour graver le CD Live de LinuxCNC il
   est recommandé de graver à la vitesse la plus lente possible pour
   éviter toute erreur de gravure.
- Lancez la gravure.
- Si le choix d'un nom de fichier est demandé pour l'image disque,
   cliquez juste _OK_.

=== Sous Windows

==== Vérifier la somme de contrôle sous Windows

Avant de graver un CD, il est fortement recommandé de vérifier la
somme de contrôle md5 (hash) du fichier de l'image iso, malheureusement
Windows ne dispose pas de programme de contrôle du md5. Vous devrez en
installer un pour vérifier la somme de contrôle de l'ISO. Plus
d'informations sont disponibles ici: http://doc.ubuntu-fr.org/md5sum

==== Gravez le CD sous Windows

- Si votre Windows n'intègre pas un logiciel de gravure d'image vous 
   pouvez télécharger Infra Recorder, un logiciel de gravure d'images 
   gratuit et open source sur http://infrarecorder.org/
- Insérez un CD vierge dans le graveur, sélectionnez _Quitter_ ou 
   _Cancel_ si un auto-run démarre.
- Cliquez bouton droit sur le fichier ISO et sélectionnez le menu 
   _Graver l'image disque_ ou lancez Infra Recorder et choisissez le 
   menu _Actions→Graver l'image_.   

== Tester LinuxCNC

Avec le CD Live de LinuxCNC dans le lecteur de CD/DVD, redémarrez votre PC
de sorte qu'il démarre sur le CD Live. Quand l'ordinateur a redémarré
vous pouvez essayer LinuxCNC sans l'installer. Vous ne pouvez pas créer de
configuration personnalisée ni modifier les réglages du système comme
la résolution de l'écran sans installer LinuxCNC.

Pour lancer LinuxCNC allez dans le menu Applications/CNC et choisissez
LinuxCNC. Puis sélectionnez une configuration en sim (simulation) et
essayez le.

Pour savoir si votre ordinateur est utilisable par le générateur de
trains d'impulsions du logiciel, lancez un test de latence comme
indiqué <<cha:test-de-latence, dans ce chapitre>>.

== Installer la distribution Ubuntu de LinuxCNC sur votre PC

Si vous avez envie d'aller plus loin, cliquez juste sur l'icône
_Install_ se trouvant sur le bureau, répondez à quelques questions (votre
nom, votre fuseau horaire, le mot de passe) et faites une installation
complète en quelques minutes. Notez bien le mot de passe indiqué et le
nom d'utilisateur. Une fois l'installation complète et que vous êtes
connecté, le gestionnaire de mises à jour vous proposera d'effectuer
une mise à jour vers la dernière version stable de LinuxCNC.

== Les mises à jour de LinuxCNC (((Mises à jour de LinuxCNC)))

Avec l'installation standard, le gestionnaire de mises à jour vous avertira des 
mises à jour de LinuxCNC disponibles quand vous serez en ligne et vous permettra 
de mettre à jour facilement sans connaissance particulière de Linux.
Si vous souhaitez passer en 10.04 à partir d'une 8.04, une installation propre 
à partir du CD live est recommandée.

WARNING: [red]#Ne pas mettre à jour Ubuntu vers une nouvelle distribution 
comme de 10.04 vers 12.04, car elle ne permettrait plus d'utiliser LinuxCNC, ne 
pas mettre non plus à jour le kernel, car les modules temps réels ne 
fonctionnerait plus.#

== Problème d'installation possible

Dans de rares cas, vous pourriez avoir à réinitialiser le BIOS aux réglages par 
défaut si lors de l'installation du Live CD, le disque dur n'est pas reconnu 
pendant le démarrage.

// vim: set syntax=asciidoc:
