:lang: en
:toc:

[[cha:getting-linuxcnc]]
= Getting LinuxCNC(((Getting LinuxCNC)))

This section describes the recommended way to download
and make a fresh install of LinuxCNC version 2.9.  

NOTE: LinuxCNC requires a special kernel because it must operate in realtime. The instructions assume th euse of the preempt_rt kernel which is found in the Debian repositories from Version 12 (Bookworm and above). Other options exist and are mainly of historic interest so please refer to documentation for Linuxcnc V2.8 and below.

[[sec:download_image]]
== Download the image - Assuming an x86 PC
// Update URL on 10 June when officially released
. Download this image of Debian Bookworm RC3.
https://cdimage.debian.org/cdimage/bookworm_di_rc3/amd64/iso-cd/debian-bookworm-DI-rc3-amd64-netinst.iso
. It now needs to be "burnt" to a USB drive. 
. Download Balena Etcher from https://www.balena.io/etcher
. Burn the Debian .iso to a thumb drive using Etcher
. Connect your computer to a wired internet connection
. Boot your computer from the USB drive. This may require changing BIOS settings to ensure the USB drive is the first location to look for a bootable image
. select 'Install' or 'Graphical Install' 
. Proceed with the installation and follow the prompts.
. Do NOT add a root account password when prompted
. Use an easy to remember username and password when prompted
. When asked to select a desktop we strongly recommend you use XFCE and don't install the default gnome desktop. This is because Gnome uses Wayland for graphic rendering. Linuxcnc has been developed over many years and was written using Xorg so full Wayland support may not have been achieved.
. When prompted, reboot into Debian 12 and login
. Open a terminal window (click on the black square at the bottom of the screen
. Type the following lines and press enter after each one to install Linuxcnc, and the preempt_rt kernel. This will take some time
----
sudo apt update
sudo apt upgrade
sudo apt install linuxcnc-uspace linuxcnc-uspace-dev mesaflash
----
Reboot into the PC again to activate the preempt_rt kernel.
When you log in, verify that `PREEMPT_RT`is reported by the following command in a terminal window.

----
uname -v
----

Thats it, you are done! 

You will find linuxcnc under the CNC menu.

Explore the menu options. You may wish to run a simulation. When Linuxcnc opens, choose "axis" or "axis mm" under 'Sample Configurations/sim/axis' in the tree to start with.
Some of the sample configurations include 3D simulated machines onscreen, look for "Vismach" to see these.

Follow these steps to get started depending on your circumstances
. To make life  easier, follow the Bookworm Basic Tweaks in a later heading.
. To see if your computer is suitable for software step pulse generation
run the Latency Test as shown <<sec:latency-test,here>>.

. To improve latency, follow the Preempt_rt Tweaks later in a later heading.

. if you intend to use  a Mesa ethernet card, follow the heading "Set fixed ip address later in this document.

. If you have a Mesa card connected and you experience "Error Finishing Read" warnings, Review the chapter about Realtek network drivers later in this document. 

. In extreme cases of poor performance,  consider installing  a later kernel as described in a later heading.



== Install Problems (x86)

Most problems booting the installation image are due to uefi hardware. Fortunately, Debian Bookworm has significantly better support for uefi systems than earlier versions of Linux.

Sometimes you can tell the BIOS to boot legacy (non-uefi) hardware.

In rare cases you might have to reset the BIOS to default settings if
during the install it cannot recognize the hard drive
during the boot up.

== Installing on Raspberry Pi using Debian Bookworm

NOTE: Raspberry Pis (and most other Single Board Computers, or SBUs) are ARM64 machines. These instructions will feature arm64 kernel and can't be used for x86 PC's (eg Intel based or similar). There are several pathways to install linuxcnc on a Raspberry Pi. We present a method that uses Debian Bookworm as everything is presnet in their repositories/

. Download a Debian Bookworm  image to suit your Pi from  https://raspi.debian.net/daily-images/ and burn to an SD card and install in the
  https://www.raspberrypi.org/documentation/installation/installing-images/README.md[usual way].
+
NOTE: These instructions assume not using the Advanced Menu to set things like userid, password, time-zone, keyboard layout,etc. +
Also, there have been reported black screen lockout with the "tested" images on some Pis. It may be that removing dtoverlay=vc4-fkms-v3d-pi4 from /boot/config.txt resolves that problem. +
These instructions were tested using the 2023/05/15 daily build.

. Ensure the Pi is connected to the internet. Boot the Pi from the image you burnt. It will  open a text based terminal
. Login using the root account (which does not have a password yet). Type:

----
root
---- 
and hit enter
. Add a password to the root user account. Type:

----
passwd
----
and allocate a password you will never forget! 
. Add a new user and allocate a password. I used pi:

----
adduser pi
----
. Add your user to the sudo group. Type:
+
----
usermod -aG sudo pi
----
. To get the Real Time (-rt-) kernel, type the following lines:

----
apt update
apt upgrade
apt install linux-image-rt-arm64 linux-headers-rt-arm64
----
NOTE: Becasue the image was sourced from the daily build, there will typically be no packages to upgrade. 

. Reboot to finalize installing the PREEMPT_RT kernel. 
. Login as root using the password set previously.

Its time to install a desktop and linuxcnc!
Type the following commands:

----
apt install task-xfce-desktop geany linuxcnc-uspace linuxcnc-uspace-dev mesaflash
----
This will take some time. During the install you will need to select a keyboard layout/language, then tab to the "OK" and press Enter. 

When complete, start the graphical environment  by typing:

----
startx
----

Finally, reboot again and log in with your user (we called pi above)
Take some time to explore the CNC menu as described in the x86 section.

. To improve performance there are several settings in two places:

.. To change the startup command line settings, which are contained in `/boot/firmware/cmdline.txt` we modify an upstream file by typing:

----
sudo geany /etc/default/raspi-extra-cmdline
----
and add this to the empty file:

----
processor.max_cstate=1 isolcpus=2,3
----
Save and exit geany
.. To change configuration settings, which will be built into  `/boot/firmware/config.txt` we modify its upstream file by typing:

----
sudo geany /etc/default/raspi-firmware-custom
----
and add to this empty file the following lines (note I commented some out which caused my Pi to go to a black screen and never return):

----
#dtoverlay=vc4-fkms-v3d-pi4
#disable_overscan=1
dtparam=audio=off
----
Save and exit geany

NOTE: These commands (a) use video graphics resources for 3D acceleration (increases performance considerably), (b) don't overscan (fixes some black border issues), and (c) don't use audio (unknown performance enhancement)

WARNING: The first command is only tested on RasPi 4 models, and it specifically references pi4. 

.. Issue the configuration update command, which will take those changes and write them to the `/boot/firmware/cmdline.txt` and `/boot/firmware/config.txt`  files:

----
sudo update-initramfs -u -k all
----

Review the Bookworm tweaks section and configure as required.


[[sec:_bookworm_tweaks]]
== Bookworm Tweaks(((LinuxCNC:Bookworm Tweaks)))(((Installation:Bookworm Tweaks)))
=== Basic Tweaks
To make life easy, there are some standard tweaks you can make to Bookworm which should work on both X86 and the pi.

From the menu settings/Power manager set the power settings to suit your needs. You can turn off screen saver and screen lock here
Install geany and grub-customizer:

----
sudo apt install geany grub-customizer
----

Finally now geany is installed, enable auto login

----
sudo geany /etc/lightdm/lightdm.conf
----

scroll down to about line 126 and uncomment (remove #) both of the following lines and add YOUR login user name. Eg an example for user matt.

----
autologin-user=matt
autologin-user-timeout=0
----

=== Preempt_rt Tweaks
isolcpus can make a huge difference to latency on some systems because it isolates specific CPU cores so they are purely used by real time threads (eg the linuxcnc servo thread). The instructions below assume a 4 core CPU eg. Celeron, i3, i5 etc) those with 2 cores or more than 4 cores need different isolcpus settings. Never isolate core 0 as it is used for system threads so it already includes a lot of running threads.
Now we need to isolate 2 cores for better RT performance on a 4 core machine.

----
sudo grub-customizer
----

On the General Settings in the kernel parameters field where it says

----
quiet
----

Change to

----
quiet isolcpus=2,3
----

Save the config, close grub-customiser and reboot for changes to take effect
Check latency with

----
latency-histogram --nobase --sbins=1000
----

It should be much improved.

=== Review Latency
Use latency-histogram  instead of latency-test to review latency particularly if you are using a mesa card or ethercat and don;t need a base thread: 

----
latency-histogram --nobase --sbins 1000 
---- 

How to evaluate latency is covered in the linuxcnc documents
Among other things, latency is affected by: BIOS settings; Isolcpus and other boot time settings; Kernel version used

=== Realtek network drivers
Some users have been reporting significant error finishing read issues with some Realtek NIC’s. 

There are two additional device drivers available in Debian for realtek cards;

r8125-dkms for 2.5 Gb network cards - RTL8125, RTL8125B(S)(G)

r8168-dkms  for the following network cards RTL8111B/RTL8111C, RTL8111D/RTL8111E, RTL8111F/RTL8111G(S), RTL8111H(S), RTL8118(A)(S), RTL8119i, RTL8111L, RTL8111K, RTL8168B, RTL8168E, RTL8168H, RTL8111DP, RTL8111EP, RTL8111FP, RTL8411/RTL8411B, RTL8101E, RTL8102E, RTL8103E, RTL8105E, RTL8106E, RTL8107E, RTL8401, RTL8402

Installing the r8168-dkms driver improved network latency by 400% on our R8111 network card. Similar results were reported on other affected hardware.

The r8168-dkms and r8125-dkms drivers are in the non-free packages which are not included in sources.list by default.

You can see your driver if you type the following to identify your NIC name: 

----
ip a
----

Now display the NIC info eg: 

----
sudo apt install ethtool
ethtool -i enps02
----
If it seems you could benefit from this driver, continue
Type:

----
sudo geany /etc/apt/sources.list
----

Append a space followed by non-free to each of the 4 lines that end with firmware-non-free as follows:

----
deb http://deb.debian.org/debian/ bookworm main non-free-firmware non-free
deb-src http://deb.debian.org/debian/ bookworm main non-free-firmware non-free
deb http://security.debian.org/debian-security bookworm-security main non-free-firmware non-free 
deb-src http://security.debian.org/debian-security bookworm-security main non-free-firmware non-free
----

Save and close geany. Type: 

----
sudo apt update
----

you now need to install some utilities. Type:

----
sudo apt install build-essential dkms 
----

If you have not installed a later kernel as described above install linux-headers. Type:

----
sudo apt install linux-headers-$(uname -r)
----

You can now install the r8168 or R8125 driver. Depending on your driver 
Type: 

----
sudo apt install r8168-dkms 
----

or type:

----
sudo apt install r8125-dkms 
----

Reboot and check you still have a network driver with

----
ip a
----
Check you can still ping the mesa card 

----
ping 10.10.10.10 
----

If you have to remove this driver, it needs to be purged completely or you will have no network. Eg.  

----
sudo apt purge r8168-dkms 
----

=== Set fixed IP address - only for mesa card.
Usually we set up the mesa card to have the ip address 10.10.10.10. We need to set a fixed ip address of 10.10.10.1 to the network interface that connects to it. Its recommended to install a second NIC or connect to a wifi network to retain internet and network access. 

Type:

----
ip a 
----

To determine the network interface name used for your mesa card. This is usually something like eth0 or enp2s0. Type 

----
sudo geany /etc/network/interfaces
----
to append the following at the end of the file:

----
auto enp2s0
iface enp2s0 inet static
address 10.10.10.1
hardware-irq-coalesce-rx-usecs 0 
----
[Note]
The last line is only required for Intel network cards (Not used on a Pi). It seems to be ignored on non-applicable hardware.

Save and close geany. 
Reboot to restart the network.
Ping the mesa card to confirm it's all working 

----
ping 10.10.10.10
----

=== Installing a later kernel
Since the release of Debian Bullseye (Linux kernel 5.10), real time performance has been  disappointing. In particular, network latency when communicating with a Mesa ethernet card has  been generating Error Finishing Read Errors. This means that the network latency left insufficient time for the servo thread cycle to complete in time.

This appears to have been more prevalent with Realtek Network interfaces. Fortunately, each iteration of the Linux kernel has improved results, particularly since the release of 6.x kernels. Debian Bookworm (Debian 12) is using the 6.1 kernel which is quite good. In our testing, we found that latency improved by 265% if we used the 6.3 kernel. We have compiled this version of the kernel for your convenience. This image was updated to the final 6.3 kernel on 1 May 2023 and may be updated form time to time.
 
Only try installing it if you have exhausted all options by following the steps below:

. Download the 2 deb files (image, source) from 
// Can these be hosted on a LinuxCNC server?
https://drive.google.com/drive/folders/1NzQIHnf9M_cHzuZCqSldVFGschOOxaER?usp=sharing 
. The link above is to  the latest kernel versions that have been built following the final release of 6.3 kernel and the matching preempt_rt patches.

. Navigate to your Downloads folder and open a new Terminal session. Install the debs as follows (pressing tab auto completes the command)

----
dpkg -i linux-source(tab)
dpkg -i linux-image(tab)
----
. Reboot into the new kernel
. Check that uname -v shows the 6.3 kernel is installed
. If it isn’t, use grub-customizer mentioned earlier to change the kernel boot order and reboot again

[[sec:_alternate_install_methods]]
== Alternate Install Methods(((LinuxCNC:Alternate Install Methods)))(((Installation:Alternate Methods)))

Experienced users who are familiar with Debian system
administration (finding install images, manipulating apt sources, changing kernel flavors, etc), new installs are supported on following platforms:
("amd64" means "64-bit", and is not specific to AMD processors, it will
run on any 64-bit x86 system)
Note that in Debian Bookworm, the preempt_rt kernel is a dependency of linuxcnc-uspace so it is automatically installed with linuxcnc so the Stock kernel is not listed.

If you wish to use RTAI or Xenomai, please follow the instructions in the Linuxcnc V2.8 documentation.  

[options="header"]
|===
| Distribution   | Architecture  | Kernel     | Package name    | Typical use
| Debian Bookworm| amd64 & arm64 | preempt-rt | linuxcnc-uspace | machine control & simulation
| Debian Buster  | amd64 & arm64 | preempt-rt | linuxcnc-uspace | machine control & simulation
| Debian Buster  | amd64         | RTAI       | linuxcnc        | machine control (known issues)
| Debian Jessie  | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
| Debian Wheezy  | i386          | RTAI       | linuxcnc        | machine control & simulation
| Debian Wheezy  | amd64 & i386  | Preempt-RT | linuxcnc-uspace | machine control & simulation
| Debian Wheezy  | amd64 & i386  | Stock      | linuxcnc-uspace | simulation only
|===





// vim: set syntax=asciidoc:
