:lang: es
:toc:

[[cha:hal-canonical-device-interfaces]]
= Interfaces de dispositivos canónicos

== Introducción

Las siguientes secciones muestran los pines, parámetros y funciones
suministrados por "dispositivos canónicos". Todos los controladores de dispositivo HAL deben
suministrar los mismos pines y parámetros, e implementar el mismo comportamiento.

Tenga en cuenta que solo los campos `<io-type>` y `<specific-name>` estan
definido para un dispositivo canónico. Los campos `<device-name>`, `<device-num>`,
y `<chan-num>` se establecen en función de las características del
dispositivo real.

[[sec:hal-cdi:digital-in]]
== Entrada digital(((HAL Entrada digital)))

La entrada digital canónica (campo tipo E/S:`digin`) es bastante simple.

[[sub:hal-cdi:di:pins]]
=== Pines(((HAL Entrada Pines)))

[horizontal]
(bit) *in*:: Estado de la entrada hardware.
(bit) *in-not*:: Estado invertido de la entrada.

[[sub:hal-cdi:di:parameters]]
=== Parámetros(((HAL Entrada Parámetros)))

Ninguno

[[sub:hal-cdi:di:functions]]
=== Funciones(((HAL Entrada Functiones)))

(funct) *read*:: Lee el hardware y configura los pines HAL 'in' y 'in-not`.

[[sec:hal-cdi:digital-out]]
== Salida digital(((HAL Salida Digital)))

La salida digital canónica (campo de tipo E/S: `digout`) también es muy
sencilla.

[[sub:hal-cdi:do:pins]]
=== Pines(((HAL Salida Pines Digital)))

(bit) *out*:: Valor a escribir (posiblemente invertido) en la salida hardware.

[[sub:hal-cdi:do:parameters]]
=== Parámetros(((HAL Salida Párametros Digital)))

(bit) *invert*:: Si es TRUE, *out* se invierte antes de escribir en el hardware.

[[sub:hal-cdi:do:functions]]
=== Funciones(((HAL Salida Funciones Digital)))

(funct) *write*:: Lee *out* e *invert* y establece la salida hardware en consecuencia.

[[sec:hal-cdi:analog-in]]
== Entrada Analógica(((HAL Entrada Funciones Analógica)))

La entrada analógica canónica (tipo E/S: `adcin`) se espera que
sea utilizada para convertidores analógico a digital que, por ejemplo,
conviertan voltaje a un rango continuo de valores.

[[sub:hal-cdi:ai:pins]]
=== Pines(((HAL Entrada Pines Analógica)))

(float) *value*:: La lectura del hardware, escalada según los parámetros
   *scale* y *offset*. *Value* = ((lectura de entrada, en
   unidades dependientes del hardware) * *scale*) - *offset*

[[sub:hal-cdi:ai:parameters]]
=== Parámetros(((HAL Entrada Parámetros Analógica)))

[horizontal]
(float) *scale*:: El voltaje de entrada (o corriente) se multiplicará
   por *scale* antes de salir a *value*.
(float) *offset*:: Se restará de la entrada de voltaje (o corriente) hardware
   después de que se haya aplicado el multiplicador de escala.
(float) *bit_weight*:: El valor del bit menos significativo(LSB).
   Es efectivamente la granularidad de la lectura de entrada.
(float) *hw_offset*:: El valor presente en la entrada cuando se aplican 0 voltios
   al pin(es) de entrada.

[[sub:hal-cdi:ai:functions]]
=== Funciones(((HAL Entrada Functiones Analógica)))

(funct) *read*:: Lee los valores de este canal de entrada analógica. Se
   puede usar para leer un canal individual, o puede hacer que se lean todos los canales

== Salida analógica(((HAL Salida Analógica)))

La salida analógica canónica (tipo E/S: *adcout*).
Esto esta pensado para cualquier tipo de hardware que pueda generar un rango de valores más o menos continuo.
Los ejemplos son convertidores de digital a analógico o generadores PWM.

[[sub:hal-cdi:ao:pins]]
=== Pines(((HAL Salida Pines Analógica)))

[horizontal]
(float) *value*:: El valor que se escribirá. El valor real de salida
   para el hardware dependerá de la escala y los parámetros de offset.
(bit) *enable*:: Si es falso, entonces salida al hardware es 0, independientemente
   del pin *value*.

[[sub:hal-cdi:ao:parameters]]
=== Parámetros(((HAL Salida Parámetros Analógica)))

(float) *offset*:: Esto se agregará a *value* antes de la
   actualizacion del hardware.
(float) *scale*:: Se debe configurar de modo que una entrada de 1 en el
   pin *value*  causará que en el pin de salida analógica se lea 1 voltio.
(float) *high_limit* (opcional):: Cuando se calcula el valor para
   salida al hardware, si *value* + *offset* es mayor que
   *high_limit*, se usará *high_limit* .
(float) *low_limit* (opcional):: Cuando se calcula el valor de salida
   para el hardware, si *value* + *offset* es menor que *low_limit*,
   se usará *low_limit*.
(float) *bit_weight* (opcional):: El valor del bit menos significativo
   (LSB), en voltios (o mA, para salidas de corriente)
(float) *hw_offset* (opcional):: El voltaje (o corriente) real
   que saldrá si se escribe 0 en el hardware.

[[sub:hal-cdi:ao:functions]]
=== Funciones(((HAL Salida Funciones Analógica)))

(funct) *write*::
  Hace que el valor calculado sea enviado al
  hardware. Si el pin enable es falso, la salida será 0,
  independientemente de *value*, *scale* y *offset*.
  El significado de "0" depende del hardware. Por ejemplo, un
  A/D bipolar de 12 bits puede necesitar escribir 0x1FF (escala intermedia) para obtener D/A 0
  voltios desde el pin de hardware. Si el pin enable es verdadero, lee scale, offset y
  value y pone a la salida del ADC (*scale* * *value*) + *offset*.

// vim: set syntax=asciidoc:
