:lang: en
:toc:

[[cha:halmodule]]
= Creating Non-realtime Python Components

(((Creating Non-realtime Python Components)))
This section explains principles behind the implementation of HAL components with the Python programming language.

== Basic usage example

A non-realtime component begins by creating its pins and parameters, then enters a loop which will periodically drive all the outputs from the inputs.
The following component copies the value seen on its input pin ('passthrough.in') to its output pin ('passthrough.out') approximately once per second.

[source,python]
----
#!/usr/bin/env python3
import hal
import time
h = hal.component("passthrough")
h.newpin("in", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("out", hal.HAL_FLOAT, hal.HAL_OUT)
h.ready()
try:
    while True:
        h['out'] = h['in']
        time.sleep(1)
except KeyboardInterrupt:
    raise SystemExit
----

Copy the above listing into a file named "passthrough", make it executable ('chmod +x').
Then try it out (assuming the cpmponent "passthrough" is located in the current directory):

.Screen copy with details on the execution of the newly created passthrough HAL module.
----
$ halrun

halcmd: loadusr ./passthrough

halcmd: show pin

Component Pins:
Owner   Type  Dir     Value  Name
     4  float IN          0  passthrough.in
     4  float OUT         0  passthrough.out

halcmd: setp passthrough.in 3.14

halcmd: show pin

Component Pins:
Owner   Type  Dir     Value  Name
     4  float IN       3.14  passthrough.in
     4  float OUT      3.14  passthrough.out
----

== Non-realtime components and delays

If you typed "show pin" quickly, you may see that 'passthrough.out' still had its old value of 0.
This is because of the call to 'time.sleep(1)', which makes the assignment to the output pin occur at most once per second.
Because this is a non-realtime component, the actual delay between assignments can be much longer if the memory used by the passthrough component is swapped to disk,
as the assignment could be delayed until that memory is swapped back in.

Thus, non-realtime components are suitable for user-interactive elements such as control panels (delays in the range of milliseconds are not noticed, and longer delays are acceptable),
but not for sending step pulses to a stepper driver board (delays must always be in the range of microseconds, no matter what).

== Create pins and parameters

.Create a HAL component
[source,python]
----
mycomp = hal.component("passthrough")
----

The component itself is created by a call to the constructor 'hal.component'.
The arguments are the HAL component name and (optionally) the prefix used for pin and parameter names.
If the prefix is not specified, the component name is used.

.Create a HAL pin or parameter
[source,python]
----
mycomp.newpin("in", hal.HAL_FLOAT, hal.HAL_IN)
mycomp.newparam("has-feature-rotate", hal.HAL_BIT, hal.HAL_RO)
----

Then pins are created by calls to methods on the component object.
The arguments are: pin name suffix, pin type, and pin direction.
For parameters, the arguments are: parameter name suffix, parameter type, and parameter direction.

.HAL Option Names
[width="100%",cols="<3s,7*<"]
|===
|Pin and Parameter Types:|`HAL_BIT`|`HAL_FLOAT`|`HAL_S32`|`HAL_U32`|`HAL_S64`|`HAL_U64`|`HAL_PORT`
|Pin Directions:         |`HAL_IN` |`HAL_OUT`  |`HAL_IO` |         |         |         |
|Parameter Directions:   |`HAL_RO` |`HAL_RW`   |         |         |         |         |
|===

[NOTE]
====
Only pins and signals can use the `HAL_PORT` type.
====

The full pin or parameter name is formed by joining the prefix and the
suffix with a ".", so in the example the pin created is called 'passthrough.in'.

[source,python]
----
mycomp.ready()
----

Once all the pins and parameters have been created, call the '.ready()' method.

=== Changing the prefix

The prefix can be changed by calling the '.setprefix()' method. The
current prefix can be retrieved by calling the '.getprefix()' method.

== Reading and writing pins and parameters

For pins and parameters which are also proper Python identifiers, the
value may be accessed or set using the attribute syntax:

[source,python]
----
mycomp.out = mycomp.in
----

For all pins, whether or not they are also proper Python identifiers,
the value may be accessed or set using the subscript syntax:

[source,python]
----
mycomp['out'] = mycomp['in']
----

To see all pins with their values, getpins returns all values in a dictionary
of that component.

[source,python]
----
mycomp.getpins()
>>>{'in': 0.0, 'out': 0.0}
----

=== Driving output (HAL_OUT) pins

Periodically, usually in response to a timer, all `HAL_OUT` pins should be "driven" by assigning them a new value.
This should be done whether or not the value is different than the last one assigned.
When a pin is connected to a signal, its old output value is not copied into the signal.
The proper value will only appear on the signal once the component assigns a new value.

=== Driving bidirectional (HAL_IO) pins

The above rule does not apply to bidirectional pins.
Instead, a bidirectional pin should only be driven by the component when the component wishes to change the value.
For instance, in the canonical encoder interface, the encoder component only sets the 'index-enable'
pin to `False` (when an index pulse is seen and the old value is `True`), but never sets it to `True`.
Repeatedly driving the pin `False` might cause the other connected component to act as though another index pulse had been seen.

== Exiting

A 'halcmd unload' request for the component is delivered as a 'KeyboardInterrupt' exception.
When an unload request arrives, the process should either
exit in a short time, or call the '.exit()' method on the component
if substantial work (such as reading or
writing files) must be done to complete the shutdown process.

== HAL Python module reference

See <<cha:python-hal-interface, Python HAL Interface>> for an overview and description of available classes and methods.

== Constants

Use these to specify details rather then the value they hold.

* Pin, parameter and signal types:
** `HAL_BIT`
** `HAL_FLOAT`
** `HAL_S32`
** `HAL_U32`
** `HAL_S64`
** `HAL_U64`
* Pin direction:
** `HAL_IN`
** `HAL_OUT`
* Parameter access:
** `HAL_RO`
** `HAL_RW`
* Message severity:
** `MSG_NONE`
** `MSG_ALL`
** `MSG_DBG`
** `MSG_ERR`
** `MSG_INFO`
** `MSG_WARN`

== System Information

Read these to acquire information about the realtime system.

* `lcnc_realtime`: See <<cha:python-lcnc_realtime, Python module for managing the realtime backend>>.
* `is_kernelspace`
* `is_userspace`
* `get_realtime_type()`

// vim: set syntax=asciidoc:
