cd /usr/share/glade/pixmaps/hicolor/16x16/actions/
ln -s widget-gtk-button.png widget-gladevcp-hal_button.png
ln -s widget-gtk-checkbutton.png widget-gladevcp-hal_checkbutton.png
ln -s widget-gtk-combobox.png widget-gladevcp-hal_combobox.png
ln -s widget-gtk-hbox.png widget-gladevcp-hal_hbox.png
ln -s widget-gtk-table.png widget-gladevcp-hal_hidetable.png
ln -s widget-gtk-hscale.png widget-gladevcp-hal_hscale.png
ln -s widget-gtk-label.png widget-gladevcp-hal_label.png
ln -s widget-gtk-colorbutton.png widget-gladevcp-hal_light_button.png
ln -s widget-gtk-progressbar.png widget-gladevcp-hal_progressbar.png
ln -s widget-gtk-radiobutton.png widget-gladevcp-hal_radiobutton.png
ln -s widget-gtk-spinbutton.png widget-gladevcp-hal_spinbutton.png
ln -s widget-gtk-table.png widget-gladevcp-hal_table.png
ln -s widget-gtk-togglebutton.png widget-gladevcp-hal_togglebutton.png
ln -s widget-gtk-vbox.png widget-gladevcp-hal_vbox.png
ln -s widget-gtk-vscale.png widget-gladevcp-hal_vscale.png
ln -s widget-gtk-button.png widget-gladevcp-halio_button.png
ln -s widget-gtk-hscale.png widget-gladevcp-halio_hscale.png
ln -s widget-gtk-label.png widget-gladevcp-state_label.png
ln -s widget-gtk-label.png widget-gladevcp-state_sensitive_table.png
ln -s widget-gtk-label.png widget-gladevcp-status_label.png
ln -s widget-gtk-hscale.png widget-gladevcp-override.png
ln -s widget-gtk-assistant.png widget-gladevcp-pyngcgui.png
ln -s widget-gtk-iconview.png widget-gladevcp-icon_filechooser.png
ln -s widget-gtk-grid.png widget-gladevcp-offsetpage.png
ln -s widget-gtk-filechooserbutton.png widget-gladevcp-vcp_filechooserbutton.png
ln -s widget-gtk-filechooserdialog.png widget-gladevcp-vcp_filechooserdialog.png
ln -s widget-gtk-treeview.png widget-gladevcp-vcp_mdihistory.png
ln -s widget-gtk-textview.png widget-gladevcp-vcp_sourceview.png
ln -s widget-gtk-hbox.png widget-gladevcp-vcp_macro_select
