#!/bin/sh

# M152 turn off HSSC and reset all of the parameters = 0.0

MCMD=$(readlink -nf $0) ;# canonical file name
MNAME=$(basename $MCMD)

echo
echo "Example for User M code invocation:"
echo "M code File: $MCMD"
echo "$MNAME Turning off HSSC and resetting parameters to zero"
halcmd setp hssc.0.hssc-on  False
halcmd setp hssc.0.duration 0.0
halcmd setp hssc.0.amplitude 0.0
halcmd setp hssc.0.interval 0.0



# exit 0 for success
exit 0 ;
