default: I20HostMot2.bit
SOURCES := \
	atrans.vhd \
	boutreg.vhd \
	hostmot2.vhd \
	hostmotid.vhd \
	I20HostMot2.vhd \
	IDParms.vhd \
	idrom.vhd \
	irqlogic.vhd \
	kubstepgeny.vhd \
	pwmpdmgenh.vhd \
	pwmrefh.vhd \
	qcounterate.vhd \
	qcountersf.vhd \
	simplespix.vhd \
	timestamp.vhd \
	uartr.vhd \
	uartx.vhd \
	ubrategen.vhd \
	watchdog.vhd \
	wordpr.vhd \
	wordrb.vhd
DEVICE := xc2s200-5pq208
CONSTRAINTS := 5i20.ucf
include ../../xilinx.mk
