component rtapi_app_main_fails "rtapi_app_main error test";
pin out bool boo;
option rtapi_app no;
option period no;
function _;
license "GPL";

;;

void *x; // Must be global or the compiler may remove it

int rtapi_app_main(void) {
    x = export; // Prevent "warning: 'export' defined but not used"
    return -ERANGE;
}

void rtapi_app_exit(void) {
    return;
}

FUNCTION(_) { boo_set(boo ^ 0x1); }
