#!/bin/bash

echo "To start Machinekit preconfigured for PocketNC, simply type:"
echo "	PocketNC"

echo '#!/bin/bash' > /usr/bin/PocketNC
echo "machinekit $PWD/PocketNC.ini" >> /usr/bin/PocketNC
chown 750 /usr/bin/PocketNC
chmod +x /usr/bin/PocketNC

chmod +x dtc.sh
./dtc.sh

