#!/bin/bash
#
# This script (M100) is called to append an integer to a log file,
# for testing purposes
#
# Put this in your .ini to use:
#
#     [RS274NGC]USER_M_PATH = ./subs
#

TEST_DIR=$(dirname INI_FILE_NAME)
OUT_FILE=$TEST_DIR/gcode-output

P=$1

echo P is $P >> $OUT_FILE

