[DISPLAY]
DISPLAY                 = axis
CYCLE_TIME              = 0.100
HELP_FILE               = doc/help.txt
POSITION_OFFSET         = RELATIVE
POSITION_FEEDBACK       = ACTUAL
MAX_FEED_OVERRIDE       = 1.2
MAX_SPINDLE_OVERRIDE    = 1.0
MAX_LINEAR_VELOCITY     = 1.2
DEFAULT_LINEAR_VELOCITY = .25
PROGRAM_PREFIX          = ../../nc_files/
INTRO_GRAPHIC           = machinekit.gif
INTRO_TIME              = 5
EDITOR                  = gedit
TOOL_EDITOR             = tooledit
INCREMENTS              = 1 in, 0.1 in, 10 mil, 1 mil, 1mm, .1mm, 1/8000 in
