.\" Copyright (c) 2007 Alex Joni
.\"                (alex_joni AT users DOT sourceforge DOT net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\"
.\"
.TH axis-remote "1"  "2007-04-01" "EMC Documentation" "The Enhanced Machine Controller"
.SH NAME
axis-remote \- AXIS Remote Interface
.SH SYNOPSIS
.B axis-remote
<\fI-ping\fR> <\fI-reload\fR> <\fI-quit\fR> <\fI-help\fR>
.SH DESCRIPTION
\fBaxis-remote\fR is a small script to control a running AXIS GUI.
Use \fBaxis-remote -help\fR for further information.
.SH OPTIONS
.TP
\fB-ping\fR
Check whether AXIS is running.
.TP
\fB-reload\fR
Make AXIS reload the currently loaded file.
.TP
\fB-quit\fR
Make AXIS quit.
.TP
\fB-help\fR
Display a list of valid parameters for \fBaxis-remote\fR.

.SH "SEE ALSO"
\fBaxis(1)\fR

Much more information about EMC2 and HAL is available in the EMC2
and HAL User Manuals, found at /usr/share/doc/emc2/.

.SH HISTORY

.SH BUGS
None known at this time. 
.PP
.SH AUTHOR
This man page written by Alex Joni, as part of the Enhanced Machine
Controller (EMC) project.
.SH REPORTING BUGS
Report bugs to alex_joni AT users DOT sourceforge DOT net
.SH COPYRIGHT
Copyright \(co 2007 Alex Joni.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
