.\" Copyright (C) 2015 Jeff Epler
.TH LinuxCNC "1" "2015-04-18" "LinuxCNC Documentation" ""
.SH NAME
elbpcom \- Communicate with Mesa ethernet cards
.SH SYNOPSIS
Common options:
.RS
.SY elbpcom
.BI [\-\-ip= IP ]
.BI [\-\-port= PORT ]
.BI [\-\-timeout= TIMEOUT ]
.RE

Reading data:
.RS
.SY elbpcom
.BI [ common\ options ]
.BI \-\-space= SPACE
.B [\-\-info]
.BI \-\-address= ADDRESS
.BI \-\-read= LENGTH
.RE

Writing data:
.RS
.SY elbpcom
.BI [ common\ options ]
.BI \-\-space= SPACE
.BI \-\-address= ADDRESS
.BI \-\-write= HEXDATA
.RE

Sending arbitrary packets:
.RS
.SY elbpcom
.BI [ common\ options ]
.I HEXDATA
.RE

.SH DESCRIPTION
Read or write data from a Mesa ethernet card that uses the LBP16 protocol,
such as the 7i80.  This can be useful for performing certain low-level tasks.

For more information about the meaning of each address space, see the card
documentation.  Incorrect use of this utility can have negative effects such
as changing the board's IP address or even corrupting the FPGA bitfile in
the eeprom.  For some tasks, such as updating FPGA bitfiles and setting IP
addresses,
.BR mesaflash (1)
is a more appropriate tool.

If not specified, the default values are
.RS
.BI \-\-ip= 192.168.1.121
.BI \-\-port= 27181
.BI \-\-timeout= .2
.RE 

This example demonstrates reading the HOSTMOT2 identifying string from the
IDROM in space 0:
.RS
.nf
$ elbpcom \-\-space 0 \-\-address 0x104 \-\-read 8
> 82420401
< 484f53544d4f5432
      HOSTMOT2
.fi
.RE
First the request is shown in hex.  Then the response (if any) is shown in hex.
Finally, the response is shown in ASCII, with "." replacing any non-ASCII
characters.  This is similar to the following invocations of mesaflash:
.RS
.nf
$ ./mesaflash  \-\-device 7i80 \-\-rpo 0x104
54534F48
$ ./mesaflash  \-\-device 7i80 \-\-rpo 0x108
32544F4D
.fi
.RE
but notice its different treatment of byte order.

.SH SEE ALSO
.BR mesaflash (1),
.BR hostmot2 (9),
.BR hm2_eth (9),
.UR http://www.mesanet.com
Mesa's documentation for the Anything I/O boards
.UE .
