.\" Copyright (c) 2006 Alex Joni
.\"                (alex_joni AT users DOT sourceforge DOT net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\"
.\"
.TH HALUI "1"  "2006-07-22" "EMC Documentation" "HAL User Interface"
.SH NAME
halui \- observe HAL pins and command EMC through NML
.SH SYNOPSIS
.B halui
[\fB-ini <path-to-ini>\fR]
.SH DESCRIPTION
\fBhalui\fR is used to build a User Interface using hardware knobs
and switches. It exports a big number of pins, and acts accordingly 
when these change.
.SH OPTIONS
.TP
\fB-ini name\fR
use the \fIname\fR as the configuration file. Note: halui must find the 
nml file specified in the ini, usually that file is in the same 
folder as the ini, so it makes sense to run halui from that folder.
.SH USAGE
When run, \fBhalui\fR will export a large number of pins. A user can connect
those to his physical knobs & switches & leds, and when a change is noticed
halui triggers an appropriate event.

\fBhalui\fR expects the signals to be debounced, so if needed (bad knob contact) connect the physical button to a HAL debounce filter first.

.SH EXPORTED PINS

.SS abort
.TP 
\fIhalui.abort\fR
pin for clearing most errors
.SS home
.TP 
\fIhalui.home-all\fR
pin for requesting home-all
.SS axis
.TP
\fIhalui.axis.N.pos-commanded\fR
Commanded axis position in machine coordinates
.TP
\fIhalui.axis.N.pos-feedback\fR
Feedback axis position in machine coordinates
.TP
\fIhalui.axis.N.pos-relative\fR
Commanded axis position in relative coordinates
.SS estop
.TP
\fIhalui.estop.activate\fR
pin for setting Estop (emc internal) On
.TP
\fIhalui.estop.is-activated\fR
pin for displaying Estop state (emc internal) On/Off
.TP
\fIhalui.estop.reset\fR
pin for resetting Estop (emc internal) Off
.SS feed override
.TP
\fIhalui.feed-override.count-enable\fR (default: \fBTRUE\fR)
When TRUE, modify feed override when counts changes.
.TP
\fIhalui.feed-override.counts\fR
counts X scale = feed override percentage
.TP
\fIhalui.feed-override.decrease\fR
pin for decreasing the FO (-=scale)
.TP
\fIhalui.feed-override.direct-value\fR
pin to enable direct value feed override input
.TP
\fIhalui.feed-override.increase\fR
pin for increasing the FO (+=scale)
.TP
\fIhalui.feed-override.scale\fR
pin for setting the scale on changing the FO
.TP
\fIhalui.feed-override.value\fR
current Feed Override value
.SS flood
.TP
\fIhalui.flood.is-on\fR
pin for flood is on
.TP
\fIhalui.flood.off\fR
pin for stopping flood
.TP
\fIhalui.flood.on\fR
pin for starting flood
.SS jog
.TP
\fIhalui.jog.deadband\fR
pin for setting jog analog deadband (where not to move)
.TP
\fIhalui.jog-speed\fR
pin for setting jog speed. will be used for minus/plus jogging.
.TP
\fIhalui.jog.N.analog\fR
pin for jogging the axis N using an float value (e.g. joystick)
.TP
\fIhalui.jog.N.minus\fR
pin for jogging axis N in negative direction at the halui.jog-speed velocity
.TP
\fIhalui.jog.N.plus\fR
pin for jogging axis N in positive direction at the halui.jog-speed velocity
.TP
\fIhalui.jog.selected.minus\fR
pin for jogging the selected axis in negative direction at the halui.jog-speed velocity
.TP
\fIhalui.jog.selected.plus\fR
pin for jogging the selected axis in positive direction at the halui.jog-speed velocity
.SS joint
.TP
\fIhalui.joint.N.has-fault\fR
status pin telling that joint N has a fault
.TP
\fIhalui.joint.N.home\fR
pin for homing joint N
.TP
\fIhalui.joint.N.is-homed\fR
status pin telling that joint N is homed
.TP
\fIhalui.joint.N.is-selected\fR
status pin that joint N is selected
.TP
\fIhalui.joint.N.on-hard-max-limit\fR
status pin telling that joint N is on the positive hardware limit
.TP
\fIhalui.joint.N.on-hard-min-limit\fR
status pin telling that joint N is on the negative hardware limit
.TP
\fIhalui.joint.N.on-soft-max-limit\fR
status pin telling that joint N is on the positive software limit
.TP
\fIhalui.joint.N.on-soft-min-limit\fR
status pin telling that joint N is on the negative software limit
.TP
\fIhalui.joint.N.select\fR
pin for selecting joint N
.TP
\fIhalui.joint.N.unhome\fR
pin for unhoming joint N
.TP
\fIhalui.joint.selected\fR
selected joint
.TP
\fIhalui.joint.selected.has-fault\fR
status pin selected joint is faulted
.TP
\fIhalui.joint.select\fR
select joint
.TP
\fIhalui.joint.selected.home\fR
pin for homing the selected joint 
.TP
\fIhalui.joint.selected.is-homed\fR
status pin telling that the selected joint is homed
.TP
\fIhalui.joint.selected.on-hard-max-limit\fR
status pin telling that the selected joint is on the positive hardware limit
.TP
\fIhalui.joint.selected.on-hard-min-limit\fR
status pin telling that the selected joint is on the negative hardware limit
.TP
\fIhalui.joint.selected.on-soft-max-limit\fR
status pin telling that the selected joint is on the positive software limit
.TP
\fIhalui.joint.selected.on-soft-min-limit\fR
status pin telling that the selected joint is on the negative software limit
.TP
\fIhalui.joint.selected.unhome\fR
pin for unhoming the selected joint
.SS lube
.TP
\fIhalui.lube.is-on\fR
pin for lube is on
.TP
\fIhalui.lube.off\fR
pin for stopping lube
.TP
\fIhalui.lube.on\fR
pin for starting lube
.SS machine
.TP 
\fIhalui.machine.is-on\fR
pin for machine is On/Off
.TP 
\fIhalui.machine.off\fR
pin for setting machine Off
.TP 
\fIhalui.machine.on\fR
pin for setting machine On
.SS max-velocity
.TP
\fIhalui.max-velocity.count-enable\fR (default: \fBTRUE\fR)
When TRUE, modify max velocity when counts changes.
.TP
\fIhalui.max-velocity.counts\fR
counts from an encoder for example to change maximum velocity
.TP
\fIhalui.max-velocity.decrease\fR
pin for decreasing the maximum velocity (-=scale)
.TP
\fIhalui.max-velocity.increase\fR
pin for increasing the maximum velocity (+=scale)
.TP
\fIhalui.max-velocity.scale\fR
pin for setting the scale on changing the maximum velocity
.TP
\fIhalui.max-velocity.value\fR
Current value for maximum velocity
.SS mist
.TP
\fIhalui.mist.is-on\fR
pin for mist is on
.TP
\fIhalui.mist.off\fR
pin for stopping mist
.TP
\fIhalui.mist.on\fR
pin for starting mist
.SS mode
.TP
\fIhalui.mode.auto\fR
pin for requesting auto mode
.TP
\fIhalui.mode.is_auto\fR
pin for auto mode is on
.TP
\fIhalui.mode.is_joint\fR
pin showing joint by joint jog mode is on
.TP
\fIhalui.mode.is_manual\fR
pin for manual mode is on
.TP
\fIhalui.mode.is_mdi\fR
pin for mdi mode is on
.TP
\fIhalui.mode.is_teleop\fR
pin showing coordinated jog mode is on
.TP
\fIhalui.mode.joint\fR
pin for requesting joint by joint jog mode
.TP
\fIhalui.mode.manual\fR
pin for requesting manual mode
.TP
\fIhalui.mode.mdi\fR
pin for requesting mdi mode
.TP
\fIhalui.mode.teleop\fR
pin for requesting coordinated jog mode
.SS program
.TP
\fIhalui.program.block-delete.is-on\fR
status pin telling that block delete is on
.TP
\fIhalui.program.block-delete.off\fR
pin for requesting that block delete is off
.TP
\fIhalui.program.block-delete.on\fR
pin for requesting that block delete is on
.TP
\fIhalui.program.is-idle\fR
status pin telling that no program is running
.TP
\fIhalui.program.is-paused\fR
status pin telling that a program is paused
.TP
\fIhalui.program.is-running\fR
status pin telling that a program is running
.TP
\fIhalui.program.optional-stop.is-on\fR
status pin telling that the optional stop is on
.TP
\fIhalui.program.optional-stop.off\fR
pin requesting that the optional stop is off
.TP
\fIhalui.program.optional-stop.on\fR
pin requesting that the optional stop is on
.TP
\fIhalui.program.pause\fR
pin for pausing a program
.TP
\fIhalui.program.resume\fR
pin for resuming a program
.TP
\fIhalui.program.run\fR
pin for running a program
.TP
\fIhalui.program.stop\fR
pin for stopping a program 
(note: this pin does the same thing as halui.abort)
.TP
\fIhalui.program.step\fR
pin for stepping in a program
.SS spindle override
.TP
\fIhalui.spindle-override.count-enable\fR (default: \fBTRUE\fR)
When TRUE, modify spindle override when counts changes.
.TP
\fIhalui.spindle-override.counts\fR
counts X scale = spindle override percentage
.TP
\fIhalui.spindle-override.decrease\fR
pin for decreasing the SO (-=scale)
.TP
\fIhalui.spindle-override.direct-value\fR
pin to enable direct spindle override value input
.TP
\fIhalui.spindle-override.increase\fR
pin for increasing the SO (+=scale)
.TP
\fIhalui.spindle-override.scale\fR
pin for setting the scale of counts for SO
.TP
\fIhalui.spindle-override.value\fR
current FO value
.SS spindle
.TP
\fIhalui.spindle.brake-is-on\fR
status pin that tells us if brake is on
.TP
\fIhalui.spindle.brake-off\fR
pin for deactivating the spindle brake
.TP
\fIhalui.spindle.brake-on\fR
pin for activating the spindle brake
.TP
\fIhalui.spindle.decrease\fR
pin for making the spindle go slower
.TP
\fIhalui.spindle.forward\fR
a rising edge on this pin makes the spindle go forward
.TP
\fIhalui.spindle.increase\fR
pin for making the spindle go faster
.TP
\fIhalui.spindle.in-on\fR
status pin telling if the spindle is on
.TP
\fIhalui.spindle.reverse\fR
a rising edge on this pin makes the spindle go reverse
.TP
\fIhalui.spindle.runs-backward\fR
status pin telling if the spindle is running backward
.TP
\fIhalui.spindle.runs-forward\fR
status pin telling if the spindle is running forward
.TP
\fIhalui.spindle.start\fR
a rising edge on this pin starts the spindle
.TP
\fIhalui.spindle.stop\fR
a rising edge on this pin stops the spindle
.SS tool
.TP
\fIhalui.tool.length-offset.a\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.b\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.c\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.u\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.v\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.w\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.x\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.y\fR
current applied tool-length-offset
.TP
\fIhalui.tool.length-offset.z\fR
current applied tool-length-offset
.TP
\fIhalui.tool.number\fR
current selected tool

.SH "SEE ALSO"

.SH HISTORY

.SH BUGS
none known at this time.
.SH AUTHOR
Written by Alex Joni, as part of the Enhanced Machine
Controller (EMC2) project. Updated by John Thornton
.SH REPORTING BUGS
Report bugs to alex_joni AT users DOT sourceforge DOT net
.SH COPYRIGHT
Copyright \(co 2006 Alex Joni.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
