.TH IOCONTROL "1" "2021-04" "LinuxCNC Documentation" "HAL Component" 

.SH NAME
iocontrol \- interacts with HAL or G-code in userspace 

.SH SYNOPSIS


.B [EMCIO] 
.br
.B EMCIO = io
.br
or
.br
.B EMCIO = iov2

.SH DESCRIPTION

I/O control handles I/O tasks like coolant, toolchange, e-stop and lube. The signals are turned on and off in userspace with G-code or in the case of e-stop in hal. 
.br
I/O Control V2 (iov2) adds more toolchager support for communication with the toolchanger.

Whether \fBio\fR or \fBiov2\fR is used can be chosen in the [EMCIO] section of the INI file.

See also 
.UR http://linuxcnc.org/docs/html/config/iov2.html
.UE
.SH SEE ALSO

.ie '\*[.T]'html' \{\

.UR io.1.html
\fBio\fR(1),
.UE
.UR iov2.1.html 
\fBiov2\fR(1)
.UE
\}
.el \{\

\fBio\fR(1)
\fBiov2\fR(1)

\}



