.TH IOCONTROL "1" "2021-04" "LinuxCNC Documentation" "HAL Component" 

.SH NAME
iocontrol \- accepts NML I/O commands, interacts with HAL in userspace
 

.SH SYNOPSIS


.B [EMCIO] 
.br
.B EMCIO = io
.br
or
.br
.B EMCIO = iov2

.SH DESCRIPTION



\fBiov2\fR is an alternative (extended) interface to \fBio\fR. 
It creates additional pins and does some things differently. 

Whether \fBio\fR or \fBiov2\fR is used can be chosen in the [EMCIO] section of the INI file.

.SH SEE ALSO

.ie '\*[.T]'html' \{\

.UR io.1.html
\fBio\fR(1),
.UE
.UR iov2.1.html 
\fBiov2\fR(1)
.UE
\}
.el \{\

\fBio\fR(1)
\fBiov2\fR(1)

\}



