.\" Copyright (c) 2016 John Thornton <bjt128@gmail.com>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
.\" USA.
.\"
.\"
.\"
.TH mb2hal "1" "January 1, 2016" "Modbus to HAL" "LinuxCNC Documentation"
.SH NAME
\fBmb2hal\fR - HAL userspace component for Modbus
.SH SYNOPSIS
.B mb2hal
.RI [OPTIONS]
.br
.SH DESCRIPTION
MB2HAL is a generic userspace HAL component to communicate with one or more
Modbus devices.
.PP
See the Documents for more information on mb2hal
.SH AUTHOR
John Thornton
.SH LICENSE
GPL
