
.TH milltask 1 "September 30, 2014" "" "The Enhanced Machine Controller"
.SH NAME
milltask \- Userspace task controller for LinuxCNC
.SH DESCRIPTION
milltask is an internal process of LinuxCNC.  It is generally not invoked directly.
It creates the pins shown as owned by the "inihal" component, which allow
runtime modification of certain values from the inifile.
.SH PINS
.SS Per-joint pins (N == joint number)
.TP
\fBini.\fIN\fB.backlash
Allows adjustment of \fB[JOINT_\fIN\fB]BACKLASH
.TP
\fBini.\fIN\fB.ferror
Allows adjustment of \fB[JOINT_\fIN\fB]FERROR
.TP
\fBini.\fIN\fB.min_ferror
Allows adjustment of \fB[JOINT_\fIN\fB]MIN_FERROR
.TP
\fBini.\fIN\fB.min_limit
Allows adjustment of \fB[JOINT_\fIN\fB]MIN_LIMIT
.TP
\fBini.\fIN\fB.max_limit
Allows adjustment of \fB[JOINT_\fIN\fB]MAX_LIMIT
.TP
\fBini.\fIN\fB.max_velocity
Allows adjustment of \fB[JOINT_\fIN\fB]MAX_VELOCITY
.TP
\fBini.\fIN\fB.max_acceleration
Allows adjustment of \fB[JOINT_\fIN\fB]MAX_ACCELERATION
.SS Per-axis pins (L == axis letter)
.TP
\fBini.\fIL\fB.min_limit
Allows adjustment of \fB[AXIS_\fIL\fB]MIN_LIMIT
.TP
\fBini.\fIL\fB.max_limit
Allows adjustment of \fB[AXIS_\fIL\fB]MAX_LIMIT
.TP
\fBini.\fIL\fB.max_velocity
Allows adjustment of \fB[AXIS_\fIL\fB]MAX_VELOCITY
.TP
\fBini.\fIL\fB.max_acceleration
Allows adjustment of \fB[AXIS_\fIL\fB]MAX_ACCELERATION

.SS Global pins
.TP
\fBini.traj_default_acceleration
Allows adjustment of \fB[TRAJ]DEFAULT_ACCELERATION
.TP
\fBini.traj_default_velocity
Allows adjustment of \fB[TRAJ]DEFAULT_VELOCITY
.TP
\fBini.traj_max_acceleration
Allows adjustment of \fB[TRAJ]MAX_ACCELERATION
.TP
\fBini.traj_max_velocity
Allows adjustment of \fB[TRAJ]MAX_VELOCITY

.SS Global pins (arc_blend trajectory planner)
.TP
\fBini.traj_arc_blend_enable
Allows adjustment of \fB[TRAJ]ARC_BLEND_ENABLE
.TP
\fBini.traj_arc_blend_fallback_enable
Allows adjustment of \fB[TRAJ]ARC_BLEND_FALLBACK_ENABLE
.TP
\fBini.traj_arc_blend_gap_cycles
Allows adjustment of \fB[TRAJ]ARC_OPTIMIZATION_DEPTH
.TP
\fBini.traj_arc_blend_optimization_depth
Allows adjustment of \fB[TRAJ]ARC_BLEND_GAP_CYCLES
.TP
\fBini.traj_arc_blend_ramp_freq
Allows adjustment of \fB[TRAJ]ARC_BLEND_RAMP_FREQ

.SH NOTES
These pins cannot be linked or set in a halfile specified by \fB[HAL]HALFILE\fR.  They can be altered by independent halcmd programs or by GUIs that support \fB[HAL]POSTGUI_HALFILE\fR.  The inifile is not automatically updated with these values but can be updated using the calibration program (emccalib.tcl) when using a \fB[HAL]POSTGUI_HALFILE\fR.
