.TH SIM_TORCH "1" "2022-02-26" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

sim-torch \- A simulated plasma torch
.SH SYNOPSIS
.HP
.B loadusr Wn sim-torch sim-torch
.SH DESCRIPTION

A simulated plasma torch for arc-ok testing.

.I VERSION:
.br
0.1


.SH PINS
.TP
.B sim-torch-rt.cut-noise-in\fR float in \fR(default: \fI0.75\fR)
the maximum amount of noise during cutting (volts)
.TP
.B sim-torch-rt.cycles-in\fR s32 in \fR(default: \fI200\fR)
the number of cycles that the arc voltage overshoots the cut voltage (cycles)
.TP
.B sim-torch-rt.on-delay-in\fR s32 in \fR(default: \fI10\fR)
the time from turn on until overshoot begins (cycles)
.TP
.B sim-torch-rt.offset-in\fR float in \fR
the cut voltage offset(volts)
.TP
.B sim-torch-rt.overshoot-in\fR s32 in \fR(default: \fI50\fR)
the percentage of the cut voltage that the arc voltage overshoots (percent)
.TP
.B sim-torch-rt.ramp-noise-in\fR float in \fR(default: \fI5\fR)
the maximum amount of noise during overshoot (volts)
.TP
.B sim-torch-rt.ramp-up-in\fR s32 in \fR(default: \fI80\fR)
percent of 'cycles_in' that the arc voltage ramps up (percent)
.TP
.B sim-torch-rt.start\fR bit in \fR
start the arc
.TP
.B sim-torch-rt.voltage-in\fR float in \fR(default: \fI100\fR)
the cut voltage (volts)
.TP
.B sim-torch-rt.voltage-out\fR float out \fR
output voltage (volts)

.SH AUTHOR
Phillip A Carter

.SH LICENSE
GPLv2 or greater
