.TH XHC-WHB04B-6 "1" "2020-04-07" "LinuxCNC Documentation" "HAL User's Manual"
.SH NAME
xhc\-whb04b\-6 \- User-space HAL component for the xhc-whb04b-6 pendant.

.SH DESCRIPTION
The xhc-whb04b-6 HAL component supports the XHC WHB04B-6, a 6-axis wireless USB pendant.
It provides a number of push-buttons, a jogwheel, two rotary buttons for axis and
speed / step selection and an ordinary LCD display.
.PP
The LCD display, having a very simple firmware interface, indicates the following listed information only.
No other information, such as custom data, can be printed.
.PP
Activated axis (X, Y, Z, A, B or C). +
Current axis position of X, Y, Z and separately of A, B, C. +
Whether machine (X, Y, Z, A, B or C) or relative (X1, Y1, Z1, A1, B1 or C1) coordinates are displayed. +
Override or Step size or velocity depending on the operating mode (MPG or Step or Continuous). +
Feed rate of axis.+
Spindle speed in [r/m]. +
Machine state such as reset. +
Battery level +
Wireless signal strength
.PP
The pendant display, its rotary selector switch, and the component pin names use designators x,y,z,a,b and c.
While this arrangement presumes a machine configured as X, Y, Z, A, B an C,
the pins can be assigned independently as required in a HAL configuration.

.SH UDEV
The xhc-whb0b-6 executable needs permission for reading the pendant's
USB device.  Debian package installs (debs) handle this automatically
but Run-In-Place (RIP) builds may need a udev rules file.  This file
should be created (using sudo and a text editor or copy from source folder) as:

.nf
\fB/etc/udev/rules.d/99\-xhc\-whb04b\-6.rules\fR with the single line:

ATTR{idProduct}=="eb93", ATTR{idVendor}=="10ce", MODE="0666", OWNER="root", GROUP="plugdev"
.fi

.SH Standalone Usage
The xhc-whb04b-6 program can be run from the command line without LinuxCNC to test a pendant.
This standalone mode is used to identify the button codes produced for each button press and debug transmitted USB data. 

Usage:

\fIloadusr \-W \fR \fBxhc\-whb04b\-6\fR \fI\-H [Options]\fR

.SH Options (suggested -HsfB)
.TP
\fB\-h\fR list command line options and exit
.TP
\fB\-ue\fR Start in userspace mode (simulation) and prints incoming USB data transfer and generated key pressed/released events.
.TP
\fB\-H\fR    run in real-time HAL mode (because simulation mode is default without args)
.TP
\fB\-s\fR    Lead + jogwheel changes the spindle override speed. Each tick will increase/decrease the spindle override.
.TP
\fB\-f n\fR  MPG + jogwheel changes the feed override. Each tick will increment/decrement the feed override.
.TP
\fB\-B n\fR  Add 5mm and 10mm to Step feedrate output
.PP


.SH hal CONNECTION

You can found the file and copy in your config folder, rename to xhc-whb04b-6.hal
https://github.com/linuxcnc/linuxcnc/blob/master/src/hal/user_comps/xhc-whb04b-6/example-configuration.md

edit your ini file and add in this section
[HAL]
HALFILE = xhc-whb04b-6.hal



.SH Author
Copyright (C) 2018 Raoul Rubien (github.com/rubienr) Updated for Linuxcnc 2020 by alkabal_free.fr.

