'\" t
.\"     Title: xyzacb-trsrn-gui
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/19/2024
.\"    Manual: LinuxCNC Documentation
.\"    Source: LinuxCNC
.\"  Language: English
.\"
.TH "XYZACB\-TRSRN\-GUI" "1" "08/19/2024" "LinuxCNC" "LinuxCNC Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xyzacb-trsrn-gui \- Vismach Virtual Machine GUI
.SH "DESCRIPTION"
.sp
\fBxyzacb\-trsrn\-gui\fR is one of the sample \fBVismach\fR GUIs for LinuxCNC, simulating a dual\-rotary machine with switchable kinematics\&.
.sp
See the main LinuxCNC documentation for more details\&.
.sp
http://linuxcnc\&.org/docs/html/gui/vismach\&.html
.SH "SEE ALSO"
.sp
linuxcnc(1)*
.sp
Much more information about LinuxCNC and HAL is available in the LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/\&.
.SH "BUGS"
.sp
None known at this time\&.
.SH "AUTHOR"
.sp
This man page was written by David Mueller, as part of the LinuxCNC project\&.
.SH "REPORTING BUGS"
.sp
Report bugs at https://github\&.com/LinuxCNC/linuxcnc/issues
.SH "COPYRIGHT"
.sp
Copyright \(co 2024 David Mueller\&.
.sp
This is free software; see the source for copying conditions\&. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.
