#!/bin/bash

TEST_DIR=$(dirname $1)
cd $TEST_DIR

# show deviation from expected output
diff -uwB expected-gcode-output gcode-output || exit 1
diff -uwB expected-linuxcncrsh-output linuxcncrsh-output || exit 1
