#!/usr/bin/python
#   This is a component of LinuxCNC
#   Copyright 2014 Jeff Epler <jepler@unpythonic.net>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

from xml.etree import ElementTree
import sys

# A list of classes where name reuse is less likely to be a problem
# (but this is only a heuristic; we really want no duplicates)
# I don't want to decide to enable the whitelist, but I leave it here
# in case Chris Morley would like to do so.
#whitelist_classes = set(('GtkLabel', 'GtkTable', 'GtkAlignment', 'GtkHBox',
#    'GtkVBox', 'GtkImage', 'GtkHSeparator', 'GtkVSeparator',
#    'GtkCellRendererText'))
whitelist_classes = set()
id2f = {}

for f in sys.argv[1:]:
    doc = ElementTree.parse(f)
    for node in doc.findall(".//object"):
        node_id = node.get('id')
        cls = node.get('class')
        of = id2f.get(node_id, None)
        if of:
            if cls not in whitelist_classes:
                print "%s:0: Uses id %r (first encountered in %s)" % (
                        f, node_id, of)
        else:
            id2f[node_id] = f
