#!/bin/bash

if [ ! -z "$EMC2_HOME" ]; then
    source $EMC2_HOME/scripts/githelper.sh
else
    if [ ! -d debian -o ! -d src ]; then
        echo "this script must be run from the root of the source tree (the directory with debian and src in it)"
        exit 1
    fi
    source scripts/githelper.sh
fi

githelper $1

echo $DEB_COMPONENT

