#!/bin/bash
#
# This script installs the RTLinux kernel modules
#

sync

#
# list of kernel modules to load
#

RTL_MODULES="rtl mbuff rtl_time rtl_sched rtl_posixio rtl_fifo"

#
# Load the modules
#
echo "Loading RTLinux modules"
for MOD in $RTL_MODULES ; do
    # check to see if the module is already installed
    if ! /sbin/lsmod | awk '{print $1}' | grep -x $MOD >/dev/null ; then
	# install the module - use modprobe so it
	# can install dependencies too
	if /sbin/modprobe $MOD ; then
	    echo "'$MOD' loaded successfully"
	else
	    echo "ERROR: Could not load '$MOD'"
	    exit -1
	fi
    else
	echo "'$MOD' already loaded"
    fi
done

exit 0


