#!/bin/bash
#
# This script installs the RTAI kernel modules
#

sync

#
# List of kernel modules to load
# NOTE:  This list contains only the modules that must
# always be loaded.  There are two other modules, "adeos"
# and "rt_mem_mgr", that may or may not be needed.  They are
# not in the list - instead modprobe automatically decides
# whether or not to install them using its dependency file.
#

RTAI_MODULES="rtai rtai_sched rtai_fifos rtai_shm"

#
# Load the modules
#
echo "Loading RTAI modules"
for MOD in $RTAI_MODULES ; do
    # check to see if the module is already installed
    if /sbin/lsmod | awk '{print $1}' | grep -x $MOD >/dev/null ; then
	echo "'$MOD' already loaded"
    else
	# install the module - use modprobe so it
	# can install dependencies too
	if /sbin/modprobe $MOD ; then
	    echo "'$MOD' loaded successfully"
	else
	    echo "ERROR: Could not load '$MOD'"
	    exit -1
	fi
    fi
done

# Handle the math module seperately, as there are two variants depending
# on the RTAI version installed.
if /sbin/modprobe  rtai_libm ; then
    echo "rtai_libm loaded successfully"
else
    if /sbin/modprobe  rtai_math ; then
	echo "rtai_libm loaded successfully"
    else
	echo "ERROR: Could not load rtai_libm or rtai_math"
	exit -1
    fi
fi

exit 0
