#!/bin/bash
#
# This script installs the RTAI kernel modules
#

sync

#
# Check for the symbols "rthal" or "adeos" in ksyms to verify the
# presence of the kernel patches
#

if ! /sbin/ksyms -a | grep -E '(rthal|adeos)' >/dev/null 2>/dev/null ; then
    echo "ERROR: 'rthal' or 'adeos' not present in kernel - cannot load RTAI"
    exit -1
fi

#
# List of kernel modules to be installed
#

RTAI_MODULES="rtai rt_mem_mgr rtai_sched rtai_fifos rtai_shm"

#
# Load the modules
#

echo "Loading RTAI modules"
for MOD in $RTAI_MODULES ; do
    # ask modprobe if it knows where to find the module
    MODLOC=`/sbin/modprobe --list $MOD.o`
    if [ -z $MODLOC ] ; then
	# can't find it - perhaps at a later date we can put a
	#   more sophisticated search here, but for now, if
	#   modprobe can't find it we simply abort
	echo "ERROR: modprobe cannot find module '$MOD'"
	exit -1
    fi
    # check to see if the module is already installed
    if /sbin/lsmod | awk '{print $1}' | grep -x $MOD >/dev/null ; then
	echo "'$MOD' already loaded"
    else
	# install the module (give insmod the full path)
	if /sbin/insmod $MODLOC >/dev/null 2>/dev/null ; then
	    echo "'$MOD' loaded successfully"
	else
	    echo "ERROR: Could not load '$MOD' - are you root?"
	    exit -1
	fi
    fi
done

exit 0


