#!/bin/bash
#
# This script removes rtai kernel modules
#

sync

#
# check for user space processes using RTAI shared memory
#

if [ -e /dev/rtai_shm ] ; then
    # device file exists, check for processes using it
    if /sbin/fuser -s /dev/rtai_shm ; then
	# at least one process is using it
	echo "ERROR:  Can't remove RTAI modules, kill the following process(es) first"
	/sbin/fuser -v /dev/rtai_shm
	exit -1
    fi
fi

#
# List of kernel modules to be removed
# NOTE: This list contains some modules that may or may not
# be loaded - specifically "rt_mem_mgr" and "adeos".  If they
# are not present, the loop below simply skips them
#

RTAI_MODULES="rtai_shm rtai_fifos rtai_sched rt_mem_mgr rtai adeos"

#
# Remove the modules
#

echo "Unloading RTAI modules"
for MOD in $RTAI_MODULES ; do
    # check to see if the module is installed
    if /sbin/lsmod | awk '{print $1}' | grep -x $MOD >/dev/null ; then
	# remove the module
	if /sbin/rmmod $MOD ; then
	    echo "'$MOD' unloaded successfully"
	else
	    echo "ERROR: Could not unload '$MOD'"
	    exit -1
	fi
    else
	echo "'$MOD' already unloaded"
    fi
done

exit 0
