#!/bin/bash
#
# This script removes rtai kernel modules
#

sync

#
# check for user space processes using RTAI shared memory
#

if [ -e /dev/rtai_shm ] ; then
    # device file exists, check for processes using it
    if /sbin/fuser -s /dev/rtai_shm ; then
	# at least one process is using it
	echo "ERROR:  Can't remove RTAI modules, kill the following process(es) first"
	/sbin/fuser -v /dev/rtai_shm
	exit -1
    fi
fi

#
# List of kernel modules to be removed
#
# Check if we need to add adeos to the list.
if /sbin/ksyms -a | grep adeos >/dev/null 2>/dev/null ; then
    RTAI_MODULES=" adeos "
fi
RTAI_MODULES="rtai_shm rtai_fifos rtai_sched rtai"$RTAI_MODULES

#
# Remove the modules
#

echo "Unloading RTAI modules"
for MOD in $RTAI_MODULES ; do
    # check to see if the module is installed
    if ! /sbin/lsmod | awk '{print $1}' | grep -x $MOD >/dev/null ; then
	echo "'$MOD' already unloaded"
    else
	# remove the module
	if /sbin/rmmod $MOD >/dev/null 2>/dev/null ; then
	    echo "'$MOD' unloaded successfully"
	else
	    echo "ERROR: Could not unload '$MOD' - are you root?"
	    exit -1
	fi
    fi
done

exit 0
