
BEGIN TRANSACTION;

DROP TABLE IF EXISTS "tools";


CREATE TABLE "tools" (
    toolno	INTEGER PRIMARY KEY, -- AUTOINCREMENT,
    pocket	INTEGER,
    diameter 	REAL DEFAULT (NULL),
    backangle   REAL DEFAULT (NULL),
    frontangle  REAL DEFAULT (NULL),
    orientation INTEGER DEFAULT (NULL),
    comment	 TEXT DEFAULT (NULL),
    x_offset REAL DEFAULT (NULL),
    y_offset REAL DEFAULT (NULL),
    z_offset REAL DEFAULT (NULL),
    a_offset REAL DEFAULT (NULL),
    b_offset REAL DEFAULT (NULL),
    c_offset REAL DEFAULT (NULL),
    u_offset REAL DEFAULT (NULL),
    v_offset REAL DEFAULT (NULL),
    w_offset REAL DEFAULT (NULL)
);



INSERT INTO "tools" VALUES (1,2,4.0, NULL,NULL,NULL,"tool1",1.2,NULL,3.7,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (2,1,2.0, NULL,NULL,NULL,"tool2",0.2,NULL,1.2,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (3,7,3.3, NULL,NULL,NULL,"tool3",3.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (4,3,1.2, NULL,NULL,NULL,"tool4",NULL,NULL,5.9,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (5,5,6.2, NULL,NULL,NULL,"tool5",NULL,NULL,1.1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (6,9,1.9, NULL,NULL,NULL,"tool6",NULL,NULL,3.4,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (7,8,0.3, NULL,NULL,NULL,"tool7",NULL,NULL,1.7,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (8,11,2.50, NULL,NULL,NULL,"tool8",NULL,NULL,2.7,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "tools" VALUES (9,24,1.1, NULL,NULL,NULL,"tool9",NULL,NULL,4.9,NULL,NULL,NULL,NULL,NULL,NULL);







COMMIT;
