# Makefile for HAL user space components

include ../../Makefile.inc

all : headers
	(cd vcp; make $@)

headers: 
	(cd vcp; make $@)

indent:
	(cd vcp; make $@)

depend:
	(cd vcp; make $@)

install:
	(cd vcp; make $@)

clean:
	(cd vcp; make $@)

.PHONY: all headers depend indent install clean

