#!/bin/bash
   NOT USED thgis  not shoyld make using it fail
# User must plug in UNSf belonging to BegNR here
# weell it simpelr gor user to say 1 yes or 0 no
# thna to lookup data so i leave as yes/no QO
# with init of -1 meaning unanswered


#24.08.2025 new mcode to set Edm3.PlungeOrbit U32 -1 dwfault 0 dontt so  plungeorbit 1 so plungeorbnit
# the -1 value is fefault
# i need to knmow if user has answered "eann orbuit  the pklunge cut " or has NOT answered yet
# The comp Edm3 will hang till answered
# Then Edm3 comp will ensure answer is 0 or 1 else abort
#    Edm2 comp will abort if value is not -1,   0 or 1
#
# usage  M164 P<PlungeOrbitWanted>
#    vaalues:s -1 (initial, user has not answered yet
#     or 1  (yes  wanted  )
#     or 0  (not waanted

printf -v WaantOrbitPlungeInt '%d' "$1"
halcmd sets dPlungeOrbitWanted $WaantOrbitPlungeInt

exit 0
