#!/bin/bash
# 02.11.2025 M190 tyrns off axis.L.eoffset.enable

# tComp.ena MUST be IN
#halcmd setp tComp.enaIN False

halcmd setp axis.x.eoffset-enable False
halcmd setp axis.y.eoffset-enable False
halcmd setp axis.z.eoffset-enable False

halcmd setp tComp.isEna False

exit 0
