#!/bin/bash
# 02.11.2025 M191 tyrns on axis.L.eoffset.enable

#halcmd setp tComp.enaIN True
halcmd setp axis.x.eoffset-enable True
halcmd setp axis.y.eoffset-enable True
halcmd setp axis.z.eoffset-enable True

halcmd setp tComp.isEna True

exit 0
