#!/bin/bash
# M197  no P no Q
# turn of jump if it was left on
# place this in ,ngc just before M02

# M197 toggles sedm.JumpEna
#   get checkbnox state
a="$(halcmd getp sedm.JumpENA)"

#echo "M197 getp said sedm.JumpENA was $a "

if [[ $a == "TRUE" ]]; then
	#echo "was TRUE,so toggling "
	b="$(halcmd setp techGui.JumpENA.changepin 1)"
fi

exit 0
