#!/bin/bash

# usage:  M199      ( no P Q  parms)
# purpose: begin using eoffsets

halcmd setp axis.x.eoffset-enable True
halcmd setp axis.y.eoffset-enable True
halcmd setp axis.z.eoffset-enable True

halcmd setp sedm.isEna True

exit 0
