#!/usr/bin/python2

import sys, os, re

halfile = os.path.join(os.path.dirname(__file__),"test.hal")
param_re = re.compile(r'^setp\s+limit3.0.([^\s]+)\s+([-0-9]+)$')
params = {}
with open(halfile, 'r') as f:
    for line in f:
        m = param_re.match(line)
        if m is None:  continue
        params[m.group(1)] = int(m.group(2))

result_filename = sys.argv[1]
result_file = open(result_filename, 'r')

retval = 0

for line in result_file.readlines():
    (line, in_val, out, vel, acc) = line.split()[:5]
    out = float(out)
    vel = float(vel)
    acc = float(acc)

    if float(out) > params['max']:
        print "max=%.3f, in=%.3f, out=%.3f, max violation on line %s" % \
            (params['max'], float(in_val), out, line)
        retval = 1

    if float(out) < params['min']:
        print "min=%.3f, in=%.3f, out=%.3f, min violation on line %s" % \
            (params['min'], float(in_val), out, line)
        retval = 1

    if abs(vel) > params['maxv']:
        print "maxv=%.3f, vel=%.3f, velocity violation on line %s" % \
            (params['maxv'], vel, line)
        retval = 1

    if abs(acc) > params['maxa']:
        print "maxa=%.3f, acc=%.3f, acceleration violation on line %s" % \
            (params['maxa'], acc, line)
        retval = 1

sys.exit(retval)
