= gs2_vfd(1)
:manmanual: HAL Components
:mansource: ../man/man1/gs2.1.asciidoc
:man version : 



== NAME
**gs2_vfd** - HAL userspace component for Automation Direct GS2 VFD's



== SYNOPSIS
gs2_vfd
.RI [OPTIONS]



== DESCRIPTION
This manual page explains the
gs2_vfd
component. This component reads and writes to the GS2 via a modbus connection.
.PP
**gs2_vfd\fP is for use with LinuxCNC
**


== OPTIONS
.IP -b,\ --bits\ <n>
(default 8) Set number of data bits to <n>, where n must be from 5 to 8 inclusive
.IP -d,\ --device\ <path>
(default /dev/ttyS0) Set the name of the serial device node to use.
.IP -v,\ --verbose
Turn on verbose mode.
.IP -g,\ --debug
Turn on debug messages. Note that if there are serial errors, this may
become annoying.  Debug mode will cause all modbus messages to be printed
in hex on the terminal.
.IP -n,\ --name\ <string>
(default gs2_vfd) Set the name of the HAL module. The HAL comp name will be set to <string>, and all pin and parameter names will begin with <string>.
.IP -p,\ --parity\ [even,odd,none]
(default odd) Set serial parity to even, odd, or none.
.IP -r,\ --rate\ <n>
(default 38400) Set baud rate to <n>. It is an error if the rate is not one of the following: 110, 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200
.IP -s,\ --stopbits\ [1,2]
(default 1) Set serial stop bits to 1 or 2 
.IP -t,\ --target\ <n>
(default 1) Set MODBUS target (slave) number. This must match the device number you set on the GS2.
.IP -A,\ --accel-seconds\ <n>
(default 10.0) Seconds to accelerate the spindle from 0 to Max RPM.
.IP -D,\ --decel-seconds\ <n>
(default 0.0) Seconds to decelerate the spindle from Max RPM to 0.
If set to 0.0 the spindle will be allowed to coast to a stop without
controlled deceleration.
.IP -R,\ --braking-resistor
This argument should be used when a braking resistor is installed on the
GS2 VFD (see Appendix A of the GS2 manual).  It disables deceleration
over-voltage stall prevention (see GS2 modbus Parameter 6.05), allowing
the VFD to keep braking even in situations where the motor is regenerating
high voltage.  The regenerated voltage gets safely dumped into the
braking resistor.



== PINS
.IP <name>.DC-bus-volts\ (float,\ out)
from the VFD
.IP <name>.at-speed\ (bit,\ out) 
when drive is at commanded speed
.IP <name>.err-reset\ (bit,\ in) 
reset errors sent to VFD
.IP <name>.firmware-revision\ (s32,\ out)
from the VFD
.IP <name>.frequency-command\ (float,\ out)
from the VFD
.IP <name>.frequency-out\ (float,\ out)
from the VFD
.IP <name>.is-stopped\ (bit,\ out)
when the VFD reports 0 Hz output
.IP <name>.load-percentage\ (float,\ out)
from the VFD
.IP <name>.motor-RPM\ (float,\ out)
from the VFD
.IP <name>.output-current\ (float,\ out)
from the VFD
.IP <name>.output-voltage\ (float,\ out)
from the VFD
.IP <name>.power-factor\ (float,\ out)
from the VFD
.IP <name>.scale-frequency\ (float,\ out)
from the VFD
.IP <name>.speed-command\ (float,\ in)
speed sent to VFD in RPM It is an error to send a speed faster than the Motor Max RPM as set in the VFD
.IP <name>.spindle-fwd\ (bit,\ in)
1 for FWD and 0 for REV sent to VFD
.IP <name>.spindle-on\ (bit,\ in)
1 for ON and 0 for OFF sent to VFD, only on when running
.IP <name>.spindle-rev\ (bit,\ in)
1 for ON and 0 for OFF, only on when running
.IP <name>.status-1\ (s32,\ out)
Drive Status of the VFD (see the GS2 manual)
.IP <name>.status-2\ (s32,\ out)
Drive Status of the VFD (see the GS2 manual) Note that the value is a sum of all the bits that are on. So a 163 which means the drive is in the run mode is the sum of 3 (run) + 32 (freq set by serial) + 128 (operation set by serial).



== PARAMETERS
.IP <name>.error-count\ (s32,\ RW)
.IP <name>.loop-time\ (float,\ RW) 
how often the modbus is polled (default 0.1)
.IP <name>.nameplate-HZ\ (float,\ RW) 
Nameplate Hz of motor (default 60)
.IP <name>.nameplate-RPM\ (float,\ RW) 
Nameplate RPM of motor (default 1730)
.IP <name>.retval\ (s32,\ RW) 
the return value of an error in HAL
.IP <name>.tolerance\ (float,\ RW)
 speed tolerance (default 0.01)
.IP <name>.ack-delay\ (s32,\ RW)
 number of read/write cycles before checking at-speed (default 2)



== SEE ALSO
__GS2 Driver__ in the LinuxCNC documentation for a full description of the **GS2** syntax

__GS2 Examples__ in the LinuxCNC documentation for examples using the **GS2** component



== BUGS



== AUTHOR
John Thornton



== LICENSE
GPL
