#!/bin/bash -e

TEST_DIR=$(dirname $1)
cd $TEST_DIR

# Avoid false negatives:  This string should be present
grep -q 'test RAN' result

# Test:  This string should be absent
if grep -q 'duplicate O-word label' result; then
    exit 1
fi
