#!/bin/bash

TEST_DIR=$(dirname "$1")
cd "$TEST_DIR" || { echo "E: Could not change directory to '$TEST_DIR'"; exit 1; }

sed 's/-0\.000000/0.000000/g' <gcode-output >gcode-output.filtered && mv gcode-output.filtered gcode-output
diff -u expected-gcode-output gcode-output
