#!/bin/bash

TEST_DIR=$(dirname $1)
cd $TEST_DIR

sed 's/-0\.000000/0.000000/g' <gcode-output >gcode-output.filtered && mv gcode-output.filtered gcode-output
diff -u expected-gcode-output gcode-output
