= elbpcom(1)

== NAME

elbpcom - Communicate with Mesa ethernet cards

== SYNOPSIS

Common options: ::
*elbpcom* [**--ip=**_IP_] [**--port=**_PORT_] [**--timeout=**_TIMEOUT_] [**--space=**_MEMSPACE_] [**--size=**_TRANSFER_SIZE_]

Reading data: ::
*elbpcom* [_common options_] [*--info*] **--address=**_ADDRESS_ **--read=**_LENGTH_

Writing data: ::
*elbpcom* [_common options_] **--address=**_ADDRESS_ **--write=**_HEXDATA_

Read and decode memory space info area: ::
*elbpcom* [**--space=**_MEMSPACE_] *--read-info*

Sending arbitrary packets: ::
*elbpcom* [_common options_] _HEXDATA_

== DESCRIPTION

Read or write data from a Mesa ethernet card that uses the LBP16
protocol, such as the 7I80. This can be useful for performing certain
low-level tasks.

For more information about the meaning of each address space, see the
card documentation. Incorrect use of this utility can have negative
effects such as changing the board's IP address or even corrupting the
FPGA bitfile in the eeprom. For some tasks, such as updating FPGA
bitfiles and setting IP addresses, *mesaflash*(1) is a more appropriate
tool.

If not specified, the default values are

**--ip=**_192.168.1.121_ **--port=**_27181_ **--timeout=**_.2_ **--space=**_0_ **--size=**_0_

If the **--size** argument _TRANSFER_SIZE_ is 0, elbpcom will look up the
preferred transfer size of the space in the space's info area.

This example demonstrates reading the HOSTMOT2 identifying string from
the IDROM in space 0:

----
$ elbpcom --address 0x104 --read 8
> 82420401
< 484f53544d4f5432
      HOSTMOT2
----

First the request is shown in hex. Then the response (if any) is shown in hex.
Finally, the response is shown in ASCII, with "." replacing any non-ASCII characters.
This is similar to the following invocations of mesaflash:

----
$ ./mesaflash  --device 7i80 --rpo 0x104
54534F48
$ ./mesaflash  --device 7i80 --rpo 0x108
32544F4D
----

but notice its different treatment of byte order.

== SEE ALSO

mesaflash(1), hostmot2(9), hm2_eth(9),
https://www.mesanet.com[Mesa's documentation for the Anything I/O boards].
