= gscreen(1)

== NAME

gscreen - TOUCHY LinuxCNC Graphical User Interface

== SYNOPSIS

*gscreen* *-ini* _INIFILE_

== DESCRIPTION

*gscreen* is one of the Graphical User Interfaces (GUI) for LinuxCNC.
It gets run by the runscript usually.

== OPTIONS

_INIFILE_::
  The ini file is the main piece of an LinuxCNC configuration. It is not
  the entire configuration; there are various other files that go with
  it (NML files, HAL files, TBL files, VAR files). It is, however, the
  most important one, because it is the file that holds the
  configuration together. It can adjust a lot of parameters itself, but
  it also tells *LinuxCNC* which other files to load and use.

== SEE ALSO

linuxcnc(1)

Much more information about LinuxCNC and HAL is available in the
LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.

== BUGS

None known at this time.

== AUTHOR

This man page written by Andy Pugh, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2020 Andy Pugh.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
