= halcmd(1)

== NAME

halcmd - manipulate the LinuxCNC HAL from the command line

== SYNOPSIS

*halcmd* [_OPTIONS_] [_COMMAND_ [_ARG_]]

== DESCRIPTION

*halcmd* is used to manipulate the HAL (Hardware Abstraction Layer) from
the command line. *halcmd* can optionally read commands from a file,
allowing complex HAL configurations to be set up with a single command.

If the *readline* library is available when LinuxCNC is compiled, then
*halcmd* offers commandline editing and completion when running
interactively. Use the up arrow to recall previous commands, and press
tab to complete the names of items such as pins and signals.

== OPTIONS

*-I*::
  Before tearing down the realtime environment, run an interactive
  halcmd. *halrun* only. If *-I* is used, it must precede all other
  commandline arguments.
*-f* [_<file>_]::
  Ignore commands on command line, take input from _file_ instead. If
  _file_ is not specified, take input from _stdin_.
*-i* _<INI file>_::
  Use variables from the specified _INI file_ for substitutions. See
  *SUBSTITUTION* below.
*-k*::
  Keep going after failed command(s). The default is to stop and return
  failure if any command fails.
*-q*::
  display errors only (default)
*-Q*::
  display nothing, execute commands silently
*-s*::
  Script-friendly mode. In this mode, _show_ will not output titles for
  the items shown. Also, module names will be printed instead of ID
  codes in pin, param, and funct listings. Threads are printed on a
  single line, with the thread period, FP usage and name first, followed
  by all of the functions in the thread, in execution order. Signals are
  printed on a single line, with the type, value, and signal name first,
  followed by a list of pins connected to the signal, showing both the
  direction and the pin name.
*-R*::
  Release the HAL mutex. This is useful for recovering when a HAL
  component has crashed while holding the HAL mutex.
*-v*::
  display results of each command
*-V*::
  display lots of debugging junk
*-h* [_<command>_]::
  display a help screen and exit, displays extended help on _command_ if
  specified

== COMMANDS

Commands tell *halcmd* what to do. Normally *halcmd* reads a single
command from the command line and executes it. If the '*-f*' option is
used to read commands from a file, *halcmd* reads each line of the file
as a new command. Anything following '*#*' on a line is a comment.

*loadrt* _modname_::
  (_load_ __r__eal__t__ime module) Loads a realtime HAL module called _modname_.
  *halcmd* looks for the module in a directory specified at compile time.

In systems with kernel-based realtime support (e.g. RTAI), *halcmd*
calls the *linuxcnc_module_helper* to load realtime modules.
*linuxcnc_module_helper* is a setuid program and is compiled with a
whitelist of modules it is allowed to load. This is currently just a
list of *LinuxCNC*-related modules. The *linuxcnc_module_helper* execs
insmod, so return codes and error messages are those from insmod.
Administrators who wish to restrict which users can load these
*LinuxCNC*-related kernel modules can do this by setting the permissions
and group on *linuxcnc_module_helper* appropriately.

In systems with userspace-based realtime support (e.g. Preempt-RT) and
in systems without realtime support *halcmd* calls the *rtapi_app* which
creates the realtime environment (simulated realtime, on systems with no
userspace realtime support) if it did not yet exist, and then loads the
requested component with a call to *dlopen(3)*.

*unloadrt* _modname_::
  (_unload_ __r__eal__t__ime module) Unloads a realtime HAL module
  called _modname_. If _modname_ is "all", it will unload all currently
  loaded realtime HAL modules. *unloadrt* also works by execing
  *linuxcnc_module_helper* or *rtapi_app*, just like *loadrt*.
*loadusr* [_flags_] _unix-command_::
  (_load_ __Us__e__r__space component) Executes the given
  _unix-command_, usually to load a non-realtime component. _[flags]_
  may be one or more of:
  +
  * *-W* to wait for the component to become ready.
    The component is assumed to have the same name as the first argument of the command.
  * *-Wn name* to wait for the component, which will have the given name.
  * *-w* to wait for the program to exit
  * *-i* to ignore the program return value (with -w)
*waitusr* _name_::
  (_wait_ for __Us__e__r__space component) Waits for non-realtime
  component _name_ to disconnect from HAL (usually on exit). The
  component must already be loaded. Useful near the end of a HAL file to
  wait until the user closes some user interface component before
  cleaning up and exiting.
*unloadusr* _compname_::
  (_unload_ __Us__e__r__space component) Unloads a non-realtime
  component called _compname_. If _compname_ is "all", it will unload
  all non-realtime components. *unloadusr* works by sending SIGTERM to
  all non-realtime components.
*unload* _compname_::
  Unloads a non-realtime component or realtime module. If _compname_ is
  "all", it will unload all non-realtime components and realtime
  modules.
*newsig* _signame_ _type_::
  (OBSOLETE - use *net* instead) (_new_ __sig__nal) Creates a new HAL
  signal called _signame_ that may later be used to connect two or more
  HAL component pins. _type_ is the data type of the new signal, and
  must be one of "*bit*", "*s32*", "*u32*", or "*float*". Fails if a
  signal of the same name already exists.
*delsig* _signame_::
  (__del__ete __sig__nal) Deletes HAL signal _signame_. Any pins
  currently linked to the signal will be unlinked. Fails if _signame_
  does not exist.
*sets* _signame_ _value_::
  (_set_ __s__ignal) Sets the value of signal _signame_ to _value_.
  Fails if _signame_ does not exist, if it already has a writer, or if
  _value_ is not a legal value. Legal values depend on the signals's
  type.
*stype* _name_::
  (__s__ignal type) Gets the type of signal _name_. Fails if _name_ does
  not exist as a signal.
*gets* _signame_::
  (_get_ __s__ignal) Gets the value of signal _signame_. Fails if
  _signame_ does not exist.
*linkps* _pinname_ [_arrow_] _signame_::
  (OBSOLETE - use *net* instead) (_link_ __p__in to __s__ignal)
  Establishes a link between a HAL component pin _pinname_ and a HAL
  signal _signame_. Any previous link to _pinname_ will be broken.
  _arrow_ can be "*=>*", "*<=*", "*<=>*", or omitted. *halcmd* ignores
  arrows, but they can be useful in command files to document the
  direction of data flow. Arrows should not be used on the command line
  since the shell might try to interpret them. Fails if either _pinname_
  or _signame_ does not exist, or if they are not the same type type.
*linksp* _signame_ [_arrow_] _pinname_::
  (OBSOLETE - use *net* instead) (_link_ __s__ignal to __p__in) Works
  like *linkps* but reverses the order of the arguments. *halcmd* treats
  both link commands exactly the same. Use whichever you prefer.
*linkpp* _pinname1_ [_arrow_] _pinname2_::
  (OBSOLETE - use *net* instead) (_link_ __p__in to __p__in) Shortcut
  for *linkps* that creates the signal (named like the first pin), then
  links them both to that signal. *halcmd* treats this just as if it
  were: *halcmd* *newsig* pinname1 *halcmd* *linksp* pinname1 pinname1
  *halcmd* *linksp* pinname1 pinname2
*net* _signame_ _pinname_ _..._::
  Create _signname_ to match the type of _pinname_ if it does not yet
  exist. Then, link _signame_ to each _pinname_ in turn. Arrows may be
  used as in *linkps*. When linking a pin to a signal for the first
  time, the signal value will inherit the pin's default value.
*unlinkp* _pinname_::
  (_unlink_ __p__in) Breaks any previous link to _pinname_. Fails if
  _pinname_ does not exist. An unlinked pin will retain the last value
  of the signal it was linked to.
*setp* _name_ _value_::
  (_set_ __p__arameter or __p__in) Sets the value of parameter or pin
  _name_ to _value_. Fails if _name_ does not exist as a pin or
  parameter, if it is a parameter that is not writable, if it is a pin
  that is an output, if it is a pin that is already attached to a
  signal, or if _value_ is not a legal value. Legal values depend on the
  type of the pin or parameter. If a pin and a parameter both exist with
  the given name, the parameter is acted on.
_paramname_ *=* _value_::
_pinname_ *=* _value_::
  Identical to *setp*. This alternate form of the command may be more
  convenient and readable when used in a file.
*ptype* _name_::
  (__p__arameter or __p__in _type_) Gets the type of parameter or pin
  _name_. Fails if _name_ does not exist as a pin or parameter. If a pin
  and a parameter both exist with the given name, the parameter is acted
  on.
*getp* _name_::
  (_get_ __p__arameter or __p__in) Gets the value of parameter or pin
  _name_. Fails if _name_ does not exist as a pin or parameter. If a pin
  and a parameter both exist with the given name, the parameter is acted
  on.
*addf* _functname_ _threadname_::
  (_add_ __f__unction) Adds function _functname_ to realtime thread
  _threadname_. _functname_ will run after any functions that were
  previously added to the thread. Fails if either _functname_ or
  _threadname_ does not exist, or if they are incompatible.
*delf* _functname_ _threadname_::
  (__del__ete __f__unction) Removes function _functname_ from realtime
  thread _threadname_. Fails if either _functname_ or _threadname_ does
  not exist, or if _functname_ is not currently part of _threadname_.
*start*::
  Starts execution of realtime threads. Each thread periodically calls
  all of the functions that were added to it with the *addf* command, in
  the order in which they were added.
*stop*::
  Stops execution of realtime threads. The threads will no longer call
  their functions.
*show* [_item_]::
  Prints HAL items to _stdout_ in human readable format. _item_ can be
  one of "*comp*" (components), "*pin*", "*sig*" (signals), "*param*"
  (parameters), "*funct*" (functions), "*thread*", or "*alias*". The
  type "*all*" can be used to show matching items of all the preceding
  types. If _item_ is omitted, *show* will print everything.
*save* [_item_]::
  Prints HAL items to _stdout_ in the form of HAL commands. These
  commands can be redirected to a file and later executed using *halcmd
  -f* to restore the saved configuration. _item_ can be one of the
  following:

"*comp*" generates a *loadrt* command for realtime component.

"*alias*" generates an *alias* command for each pin or parameter alias
pairing

"*sig*" (or "*signal*") generates a *newsig* command for each signal,
and "*sigu*" generates a *newsig* command for each unlinked signal (for
use with *netl* and *netla*).

"*link*" and "*linka*" both generate *linkps* commands for each link.
(*linka* includes arrows, while *link* does not.)

"*net*" and "*neta*" both generate one *newsig* command for each signal,
followed by *linksp* commands for each pin linked to that signal.
(*neta* includes arrows.)

"*netl*" generates one *net* command for each linked signal, and
"*netla*" (or "*netal*") generates a similar command using arrows.

"*param*" (or "*parameter*) "generates one *setp* command for each parameter.

"*thread*" generates one *addf* command for each function in each
realtime thread.

"*unconnectedinpins*" generates a setp command for each unconnected HAL input pin.

If _item_ is *allu*), *save* does the equivalent of *comp*, *alias*, *sigu*, *netla*, *param*, *thread*, and *unconnectedinpins*.

If _item_ is omitted (or *all*), *save* does the equivalent of *comp*, *alias*, *sigu*, *netla*, *param*, and *thread*.

*source* _filename.hal_::
  Execute the commands from _filename.hal_.
*alias* _type_ _name_ _alias_::
  Assigns "*alias*" as a second name for the pin or parameter "name".
  For most operations, an alias provides a second name that can be used
  to refer to a pin or parameter, both the original name and the alias
  will work. "type" must be *pin* or *param*. "name" must be an existing
  name or *alias* of the specified type. Note that the "show" command
  will only show the aliased name, but the original name is still valid
  to use in HAL. The original names can still be seen with "show all" or
  "show alias" Existing nets will be preserved when a pin name is aliased.
*unalias* _type_ _alias_::
  Removes any alias from the pin or parameter alias. "type" must be
  *pin* or *param* "alias" must be an existing name or *alias* of the
  specified type.
*list* _type_ [_pattern_]::
  Prints the names of HAL items of the specified type. 'type' is
  '*comp*', '*pin*', '*sig*', '*param*', '*funct*', or '*thread*'. If
  'pattern' is specified it prints only those names that match the
  pattern, which may be a 'shell glob'. For '*sig*', '*pin*' and
  '*param*', the first pattern may be -t**datatype** where datatype is
  the data type (e.g., 'float') in this case, the listed pins, signals,
  or parameters are restricted to the given data type Names are printed
  on a single line, space separated.
*print* [_message_]::
  Prints the filename, linenumber and an optional message. wrap the
  message in quotes if it has spaces.
*lock* [__all__|__tune__|__none__]::
  Locks HAL to some degree. none - no locking done. tune - some tuning
  is possible (*setp* & such). all - HAL completely locked.
*unlock* [__all__|__tune__]::
  Unlocks HAL to some degree. tune - some tuning is possible (*setp* &
  such). all - HAL completely unlocked.
*status* [_type_]::
  Prints status info about HAL. 'type' is '*lock*', '*mem*', or '*all*'.
  If 'type' is omitted, it assumes '*all*'.
*debug* [_level_]::
  Sets the rtapi messaging level (see man3 rtapi_set_msg_level).
*help* [_command_]::
  Give help information for command. If 'command' is omitted, list
  command and brief description.

== SUBSTITUTION

After a command is read but before it is executed, several types of
variable substitution take place.

=== Environment Variables

Environment variables have the following formats:

____
*$ENVVAR* followed by end-of-line or whitespace

*$(ENVVAR)*
____

=== INI file variables

INI file variables are available only when an INI file was specified
with the halcmd *-i* flag. They have the following formats:

____
*[SECTION]VAR* followed by end-of-line or whitespace

*[SECTION](VAR)*
____

== LINE CONTINUATION

The backslash character (*\*) may be used to indicate the line is
extended to the next line. The backslash character must be the last
character before the newline.

== BUGS

None known at this time.

== AUTHOR

Original version by John Kasunich, as part of the LinuxCNC project. Now
includes major contributions by several members of the project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2003 John Kasunich.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

== SEE ALSO

halrun(1) -- a convenience script to start a realtime environment,
process a HAL or a .tcl file, and optionally start an interactive
command session using *halcmd* (described here) or haltcl(1).
