= halreport(1)

== NAME

halreport - creates a report on the status of the HAL

== SYNOPSIS

*halreport* [_outfilename_]

== DESCRIPTION

*halreport*

. supports components made by halcompile and numerous legacy components
. Known unhandled components:
+
  at_pid:: naming conflicts with pid, seldom used
  boss_plc:: no manpage or docs (any users?)
  watchdog:: seldom used (no users in-tree)
. deprecated/obsolete components counter supply

Identificaion of functions used according to pin name. Default handling
works for components that:
. use names=|count= (.comp components created with halcompile)
. have a *single* function

Full docs: http://linuxcnc.org/docs/html/hal/tools.html#_halreport

== SEE ALSO

linuxcnc(1)

Much more information about LinuxCNC and HAL is available in the
LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.

== BUGS

None known at this time.

== AUTHOR

This man page written by Andy Pugh, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2020 Andy Pugh.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
