= halshow(1)

== NAME

halshow - Show HAL parameters, pins and signals

== SYNOPSIS

*halshow* [_options_] [_watchfile_]

== OPTIONS

--help:: Displays the help

--fformat _format_string_for_float_:: Float format string

--iformat _format_string_for_int_:: Integer format string

For format see https://www.tcl.tk/man/tcl8.6.11/TclCmd/format.html[]

Example: "%.5f" displays a float with 5 digits right of the decimal point.

--noprefs:: Don't use preference file to save settings

== DESCRIPTION

The program *halshow* creates a GUI interface to view and interact with a running HAL session.

== SEE ALSO

linuxcnc(1)

Halshow is documented in the PDF and HTML documentation much more completely than is possible in a manpage:
https://linuxcnc.org/docs/html/hal/halshow.html[]

== HISTORY

LinuxCNC 2.9::
 - Added buttons for pin/parameter/signal manipulation.
 - Added menu entries for setting update interval, adding manually.
 - Added right-click menu for copy, set, unlink pin and remove from view.
 - Added button to expand/collapse the tree view
 - Added search entry

== BUGS

None known at this time.

== AUTHOR

Raymond E. Henry

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2020 Andy Pugh.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
