= inivar(1)

== NAME

inivar - Query an INI file

== SYNOPSIS

*inivar -var <variable> \{-sec _<section>_} \{-ini _<INI_ file>}*

== DESCRIPTION

*inivar* does stuff for LinuxCNC

Prints to stdout the INI file result of a variable-in-section search,
useful for scripts that want to pick things out of INI files.

syntax: inivar -var <variable> \{-sec <section>} \{-ini _<INI file>_}

Uses emc.ini as default. <variable> needs to be supplied. If <section>
is omitted, first instance of <variable> will be looked for in any
section. Otherwise only a match of the variable in <section> will be
returned.

== SEE ALSO

*LinuxCNC(1)*

Much more information about LinuxCNC and HAL is available in the
LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.

== BUGS

None known at this time.

== AUTHOR

This man page written by andypugh, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues

== COPYRIGHT

Copyright © 2020 andypugh. +
This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
