= linuxcnclcd(1)

== NAME

linuxcnclcd - LinuxCNC Graphical User Interface for LCD character display

== SYNOPSIS

*linuxcnclcd* *-ini* _<INI file>_

== DESCRIPTION

*linuxcnclcd* is one of the Graphical User Interfaces (GUI) for LinuxCNC.
It gets typically run by the runscript. Linuxcnclcd is designed to run on
a 4 x 20 LCD character display. It is not clear if it has ever worked.

== OPTIONS

_INI file_::
  The INI file is the main piece of an LinuxCNC configuration.
  It is not the entire configuration; there are various other
  files that go with it (NML files, HAL files, TBL files, VAR files).
  It is, however, the most important one, because it is the file that holds the
  configuration together. It can adjust a lot of parameters itself, but
  it also tells *LinuxCNC* which other files to load and use.

== SEE ALSO

linuxcnc(1)

Much more information about LinuxCNC and HAL is available in the
LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.

== BUGS

None known at this time.

== AUTHOR

This man page written by Andy Pugh, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2020 Andy Pugh.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
