= scorbot-er-3(1)

== NAME

scorbot-er-3 - to link the Intellitek Scorbot educational robot to
LinuxCNC

== DESCRIPTION

*scorbot-er-3* is a non-realtime component that interfaces the control
box of a Scorbot ER-3 robot arm to the LinuxCNC HAL.

Joint 0: rotation around the base Joint 1: shoulder Joint 2: elbow Joint
3: wrist (+ is wrist up & rotate hand) Joint 4: wrist (+ is wrist down &
rotate hand) Joint 5: unused Joint 6: unused Joint 7: hand open/close (+
is close)

== SEE ALSO

linuxcnc(1)

Much more information about LinuxCNC and HAL is available in the
LinuxCNC and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.

== BUGS

None known at this time.

== AUTHOR

This man page written by Andy Pugh, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues.

== COPYRIGHT

Copyright © 2020 Andy Pugh.

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
