#!/bin/bash
#
# given a list of protobuf definition files (.proto),
#
# extract all message definition names and generate
# PB_MESSAGE(stringname, symbol) to serve as a
# include file fragment

echo "// generated " `date`
grep '^\s*message' $*  | \
sed -e 's/:[ \t]*message[ \t]*/:/'| \
sed -e 's/[ \t]*.$//'   | tr ':' ' ' | \
while read File Message ; do
    echo "PB_MESSAGE( \""$Message\"", "$Message");  // "$File
done
