package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientGo writes a Go REST client package for calling the API
// over HTTP/JSON. This is for external Go programs (like halcmd replacement).
func GenerateClientGo(w io.Writer, api *ast.API, packageName string) error {
	g := &clientGoGen{w: w, api: api, pkg: packageName}
	return g.generate()
}

type clientGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *clientGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientGoGen) generate() error {
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitClient()
	g.emitClientMethods()
	return g.err
}

// --- Header ---

func (g *clientGoGen) emitHeader() {
	g.printf("// Code generated by gmicompile --client-go - DO NOT EDIT.\n")
	g.printf("//\n")
	g.printf("// REST client for %s API v%d\n\n", g.api.Name, g.api.Version)
	g.printf("package %s\n\n", g.pkg)

	g.printf("import (\n")
	g.printf("\t\"bytes\"\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"fmt\"\n")
	g.printf("\t\"io\"\n")
	g.printf("\t\"net/http\"\n")
	g.printf("\t\"net/url\"\n")
	g.printf("\t\"strings\"\n")
	g.printf(")\n\n")

	// Suppress unused import warnings
	g.printf("var (\n")
	g.printf("\t_ = bytes.NewReader\n")
	g.printf("\t_ = json.Marshal\n")
	g.printf("\t_ = fmt.Sprintf\n")
	g.printf("\t_ = io.ReadAll\n")
	g.printf("\t_ = url.QueryEscape\n")
	g.printf("\t_ = strings.Replace\n")
	g.printf(")\n\n")
}

// --- Constants ---

func (g *clientGoGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	g.printf("const (\n")
	for _, c := range g.api.Consts {
		g.printf("\t%s = %d\n", c.Name, c.Value)
	}
	g.printf(")\n\n")
}

// --- Enums ---

func (g *clientGoGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		goName := toPascalCase(e.Name)
		g.printf("type %s int32\n\n", goName)
		g.printf("const (\n")
		for _, v := range e.Values {
			g.printf("\t%s_%s %s = %d\n", goName, v.Name, goName, v.Value)
		}
		g.printf(")\n\n")
	}
}

// --- Types ---

func (g *clientGoGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		g.printf("type %s struct {\n", goName)
		for _, f := range t.Fields {
			fieldName := toPascalCase(f.Name)
			fieldType := g.toGoType(f.Type)
			jsonTag := f.Name
			omit := ""
			if f.Type.Nullable {
				omit = ",omitempty"
			}
			g.printf("\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, jsonTag, omit)
		}
		g.printf("}\n\n")
	}
}

// --- Client Struct ---

func (g *clientGoGen) emitClient() {
	clientName := toPascalCase(g.api.Name) + "Client"

	g.printf("// --- Client ---\n\n")

	// Error type
	g.printf("// APIError represents an error response from the server.\n")
	g.printf("type APIError struct {\n")
	g.printf("\tStatusCode int\n")
	g.printf("\tMessage    string\n")
	g.printf("}\n\n")

	g.printf("func (e *APIError) Error() string {\n")
	g.printf("\treturn fmt.Sprintf(\"%%s (HTTP %%d)\", e.Message, e.StatusCode)\n")
	g.printf("}\n\n")

	// Client struct
	g.printf("// %s is a REST client for the %s API.\n", clientName, g.api.Name)
	g.printf("type %s struct {\n", clientName)
	g.printf("\tbaseURL string\n")
	g.printf("\thttp    *http.Client\n")
	g.printf("}\n\n")

	// Constructor
	g.printf("// New%s creates a new client.\n", clientName)
	g.printf("// baseURL should be the server address, e.g. \"http://localhost:8080\".\n")
	g.printf("// The API prefix \"/api/v1/%s\" is appended automatically.\n", g.api.Prefix)
	g.printf("func New%s(baseURL string) *%s {\n", clientName, clientName)
	g.printf("\treturn &%s{\n", clientName)
	g.printf("\t\tbaseURL: strings.TrimSuffix(baseURL, \"/\") + \"/api/v1/%s\",\n", g.api.Prefix)
	g.printf("\t\thttp:    &http.Client{},\n")
	g.printf("\t}\n")
	g.printf("}\n\n")

	// WithHTTPClient option
	g.printf("// WithHTTPClient sets a custom HTTP client (e.g., for timeouts or TLS).\n")
	g.printf("func (c *%s) WithHTTPClient(hc *http.Client) *%s {\n", clientName, clientName)
	g.printf("\tc.http = hc\n")
	g.printf("\treturn c\n")
	g.printf("}\n\n")

	// Internal request helper
	g.printf("func (c *%s) doRequest(method, path string, body interface{}, result interface{}) error {\n", clientName)
	g.printf("\turl := c.baseURL + path\n\n")

	g.printf("\tvar bodyReader io.Reader\n")
	g.printf("\tif body != nil {\n")
	g.printf("\t\tdata, err := json.Marshal(body)\n")
	g.printf("\t\tif err != nil {\n")
	g.printf("\t\t\treturn fmt.Errorf(\"marshal request: %%w\", err)\n")
	g.printf("\t\t}\n")
	g.printf("\t\tbodyReader = bytes.NewReader(data)\n")
	g.printf("\t}\n\n")

	g.printf("\treq, err := http.NewRequest(method, url, bodyReader)\n")
	g.printf("\tif err != nil {\n")
	g.printf("\t\treturn fmt.Errorf(\"create request: %%w\", err)\n")
	g.printf("\t}\n")
	g.printf("\tif body != nil {\n")
	g.printf("\t\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	g.printf("\t}\n")
	g.printf("\treq.Header.Set(\"Accept\", \"application/json\")\n\n")

	g.printf("\tresp, err := c.http.Do(req)\n")
	g.printf("\tif err != nil {\n")
	g.printf("\t\treturn fmt.Errorf(\"do request: %%w\", err)\n")
	g.printf("\t}\n")
	g.printf("\tdefer resp.Body.Close()\n\n")

	g.printf("\trespBody, err := io.ReadAll(resp.Body)\n")
	g.printf("\tif err != nil {\n")
	g.printf("\t\treturn fmt.Errorf(\"read response: %%w\", err)\n")
	g.printf("\t}\n\n")

	g.printf("\tif resp.StatusCode >= 400 {\n")
	g.printf("\t\tvar errResp struct {\n")
	g.printf("\t\t\tError string `json:\"error\"`\n")
	g.printf("\t\t}\n")
	g.printf("\t\tif json.Unmarshal(respBody, &errResp) == nil && errResp.Error != \"\" {\n")
	g.printf("\t\t\treturn &APIError{StatusCode: resp.StatusCode, Message: errResp.Error}\n")
	g.printf("\t\t}\n")
	g.printf("\t\treturn &APIError{StatusCode: resp.StatusCode, Message: string(respBody)}\n")
	g.printf("\t}\n\n")

	g.printf("\tif result != nil && len(respBody) > 0 {\n")
	g.printf("\t\tif err := json.Unmarshal(respBody, result); err != nil {\n")
	g.printf("\t\t\treturn fmt.Errorf(\"unmarshal response: %%w\", err)\n")
	g.printf("\t\t}\n")
	g.printf("\t}\n")
	g.printf("\treturn nil\n")
	g.printf("}\n\n")
}

// --- Client Methods ---

func (g *clientGoGen) emitClientMethods() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// --- API Methods ---\n\n")

	clientName := toPascalCase(g.api.Name) + "Client"

	for _, fn := range g.api.Funcs {
		g.emitClientMethod(clientName, fn)
	}
}

func (g *clientGoGen) emitClientMethod(clientName string, fn ast.Func) {
	methodName := toPascalCase(fn.Name)

	// Doc comment
	if fn.Doc != "" {
		g.printf("// %s %s\n", methodName, fn.Doc)
	} else {
		g.printf("// %s calls %s %s\n", methodName, fn.Method, fn.Path)
	}

	// Signature
	params := g.methodParams(fn)
	retType := g.methodReturn(fn)
	g.printf("func (c *%s) %s(%s) %s {\n", clientName, methodName, params, retType)

	// Build path with substitutions
	path := fn.Path
	pathParams := extractPathParams(path)

	// Path parameter substitution
	if len(pathParams) > 0 {
		g.printf("\tpath := %q\n", path)
		for _, pp := range pathParams {
			paramName := toLowerCamel(pp)
			g.printf("\tpath = strings.Replace(path, \"{%s}\", url.PathEscape(%s), 1)\n", pp, paramName)
		}
	} else {
		g.printf("\tpath := %q\n", path)
	}

	// Query parameters (for GET/DELETE with non-path params)
	queryParams := g.queryParams(fn, pathParams)
	if len(queryParams) > 0 && (fn.Method == "GET" || fn.Method == "DELETE" || fn.Method == "") {
		g.printf("\tquery := url.Values{}\n")
		for _, qp := range queryParams {
			paramName := toLowerCamel(qp.Name)
			if qp.Type.Nullable {
				g.printf("\tif %s != nil {\n", paramName)
				if qp.Type.Name == "string" {
					g.printf("\t\tquery.Set(%q, *%s)\n", qp.Name, paramName)
				} else {
					g.printf("\t\tquery.Set(%q, fmt.Sprintf(\"%%v\", *%s))\n", qp.Name, paramName)
				}
				g.printf("\t}\n")
			} else {
				if qp.Type.Name == "string" {
					g.printf("\tquery.Set(%q, %s)\n", qp.Name, paramName)
				} else {
					g.printf("\tquery.Set(%q, fmt.Sprintf(\"%%v\", %s))\n", qp.Name, paramName)
				}
			}
		}
		g.printf("\tif len(query) > 0 {\n")
		g.printf("\t\tpath += \"?\" + query.Encode()\n")
		g.printf("\t}\n")
	}

	// Request body (for POST/PUT/PATCH with non-path params)
	bodyParams := g.queryParams(fn, pathParams) // same logic - non-path params
	var bodyVar string
	if len(bodyParams) > 0 && (fn.Method == "POST" || fn.Method == "PUT" || fn.Method == "PATCH") {
		g.printf("\tbody := struct {\n")
		for _, bp := range bodyParams {
			fieldName := toPascalCase(bp.Name)
			fieldType := g.toGoType(bp.Type)
			jsonTag := bp.Name
			omit := ""
			if bp.Type.Nullable {
				omit = ",omitempty"
			}
			g.printf("\t\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, jsonTag, omit)
		}
		g.printf("\t}{\n")
		for _, bp := range bodyParams {
			fieldName := toPascalCase(bp.Name)
			paramName := toLowerCamel(bp.Name)
			g.printf("\t\t%s: %s,\n", fieldName, paramName)
		}
		g.printf("\t}\n")
		bodyVar = "body"
	} else {
		bodyVar = "nil"
	}

	// HTTP method
	method := fn.Method
	if method == "" {
		method = "GET"
	}

	// Make request
	if fn.Return == nil {
		g.printf("\treturn c.doRequest(%q, path, %s, nil)\n", method, bodyVar)
	} else {
		retGoType := g.toGoType(*fn.Return)
		if fn.Return.Kind == ast.TypeSlice {
			g.printf("\tvar result %s\n", retGoType)
			g.printf("\terr := c.doRequest(%q, path, %s, &result)\n", method, bodyVar)
			g.printf("\treturn result, err\n")
		} else if fn.Return.Kind == ast.TypeNamed {
			g.printf("\tvar result %s\n", retGoType)
			g.printf("\terr := c.doRequest(%q, path, %s, &result)\n", method, bodyVar)
			g.printf("\tif err != nil {\n")
			g.printf("\t\treturn nil, err\n")
			g.printf("\t}\n")
			g.printf("\treturn &result, nil\n")
		} else {
			// Primitive return
			g.printf("\tvar result %s\n", retGoType)
			g.printf("\terr := c.doRequest(%q, path, %s, &result)\n", method, bodyVar)
			g.printf("\treturn result, err\n")
		}
	}

	g.printf("}\n\n")
}

func (g *clientGoGen) methodParams(fn ast.Func) string {
	parts := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		goType := g.toGoType(p.Type)
		parts = append(parts, fmt.Sprintf("%s %s", toLowerCamel(p.Name), goType))
	}
	return strings.Join(parts, ", ")
}

func (g *clientGoGen) methodReturn(fn ast.Func) string {
	if fn.Return == nil {
		return "error"
	}
	retType := g.toGoType(*fn.Return)
	if fn.Return.Kind == ast.TypeNamed {
		return fmt.Sprintf("(*%s, error)", retType)
	}
	return fmt.Sprintf("(%s, error)", retType)
}

// queryParams returns parameters that are not in the path
func (g *clientGoGen) queryParams(fn ast.Func, pathParams []string) []ast.Param {
	pathSet := make(map[string]bool)
	for _, pp := range pathParams {
		pathSet[pp] = true
	}
	result := make([]ast.Param, 0)
	for _, p := range fn.Params {
		if !pathSet[p.Name] {
			result = append(result, p)
		}
	}
	return result
}

func (g *clientGoGen) toGoType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToGoType(t.Name)
		if t.Nullable && t.Name != "string" {
			return "*" + base
		}
		if t.Nullable && t.Name == "string" {
			return "*string"
		}
		return base
	case ast.TypeNamed:
		return toPascalCase(t.Name)
	case ast.TypeSlice:
		return "[]" + g.toGoType(*t.Elem)
	case ast.TypeArray:
		return fmt.Sprintf("[%d]%s", t.ArrayLen, g.toGoType(*t.Elem))
	}
	return "interface{}"
}

// extractPathParams extracts parameter names from path like "/pin/{name}"
func extractPathParams(path string) []string {
	var params []string
	for {
		start := strings.Index(path, "{")
		if start < 0 {
			break
		}
		end := strings.Index(path[start:], "}")
		if end < 0 {
			break
		}
		params = append(params, path[start+1:start+end])
		path = path[start+end+1:]
	}
	return params
}
