// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientGoInternal writes a Go cgo file that provides a typed Go client
// for calling C module APIs directly (gomod-to-cmod pattern). This file:
//   - Includes the C header via cgo preamble
//   - Generates static C call wrappers for function pointers
//   - Generates Go types matching the C types
//   - Generates C↔Go struct converters
//   - Generates a typed client struct with Go methods
//   - Generates a GetXxxClient() factory that looks up the registry
//
// This is different from --client-go which generates a REST client.
// This generates an internal direct-call client via cgo.
func GenerateClientGoInternal(w io.Writer, api *ast.API, packageName, headerFile string) error {
	g := &clientGoInternalGen{w: w, api: api, pkg: packageName, header: headerFile}
	return g.generate()
}

type clientGoInternalGen struct {
	w      io.Writer
	api    *ast.API
	pkg    string
	header string // C header filename, e.g. "kins_api.h"
	err    error
}

func (g *clientGoInternalGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientGoInternalGen) generate() error {
	g.emitCgoPreamble()
	g.emitImports()
	g.emitConstants()
	g.emitGoTypes()
	g.emitCToGoConverters()
	g.emitGoToCConverters()
	g.emitClient()
	g.emitClientMethods()
	g.emitGetClient()
	return g.err
}

// --- cgo Preamble ---

func (g *clientGoInternalGen) emitCgoPreamble() {
	g.printf("// Code generated by gmicompile --client-go-internal - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("//\n")
	g.printf("// Internal cgo client for %s API v%d (gomod-to-cmod calls)\n\n", g.api.Name, g.api.Version)
	g.printf("package %s\n\n", g.pkg)

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", strings.ToUpper(g.api.Name))
	g.printf("#include \"%s\"\n", g.header)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")
	g.printf("\n")

	// Static call wrappers — cgo cannot call C function pointers directly
	for _, fn := range g.api.Funcs {
		g.emitCallWrapper(fn)
	}

	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

func (g *clientGoInternalGen) emitCallWrapper(fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	wrapperName := fmt.Sprintf("call_%s_%s", apiName, fnSnake)
	fnType := fmt.Sprintf("%s_%s_fn", apiName, fnSnake)

	// Build return type
	retCType := "int32_t" // errno-style return for void functions
	if fn.Return != nil {
		retCType = toCTypeForAPI(apiName, *fn.Return)
	}

	// Build parameter list
	params := []string{fmt.Sprintf("%s fn", fnType)}
	args := []string{}

	for _, p := range fn.Params {
		name := p.Name
		cDecl := g.cParamDecl(apiName, p)
		params = append(params, cDecl)
		args = append(args, name)
		if p.Type.Kind == ast.TypeSlice {
			args = append(args, name+"_len")
		}
	}

	// Static wrapper function
	g.printf("static %s %s(%s) {\n", retCType, wrapperName, strings.Join(params, ", "))
	if fn.Return != nil {
		g.printf("    return fn(%s);\n", strings.Join(args, ", "))
	} else {
		g.printf("    fn(%s);\n", strings.Join(args, ", "))
	}
	g.printf("}\n\n")
}

func (g *clientGoInternalGen) cParamDecl(apiName string, p ast.Param) string {
	name := p.Name

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.ByRef {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("%s %s", cType, name)

	case ast.TypeNamed:
		cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
		if g.isEnum(p.Type.Name) {
			return fmt.Sprintf("%s %s", cType, name)
		}
		if p.ByRef {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("const %s *%s", cType, name)

	case ast.TypeSlice:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		if p.ByRef {
			return fmt.Sprintf("%s *%s, size_t %s_len", elemCType, name, name)
		}
		return fmt.Sprintf("const %s *%s, size_t %s_len", elemCType, name, name)

	case ast.TypeArray:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		if p.ByRef {
			return fmt.Sprintf("%s %s[%d]", elemCType, name, p.Type.ArrayLen)
		}
		return fmt.Sprintf("const %s %s[%d]", elemCType, name, p.Type.ArrayLen)
	}

	return fmt.Sprintf("void *%s", name)
}

func (g *clientGoInternalGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

// --- Imports ---

func (g *clientGoInternalGen) emitImports() {
	g.printf("import (\n")
	g.printf("\t\"syscall\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	g.printf("var _ = syscall.EINVAL\n")
	g.printf("var _ unsafe.Pointer\n\n")
}

// --- Constants ---

func (g *clientGoInternalGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	g.printf("const (\n")
	for _, c := range g.api.Consts {
		g.printf("\t%s = %d\n", c.Name, c.Value)
	}
	g.printf(")\n\n")
}

// --- Go Types ---

func (g *clientGoInternalGen) emitGoTypes() {
	// Enums
	if len(g.api.Enums) > 0 {
		g.printf("// --- Enums ---\n\n")
		for _, e := range g.api.Enums {
			goName := toPascalCase(e.Name)
			g.printf("type %s int32\n\n", goName)
			g.printf("const (\n")
			for _, v := range e.Values {
				g.printf("\t%s %s = %d\n", v.Name, goName, v.Value)
			}
			g.printf(")\n\n")
		}
	}

	// Struct types
	if len(g.api.Types) > 0 {
		g.printf("// --- Types ---\n\n")
		for _, t := range g.api.Types {
			goName := toPascalCase(t.Name)
			g.printf("type %s struct {\n", goName)
			for _, f := range t.Fields {
				fieldName := toPascalCase(f.Name)
				fieldType := g.toGoType(f.Type)
				g.printf("\t%s %s\n", fieldName, fieldType)
			}
			g.printf("}\n\n")
		}
	}
}

func (g *clientGoInternalGen) toGoType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToGoType(t.Name)
		if t.Nullable && t.Name != "string" {
			return "*" + base
		}
		if t.Nullable {
			return "*string"
		}
		return base
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			return toPascalCase(t.Name)
		}
		return toPascalCase(t.Name)
	case ast.TypeSlice:
		return "[]" + g.toGoType(*t.Elem)
	case ast.TypeArray:
		return fmt.Sprintf("[%d]%s", t.ArrayLen, g.toGoType(*t.Elem))
	}
	return "interface{}"
}

// --- CToGo Converters ---

func (g *clientGoInternalGen) emitCToGoConverters() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- CToGo Converters ---\n\n")
	apiName := g.api.Name

	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", apiName, toSnakeCase(t.Name))
		funcName := toLowerCamel(t.Name) + "FromC"

		g.printf("func %s(src *%s) %s {\n", funcName, cType, goName)
		g.printf("\treturn %s{\n", goName)
		for _, f := range t.Fields {
			fieldName := toPascalCase(f.Name)
			cFieldName := cgoFieldAccess(f.Name)
			g.printf("\t\t%s: %s,\n", fieldName, g.cToGoFieldConv(f.Type, "src."+cFieldName))
		}
		g.printf("\t}\n")
		g.printf("}\n\n")
	}
}

func (g *clientGoInternalGen) cToGoFieldConv(t ast.TypeRef, expr string) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "string":
			return fmt.Sprintf("C.GoString(%s)", expr)
		case "bool":
			return fmt.Sprintf("%s != 0", expr)
		case "f32":
			return fmt.Sprintf("float32(%s)", expr)
		case "f64":
			return fmt.Sprintf("float64(%s)", expr)
		default:
			return fmt.Sprintf("%s(%s)", primitiveToGoType(t.Name), expr)
		}
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			return fmt.Sprintf("%s(%s)", toPascalCase(t.Name), expr)
		}
		return fmt.Sprintf("%sFromC(&%s)", toLowerCamel(t.Name), expr)
	case ast.TypeArray:
		// Handle array conversion
		return fmt.Sprintf("/* array conversion for %s */", expr)
	}
	return expr
}

// --- GoToC Converters ---

func (g *clientGoInternalGen) emitGoToCConverters() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- GoToC Converters ---\n\n")
	apiName := g.api.Name

	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", apiName, toSnakeCase(t.Name))
		funcName := toLowerCamel(t.Name) + "ToC"

		g.printf("func %s(src *%s, dst *%s) {\n", funcName, goName, cType)
		for _, f := range t.Fields {
			fieldName := toPascalCase(f.Name)
			cFieldName := cgoFieldAccess(f.Name)
			g.printf("\tdst.%s = %s\n", cFieldName, g.goToCFieldConv(f.Type, "src."+fieldName))
		}
		g.printf("}\n\n")
	}
}

func (g *clientGoInternalGen) goToCFieldConv(t ast.TypeRef, expr string) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "string":
			return fmt.Sprintf("C.CString(%s)", expr)
		case "bool":
			return fmt.Sprintf("C.bool(%s)", expr)
		case "f32":
			return fmt.Sprintf("C.float(%s)", expr)
		case "f64":
			return fmt.Sprintf("C.double(%s)", expr)
		case "i8":
			return fmt.Sprintf("C.int8_t(%s)", expr)
		case "i16":
			return fmt.Sprintf("C.int16_t(%s)", expr)
		case "i32":
			return fmt.Sprintf("C.int32_t(%s)", expr)
		case "i64":
			return fmt.Sprintf("C.int64_t(%s)", expr)
		case "u8":
			return fmt.Sprintf("C.uint8_t(%s)", expr)
		case "u16":
			return fmt.Sprintf("C.uint16_t(%s)", expr)
		case "u32":
			return fmt.Sprintf("C.uint32_t(%s)", expr)
		case "u64":
			return fmt.Sprintf("C.uint64_t(%s)", expr)
		}
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
			return fmt.Sprintf("%s(%s)", cType, expr)
		}
		// For struct types, need nested conversion
		return fmt.Sprintf("/* nested struct %s */", expr)
	}
	return expr
}

// --- Client Struct ---

func (g *clientGoInternalGen) emitClient() {
	clientName := toPascalCase(g.api.Name) + "Client"
	cbsType := fmt.Sprintf("C.%s_callbacks_t", g.api.Name)

	g.printf("// --- Client ---\n\n")

	g.printf("// %s provides typed Go access to %s API callbacks.\n", clientName, g.api.Name)
	g.printf("// Use Get%s() to obtain an instance from the registry.\n", clientName)
	g.printf("type %s struct {\n", clientName)
	g.printf("\tcbs *%s\n", cbsType)
	g.printf("}\n\n")
}

// --- Client Methods ---

func (g *clientGoInternalGen) emitClientMethods() {
	if len(g.api.Funcs) == 0 {
		return
	}

	clientName := toPascalCase(g.api.Name) + "Client"
	g.printf("// --- API Methods ---\n\n")

	for _, fn := range g.api.Funcs {
		g.emitClientMethod(clientName, fn)
	}
}

func (g *clientGoInternalGen) emitClientMethod(clientName string, fn ast.Func) {
	methodName := toPascalCase(fn.Name)
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	callWrapper := fmt.Sprintf("C.call_%s_%s", apiName, fnSnake)

	// Method signature
	params := g.goMethodParams(fn)
	retType := g.goMethodReturn(fn)

	if fn.Doc != "" {
		g.printf("// %s %s\n", methodName, fn.Doc)
	}
	g.printf("func (c *%s) %s(%s) %s {\n", clientName, methodName, params, retType)

	// Convert Go params to C
	var callArgs []string
	callArgs = append(callArgs, fmt.Sprintf("c.cbs.%s", cgoFieldAccess(fnSnake)))

	for _, p := range fn.Params {
		goName := toLowerCamel(p.Name)
		g.emitParamConversion(p, goName)

		switch p.Type.Kind {
		case ast.TypePrimitive:
			if p.Type.Name == "string" {
				callArgs = append(callArgs, fmt.Sprintf("c%s", toPascalCase(p.Name)))
			} else if p.ByRef {
				callArgs = append(callArgs, fmt.Sprintf("&c%s", toPascalCase(p.Name)))
			} else {
				callArgs = append(callArgs, fmt.Sprintf("c%s", toPascalCase(p.Name)))
			}
		case ast.TypeArray:
			callArgs = append(callArgs, fmt.Sprintf("&c%s[0]", toPascalCase(p.Name)))
		case ast.TypeNamed:
			callArgs = append(callArgs, fmt.Sprintf("&c%s", toPascalCase(p.Name)))
		default:
			callArgs = append(callArgs, fmt.Sprintf("c%s", toPascalCase(p.Name)))
		}
	}

	// Call the C function
	if fn.Return != nil {
		g.printf("\tresult := %s(%s)\n", callWrapper, strings.Join(callArgs, ", "))
		g.emitReturnConversion(fn)
	} else {
		g.printf("\t%s(%s)\n", callWrapper, strings.Join(callArgs, ", "))
		g.printf("\treturn nil\n")
	}

	g.printf("}\n\n")
}

func (g *clientGoInternalGen) emitParamConversion(p ast.Param, goName string) {
	cName := "c" + toPascalCase(p.Name)

	switch p.Type.Kind {
	case ast.TypePrimitive:
		if p.Type.Name == "string" {
			g.printf("\t%s := C.CString(%s)\n", cName, goName)
			g.printf("\tdefer C.free(unsafe.Pointer(%s))\n", cName)
		} else {
			cType := g.cgoType(p.Type)
			g.printf("\t%s := %s(%s)\n", cName, cType, goName)
		}

	case ast.TypeArray:
		elemCType := g.cgoType(*p.Type.Elem)
		g.printf("\tvar %s [%d]%s\n", cName, p.Type.ArrayLen, elemCType)
		g.printf("\tfor i := range %s {\n", goName)
		g.printf("\t\t%s[i] = %s(%s[i])\n", cName, elemCType, goName)
		g.printf("\t}\n")

	case ast.TypeNamed:
		cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(p.Type.Name))
		g.printf("\tvar %s %s\n", cName, cType)
		g.printf("\t%sToC(&%s, &%s)\n", toLowerCamel(p.Type.Name), goName, cName)
	}
}

func (g *clientGoInternalGen) emitReturnConversion(fn ast.Func) {
	if fn.Return == nil {
		return
	}

	switch fn.Return.Kind {
	case ast.TypePrimitive:
		goType := primitiveToGoType(fn.Return.Name)
		g.printf("\treturn %s(result), nil\n", goType)

	case ast.TypeNamed:
		if g.isEnum(fn.Return.Name) {
			g.printf("\treturn %s(result), nil\n", toPascalCase(fn.Return.Name))
		} else {
			g.printf("\treturn %sFromC(&result), nil\n", toLowerCamel(fn.Return.Name))
		}

	default:
		g.printf("\treturn result, nil\n")
	}
}

func (g *clientGoInternalGen) goMethodParams(fn ast.Func) string {
	parts := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		goType := g.toGoType(p.Type)
		parts = append(parts, fmt.Sprintf("%s %s", toLowerCamel(p.Name), goType))
	}
	return strings.Join(parts, ", ")
}

func (g *clientGoInternalGen) goMethodReturn(fn ast.Func) string {
	if fn.Return == nil {
		return "error"
	}
	retType := g.toGoType(*fn.Return)
	return fmt.Sprintf("(%s, error)", retType)
}

func (g *clientGoInternalGen) cgoType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "C.bool"
		case "i8":
			return "C.int8_t"
		case "i16":
			return "C.int16_t"
		case "i32":
			return "C.int32_t"
		case "i64":
			return "C.int64_t"
		case "u8":
			return "C.uint8_t"
		case "u16":
			return "C.uint16_t"
		case "u32":
			return "C.uint32_t"
		case "u64":
			return "C.uint64_t"
		case "f32":
			return "C.float"
		case "f64":
			return "C.double"
		case "string":
			return "*C.char"
		}
	case ast.TypeNamed:
		return fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
	}
	return "C.int"
}

// --- GetClient Factory ---

func (g *clientGoInternalGen) emitGetClient() {
	clientName := toPascalCase(g.api.Name) + "Client"
	cbsType := fmt.Sprintf("C.%s_callbacks_t", g.api.Name)
	apiName := g.api.Name
	version := g.api.Version

	g.printf("// --- Factory ---\n\n")

	g.printf("// Get%s returns a typed client for the %s API.\n", clientName, apiName)
	g.printf("// It looks up the API in the given registry and returns a client\n")
	g.printf("// that can call the C callbacks directly via cgo.\n")
	g.printf("// Note: does not record the caller as a consumer. Use Get%sFor\n", clientName)
	g.printf("// when consumer tracking is needed (the common case for modules).\n")
	g.printf("func Get%s(reg *apiserver.Registry, instance string) (*%s, error) {\n", clientName, clientName)
	g.printf("\tptr, err := reg.GetAPIUntracked(%q, instance, %d)\n", apiName, version)
	g.printf("\tif err != nil {\n")
	g.printf("\t\treturn nil, err\n")
	g.printf("\t}\n")
	g.printf("\treturn &%s{cbs: (*%s)(ptr)}, nil\n", clientName, cbsType)
	g.printf("}\n\n")

	g.printf("// Get%sFor returns a typed client and records the caller as a consumer.\n", clientName)
	g.printf("// This is the preferred factory for Go modules.\n")
	g.printf("func Get%sFor(reg *apiserver.Registry, consumer, instance string) (*%s, error) {\n", clientName, clientName)
	g.printf("\tptr, err := reg.GetAPIFor(consumer, %q, instance, %d)\n", apiName, version)
	g.printf("\tif err != nil {\n")
	g.printf("\t\treturn nil, err\n")
	g.printf("\t}\n")
	g.printf("\treturn &%s{cbs: (*%s)(ptr)}, nil\n", clientName, cbsType)
	g.printf("}\n\n")

	// Also provide a version using DefaultRegistry
	g.printf("// Get%sDefault returns a client using the default registry.\n", clientName)
	g.printf("func Get%sDefault(instance string) (*%s, error) {\n", clientName, clientName)
	g.printf("\treturn Get%s(apiserver.DefaultRegistry, instance)\n", clientName)
	g.printf("}\n")
}
