package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientCgo writes a Go package that provides a typed Client struct
// wrapping C callback function pointers. Unlike --client-go (REST) this calls
// directly through the cgo bridge without JSON serialization.
//
// Generated output:
//   - Reuses the same cgo preamble + call wrappers as dispatch_c.go
//   - Generates Go types matching the C types (Pose, StateTag, etc.)
//   - Generates a Client struct holding unsafe.Pointer to callbacks_t
//   - Generates typed methods on Client that convert Go → C, call, convert return
func GenerateClientCgo(w io.Writer, api *ast.API, packageName string) error {
	g := &clientCgoGen{
		dispatchCGen: dispatchCGen{w: w, api: api, pkg: packageName, header: api.Name + "_api.h"},
	}
	return g.generate()
}

type clientCgoGen struct {
	dispatchCGen // embed for reuse of preamble, types, converters
}

func (g *clientCgoGen) generate() error {
	// The cgo preamble, types, constants, and converters are already generated
	// by --server-go into the same package (*_cgo.go). We only need:
	// 1. A minimal cgo comment referencing the header (for the callbacks_t type)
	// 2. Imports
	// 3. The Client struct and methods
	g.emitClientPreamble()
	g.emitImports()
	g.emitClient()
	g.emitClientMethods()
	return g.err
}

// emitClientPreamble emits a minimal cgo block that references the API header
// to get access to the callbacks_t type. The call wrappers and types are
// already available from the dispatch file in the same package.
func (g *clientCgoGen) emitClientPreamble() {
	apiUpper := strings.ToUpper(g.api.Name)
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)
	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", apiUpper)
	g.printf("#include \"%s\"\n", g.header)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")
	g.printf("\n")
	// Emit static call wrappers — they must be in this TU since each
	// Go file with import "C" is a separate C translation unit.
	g.emitCallWrapperBodies()
	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

// emitCallWrapperBodies emits the static C call wrappers that invoke
// function pointers. These are needed in this TU for the client methods.
func (g *clientCgoGen) emitCallWrapperBodies() {
	for _, fn := range g.api.Funcs {
		if fn.Publish || (fn.Watch && fn.Method == "") {
			continue
		}
		g.emitCallWrapper(fn)
	}
}

// emitImports overrides the dispatch_c version to not include apiserver/json.
func (g *clientCgoGen) emitImports() {
	g.printf("import (\n")
	g.printf("\t\"fmt\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf(")\n\n")
	g.printf("var _ = fmt.Sprintf // suppress unused import\n")
	g.printf("var _ = unsafe.Pointer(nil)\n\n")
}

func (g *clientCgoGen) emitClient() {
	clientName := toPascalCase(g.api.Name) + "Client"
	cbsType := fmt.Sprintf("C.%s_callbacks_t", g.api.Name)

	g.printf("// --- Client ---\n\n")
	g.printf("// %s provides typed Go methods that call through C function pointers.\n", clientName)
	g.printf("type %s struct {\n", clientName)
	g.printf("\tcb *%s\n", cbsType)
	g.printf("}\n\n")

	g.printf("// New%s wraps a C callbacks pointer in a typed Go client.\n", clientName)
	g.printf("// The pointer must remain valid for the lifetime of the client.\n")
	g.printf("func New%s(callbacks unsafe.Pointer) *%s {\n", clientName, clientName)
	g.printf("\treturn &%s{cb: (*%s)(callbacks)}\n", clientName, cbsType)
	g.printf("}\n\n")
}

func (g *clientCgoGen) emitClientMethods() {
	clientName := toPascalCase(g.api.Name) + "Client"

	g.printf("// --- Client Methods ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Publish || (fn.Watch && fn.Method == "") {
			continue
		}
		g.emitOneMethod(clientName, fn)
	}
}

func (g *clientCgoGen) emitOneMethod(clientName string, fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	methodName := toPascalCase(fn.Name)
	wrapperName := fmt.Sprintf("C.call_%s_%s", apiName, fnSnake)

	// Separate params into input (in signature) and output (returned as values).
	// - Regular params → in signature
	// - byref params → *Type in signature (in/out, caller provides & receives)
	// - out params → NOT in signature, returned as additional value
	type outParam struct {
		param ast.Param
		cVar  string
	}
	var inputParams []string
	var outParams []outParam

	for _, p := range fn.Params {
		paramName := toLowerCamel(p.Name)
		if p.IsOut {
			// out params are not in the method signature
			outParams = append(outParams, outParam{param: p, cVar: "c" + toPascalCase(p.Name)})
			continue
		}
		var paramType string
		if p.IsPtr {
			paramType = "uint64"
		} else if p.ByRef && p.Type.Kind == ast.TypeNamed && !g.isEnum(p.Type.Name) {
			paramType = "*" + toPascalCase(p.Type.Name)
		} else {
			paramType = goTypeForDispatch(p.Type)
		}
		inputParams = append(inputParams, paramName+" "+paramType)
	}
	paramStr := strings.Join(inputParams, ", ")

	// Determine return type.
	// - @returns_value i32 → (int32, error) — value, not error code
	// - plain i32 → error (error code convention)
	// - out params are added as return values
	i32Return := false
	i32Value := false
	var retParts []string

	// Add out param types to return signature
	for _, op := range outParams {
		retParts = append(retParts, toPascalCase(op.param.Type.Name))
	}

	if fn.Return == nil {
		// no return value from C
	} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimI32 {
		i32Return = true
		if fn.ReturnsValue {
			i32Value = true
			retParts = append(retParts, "int32")
		}
	} else {
		retParts = append(retParts, goTypeForDispatch(*fn.Return))
	}
	retParts = append(retParts, "error")

	var retSig string
	if len(retParts) == 1 {
		retSig = retParts[0]
	} else {
		retSig = "(" + strings.Join(retParts, ", ") + ")"
	}

	g.printf("func (cl *%s) %s(%s) %s {\n", clientName, methodName, paramStr, retSig)
	g.printf("\tvar _freeList []unsafe.Pointer\n")
	g.printf("\tdefer func() { for _, p := range _freeList { C.free(p) } }()\n")

	// Declare zeroed C structs for out params
	for _, op := range outParams {
		cType := fmt.Sprintf("C.%s_%s_t", apiName, toSnakeCase(op.param.Type.Name))
		g.printf("\tvar %s %s\n", op.cVar, cType)
	}

	// Convert Go params → C
	var callArgs []string
	callArgs = append(callArgs, "cl.cb."+cgoFieldAccess(fnSnake))
	callArgs = append(callArgs, "cl.cb.ctx")

	// Track byref params that need C→Go writeback after the call
	type byrefWriteback struct {
		cVar  string
		goVar string
		param ast.Param
	}
	var writebacks []byrefWriteback

	for _, p := range fn.Params {
		cVar := "c" + toPascalCase(p.Name)
		goVar := toLowerCamel(p.Name)

		if p.IsOut {
			// out param: already declared as zeroed var, pass pointer
			callArgs = append(callArgs, "&"+cVar)
			continue
		}

		if p.ByRef && p.Type.Kind == ast.TypeNamed && !g.isEnum(p.Type.Name) {
			converter := toLowerCamelRaw(p.Type.Name) + "GoToC"
			g.printf("\t%s := %s(*%s, &_freeList)\n", cVar, converter, goVar)
			writebacks = append(writebacks, byrefWriteback{cVar, goVar, p})
		} else {
			g.emitParamGoToC(cVar, goVar, p)
		}
		callArgs = append(callArgs, g.paramCallArg(cVar, p)...)
	}

	// Build zero-value prefix for error returns with out params
	var zeroRets []string
	for _, op := range outParams {
		zeroRets = append(zeroRets, g.zeroValue(op.param.Type))
	}

	// Call + return handling
	callExpr := fmt.Sprintf("%s(%s)", wrapperName, strings.Join(callArgs, ", "))

	if i32Return {
		g.printf("\trc := int32(%s)\n", callExpr)
		// Writeback byref params
		for _, wb := range writebacks {
			converter := toLowerCamelRaw(wb.param.Type.Name) + "CToGo"
			g.printf("\t*%s = %s(&%s)\n", wb.goVar, converter, wb.cVar)
		}
		// Convert out params
		var outVars []string
		for _, op := range outParams {
			converter := toLowerCamelRaw(op.param.Type.Name) + "CToGo"
			outVar := toLowerCamel(op.param.Name) + "Out"
			g.printf("\t%s := %s(&%s)\n", outVar, converter, op.cVar)
			outVars = append(outVars, outVar)
		}

		if i32Value {
			// @returns_value: rc is a meaningful value, only error on negative
			retVals := append(outVars, "rc")
			g.printf("\treturn %s, nil\n", strings.Join(retVals, ", "))
		} else {
			// Error code convention: 0=success
			if len(outVars) > 0 {
				g.printf("\tif rc != 0 {\n")
				g.printf("\t\treturn %s, fmt.Errorf(\"%s: rc=%%d\", rc)\n",
					strings.Join(zeroRets, ", "), fn.Name)
				g.printf("\t}\n")
				g.printf("\treturn %s, nil\n", strings.Join(outVars, ", "))
			} else {
				g.printf("\tif rc != 0 {\n")
				g.printf("\t\treturn fmt.Errorf(\"%s: rc=%%d\", rc)\n", fn.Name)
				g.printf("\t}\n")
				g.printf("\treturn nil\n")
			}
		}
	} else if fn.Return != nil {
		g.printf("\tout := %s\n", callExpr)
		for _, wb := range writebacks {
			converter := toLowerCamelRaw(wb.param.Type.Name) + "CToGo"
			g.printf("\t*%s = %s(&%s)\n", wb.goVar, converter, wb.cVar)
		}
		for _, op := range outParams {
			converter := toLowerCamelRaw(op.param.Type.Name) + "CToGo"
			outVar := toLowerCamel(op.param.Name) + "Out"
			g.printf("\t%s := %s(&%s)\n", outVar, converter, op.cVar)
		}
		g.emitClientReturnConvert(fn)
	} else {
		g.printf("\t%s\n", callExpr)
		for _, wb := range writebacks {
			converter := toLowerCamelRaw(wb.param.Type.Name) + "CToGo"
			g.printf("\t*%s = %s(&%s)\n", wb.goVar, converter, wb.cVar)
		}
		var outVars []string
		for _, op := range outParams {
			converter := toLowerCamelRaw(op.param.Type.Name) + "CToGo"
			outVar := toLowerCamel(op.param.Name) + "Out"
			g.printf("\t%s := %s(&%s)\n", outVar, converter, op.cVar)
			outVars = append(outVars, outVar)
		}
		if len(outVars) > 0 {
			g.printf("\treturn %s, nil\n", strings.Join(outVars, ", "))
		} else {
			g.printf("\treturn nil\n")
		}
	}

	g.printf("}\n\n")
}

// zeroValue returns the Go zero literal for a type (used in error returns).
func (g *clientCgoGen) zeroValue(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			return "\"\""
		case ast.PrimBool:
			return "false"
		default:
			return "0"
		}
	default:
		return toPascalCase(t.Name) + "{}"
	}
}

// emitClientReturnConvert converts the C return value to Go and returns it.
func (g *clientCgoGen) emitClientReturnConvert(fn ast.Func) {
	ret := fn.Return

	switch ret.Kind {
	case ast.TypePrimitive:
		switch ret.Name {
		case ast.PrimString:
			g.printf("\treturn C.GoString(out), nil\n")
		case ast.PrimBool:
			g.printf("\treturn bool(out), nil\n")
		default:
			goType := primitiveToGoType(ret.Name)
			g.printf("\treturn %s(out), nil\n", goType)
		}

	case ast.TypeNamed:
		if g.isEnum(ret.Name) {
			goType := toPascalCase(ret.Name)
			g.printf("\treturn %s(out), nil\n", goType)
		} else {
			converter := toLowerCamelRaw(ret.Name) + "CToGo"
			if g.typeHasSlices(ret.Name) {
				converter += "Free"
			}
			g.printf("\treturn %s(&out), nil\n", converter)
		}

	case ast.TypeSlice:
		g.printf("\tn := int(out.len)\n")
		if ret.Elem.Kind == ast.TypeNamed && !g.isEnum(ret.Elem.Name) {
			goElemType := toPascalCase(ret.Elem.Name)
			converter := toLowerCamelRaw(ret.Elem.Name) + "CToGo"
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(out.data, n)\n")
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			g.printf("\t\t\tresult[i] = %s(&cSlice[i])\n", converter)
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(out.data))\n")
			g.printf("\t}\n")
		} else {
			goElemType := goTypeForDispatch(*ret.Elem)
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(out.data, n)\n")
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			if ret.Elem.Kind == ast.TypePrimitive && ret.Elem.Name == ast.PrimString {
				g.printf("\t\t\tresult[i] = C.GoString(cSlice[i])\n")
			} else {
				g.printf("\t\t\tresult[i] = %s(cSlice[i])\n", goElemType)
			}
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(out.data))\n")
			g.printf("\t}\n")
		}
		g.printf("\treturn result, nil\n")
	}
}
