// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GeneratePublishGo writes a Go file with cgo that provides:
//   - A drain goroutine reading the C ring buffer
//   - An accumulator collecting events
//   - A WatchFunc returning accumulated events as JSON (for @watch_source)
//
// Returns false if the API has no @publish functions.
func GeneratePublishGo(w io.Writer, api *ast.API, packageName string) (bool, error) {
	g := &publishGoGen{w: w, api: api, pkg: packageName}
	if !g.hasPublishFuncs() {
		return false, nil
	}
	return true, g.generate()
}

type publishGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *publishGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *publishGoGen) hasPublishFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			return true
		}
	}
	return false
}

func (g *publishGoGen) generate() error {
	g.emitHeader()
	g.emitCgoPreamble()
	g.emitImports()
	g.emitAtomicHelpers()

	for _, fn := range g.api.Funcs {
		if !fn.Publish {
			continue
		}
		g.emitGoEventType(fn)
		g.emitDrainType(fn)
		g.emitDrainMethods(fn)
		g.emitWatchFunc(fn)
	}

	return g.err
}

func (g *publishGoGen) emitHeader() {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("\n")
	g.printf("package %s\n\n", g.pkg)
}

func (g *publishGoGen) emitCgoPreamble() {
	g.printf("/*\n")
	g.printf("#include \"%s_pub.h\"\n", g.api.Name)
	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

func (g *publishGoGen) emitImports() {
	g.printf("import (\n")
	g.printf("\t\"context\"\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"sync\"\n")
	g.printf("\t\"sync/atomic\"\n")
	g.printf("\t\"time\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf(")\n\n")
}

func (g *publishGoGen) emitAtomicHelpers() {
	g.printf("// Atomic load/store helpers for ring buffer sequence numbers.\n")
	g.printf("func __atomicLoadU32(p *uint32) uint32 {\n")
	g.printf("\treturn atomic.LoadUint32(p)\n")
	g.printf("}\n\n")
	g.printf("func __atomicStoreU32(p *uint32, val uint32) {\n")
	g.printf("\tatomic.StoreUint32(p, val)\n")
	g.printf("}\n\n")
}

func (g *publishGoGen) emitGoEventType(fn ast.Func) {
	typeName := toPascalCase(fn.Name) + "Event"
	g.printf("// %s is the Go representation of a %s event.\n", typeName, fn.Name)
	g.printf("type %s struct {\n", typeName)
	for _, p := range fn.Params {
		goType := g.paramGoType(p)
		jsonTag := p.Name
		g.printf("\t%s %s `json:\"%s\"`\n", toPascalCase(p.Name), goType, jsonTag)
	}
	g.printf("}\n\n")
}

func (g *publishGoGen) emitDrainType(fn ast.Func) {
	drainType := toPascalCase(fn.Name) + "Drain"
	ringType := fmt.Sprintf("C.%s_%s_ring_t", g.api.Name, fn.Name)

	g.printf("// %s drains the %s ring buffer and accumulates events.\n", drainType, fn.Name)
	g.printf("type %s struct {\n", drainType)
	g.printf("\tring    *%s\n", ringType)
	g.printf("\treadPos uint32\n")
	g.printf("\tcancel  context.CancelFunc\n")
	g.printf("\twg      sync.WaitGroup\n")
	g.printf("\n")
	g.printf("\tmu     sync.Mutex\n")
	g.printf("\tevents []%sEvent\n", toPascalCase(fn.Name))
	g.printf("}\n\n")
}

func (g *publishGoGen) emitDrainMethods(fn ast.Func) {
	drainType := toPascalCase(fn.Name) + "Drain"
	ringType := fmt.Sprintf("C.%s_%s_ring_t", g.api.Name, fn.Name)
	slotType := fmt.Sprintf("C.%s_%s_slot_t", g.api.Name, fn.Name)
	prefix := strings.ToUpper(g.api.Name) + "_" + strings.ToUpper(fn.Name)
	eventType := toPascalCase(fn.Name) + "Event"

	// CreateRing — exported ring allocation
	createRingFunc := "Create" + toPascalCase(fn.Name) + "Ring"
	g.printf("// %s allocates a new C ring buffer for %s events.\n", createRingFunc, fn.Name)
	g.printf("func %s() unsafe.Pointer {\n", createRingFunc)
	g.printf("\treturn unsafe.Pointer(C.%s_%s_ring_create())\n", g.api.Name, fn.Name)
	g.printf("}\n\n")

	// Constructor
	g.printf("// New%s creates a drain for the given ring buffer.\n", drainType)
	g.printf("func New%s(ring unsafe.Pointer) *%s {\n", drainType, drainType)
	g.printf("\treturn &%s{ring: (*%s)(ring)}\n", drainType, ringType)
	g.printf("}\n\n")

	// Ring accessor
	g.printf("// Ring returns the underlying C ring pointer.\n")
	g.printf("func (d *%s) Ring() unsafe.Pointer {\n", drainType)
	g.printf("\treturn unsafe.Pointer(d.ring)\n")
	g.printf("}\n\n")

	// Start
	g.printf("// Start begins the drain goroutine.\n")
	g.printf("func (d *%s) Start() {\n", drainType)
	g.printf("\tctx, cancel := context.WithCancel(context.Background())\n")
	g.printf("\td.cancel = cancel\n")
	g.printf("\td.wg.Add(1)\n")
	g.printf("\tgo d.loop(ctx)\n")
	g.printf("}\n\n")

	// Stop
	g.printf("// Stop signals the drain goroutine to exit and waits.\n")
	g.printf("func (d *%s) Stop() {\n", drainType)
	g.printf("\tif d.cancel != nil {\n")
	g.printf("\t\td.cancel()\n")
	g.printf("\t\td.wg.Wait()\n")
	g.printf("\t}\n")
	g.printf("\td.drainAll()\n")
	g.printf("}\n\n")

	// Drain loop
	g.printf("func (d *%s) loop(ctx context.Context) {\n", drainType)
	g.printf("\tdefer d.wg.Done()\n")
	g.printf("\tfor {\n")
	g.printf("\t\tn := d.drainAll()\n")
	g.printf("\t\tif n == 0 {\n")
	g.printf("\t\t\tselect {\n")
	g.printf("\t\t\tcase <-ctx.Done():\n")
	g.printf("\t\t\t\treturn\n")
	g.printf("\t\t\tdefault:\n")
	g.printf("\t\t\t\ttime.Sleep(1 * time.Millisecond)\n")
	g.printf("\t\t\t}\n")
	g.printf("\t\t}\n")
	g.printf("\t}\n")
	g.printf("}\n\n")

	// drainAll
	g.printf("func (d *%s) drainAll() int {\n", drainType)
	g.printf("\tcount := 0\n")
	g.printf("\tfor {\n")
	g.printf("\t\tidx := d.readPos & C.%s_RING_MASK\n", prefix)
	g.printf("\t\tslot := &d.ring.slots[idx]\n")
	g.printf("\t\tseq := (*uint32)(unsafe.Pointer(&slot.seq))\n")
	g.printf("\t\tif __atomicLoadU32(seq) != d.readPos+1 {\n")
	g.printf("\t\t\tbreak\n")
	g.printf("\t\t}\n")
	g.printf("\n")
	g.printf("\t\tev := d.slotToEvent(slot)\n")
	g.printf("\t\t__atomicStoreU32(seq, 0)\n")
	g.printf("\t\td.readPos++\n")
	g.printf("\t\tcount++\n")
	g.printf("\n")
	g.printf("\t\td.mu.Lock()\n")
	g.printf("\t\td.events = append(d.events, ev)\n")
	g.printf("\t\td.mu.Unlock()\n")
	g.printf("\t}\n")
	g.printf("\treturn count\n")
	g.printf("}\n\n")

	// slotToEvent conversion
	g.printf("func (d *%s) slotToEvent(slot *%s) %s {\n", drainType, slotType, eventType)
	g.printf("\treturn %s{\n", eventType)
	for _, p := range fn.Params {
		fieldName := toPascalCase(p.Name)
		if p.Type.Kind == ast.TypePrimitive && p.Type.Name == "string" {
			g.printf("\t\t%s: C.GoString(&slot.%s[0]),\n", fieldName, p.Name)
		} else if p.Type.Kind == ast.TypeNamed {
			// Enum or struct — cast from C type
			goType := g.paramGoType(p)
			g.printf("\t\t%s: %s(slot.%s),\n", fieldName, goType, p.Name)
		} else {
			goType := g.paramGoType(p)
			g.printf("\t\t%s: %s(slot.%s),\n", fieldName, goType, p.Name)
		}
	}
	g.printf("\t}\n")
	g.printf("}\n\n")

	// Flush — returns accumulated events and clears the buffer
	g.printf("// Flush returns all accumulated events and clears the buffer.\n")
	g.printf("func (d *%s) Flush() []%s {\n", drainType, eventType)
	g.printf("\td.mu.Lock()\n")
	g.printf("\tevents := d.events\n")
	g.printf("\td.events = nil\n")
	g.printf("\td.mu.Unlock()\n")
	g.printf("\treturn events\n")
	g.printf("}\n\n")
}

func (g *publishGoGen) emitWatchFunc(fn ast.Func) {
	drainType := toPascalCase(fn.Name) + "Drain"
	eventType := toPascalCase(fn.Name) + "Event"

	g.printf("// %sWatchFunc returns a WatchFunc that flushes accumulated events as JSON.\n", toPascalCase(fn.Name))
	g.printf("// The returned function is safe to call from the WS push goroutine.\n")
	g.printf("func (d *%s) WatchFunc() func() (json.RawMessage, error) {\n", drainType)
	g.printf("\treturn func() (json.RawMessage, error) {\n")
	g.printf("\t\tevents := d.Flush()\n")
	g.printf("\t\tif len(events) == 0 {\n")
	g.printf("\t\t\treturn []byte(\"[]\"), nil\n")
	g.printf("\t\t}\n")
	g.printf("\t\treturn json.Marshal(events)\n")
	g.printf("\t}\n")
	g.printf("}\n\n")

	// Also emit the atomic helpers (only once per file)
	_ = eventType // used above
}

func (g *publishGoGen) paramGoType(p ast.Param) string {
	t := p.Type
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "bool"
		case "i8":
			return "int8"
		case "u8":
			return "uint8"
		case "i16":
			return "int16"
		case "u16":
			return "uint16"
		case "i32":
			return "int32"
		case "u32":
			return "uint32"
		case "i64":
			return "int64"
		case "u64":
			return "uint64"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		case "string":
			return "string"
		}
	case ast.TypeNamed:
		return toPascalCase(t.Name)
	}
	return "int32"
}
