package cgen

import (
	"fmt"
	"io"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GeneratePushConvert writes a Go file that registers a push converter
// for each @watch function returning a struct type. The generated code:
//   - Converts a raw C struct pointer to the Go type using the no-free CToGo converter
//   - Caches the latest Go struct for in-process consumers (GetLatestXxx)
//   - Registers the converter with apiserver.RegisterPushConverter in init()
//
// Returns true if any push converters were generated.
func GeneratePushConvert(w io.Writer, api *ast.API, packageName string) (bool, error) {
	// Collect @watch functions that return a named struct type.
	var watchFuncs []ast.Func
	for _, fn := range api.Funcs {
		if fn.Watch && fn.Return.Kind == ast.TypeNamed {
			watchFuncs = append(watchFuncs, fn)
		}
	}
	if len(watchFuncs) == 0 {
		return false, nil
	}

	g := &pushConvertGen{w: w, api: api, pkg: packageName, funcs: watchFuncs}
	g.generate()
	return true, g.err
}

type pushConvertGen struct {
	w     io.Writer
	api   *ast.API
	pkg   string
	funcs []ast.Func
	err   error
}

func (g *pushConvertGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *pushConvertGen) generate() {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", toUpperCase(g.api.Name))
	g.printf("#include \"%s_api.h\"\n", g.api.Name)
	g.printf("*/\n")
	g.printf("import \"C\"\n\n")

	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"sync\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	for _, fn := range g.funcs {
		g.emitPushConverter(fn)
	}

	g.emitInit()
}

func (g *pushConvertGen) emitPushConverter(fn ast.Func) {
	goType := toPascalCase(fn.Return.Name)
	cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(fn.Return.Name))
	converter := toLowerCamelRaw(fn.Return.Name) + "CToGo"
	funcName := "pushConvert" + toPascalCase(fn.Name)
	cacheVar := "latest" + goType
	cacheMu := cacheVar + "Mu"
	getterName := "GetLatest" + goType

	// Cache variable + mutex
	g.printf("var (\n")
	g.printf("\t%s sync.Mutex\n", cacheMu)
	g.printf("\t%s *%s\n", cacheVar, goType)
	g.printf(")\n\n")

	// GetLatestXxx returns the cached struct.
	g.printf("// %s returns the most recently pushed %s, or nil if none yet.\n", getterName, goType)
	g.printf("func %s() *%s {\n", getterName, goType)
	g.printf("\t%s.Lock()\n", cacheMu)
	g.printf("\ts := %s\n", cacheVar)
	g.printf("\t%s.Unlock()\n", cacheMu)
	g.printf("\treturn s\n")
	g.printf("}\n\n")

	// Push converter function.
	g.printf("func %s(data unsafe.Pointer, size int) (json.RawMessage, error) {\n", funcName)
	g.printf("\tsrc := (*%s)(data)\n", cType)
	g.printf("\ts := %s(src)\n", converter)
	g.printf("\t%s.Lock()\n", cacheMu)
	g.printf("\t%s = &s\n", cacheVar)
	g.printf("\t%s.Unlock()\n", cacheMu)
	g.printf("\treturn json.Marshal(s)\n")
	g.printf("}\n\n")
}

func (g *pushConvertGen) emitInit() {
	g.printf("func init() {\n")
	for _, fn := range g.funcs {
		funcName := "pushConvert" + toPascalCase(fn.Name)
		g.printf("\tapiserver.RegisterPushConverter(%q, %s)\n", g.api.Name, funcName)
	}
	g.printf("}\n")
}

func toUpperCase(s string) string {
	result := ""
	for _, c := range s {
		if c >= 'a' && c <= 'z' {
			result += string(c - 32)
		} else {
			result += string(c)
		}
	}
	return result
}
