// Package cgen generates C source code from a GMI AST.
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateServerHeader writes C server header (types, callback typedefs, registration).
func GenerateServerHeader(w io.Writer, api *ast.API) error {
	g := &serverGen{w: w, api: api}
	return g.generate()
}

type serverGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *serverGen) generate() error {
	g.emitHeaderGuard()
	g.emitIncludes()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitCallbackDecls()
	g.emitCallbackTypedefs()
	g.emitCallbacksStruct()
	g.emitRegistration()
	g.emitHeaderGuardEnd()
	return g.err
}

func (g *serverGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *serverGen) emitHeaderGuard() {
	guard := strings.ToUpper(g.api.Name) + "_API_H"
	g.printf("// Generated by gmicompile - DO NOT EDIT\n")
	g.printf("#ifndef %s\n", guard)
	g.printf("#define %s\n\n", guard)
}

func (g *serverGen) emitHeaderGuardEnd() {
	guard := strings.ToUpper(g.api.Name) + "_API_H"
	g.printf("#endif // %s\n", guard)
}

func (g *serverGen) emitIncludes() {
	g.printf("#include <stdint.h>\n")
	g.printf("#include <stdbool.h>\n")
	g.printf("#include <stddef.h>\n")

	// Emit includes for imported APIs.
	for _, imp := range g.api.Imports {
		g.printf("#include \"%s_api.h\"\n", imp.Name)
	}

	g.printf("\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
}

func (g *serverGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("#define %s_%s %d\n", strings.ToUpper(g.api.Name), c.Name, c.Value)
	}
	g.printf("\n")
}

func (g *serverGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		g.printf("typedef enum {\n")
		for i, v := range e.Values {
			comma := ","
			if i == len(e.Values)-1 {
				comma = ""
			}
			g.printf("    %s_%s = %d%s\n", strings.ToUpper(g.api.Name), v.Name, v.Value, comma)
		}
		g.printf("} %s_%s_t;\n\n", g.api.Name, toSnakeCase(e.Name))
	}
}

func (g *serverGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

func (g *serverGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		structTag := fmt.Sprintf("%s_%s", g.api.Name, toSnakeCase(t.Name))
		g.printf("typedef struct %s {\n", structTag)
		for _, f := range t.Fields {
			g.printf("    %s;\n", g.fieldDecl(f))
			if f.Type.Kind == ast.TypeSlice {
				g.printf("    size_t %s_len;\n", f.Name)
			}
		}
		g.printf("} %s_t;\n\n", structTag)
	}
}

func (g *serverGen) fieldDecl(f ast.Field) string {
	if f.Type.Kind == ast.TypeArray {
		// Arrays declared inline: type name[SIZE]
		elemType := g.toCType(*f.Type.Elem)
		name := f.Name
		sizeStr := g.arraySizeStr(f.Type)
		return fmt.Sprintf("%s %s[%s]", elemType, name, sizeStr)
	}
	cType := g.toCType(f.Type)
	name := f.Name
	return fmt.Sprintf("%s %s", cType, name)
}

func (g *serverGen) toCType(t ast.TypeRef) string {
	if t.Nullable && t.Kind == ast.TypePrimitive && t.Name == "string" {
		return "const char *" // nullable string is just const char* (can be NULL)
	}

	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", g.api.Name, toSnakeCase(t.Name))
	case ast.TypeCallback:
		return g.callbackCType(t.Name)
	case ast.TypeImport:
		return fmt.Sprintf("%s_callbacks_t", t.Name)
	case ast.TypeSlice:
		// Slice becomes pointer + length
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		// For param typedefs, arrays decay to pointers — handled at call site
		elemType := g.toCType(*t.Elem)
		sizeStr := g.arraySizeStr(t)
		return fmt.Sprintf("%s[%s]", elemType, sizeStr)
	}
	return "void"
}

// arraySizeStr returns the C size expression for an array type.
// Uses the #define constant name if available.
func (g *serverGen) arraySizeStr(t ast.TypeRef) string {
	if t.ArrayLenName != "" {
		return fmt.Sprintf("%s_%s", strings.ToUpper(g.api.Name), t.ArrayLenName)
	}
	return fmt.Sprintf("%d", t.ArrayLen)
}

func primitiveToCType(name string) string {
	switch name {
	case "bool":
		return "bool"
	case "i8":
		return "int8_t"
	case "u8":
		return "uint8_t"
	case "i16":
		return "int16_t"
	case "u16":
		return "uint16_t"
	case "i32":
		return "int32_t"
	case "u32":
		return "uint32_t"
	case "i64":
		return "int64_t"
	case "u64":
		return "uint64_t"
	case "f32":
		return "float"
	case "f64":
		return "double"
	case "string":
		return "const char *"
	case "ptr":
		return "void *"
	}
	return "int"
}

// isCallback returns true if name matches a declared callback type.
func (g *serverGen) isCallback(name string) bool {
	for _, cb := range g.api.Callbacks {
		if cb.Name == name {
			return true
		}
	}
	return false
}

// callbackCType returns the C typedef name for a callback.
func (g *serverGen) callbackCType(name string) string {
	return fmt.Sprintf("%s_%s_cb", g.api.Name, toSnakeCase(name))
}

func (g *serverGen) emitCallbackDecls() {
	if len(g.api.Callbacks) == 0 {
		return
	}
	g.printf("// --- Callback Types ---\n\n")
	for _, cb := range g.api.Callbacks {
		retCType := "void"
		if cb.Return != nil {
			retCType = g.toCType(*cb.Return)
		}
		cbName := g.callbackCType(cb.Name)
		g.printf("typedef %s (*%s)(\n", retCType, cbName)
		var params []string
		for _, p := range cb.Params {
			params = append(params, g.paramDecl(p))
		}
		for i, p := range params {
			comma := ","
			if i == len(params)-1 {
				comma = ""
			}
			g.printf("    %s%s\n", p, comma)
		}
		g.printf(");\n\n")
	}
}

func (g *serverGen) emitCallbackTypedefs() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// --- Callback Typedefs ---\n\n")

	// Emit result structs for functions that return slices (need ptr + len).
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue // publish functions use ring buffers, not callbacks
		}
		if fn.Return != nil && fn.Return.Kind == ast.TypeSlice {
			fnSnake := toSnakeCase(fn.Name)
			elemCType := g.toCType(*fn.Return.Elem)
			g.printf("typedef struct {\n")
			g.printf("    %s *data;\n", elemCType)
			g.printf("    size_t len;\n")
			g.printf("} %s_%s_result_t;\n\n", g.api.Name, fnSnake)
		}
	}

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue // publish functions use ring buffers, not callbacks
		}
		// Direct return: function returns the declared type (or void).
		retCType := "void"
		if fn.Return != nil {
			if fn.Return.Kind == ast.TypeSlice {
				// Slice returns use the result struct
				retCType = fmt.Sprintf("%s_%s_result_t", g.api.Name, toSnakeCase(fn.Name))
			} else {
				retCType = g.toCType(*fn.Return)
			}
		}
		g.printf("typedef %s (*%s_%s_fn)(\n", retCType, g.api.Name, toSnakeCase(fn.Name))

		// First parameter is always void *ctx for instance context.
		params := []string{"void *ctx"}
		for _, p := range fn.Params {
			params = append(params, g.paramDecl(p))
		}

		for i, p := range params {
			comma := ","
			if i == len(params)-1 {
				comma = ""
			}
			g.printf("    %s%s\n", p, comma)
		}
		g.printf(");\n\n")
	}
}

// paramDecl returns the C parameter declaration for a function parameter.
//
// byref semantics:
//
//	primitive         → value:     int32_t x
//	primitive byref   → pointer:   int32_t *x
//	named (struct)    → const ptr: const kins_pose_t *x
//	named byref       → mut ptr:   kins_pose_t *x
//	[]T               → const ptr: const double *x, size_t x_len
//	[]T byref         → mut ptr:   double *x, size_t x_len
//	[N]T              → const arr: const double x[N]
//	[N]T byref        → mut arr:   double x[N]
func (g *serverGen) paramDecl(p ast.Param) string {
	name := p.Name

	// ptr qualifier: always a mutable typed pointer, for any type kind.
	if p.IsPtr {
		switch p.Type.Kind {
		case ast.TypePrimitive:
			return fmt.Sprintf("%s *%s", primitiveToCType(p.Type.Name), name)
		default:
			return fmt.Sprintf("%s *%s", g.toCType(p.Type), name)
		}
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.Type.Name == "ptr" {
			// ptr is void* — no pointer-to-pointer with byref, just void*
			return fmt.Sprintf("void *%s", name)
		}
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("%s %s", cType, name)

	case ast.TypeCallback:
		return fmt.Sprintf("%s %s", g.callbackCType(p.Type.Name), name)

	case ast.TypeImport:
		cType := g.toCType(p.Type)
		if p.IsPtr || p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("const %s *%s", cType, name)

	case ast.TypeNamed:
		cType := g.toCType(p.Type)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		if g.isEnum(p.Type.Name) {
			return fmt.Sprintf("%s %s", cType, name)
		}
		return fmt.Sprintf("const %s *%s", cType, name)

	case ast.TypeSlice:
		elemType := g.toCType(*p.Type.Elem)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s, size_t %s_len", elemType, name, name)
		}
		return fmt.Sprintf("const %s *%s, size_t %s_len", elemType, name, name)

	case ast.TypeArray:
		elemType := g.toCType(*p.Type.Elem)
		sizeStr := g.arraySizeStr(p.Type)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s %s[%s]", elemType, name, sizeStr)
		}
		return fmt.Sprintf("const %s %s[%s]", elemType, name, sizeStr)
	}

	return fmt.Sprintf("void *%s", name)
}

func (g *serverGen) emitCallbacksStruct() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// --- Callbacks Struct ---\n\n")
	g.printf("typedef struct %s_callbacks {\n", g.api.Name)
	g.printf("    void *ctx;\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		fieldName := cSafeName(toSnakeCase(fn.Name))
		g.printf("    %s_%s_fn %s;\n", g.api.Name, toSnakeCase(fn.Name), fieldName)
	}
	g.printf("} %s_callbacks_t;\n\n", g.api.Name)

	// Emit GMI_<UPPER>_CALLBACKS macro for modcompile integration.
	// User writes gmi_<api>_<func>() and this macro wires them into the struct.
	upper := strings.ToUpper(g.api.Name)
	g.printf("// Convenience macro for modcompile gmi_provide integration.\n")
	g.printf("// Maps gmi_%s_<name>() user functions to callback struct fields.\n", g.api.Name)
	g.printf("#define GMI_%s_CALLBACKS { \\\n", upper)
	first := true
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		fieldName := cSafeName(toSnakeCase(fn.Name))
		funcName := fmt.Sprintf("gmi_%s_%s", g.api.Name, toSnakeCase(fn.Name))
		if !first {
			g.printf(", \\\n")
		}
		g.printf("    .%s = %s", fieldName, funcName)
		first = false
	}
	g.printf(" \\\n}\n\n")
}

func (g *serverGen) emitRegistration() {
	name := g.api.Name
	cbsType := fmt.Sprintf("%s_callbacks_t", name)
	version := g.api.Version
	guard := strings.ToUpper(name) + "_API_CGO"

	g.printf("// --- Registration & Lookup ---\n")
	g.printf("//\n")
	g.printf("// These static inline wrappers call through the gomc_api_t callback\n")
	g.printf("// table provided in cmod_env_t.  No extern symbols -- the C plugin\n")
	g.printf("// has zero undefined references to the Go launcher.\n")
	g.printf("// Skipped when included from the cgo dispatcher (types only).\n\n")
	g.printf("#ifndef %s\n\n", guard)
	g.printf("#include \"gomc_api.h\"\n\n")

	// Register wrapper
	g.printf("static inline int %s_api_register(\n", name)
	g.printf("    const gomc_api_t *api,\n")
	g.printf("    const char *instance_name,\n")
	g.printf("    const %s *callbacks)\n", cbsType)
	g.printf("{\n")
	g.printf("    return api->register_api(api->ctx, %q, %d,\n", name, version)
	g.printf("                             instance_name, callbacks);\n")
	g.printf("}\n\n")

	// Get wrapper
	g.printf("static inline const %s *%s_api_get(\n", cbsType, name)
	g.printf("    const gomc_api_t *api,\n")
	g.printf("    const char *instance_name)\n")
	g.printf("{\n")
	g.printf("    return (const %s *)api->get_api(\n", cbsType)
	g.printf("        api->ctx, %q, %d, instance_name);\n", name, version)
	g.printf("}\n\n")

	g.printf("#endif // %s\n\n", guard)

	g.printf("#ifdef __cplusplus\n}\n#endif\n\n")
}

// cKeywords is the set of C/C++ reserved words that cannot be used as identifiers.
var cKeywords = map[string]bool{
	"auto": true, "break": true, "case": true, "char": true,
	"const": true, "continue": true, "default": true, "do": true,
	"double": true, "else": true, "enum": true, "extern": true,
	"float": true, "for": true, "goto": true, "if": true,
	"int": true, "long": true, "register": true, "return": true,
	"short": true, "signed": true, "sizeof": true, "static": true,
	"struct": true, "switch": true, "typedef": true, "union": true,
	"unsigned": true, "void": true, "volatile": true, "while": true,
}

// cSafeName appends an underscore to C reserved words.
func cSafeName(name string) string {
	if cKeywords[name] {
		return name + "_"
	}
	return name
}

// toSnakeCase converts CamelCase to snake_case.
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
