package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateStreamServerGo writes Go bridge code that:
//   - Defines a cgo preamble with C call wrappers for the stream callbacks
//   - Creates a StreamServer type per stream_server block
//   - Implements per-connection goroutine logic (WS → new_conn → loop → closed_conn)
//   - Registers the stream endpoint with the apiserver
//
// Returns false if no stream_server blocks exist.
func GenerateStreamServerGo(w io.Writer, api *ast.API, packageName string) (bool, error) {
	if len(api.StreamServers) == 0 {
		return false, nil
	}
	g := &streamServerGoGen{w: w, api: api, pkg: packageName}
	return true, g.generate()
}

// HasStreamServers returns true if the API has stream_server blocks.
func HasStreamServers(api *ast.API) bool {
	return len(api.StreamServers) > 0
}

type streamServerGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *streamServerGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *streamServerGoGen) generate() error {
	g.emitHeader()
	g.emitCgoPreamble()
	g.emitImports()

	for _, ss := range g.api.StreamServers {
		g.emitStreamServerType(ss)
		g.emitServeConn(ss)
		g.emitHandleDataReceived(ss)
	}

	g.emitRegisterStreams()
	g.emitInit()
	return g.err
}

func (g *streamServerGoGen) emitHeader() {
	g.printf("// Code generated by gmicompile --stream-server-go - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)
}

func (g *streamServerGoGen) emitCgoPreamble() {
	g.printf("/*\n")
	// Define the CGO guard so the C header skips the register helper
	// (which needs gomc_api.h — not available in the Go build context).
	g.printf("#define %s_API_CGO\n", strings.ToUpper(g.api.Name))
	g.printf("#include \"%s_stream_api.h\"\n", g.api.Name)
	g.printf("#include <stdlib.h>\n\n")

	// Static call wrappers for each stream function
	for _, ss := range g.api.StreamServers {
		for _, fn := range ss.Funcs {
			g.emitCallWrapper(ss, fn)
		}
		// Emit cfg accessor (CGO can't expose char* struct fields directly)
		g.printf("static inline char *%s_get_cfg(%s_stream_callbacks_t *cb) {\n", ss.Name, ss.Name)
		g.printf("    return cb->cfg;\n")
		g.printf("}\n\n")
	}

	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

func (g *streamServerGoGen) emitCallWrapper(ss ast.StreamServer, fn ast.StreamFunc) {
	prefix := ss.Name
	retType := "void"
	if fn.Return != nil {
		retType = streamCType(fn.Return)
	}

	// Build C params — in C preamble, use the raw C struct type
	params := fmt.Sprintf("%s_stream_callbacks_t *cb", prefix)
	callArgs := "cb->ctx"
	for _, p := range fn.Params {
		cType := streamCType(&p.Type)
		params += fmt.Sprintf(", %s %s", cType, p.Name)
		callArgs += ", " + p.Name
	}

	funcName := fmt.Sprintf("%s_call_%s", prefix, fn.Name)
	g.printf("static inline %s %s(%s) {\n", retType, funcName, params)
	if fn.Return != nil {
		g.printf("    return cb->%s(%s);\n", fn.Name, callArgs)
	} else {
		g.printf("    cb->%s(%s);\n", fn.Name, callArgs)
	}
	g.printf("}\n\n")
}

func (g *streamServerGoGen) emitImports() {
	// Check if any stream server uses poll_transmit (needs time package)
	needsTime := false
	for _, ss := range g.api.StreamServers {
		for _, fn := range ss.Funcs {
			if fn.Name == "poll_transmit" {
				needsTime = true
			}
		}
	}

	g.printf("import (\n")
	g.printf("\t\"sync\"\n")
	g.printf("\t\"sync/atomic\"\n")
	if needsTime {
		g.printf("\t\"time\"\n")
	}
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")
	g.printf("var _ unsafe.Pointer\n")
	g.printf("var _ sync.Mutex\n")
	g.printf("var _ atomic.Uint32\n")
	if needsTime {
		g.printf("var _ time.Duration\n")
	}
	g.printf("\n")
}

func (g *streamServerGoGen) emitStreamServerType(ss ast.StreamServer) {
	typeName := streamGoTypeName(ss.Name)

	g.printf("// %s manages per-connection streaming for %s.\n", typeName, ss.Name)
	g.printf("type %s struct {\n", typeName)
	g.printf("\tcb   *C.%s_stream_callbacks_t\n", ss.Name)
	g.printf("\tnext atomic.Uint32 // next conn_id\n")
	g.printf("}\n\n")

	g.printf("// New%s creates a stream server backed by the given C callbacks.\n", typeName)
	g.printf("func New%s(ptr unsafe.Pointer) *%s {\n", typeName, typeName)
	g.printf("\treturn &%s{cb: (*C.%s_stream_callbacks_t)(ptr)}\n", typeName, ss.Name)
	g.printf("}\n\n")
}

func (g *streamServerGoGen) emitServeConn(ss ast.StreamServer) {
	typeName := streamGoTypeName(ss.Name)

	// Check which pattern this stream uses
	hasPollTransmit := false
	hasDataReceived := false
	for _, fn := range ss.Funcs {
		if fn.Name == "poll_transmit" {
			hasPollTransmit = true
		}
		if fn.Name == "data_received" {
			hasDataReceived = true
		}
	}

	if !hasPollTransmit && !hasDataReceived {
		return
	}

	g.printf("// ServeConn handles a single WebSocket connection for %s.\n", ss.Name)
	g.printf("func (s *%s) ServeConn(conn apiserver.StreamConn) {\n", typeName)
	g.printf("\tconnID := s.next.Add(1)\n")
	g.printf("\n")
	g.printf("\tret := C.%s_call_new_conn(s.cb, C.uint32_t(connID))\n", ss.Name)
	g.printf("\tif ret != 0 {\n")
	g.printf("\t\treturn\n")
	g.printf("\t}\n")
	g.printf("\tdefer C.%s_call_closed_conn(s.cb, C.uint32_t(connID))\n", ss.Name)
	g.printf("\n")

	// Send config header if cfg is set
	g.printf("\tif cfgStr := C.%s_get_cfg(s.cb); cfgStr != nil {\n", ss.Name)
	g.printf("\t\thdr := \"cfg:\" + C.GoString(cfgStr)\n")
	g.printf("\t\tif err := conn.WriteBinary([]byte(hdr)); err != nil {\n")
	g.printf("\t\t\treturn\n")
	g.printf("\t\t}\n")
	g.printf("\t}\n")
	g.printf("\n")

	if hasPollTransmit {
		// Transmit loop: poll C for data, send to client
		g.printf("\tbuf := make([]byte, 4096)\n")
		g.printf("\tfor {\n")
		g.printf("\t\tselect {\n")
		g.printf("\t\tcase <-conn.Done():\n")
		g.printf("\t\t\treturn\n")
		g.printf("\t\tdefault:\n")
		g.printf("\t\t}\n")
		g.printf("\t\tn := C.%s_call_poll_transmit(s.cb, C.uint32_t(connID),\n", ss.Name)
		g.printf("\t\t\tunsafe.Pointer(&buf[0]), C.int32_t(len(buf)))\n")
		g.printf("\t\tif n < 0 {\n")
		g.printf("\t\t\tbreak\n")
		g.printf("\t\t}\n")
		g.printf("\t\tif n == 0 {\n")
		g.printf("\t\t\tselect {\n")
		g.printf("\t\t\tcase <-conn.Done():\n")
		g.printf("\t\t\t\treturn\n")
		g.printf("\t\t\tcase <-time.After(time.Millisecond):\n")
		g.printf("\t\t\t}\n")
		g.printf("\t\t\tcontinue\n")
		g.printf("\t\t}\n")
		g.printf("\t\tif err := conn.WriteBinary(buf[:n]); err != nil {\n")
		g.printf("\t\t\tbreak\n")
		g.printf("\t\t}\n")
		g.printf("\t}\n")
	} else if hasDataReceived {
		// Receive loop: read from client, pass to C
		g.printf("\tfor {\n")
		g.printf("\t\tdata, err := conn.ReadBinary()\n")
		g.printf("\t\tif err != nil {\n")
		g.printf("\t\t\tbreak\n")
		g.printf("\t\t}\n")
		g.printf("\t\tif len(data) == 0 {\n")
		g.printf("\t\t\tcontinue\n")
		g.printf("\t\t}\n")
		g.printf("\t\tret := C.%s_call_data_received(s.cb, C.uint32_t(connID),\n", ss.Name)
		g.printf("\t\t\tunsafe.Pointer(&data[0]), C.int32_t(len(data)))\n")
		g.printf("\t\tif ret < 0 {\n")
		g.printf("\t\t\tbreak\n")
		g.printf("\t\t}\n")
		g.printf("\t}\n")
	}

	g.printf("}\n\n")
}

func (g *streamServerGoGen) emitHandleDataReceived(ss ast.StreamServer) {
	typeName := streamGoTypeName(ss.Name)

	// Check if this stream has data_received
	hasDataReceived := false
	for _, fn := range ss.Funcs {
		if fn.Name == "data_received" {
			hasDataReceived = true
			break
		}
	}

	if !hasDataReceived {
		return
	}

	g.printf("// HandleData passes received data to the C callback for a connection.\n")
	g.printf("func (s *%s) HandleData(connID uint32, data []byte) int {\n", typeName)
	g.printf("\tif len(data) == 0 {\n")
	g.printf("\t\treturn 0\n")
	g.printf("\t}\n")
	g.printf("\tret := C.%s_call_data_received(s.cb, C.uint32_t(connID),\n", ss.Name)
	g.printf("\t\tunsafe.Pointer(&data[0]), C.int32_t(len(data)))\n")
	g.printf("\treturn int(ret)\n")
	g.printf("}\n\n")
}

func (g *streamServerGoGen) emitRegisterStreams() {
	g.printf("// RegisterStreamServers creates stream server instances from registered\n")
	g.printf("// API callbacks and registers them with the apiserver.\n")
	g.printf("func RegisterStreamServers(srv *apiserver.Server, instanceName string, callbacks unsafe.Pointer) {\n")

	for _, ss := range g.api.StreamServers {
		typeName := streamGoTypeName(ss.Name)
		g.printf("\t{\n")
		g.printf("\t\ts := New%s(callbacks)\n", typeName)
		g.printf("\t\tsrv.RegisterStream(\"%s_stream\", instanceName, s)\n", ss.Name)
		g.printf("\t}\n")
	}

	g.printf("}\n")
}

// streamGoTypeName converts "hal_sampler" to "HalSamplerStream"
func streamGoTypeName(name string) string {
	parts := strings.Split(name, "_")
	result := ""
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result + "Stream"
}

func (g *streamServerGoGen) emitInit() {
	// The stream_server uses a different API name suffix (_stream) to
	// distinguish from normal API registrations.
	g.printf("\nfunc init() {\n")
	for _, ss := range g.api.StreamServers {
		typeName := streamGoTypeName(ss.Name)
		g.printf("\tapiserver.RegisterStreamFactory(\"%s_stream\", func(instance string, callbacks unsafe.Pointer) apiserver.StreamServer {\n", ss.Name)
		g.printf("\t\treturn New%s(callbacks)\n", typeName)
		g.printf("\t})\n")
	}
	g.printf("}\n")
}
