= ENCODER(9)
:manmanual: HAL Components
:mansource: ../man/man9/encoder.9.asciidoc
:man version : 

== NAME
encoder - software counting of quadrature encoder signals

== SYNOPSIS
**loadrt encoder [num_chan=__num__** | names=**__name1__**[,**__name2...__**]]**

== DESCRIPTION
**encoder** is used to measure position by counting the pulses
generated by a quadrature encoder.  As a software-based implementation
it is much less expensive than hardware, but has a limited maximum
count rate.  The limit is in the range of 10KHz to 50KHz, depending
on the computer speed and other factors.  If better performance is
needed, a hardware encoder counter is a better choice.  
Some hardware-based systems can count at MHz rates.

**encoder** supports a maximum of eight channels.  The number of
channels actually loaded is set by the **num_chan** argument when
the module is loaded.  Alternatively, specify names= and unique names
separated by commas.

The **num_chan=** and **names=** specifiers are mutually exclusive.
If neither **num_chan=** nor **names=** are specified, the default
value is three.

**encoder** has a one-phase, unidirectional mode called __counter__.
In this mode, the **phase-B** input is ignored; the counts increase on
each rising edge of **phase-A**.  This mode may be useful for counting
a unidirectional spindle with a single input line, though the noise-resistant
characteristics of quadrature are lost.

== FUNCTIONS
**encoder.update-counters** (no floating-point)
    Does the actual counting, by sampling the encoder signals and
    decoding the quadrature waveforms.  Must be called as frequently
    as possible, preferably twice as fast as the maximum desired
    count rate.  Operates on all channels at once.

**encoder.capture-position** (uses floating point)
    Captures the raw counts from **update-counters** and performs
    scaling and other necessary conversion, handles counter rollover,
    etc. Can (and should) be called less frequently than **update-
    counters**. Operates on all channels at once.

== NAMING
The names for pins and parameters are prefixed as:
  **encoder.N.** for N=0,1,...,num-1 when using **num_chan=num**
  **nameN.** for nameN=name1,name2,... when using **names=name1,name2,...**

The **encoder.N.** format is shown in the following descriptions.

== PINS
**encoder.**__N__**.counter-mode** bit i/o
    Enables counter mode.  When true, the counter counts each rising
    edge of the phase-A input, ignoring the value on phase-B.  This
    is useful for counting the output of a single channel (non-
    quadrature) sensor.  When false (the default), it counts in
    quadrature mode.

**encoder.**__N__**.counts** s32 out
    Position in encoder counts.

**encoder.**__N__**.index-enable** bit i/o
    When true, **counts** and **position** are reset to zero on the next
    rising edge of **Phase-Z**.  At the same time, **index-enable** is reset
    to zero to indicate that the rising edge has occurred.

**encoder.**__N__**.phase-A** bit in
    Quadrature input for encoder channel __N__.

**encoder.**__N__**.phase-B** bit in
    Quadrature input.

**encoder.**__N__**.phase-Z** bit in
    Index pulse input.

**encoder.**__N__**.position** float out
    Position in scaled units (see **position-scale**)

**encoder.**__N__**.position-interpolated** float out
    Position in scaled units, interpolated between encoder counts.
    Only valid when velocity is approximately constant and above
    **min-velocity-estimate**. Do not use for position control.

**encoder.**__N__**.position-scale** float i/o
    Scale factor, in counts per length unit.  For example, if
    **position-scale** is 500, then 1000 counts of the encoder will
    be reported as a position of 2.0 units.

**encoder.**__N__**.rawcounts** s32 out
    The raw count, as determined by **update-counters**. This value
    is updated more frequently than **counts** and **position**.  It is
    also unaffected by **reset** or the index pulse.

**encoder.**__N__**.reset** bit in
    When true, **counts** and **position** are reset to zero immediately.

**encoder.**__N__**.velocity** float out
    Velocity in scaled units per second.  **encoder** uses an algorithm
    that greatly reduces quantization noise as compared to simply
    differentiating the **position** output.  When the magnitude of the
    true velocity is below min-velocity-estimate, the velocity
    output is 0.

**encoder.**__N__**.x4-mode** bit i/o
    Enables times-4 mode.  When true (the default), the counter counts
    each edge of the quadrature waveform (four counts per full cycle).
    When false, it only counts once per full cycle.  In **counter-
    mode**, this parameter is ignored.

**encoder.**__N__**.latch-input** bit in

**encoder.**__N__**.latch-falling** bit in (default: **TRUE**)

**encoder.**__N__**.latch-rising** bit in (default: **TRUE**)

**encoder.**__N__**.counts-latched** s32 out

**encoder.**__N__**.position-latched** float out
    Update **counts-latched** and **position-latched** on the rising and/or
    falling edges of **latch-input** as indicated by **latch-rising** and
    **latch-falling**.

**encoder.**__N__**.counter-mode** bit rw
    Enables counter mode.  When true, the counter counts each rising
    edge of the phase-A input, ignoring the value on phase-B.  This
    is useful for counting the output of a single channel (non-
    quadrature) sensor. When false (the default), it counts in
    quadrature mode.

**encoder.**__N__**.capture-position.tmax** s32 rw
    Maximum number of CPU cycles it took to execute this function.

== PARAMETERS
Parameter names for num_chan= specifier are:
    **encoder.**__N__**.the_parameter_name**

Parameter names for names= specifier are:
    **nameN.the_parameter_name**

**encoder.**__N__**.min-velocity-estimate** float rw (default: 1.0)
    Determine the minimum true velocity magnitude at which **velocity**
    will be estimated as nonzero and **postition-interpolated** will
    be interpolated. The units of **min-velocity-estimate** are the same
    as the units of **velocity**.  Setting this parameter too low will
    cause it to take a long time for **velocity** to go to 0 after
    encoder pulses have stopped arriving.